### ISSUE TITLE
bitwarden-icons gets unhealthy

### ISSUE THREAD

**Issue by Schnuecks** [bitwarden/server#1011]
We use bitwarden behind a corporate proxy and it seems to work.
Only the bitwarden-icons get unhealthy because he cant lookup google.

[docker_logs.txt](https://github.com/bitwarden/server/files/5606930/docker_logs.txt)

proxy is set in docker env
dns is set in daemon.json

**Comment by Greenderella** [comment]
Have you checked on this issue: https://github.com/bitwarden/server/issues/724 ? The scenario looks similar.

**Comment by Schnuecks** [comment]
Hi, thank for the hint but iptables is enabled

```
root@562f186b3396:/app# curl -f http://localhost:5000/google.com/icon.png
curl: (22) The requested URL returned error: 404 Not Found
```

i run centos 8 configured firewalld for docker using this commands

```
firewall-cmd --zone=trusted --change-interface=docker0 --permanent
firewall-cmd --zone=trusted --add-masquerade --permanent
```
we must use a corporate proxy for this is set via docker.d proxy conf

```
[Service]
Environment="HTTP_PROXY=http://ourproxy.net:3280"
Environment="HTTPS_PROXY=http://ourproxy.net:3280"
Environment="NO_PROXY= localhost,127.0.0.1"
```
i dont' no if that's a problem with the proxy setup but on admin page the latest version aren't loaded

How could i ran bitwarden to fully work behind a corporate proxy.

**Comment by Schnuecks** [comment]
So, my problem still exists.

With iptables: false or true in daemon.json the behaviour still exists
