### ISSUE TITLE
builder.UseWebRoot is only called with empty or null string

### ISSUE THREAD

**Issue by vonas** [bitwarden/server#1025]
I was just skimming your code and found that `builder.UseWebRoot` is only ever called with a string that `IsNullOrWhiteSpace`:
https://github.com/bitwarden/server/blob/master/util/Server/Program.cs#L37

I assume this is a logic error. A similar mistake has been fixed before a few lines above it: https://github.com/bitwarden/server/commit/dacb2a8e2b948d67909dcec61a80945a7059e1f3

**Comment by kspearrin** [comment]
This does look like a bug. Maybe we should not be passing in a webRoot value, since things seem to be working as expected right now.
