### ISSUE TITLE
bitwarden.sh not updated?

### ISSUE THREAD

**Issue by Raptor039** [bitwarden/server#1053]
Hi,

just after logged myself in bitwarden self-hosted admin panel, I saw that latest release version of Bitwarden was 1.38.4. I'm using crontab to auto update my instance, so I was a little surprised to disocover my bitwarden was not up to date.

I ran `bitwarden.sh updateself` but the version remained at 1.38.2, so cannot upgrade to 1.38.4. Is it normal ? However, it works if COREVERSION is manualy changed to the desired bitwarden version.

Thanks for your help.

**Comment by martinorob** [comment]
Same issue here!

**Comment by tgreer-bw** [comment]
We pushed some patches to our servers and will make them available to self-hosted instances in a couple of days after we've made sure all patches are solid for distribution to instances we can't instantly update 😃

**Comment by martinorob** [comment]
ok thank you! I have a crontab that check the last available stable release form the github tag and if there is some new version, it update my docker. So the script find the new version but the docker not. 

I'll check later

Thanks

**Comment by Raptor039** [comment]
> We pushed some patches to our servers and will make them available to self-hosted instances in a couple of days after we've made sure all patches are solid for distribution to instances we can't instantly update 😃

Thanks for your answer! I won't be worried anymore about delayed update so! ☺️
