### ISSUE TITLE
Run Bitwarden with < 2000 megabytes of memory

### ISSUE THREAD

**Issue by sombatos** [bitwarden/server#1054]
I'm trying to run Bitwarden on a cheapest DigitalOcean droplet with 1GB of memory and 2 GB swap.

bitwarden/mssql does not start:
```
sqlservr: This program requires a machine with at least 2000 megabytes of memory.
/opt/mssql/bin/sqlservr: This program requires a machine with at least 2000 megabytes of memory.
```

There is a docker image with lowered memory requirements: https://hub.docker.com/r/justin2004/mssql_server_tiny

> Microsoft's sqlservr, at startup, looks to see how much physical memory its host has
> if the host has less than 2 GiB sqlservr just quits with the message:
> "sqlservr: This program requires a machine with at least 2000 megabytes of memory."
> it turns out that sqlservr does not try to allocate that much memory and fail but rather sqlservr enforces that as a policy (perhaps to cut down on performance related issues due to page faulting)

How can I make my Bitwarden to use https://hub.docker.com/r/justin2004/mssql_server_tiny instead of https://hub.docker.com/r/bitwarden/mssql ?

**Comment by sombatos** [comment]
docker-compose.yml:
```
services:
  mssql:
#    image: bitwarden/mssql:1.38.2
    image: justin2004/mssql_server_tiny:latest
#    container_name: bitwarden-mssql
    container_name: justin2004-mssql_server_tiny
```

Now mssql container is running:
```
docker ps -a
CONTAINER ID   IMAGE                                 COMMAND                  CREATED         STATUS                        PORTS     NAMES
1b0c66790baa   justin2004/mssql_server_tiny:latest   "/bin/sh -c 'LD_PREL…"   4 minutes ago   Up 4 minutes                            bitwarden-mssql
```

But Bitwarden can't connect to the DB:

```
2020-12-19 11:58:53.999 +00:00 [Information] Migrating database.
2020-12-19 11:58:54.011 +00:00 [Error] Database unavailable for migration. Trying again (attempt #6)...
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)
```

**Comment by sombatos** [comment]
But it looks like DB is not working properly.

In Admin log:
```
2020-12-19 12:35:01.519 +00:00 [Information] Starting job "DeleteSendsJob" at 12/19/2020 12:35:01.
2020-12-19 12:35:26.852 +00:00 [Error] Error performing "DeleteSendsJob".
System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)
 ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
```

In mssql log:
```
2020-12-19 12:20:22.61 spid9s      Unable to open the physical file "d:\dbs\sh\sqfe\0615_000323\cmd\30\obj\x64retail\sql\mkmastr\databases\mkmastr.proj\model.mdf". Operating system error 2: "2(The system cannot find the file specified.)".
```

**Comment by SergeantConfused** [comment]
Hi there,

I recommend checking out this thread: https://github.com/bitwarden/server/issues/473
If you run into any trouble, please feel free to get in touch with us here: https://bitwarden.com/contact/

I hope that helps.

All the best,

**Comment by sombatos** [comment]
Thanks.

**Comment by karl-xing** [comment]
Is this the only choice? Is it possible to reduce the memory requirements of mssql docker by modifying the configuration?

> Hi there,
> 
> I recommend checking out this thread: #473 If you run into any trouble, please feel free to get in touch with us here: https://bitwarden.com/contact/
> 
> I hope that helps.
> 
> All the best,
