### ISSUE TITLE
Sec

### ISSUE THREAD

**Issue by joshfoxsa** [bitwarden/server#1058]
![16086196540884752722036565624441.png](https://user-images.githubusercontent.com/63128581/102858100-4d6a7800-43ef-11eb-8c46-966342c9bbbe.png)

**Comment by SergeantConfused** [comment]
Hi there,

Can you please clarify what seems to be the issue?

Thank you in advance,

**Comment by cscharf** [comment]
Hi @joshfoxsa , it looks like you're undecided on which direction to travel and by what means. I would highly suggest you take the offramp on the right-hand side and avoid cruise-line travel at the moment; take the first exit off of the traffic circle and go 2 miles; your destination will be on the left.

If you get lost or have more detail for this particular issue please feel free to re-open it, update the title and appropriate detail so we can help you out.
