### ISSUE TITLE
docker inspect" requires at least 1 argument?

### ISSUE THREAD

**Issue by benlenau** [bitwarden/server#1059]
When running bitwarden.sh.

`Docker version 20.10.1, build 831ebea from https://download.docker.com/linux/debian buster stable.`

```
 _     _ _                         _
| |__ (_) |___      ____ _ _ __ __| | ___ _ __
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2020, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

bitwarden.sh version 1.38.4
Docker version 20.10.1, build 831ebea
docker-compose version 1.21.0, build unknown

"docker inspect" requires at least 1 argument.
See 'docker inspect --help'.

Usage:  docker inspect [OPTIONS] NAME|ID [NAME|ID...]

Return low-level information on Docker objects

```

**Comment by joseph-flinn** [comment]
@benlenau, It looks like running the `bitwarden update` command assumes that the docker-compose stack is up and running to collect some current version data about it. Could you confirm that this is/was the case when you ran it?

**Comment by benlenau** [comment]
@joseph-flinn yeah it writes this with every container spinup ... somehow docker-compose -v does this
`docker-compose version 1.21.0, build unknown`
