### ISSUE TITLE
Self-hosted Login errors (QNAP or other)

### ISSUE THREAD

**Issue by ZXant** [bitwarden/server#1061]
At different devices got the dreadful "fail to fetch" error message, at login or when trying to save at a Bitwarden self-hosted NAS (QNAP) server. Weird enough, some devices were still able to connect, while others dont. But if log-out, would NOT be able to Login again.

After many many hours trying to fix self Certification or so, the "aka Solution" was JUST to restart the App (no need to restart NAS itself, but just the app).

For my surprise (and hair pulling out)... it was just that.

Xant

**Comment by benlenau** [comment]
Good to know - any reason for this to still have the status "Open"?
