### ISSUE TITLE
Conenction closed when accessing /sso/connect/authorize

### ISSUE THREAD

**Issue by ghost** [bitwarden/server#1078]
Version 2.17.1

SSO Enabled and configured as Open ID Conenct,

After being redirected back to bitwarden we get conenction closed.

**Comment by cscharf** [comment]
Hi @Sean-Intellicore , can you please provide a bit more detail (anything that you can at least). If it's sensitive or you'd be more comfortable you can also [send information to our support team](https://bitwarden.com/contact/) noting this issue so they can let our engineering team know.

Self-hosted/Cloud?
Browser and client used for SSO (i.e. Chrome / extension, etc.)?
OIDC IdP provider (Azure, Okta, OneLogin, etc.)?
POST or Redirect/GET?
Claims from Endpoint or no?
Any other pertinent configuration details?
Bitwarden URL where you see the Connection Closed error?
Request headers via Dev Tools?
Screen shot of the error?
etc.

That type of detail/information will help us further troubleshoot any problems or issues with either the configuration and/or service itself.
