### ISSUE TITLE
Bitwarden/nginx internal port choices?

### ISSUE THREAD

**Issue by haneef95** [bitwarden/server#1082]
Hi,

Any specific reason as to why the internal ports on the Docker Container are listening on 8080 as opposed to 80 and 8443 as opposed to just 443?

https://github.com/bitwarden/server/blob/96cc88aafc7e7c6dc94a2bb961dd2ecfe0730abb/util/Setup/Templates/NginxConfig.hbs#L9

https://github.com/bitwarden/server/blob/96cc88aafc7e7c6dc94a2bb961dd2ecfe0730abb/util/Setup/Templates/NginxConfig.hbs#L18

Just curious here, as I'm thinking of using the bitwarden/nginx image for an nginx deployment.

Thanks

**Comment by Pulsar** [comment]
Hello @haneef95,
>  8080 as opposed to 80 and 8443 as opposed to just 443
This is normally done for security reasons. The ports bellow 1000 need root user to be used. The user defined on **entrypoint.sh** has default guid 1000 which is not root (thus safer) and therefore can not run on port 80 or 443.

You can still assign the ports 80 and 443 on the `docker-compose.yml` file like this:
```yml
...
ports:
  - 80:8080
  - 443:8443
