### ISSUE TITLE
Wrong reporting of "Web Installed" in Admin interface

### ISSUE THREAD

**Issue by klemenkobetic** [bitwarden/server#1093]
Hi,

my admin portal looks like this :

Version

- Server Installed       1.38.4 
- Server Latest           1.38.4 
- Web Installed           - 
- Web Latest              2.17.1 

It seems that, at some point, 'GetInstalledWebVersion()' in 'Admin.dll' is called? Could anyone help me understand what do I need to check, to fix this?

**Comment by Schnuecks** [comment]
Hi, i have the same problem, couldn't find a solution yet.

![917dc5c445ea02277cc3c2dfad94319d0b19968f](https://user-images.githubusercontent.com/27301329/130615774-fd15d64d-e47b-4d58-b20d-50f07e9a9842.png)

**Comment by Hinton** [comment]
For context: We should return some error message in https://github.com/bitwarden/server/blob/2ec10cfd2ac25e71ddd865d174a43b2bb9905023/src/Admin/Controllers/HomeController.cs#L61, and display it visually.
