### ISSUE TITLE
Encrypted Exports File Format missing

### ISSUE THREAD

**Issue by benlenau** [bitwarden/server#1104]
Hi all, happy to see that _Encrypted Exports_ is now possible however after trying browser app, web vault etc. (of course clearing login + cache) the File Format _.json (Encrypted)_ simply isn't there. Server v1.39.0 / Web 2.17.1.

![image](https://user-images.githubusercontent.com/70938462/105471510-16f87500-5c9b-11eb-818d-a7e5e250c219.png)
![image](https://user-images.githubusercontent.com/70938462/105471624-3abbbb00-5c9b-11eb-9b27-8272449963f8.png)

Howto https://bitwarden.com/help/article/encrypted-export/

**Comment by tgreer-bw** [comment]
Try doing a shift + refresh to download the latest Web vault. Encrypted export is in 2.18.0.

**Comment by benlenau** [comment]
> Try doing a shift + refresh to download the latest Web vault. Encrypted export is in 2.18.0.

That did the trick.
