### ISSUE TITLE
Emergency Access Invite URL not processed in On Premises Instance

### ISSUE THREAD

**Issue by ckrippner** [bitwarden/server#1108]
Hi All,

I just tried my first emergency access invitation with my self hosted BW instance, the email has been sent.
The URL in shown in the email received.

Clicking on the the link opens the browser, asking to log into BW. Done that, navigated to emergency access, no information about granted access visible.

Navigated to the emergency account of the grantor account -> still in status invited.

Tested that with with reversed roles to check both directions of the invite. Same result.

What information can I provide that could help to fix this?

Cheers,
Carsten

**Comment by cscharf** [comment]
Hi @ckrippner , this should be working now with the latest version, please try again. Our team was not able to reproduce this, so assuming the latest bits will resolve this behavior.

**Comment by ckrippner** [comment]
Hi @cscharf ,

yep, it works now. Thank you very much!
