### ISSUE TITLE
Implement a fair and bilateral Contributor Agreement or remove it completely

### ISSUE THREAD

**Issue by setyb** [bitwarden/server#1115]
I have submitted multiple pull requests, but some of my code still has not been added to the project because I have not agreed to the unilateral Contributor Agreement.

I will not sign the agreement, as currently written.

The current lengthy legal agreement is unilateral and only serves to protect the interests and profits of Bitwarden, Inc.

It does not protect the author of the code in any way.

I am willing to sign a bilateral agreement that serves both Bitwarden, Inc. and contributors, but I am not willing to sign a lopsided agreement like this one.

I also do find it a bit egregious for a **for-profit** corporation to ask an individual *- especially one who has received no financial compensation -*  to sign a written contract of this length and severity without compensating them for the cost of legal counsel to review the contract in full.  If you would like to provide compensation, we can discuss that possibility, but I doubt any competent legal counsel will advise me (or anyone else) to sign such a unilateral contract.

I have contributed to over 80 different open-source projects over the years (from the smallest to the largest), and I have never been required to sign any legally binding agreements.

Here is the unilateral legal agreement that I am being asked by Bitwarden Inc., via their assigned agent, to sign:

> Bitwarden Inc. Contributor Agreement
> 
> This Bitwarden Inc. Contributor Agreement ("Agreement") applies to any Contribution you make or have made to any Work. This is a binding legal agreement on you and any organization you represent. If you are signing this Agreement on behalf of your employer or other organization, you represent and warrant that you have the authority to agree to this Agreement on behalf of the organization.
> 
>Definitions.
> 
>"Bitwarden", "we", "us", or "our" means Bitwarden Inc.
> 
>"Contribution" means any original work, including any modification of or addition to an existing work, that you submit to Bitwarden in any manner for inclusion in any Work.
> 
>"Work" means any project, work, or materials owned or managed by Bitwarden.
> 
>"you" or "your" means you and any organization on whose behalf you are entering into this Agreement.
> 
>Copyright Assignment, License, Waiver.
> 
>Assignment. By submitting a Contribution, you assign to Bitwarden all right, title, and interest in any copyright in the Contribution and you waive any rights, including any moral rights or database rights, that may affect our ownership of the copyright in the Contribution.
> 
>License to Bitwarden. If your assignment in Section 2.1 is ineffective for any reason, you grant to us and to any recipient of any Work distributed by us, a perpetual, worldwide, transferable, non-exclusive, no-charge, royalty-free, irrevocable, and sublicensable license to use, reproduce, prepare derivative works of, publicly display, publicly perform, sublicense, and distribute Contributions and any derivative work created based on a Contribution. If your license grant is ineffective for any reason, you irrevocably waive and covenant to not assert any claim you may have against us, our successors in interest, and any of our direct or indirect licensees and customers, arising out of our, our successors in interests', or any of our direct or indirect licensees' or customers' use reproduction, preparation of derivative works, public display, public performance, sublicense, and distribution of a Contribution. You also agree that we may publicly use your name and the name of any organization on whose behalf you are entering into this Agreement in connection with publicizing the Work.
> 
>License to You. We grant to you a perpetual, worldwide, transferable, non-exclusive, no-charge, royalty-free, irrevocable, and sublicensable license to use, reproduce, prepare derivative works of, publicly display, publicly perform, sublicense, and distribute a Contribution and any derivative works you create based on a Contribution.
> 
>Patent License. You grant to us and to any recipient of any Work distributed by us, a perpetual, worldwide, transferable, non-exclusive, no-charge, royalty-free, irrevocable, and sublicensable patent license to make, have made, use, sell, offer to sell, import, and otherwise transfer the Contribution in whole or in part, alone or included in any Work, under any patent you own or license from a third party that is necessarily infringed by the Contribution or by combination of the Contribution with any Work.
> 
>Your Representations and Warranties. By submitting a Contribution, you represent and warrant that (a) each Contribution you submit is an original work and you can legally grant the rights set out in this Agreement; (b) the Contribution does not, and any exercise of the rights granted by you will not, infringe any third party's intellectual property or other right; and (c) you are not aware of any claims, suits, or actions pertaining to the Contribution. You will notify us immediately if you become aware or have reason to believe that any of your representations and warranties is or becomes inaccurate.
> 
>Intellectual Property. Except for the assignment and licenses set forth in this Agreement, this Agreement does not transfer any right, title or interest in any intellectual property right of either party to the other. If you choose to provide us with suggestions, ideas for improvement, recommendations, or other feedback on any Work, we may use your feedback without restriction or payment.
> 
>Miscellaneous. California law governs this Agreement, excluding any applicable conflict of law rules or principles. This Agreement does not create any partnership, agency relationship, or joint venture between the parties. We may assign this Agreement without notice or restriction. If any provision of this Agreement is unenforceable, that provision will be modified to render it enforceable to the extent possible to effect the parties' intention and the remaining provisions will not be affected. The parties may amend this Agreement only in a written amendment signed by both parties. This Agreement comprises the entire agreement between the parties relating to the subject matter of this Agreement.
> 
>This Agreement is effective as of the date of your first Contribution.
> 
>Agreement and accepted on my behalf and on behalf of my organization.
>

**Comment by kspearrin** [comment]
Hi @setyb,

Thanks for your feedback on the CLA requirement.

As you may know, Bitwarden is an open-source product owned and backed by a company, Bitwarden, Inc. We market and sell the Bitwarden product to millions of users. Our business customers range from small teams to large enterprise organizations. Sometimes our customers require us to re-license our product to them under a commercial license since that is more familiar and comfortable for them. In order to relicense code, we must own the copyright to that code. Without a CLA in place, the original contributors own that copyright which would prevent us from engaging in business with these types of customers. This is the main reason why we have a CLA in place.

CLA requirements are not that uncommon whenever you contribute to open-source codebases of products managed by a backing company. Some examples here on GitHub include Microsoft, Google, MySQL, kubernetes, and Mattermost, just to name a few.

We understand that you may not be comfortable signing a CLA and we respect your decision not to contribute due to this requirement. If you have any specific questions or concerns, feel free to [contact us](https://bitwarden.com/contact/) directly and we'll do our best to address them.

**Comment by setyb** [comment]
@kspearrin 

Hi Kyle,

Thank you for your nice and thoughtful response.

I spent a few days time thinking about the desires of Bitwarden Inc., which as you mentioned, are really just a reflection of the desires of some of Bitwarden Inc.'s clients.

Would it be satisfactory to replace the lengthy CLA with something that simply reads along the lines of:

***"By providing contributions to the Bitwarden project, I hereby release all such contributions into the public domain."***

I would be willing to sign such an agreement, and I think it would meet the expressed desires of Bitwarden Inc.'s clients.

I think the fewer words, the better.  But, if needed, the words *"free of all restrictions"* could be added after the words "public domain".
