### ISSUE TITLE
Custom Permissions - Without "Manage Groups" I can still assign AND remove people from groups, but cannot see membership

### ISSUE THREAD

**Issue by slavdok** [bitwarden/server#1118]
I understand this is a tricky subject, but current implementation seems wrong (whether a bug or design).

The idea is that Collections, Groups and access between Collections and Groups is preconfigured beforehand.
I created a user **with** "Manage Users" role, but **without** "Manage Groups".
Now this "Manage Users" user (let's call him "manager") should **not** be able to change the "structure" of the Organization Vault (so Collections, Groups and Access between them stay intact).
But this "manager" should be able to accept/confirm invited users and assign them to correct groups.

This actually works:
The manager can invite/confirm users and can both **add** and **remove** users from groups (using Manage -> People section, not Manage -> Groups section).
However, the manager is doing it blind, cause he is unable to see people's membership when adding/removing their groups through Manage -> People -> Cog on user -> Groups interface

![image](https://user-images.githubusercontent.com/54748546/106199883-0f960780-6184-11eb-95f2-b9cac2dab480.png)

All group membership are shown unchecked (even though they are there)

![image](https://user-images.githubusercontent.com/54748546/106199955-305e5d00-6184-11eb-8045-8c7a16b8fabd.png)

**However** if the "manager" just clicks "Save", he will in fact remove all group membership (without knowing it).
If the manager picks just 1 group to add (leaving others unchecked), it will override (i.e. remove) ownership from unchecked groups, if there was any (again, without manager's knowledge).

Basically, this "manager" has **full control** over people's membership in groups, but cannot **see** the actual membership.

I actually think the functionality is great and is how it should be (other than the fact the "manager" should see existing membership). As for concerns that the "manager" could assign himself unauthorized access to collections: he cannot, because he cannot change his own group membership from anywhere. The only remaining concern is that the "Manage Users" manager could invite his own alternative email, and assign that alternative email to a group he doesn't belong to. But this is an issue that should be solved by a separate custom permission "Invite Users" which is sorely lacking.

Added a feature request for separate "Invite Users" permission to alleviate security concerns  https://community.bitwarden.com/t/custom-permission-invite-users/17155

**Comment by cscharf** [comment]
@addisonbeck , @clayadams5226 ☝🏻

**Comment by cscharf** [comment]
Current understanding of upcoming implementation:

As a user with only Manage Users permission:
- I should be able to see membership of, add and remove membership of a user within a group from the User Edit page.
- I should not be able to see or modify any association with a Collection for that user from the User Edit page.

As a user with only Manage Group permission:
- I should be able to create, edit or delete groups.

As a user with only Manage Collections permission:
- I should be able to create, edit or delete collections.

As a user with only Manage Users and Manage Collections permissions:
- I should be able to see membership of, add and remove membership of a user with a group from the User Edit dialog.
- I should be able to see or modify any association with a Collection for that user from the User Edit page.
- I should be able to create, edit or delete collections.

As a user with only Manage Users and Manage Groups permissions:
- I should be able to see membership of, add and remove membership of a user with a group from the User Edit dialog.
- I should not be able to see or modify any association with a Collection for that user from the User Edit page.
- I should be able to create, edit or delete groups.
- I should be able to modify associated users for groups from the Group Edit page.

As a user with all of Manage Users, Manage Collections, and Manage Groups permissions:
- I should be able to do all the things
