### ISSUE TITLE
Account Takeover disables 2FA, but even after password change and removal of emergency contact, the company 2FA policy is never enforced again

### ISSUE THREAD

**Issue by slavdok** [bitwarden/server#1119]
- I have an organization with 2FA policy enabled (not an organization-integrated Duo, just a requirement that all members have personal 2FA)
- Organization user A designates organization user B as Emergency Contact with Takeover ability
- User A loses their 2FA phone and also forgets his password.
- User B requests takeover
- User A accepts (in logged browser) or timeout lapses
- User B changes master password on User A's account. Also, the 2FA is disabled, as per design and documentation.
- User B can now login to User A's account with the new password and without 2FA (as required). 

At this point User B can share the temporary password with User A.
User A will then login, and **could** reconfigure new 2FA device...

**But the problem is:**
The organization's 2FA policy is no longer enforced on User A's (recovered) account. 
User A can keep login in without 2FA for as long as he wants now.

I've tried removing emergency contact association to see if that restored company 2FA policy. That didn't help.
Also, changing the master password and cycling the encryption key. Neither helped restore company 2FA policy.

I understand that disabling 2FA is required in Takeover scenario. But there should be a time the company policy is re-enforced.
Maybe after second password change? Maybe after a day? Maybe after the emergency-contact association is removed?

**Comment by tgreer-bw** [comment]
When the 2FA is disabled, the user is removed from the Org and cannot be added back until two-step is re-enabled.

**Comment by slavdok** [comment]
> When the 2FA is disabled, the user is removed from the Org and cannot be added back until two-step is re-enabled.

Yes, but that is not what I described.

You are right, when 2FA is disabled **by a user**, or when Organization removes org-level Duo integration, and a user doesn't have account-level 2FA, they get removed from the Organization (if policy is set). I have tested that. That works.

I am describing a scenario where Emergency Contact performs a "Takeover" on account. During this time, 2FA is (understandably) disabled, however user retains Organization access (even on multiple logins, password changes, key cycling). The organization policy seems to be suppressed (just for this user). However it appears it remains suppressed forever (or at least until the user leaves and is re-invited to organization).

Try it. I tested it 3 times before writing the ticket

**Comment by tgreer-bw** [comment]
If the user is an Admin/Owner they are not bound to the 2FA rule (since they can disable the policy), so that may be the issue.

**Comment by slavdok** [comment]
> If the user is an Admin/Owner they are not bound to the 2FA rule (since they can disable the policy), so that may be the issue.

The user in question (with indefinitely suspended 2FA enforcement) is "Custom", not Owner/Admin, with the following permissions:

![image](https://user-images.githubusercontent.com/54748546/106474131-942da200-6472-11eb-99f0-81095c675682.png)

**Comment by tgreer-bw** [comment]
Thanks for the update! @clayadams5226 perhaps the issue here is the manage policies permission.

**Comment by slavdok** [comment]
> Thanks for the update! @clayadams5226 perhaps the issue here is the manage policies permission.

Tried with "Access Business Portal" and "Manage Policies permissions, both removed

![image](https://user-images.githubusercontent.com/54748546/106480380-56804780-6479-11eb-8bab-43aa66f0b569.png)

Still same behaviour:
- On "Takeover", 2FA is "suppressed"
- It never get re-enforced again, even after loging in and out multiple times and changing master password.

The only time I managed to "re-enforce" it is by actively changing 2FA settings. After that, removing 2FA from personal account removed user from Org.

I think this leaves a giant blindside:
There is no "Users' 2FA report" that would show me what Org users have 2FA enabled or not. I have to rely on "2-step login policy" being active and **trust** that it works.
In case of account "Takeover", it is suppressed (understandably), but the problem is: it never gets re-enforced/unsuppressed. And without a "Users' 2FA report", I have no way of knowing if that user (whose account is taken over cause they forgot password [but still had browser session logged in]) has reenabled 2FA on their account or not.
I can "ask" them to, but they can forget (or not do it, maliciously), and I have no way to be sure it's configured, as I cannot trust the Org policy anymore.

The policy should be re-enforced either after first 2FA-less login, or at least after master password change.

**Comment by clayadams5226** [comment]
Thanks for the details @tgreer-bw @slavdok I'll take a look and let you guys know if i need anything else.

**Comment by clayadams5226** [comment]
I did some more digging, it looks like this is specific to emergency contact and not custom permissions at all. I was able to replicate the issue with a "user" role just as well as a "custom" role.

**Comment by eliykat** [comment]
Hey @slavdok, thanks for reporting this issue! I think you raise some good points about how takeover access affects organizations in general. We're going to tweak how this works which should also solve your immediate concerns about 2FA - check out the PR for more info.
