### ISSUE TITLE
Typo in bitwarden.sh

### ISSUE THREAD

**Issue by xoaaC** [bitwarden/server#1126]
Hi,
 
I wanted to renew my cert manually today and ./bitwarden.sh renewcert always told me "Unknown command."
Seems like there is a typo in Line 138 of the bitwarden.sh script. (should be "renewcert" instead of "renewcrt" i guess)

Reference:
https://github.com/bitwarden/server/blob/6d8e37ebf634ef73ba7e99f26ef60ffacb59d74e/scripts/bitwarden.sh#L138

Kind regards

**Comment by cscharf** [comment]
Wow, thanks @xoaaC , fix is forthcoming.
