### ISSUE TITLE
Can't sync users from LDAP

### ISSUE THREAD

**Issue by dusatvoj** [bitwarden/server#1141]
Hello,
I have a problem with syncing users from LDAP to Bitwarden using `bwdc`. I've created issue that has been ignored (https://github.com/bitwarden/directory-connector/issues/76).
I can see these in logs `bitwarden/events`:
```
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.0 POST http://10.11.12.2/organizations/d12e0e46-b53e-4f61-93cd-aba400aed55f/import application/json; charset=utf-8 7664\n","stream":"stdout","time":"2021-02-10T16:23:05.365526558Z"}
info: Microsoft.AspNetCore.Authentication.JwtBearer.JwtBearerHandler[2]
      Successfully validated the token.
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[1]
      Authorization was successful.
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'Bit.Api.Controllers.OrganizationsController.Import (Api)'
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = \"Import\", controller = \"Organizations\"}. Executing controller action with signature System.Threading.Tasks.Task Import(System.String, Bit.Core.Models.Api.ImportOrganizationUsersRequestModel) on controller Bit.Api.Controllers.OrganizationsController (Api).
info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
      Executing ObjectResult, writing value of type 'Bit.Core.Models.Api.ErrorResponseModel'.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action Bit.Api.Controllers.OrganizationsController.Import (Api) in 1.8613ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'Bit.Api.Controllers.OrganizationsController.Import (Api)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 4.6608ms 400 application/json; charset=utf-8
```
But IDK how to deal with it. (How to debug the state or whatever).

Thank's for any help

**Comment by Greenderella** [comment]
Hi @dusatvoj,

It is recommended to run the Directory Connector GUI (https://bitwarden.com/help/article/directory-sync/) and test the sync first. Once the sync is successful you can copy the data.json file and use it with the CLI. If you are running a headless system, you can run the Directory Connector on any workstation with a desktop environment. It does not need to be run from the server host.

Could you test it there and let us know how it goes?

**Comment by cscharf** [comment]
Also, validation on that endpoint model is as follows:
* For Groups[]
   * Name is required, max string length of 100 characters
   * External ID is required, max string length of 300 characters
* For Users[]
   * Email has a max string length of 50
   * External ID is required, max string length of 300 characters

This could mean perhaps the LDAP configuration you have or are pulling in your sync is missing the `name` and `externalId` properties of the group, OR `externalId` property of the user, or one or more of those are outside of the bounds allowed. But that is the code in the `buildRequest` [method](https://github.com/bitwarden/directory-connector/blob/master/src/services/sync.service.ts#L141) where that model is created in the bwdc before being sent to the API server endpoint.

**Comment by dusatvoj** [comment]
@Greenderella That's what I've done. It was working for months but suddenly it stopped working with this error. Don't know how to debug it.
@cscharf what means `externalId`? I'm not syncing groups, just users. It was working and suddenly stopped (IDK why). Is there any way to debug what happend?
Thank you

**Comment by cscharf** [comment]
I'm not quite sure what else to look at (or what an externalId is as I'm not really a directory guru type, but perhaps let's start with some of the basics and see if we can't figure it out:

* What version of bwdc and/or directory connector UI are you using?
* What version of self-hosted server are you using?
* What flavor of directory service are you connecting to (LDAP, AD, etc.)?
* Did anything change when this started happening (updated to latest version of Y to X, migrated directories, updating directory server, etc.)?
* What is your favorite colour?
* How many users are you expecting to sync or what has typically sync'd?
* Are you running any configurations/settings outside of defaults, paged search, overwrite existing, remove disabled, etc.?

**Comment by dusatvoj** [comment]
- ```
  # bwdc --version
  2.6.2
  ```
- server: 1.33.1
- LDAP
- Nothing (maybe somebody created non-ldap user or deleted ldap user)
- It depends. Mainly red (but not in monitoring dashboards :grinning: )
- < 100 users with < 3 changes per week (maybe per month)
- Config below
```
  "syncConfig": {
    "users": true,
    "groups": false,
    "interval": 5,
    "removeDisabled": true,
    "overwriteExisting": true,
    "useEmailPrefixSuffix": false,
    "memberAttribute": "uniqueMember",
    "userPath": "ou=users",
    "userEmailAttribute": "mail",
    "userObjectClass": "inetOrgPerson",
    "groupPath": "ou=groups",
    "groupObjectClass": "groupOfUniqueNames",
    "groupNameAttribute": "cn",
    "creationDateAttribute": "createTimestamp",
    "revisionDateAttribute": "modifyTimestamp"
  }
```

**Comment by cscharf** [comment]
Thank you, very helpful! Since it's a model validation error, I wonder if something unforeseen changed in the environment; but those are both pretty old versions of bwdc and the server; any reason to avoid updating those?

**Comment by dusatvoj** [comment]
I don't think so. I will try to snapshot server, upgrade both and give you a feedback tomorrow.

**Comment by dusatvoj** [comment]
I've upgraded bitwarden and bwdc and it's still the same :/ .
```
bitwarden.sh version 1.39.4
Docker version 19.03.14, build 5eb3275d40
docker-compose version 1.23.1, build b02f1306
# bwdc --version
2.8.2
```

**Comment by cscharf** [comment]
Okay, darn, I leaning towards an assumption it's something to do with the data itself. 

`externalId` is going to be one of `objectGUID` coming from LDAP, or fallback to `objectName` coming from the same entry. Can you run your filter against your directory and determine if these 2 are missing from any entries?

```
ou=users
(&(&(objectClass=inetOrgPerson))<user_filter>)
```

**Comment by dusatvoj** [comment]
Solved! :champagne: ... one of our users had invalid email (`bwdc` GUI has better errors than CLI, so it told me what's wrong) and after that one of our users was duplicitly created in bitwarden organization (IDK how but deleting them helped).
