### ISSUE TITLE
Alternative IdentityServer (Limited and Paid)

### ISSUE THREAD

**Issue by marcrib** [bitwarden/server#1142]
Hi

IdentityServer is paid and your charges by client (Bitwarden has 9 client)

Any alternative?

**Comment by cscharf** [comment]
We are exploring options and have been in contact with [Duende Software](https://duendesoftware.com/) as we look at future options for moving to their new product, however at this time we don't have plans to move away from the current [IdentityServer4](https://github.com/IdentityServer/IdentityServer4), which is under Apache License 2.0.
