### ISSUE TITLE
Raspberry Pi Self-Hosted docker image does not allow re-entering password to unlock account.

### ISSUE THREAD

**Issue by JamieMair** [bitwarden/server#1143]
I have a Raspberry Pi self-hosted docker image of BitwardenRS running at home. I can use bitwarden from any of my browsers, and even on the android app. However, when I need to re-enter my password to unlock the account, there is always an error. I need to log out and log back in for it to work. I am not sure if this is only a problem for the raspberry pi image.

The image is bitwardenrs/server:raspberry and it was created 4 weeks ago. I don't know the version but the SHA256 of the image is 
bf5a81392a3e4390ced2a9e935b53165049ec8b2dcf1a531b8b2426d38f1ca26

Thanks for any help!

**Comment by reinob** [comment]
You should seek support at BitwardenRS. They state this very clearly.

**Comment by kspearrin** [comment]
Bitwarden_rs is not affiliated with the official Bitwarden project.
