### ISSUE TITLE
405 Method Not Allowed

### ISSUE THREAD

**Issue by YehudaEi** [bitwarden/server#1147]
I get a 405 Method Not Allowed when I click submit with my email address on the https://bitwarden.com/host/ web page.

Thank.

**Comment by cscharf** [comment]
Hi @YehudaEi , I'm not able to reproduce this issue, can you please try again? Any chance you can check your browser dev tools if it occurs again to see what may be going on there?

**Comment by YehudaEi** [comment]
![image](https://user-images.githubusercontent.com/32451776/108273674-8d927080-717c-11eb-8625-d13e89cf00f2.png)

Does it help you?

**Comment by cscharf** [comment]
Ah, that page should be POST'ing to our API, are you running any script or ad-blockers by chance?
You should be seeing something like this:
![image](https://user-images.githubusercontent.com/3904944/108276309-9d429280-7145-11eb-8e34-4c80e61770c2.png)

**Comment by YehudaEi** [comment]
Very strange because I canceled it (based on previous issues) and it did not work for me.

**Comment by cscharf** [comment]
Are there JavaScript errors in your console there, perhaps a script failed to load?

**Comment by YehudaEi** [comment]
But I really acted based on the image you sent and sent an API request through the console and it worked.

```js
fetch("https://api.bitwarden.com/installations", {
  "headers": {
    "accept": "application/json, text/javascript, */*; q=0.01",
    "content-type": "application/json; charset=UTF-8",
  },
  "referrer": "https://bitwarden.com/host/",
  "referrerPolicy": "same-origin",
  "body": "{\"email\":\"\"}",
  "method": "POST",
  "mode": "cors",
  "credentials": "include"
});
```

**Comment by YehudaEi** [comment]
Anyway, thanks for the help
