### ISSUE TITLE
Password Maximum Length, can't store (k8s) access token

### ISSUE THREAD

**Issue by hteibler** [bitwarden/server#1148]
the password field is to short to store k8s access token.
this is also a problem when importing from lastpass, where I stored this token.

**Comment by Greenderella** [comment]
Hi @hteibler 

If you have a premium account you can save the keys as an attachment, otherwise you may want to split the entry in multiple fields.

**Comment by hteibler** [comment]
> Hi @hteibler
> 
> If you have a premium account you can save the keys as an attachment, otherwise you may want to split the entry in multiple fields.

a Kubernetes Token is like a password, so I would be great if it would fit in the password field
usually a token is about 900 bytes long 
but    
An error has occurred
The field Password exceeds the maximum encrypted value length of 1000 characters.

would be great if you could expand this limit
and if I need a premium account for this, would be ok.

btw: there is no problem with lastpass

**Comment by jose-valdes-pro** [comment]
+1

**Comment by cscharf** [comment]
Hi @hteibler ,

There is already an open [request for this enhancement](https://community.bitwarden.com/t/remove-increase-1000-character-password-field-limit-length/1165/7) on our community forums. With that, we also have this on our roadmap to address this first half of the year. You can vote for it there and contribute to any discussions about it.

As an aside, we use GitHub issues as a place to track bugs and other development related issues. The [Bitwarden Community Forums](https://community.bitwarden.com) has a section for submitting, voting for, and discussing product [feature requests](https://community.bitwarden.com/c/feature-requests) like this one.

This issue will now be closed. Thanks!
