### ISSUE TITLE
Unable to connect SMTP to my self-hosted Bitwarden Server

### ISSUE THREAD

**Issue by DylanBadolato** [bitwarden/server#1180]
Hello! Im new to installing and hosting bitwarden! I have everything up and running correctly, however i am having trouble getting my server to send the confirmation email. I have the SMTP settings correctly configured in the global.override.env file. When i go to my vault, it will say it successfully sends, but nothing comes though!

Thank you for your help and let me know how i can help!
Dylan.

**Comment by firefox2150** [comment]
I'm actually having a similar issue.  Have you dug through your logs yet?

**Comment by DylanBadolato** [comment]
hello firefox2150,
I havent, im not to sure what logs i should look at and where they are?

**Comment by firefox2150** [comment]
Hi Dylan.  I'm actually making progress on my own issue, hopefully I can help you out with yours in the process.  Are you familiar with Docker at all, and some of the commands used?  Also, what operating system are you running Docker from?

**Comment by sso-bitwarden** [comment]
Which SMTP are u using? If you are using postfix installed locally, you may want to start checking postfix logs.

**Comment by clayadams5226** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.

**Comment by sanjaydatasciencedojo** [comment]
@Clayadams5226 what is the best place to report issues for bitwarden open source version?

**Comment by clayadams5226** [comment]
Hey @sanjaydatasciencedojo you can use the contact link I posted above and someone from our support team will reach out and help you with your setup.

**Comment by sanjaydatasciencedojo** [comment]
@clayadams5226 thank you so much.
