### ISSUE TITLE
Update required to implement Duo "Universal Prompt"?

### ISSUE THREAD

**Issue by benfishbus** [bitwarden/server#1189]
I had reset some things in my Duo account, so found myself setting up Bitwarden again as a new application. As I did so, I noticed them saying Bitwarden requires a back-end update with "minimal changes" to support a change in the authentication prompt (ditching iframes). Details here here: [Duo Universal Prompt Update Guide](https://duo.com/docs/universal-prompt-update-guide#changes-to-support-the-universal-prompt)... Basically saying move to API version 4. Their [blog post on the subject](https://duo.com/blog/breaking-up-with-the-iframe-introducing-our-new) from last September states that v4 is in "public preview", with no indication when v2 might actually go away.

Here is the exact text:
**Waiting on App Provider**
Update details are not available. Please contact the app provider.

**Comment by TargetCrafter** [comment]
I just setup DUO on our Bitwarden Business account, and i see the same message. For now it works, but i do suggest implementing the latest version for obvious reasons.

**Comment by enthusedamateur** [comment]
Can this issue be reopened or should I create a new one? 

I'm using Duo with Bitwarden and have the same issue as mentioned above.

**Comment by janstadt** [comment]
Im still seeing this. What is the plan here?

**Comment by TargetCrafter** [comment]
From what i can see on the [DUO website](https://duo.com/docs/duoweb-v2), Duo Web v2 SDK has been retired since July 18th, 2022. I suggest the sdk to be updated to [v4](https://duo.com/docs/universal-prompt-update-guide#changes-to-support-the-universal-prompt).

**Comment by CrazyHenk44** [comment]
Please reopen. Support for 'universal prompt' is still missing and gives a way nicer user eperience. And the 'traditional prompt' as it is now, will stop working March 30, 2024.

**Comment by 68656c6c** [comment]
Please open this issue, support for the traditional prompt is, like CrazyHenk44 said, stopping on March 30th, 2024.

**Comment by djsmith85** [comment]
Link to the thread in Bitwarden's community forum: https://community.bitwarden.com/t/support-for-duo-universal-prompt/37017/11

**Comment by benfishbus** [comment]
Thanks for the forum link. Good to see that they plan to work on it!
