### ISSUE TITLE
Latest update yields a "Resource not found" error in browser extension.

### ISSUE THREAD

**Issue by SpiritBob** [bitwarden/server#1205]
Seems that powershell.ps1 has not been updated and it keeps downloading the older version. For anyone having this issue, just manually update your script file by bumping the version numbers to the latest ones in this repository and the web one.

Also worth pointing out: Waterfox (Latest classic build) fails to load the new version of Bitwarden (Browser extension)

If this is not by design/intentional, i.e keep everyone on a stable version while the newer ones are still being tested out, I can make a PR bumping the versions.

**Comment by cscharf** [comment]
Thanks @SpiritBob , self-hosted update (powershell.ps1 and bitwarden.sh) will not be released until Monday. We generally like to ensure there won't be a need for any emergency patches, etc. before unleashing our server on the self-hosted world until after it's baked into Production in our cloud for a bit.

> If this is not by design/intentional, i.e keep everyone on a stable version while the newer ones are still being tested out, I can make a PR bumping the versions.

Several community members have already done so (I love how eager our users are!) and there are already version bump PRs pending with the `hold` tag waiting for Monday.

> Also worth pointing out: Waterfox (Latest classic build) fails to load the new version of Bitwarden (Browser extension)

Can you please update this item's description with more detail as to the versions, circumstances, steps attempted, errors/failure descriptions, etc. so the team can take a closer look?

**Comment by cscharf** [comment]
Actually, going to politely ask that you open up the browser extension issue in the [browser repo](https://github.com/bitwarden/browser/issues), and I'll close this issue here. Thanks again!

**Comment by SpiritBob** [comment]
@cscharf  No worries, keep up the great work!
