### ISSUE TITLE
Latest bitwarden.sh does not have version 1.40.0 inside

### ISSUE THREAD

**Issue by Messinger** [bitwarden/server#1208]
I just got the information in my admin portal, that there are newer version of bitwarden:

Server Installed
    1.39.4 
Server Latest
    1.40.0 
Web Installed
    2.18.1 
Web Latest
    2.19.0 

So I tried to start the update as recommended - but nothing happend. I took a look into `bitwarden.sh` and saw, that latest downloadable version points to current installed but not new release.

I checked the docker hub - it has the latest container for this release. So is there a reason for not updating the install script or just forgot updating the version numbers for this release?

So I think 

```bash
SCRIPTS_DIR="$OUTPUT/scripts"
GITHUB_BASE_URL="https://raw.githubusercontent.com/bitwarden/server/master"
COREVERSION="1.39.4"
WEBVERSION="2.18.1"
```

should be 

```bash
SCRIPTS_DIR="$OUTPUT/scripts"
GITHUB_BASE_URL="https://raw.githubusercontent.com/bitwarden/server/master"
COREVERSION="1.40.0"
WEBVERSION="2.19.0"
```

**Comment by martinorob** [comment]
Same problem here

**Comment by BlackScreen** [comment]
The update is also not working for me.

**Comment by Schnuecks** [comment]
Same here, changed it by hand with 1.40.0 and 2.19.0

**Comment by tgreer-bw** [comment]
Hey folks! We do this on purpose to let our updates 'marinate' for a couple of days before making them available to everyone automatically. 

Updating by hand is technically fine, but this delay between our cloud and self-hosting updates is absolutely by design 😎

**Comment by martinorob** [comment]
So let’s public users to do some beta test for us!
I’ll wait the self hosting release 😊

**Comment by BlackScreen** [comment]
I understand this. Maybe you could find a solution that new releases on GitHub are only posted when all users can use them or alternatively a second notification for all self hosters that the new release is ready to use for them? 🤔

**Comment by cscharf** [comment]
> I understand this. Maybe you could find a solution that new releases on GitHub are only posted when all users can use them or alternatively a second notification for all self hosters that the new release is ready to use for them? 🤔

This in-lies the both the beauty AND sacrifice of dual hosting models with a single code base (and only a singular way to publish a release in GitHub). This update has been done, what we will start doing going forward is putting the scheduled self-hosting release date in the release notes themselves. We prefer to feel the pain however vs. our customers self-hosting, so not all releases get pushed for self-hosting (sometimes there are legitimate hot-fixes, etc. where we skip over a few patch versions before you get the final script updates on purpose).

**Comment by martinorob** [comment]
I'm still unable to get the latest updated version 

```
/usr/bin/bash /home/martinorob/bitwarden.sh updateself
 _     _ _                         _
| |__ (_) |___      ____ _ _ __ __| | ___ _ __
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2021, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

bitwarden.sh version 1.40.0
Docker version 19.03.13, build 4484c46d9d
docker-compose version 1.26.2, build eefe0d31

Updated self.







/usr/bin/bash /home/martinorob/bitwarden.sh update

 _     _ _                         _
| |__ (_) |___      ____ _ _ __ __| | ___ _ __
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2021, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

bitwarden.sh version 1.40.0
Docker version 19.03.13, build 4484c46d9d
docker-compose version 1.26.2, build eefe0d31

```
```

curl -s https://hub.docker.com/v2/repositories/bitwarden/api/tags/ | /usr/local/bin/jq -r '."results"[]["name"]' | grep -Ev "latest|beta|dev|rc" |  sed -n '1p'
1.40.0
```

```
 /bin/curl -k -s http://192.168.3.50:8085/api/version | /usr/bin/jq -r .Version
1.39.4

```
