### ISSUE TITLE
Can't connect to DB running in localhost

### ISSUE THREAD

**Issue by mikibakaiki** [bitwarden/server#1210]
Hi there! 

While still on my quest to get some of the bitwarden project running on localhost, for development's sake, I found out that I can't make requests to the DB.

[I described my issue here](https://community.bitwarden.com/t/running-in-localhost-for-development-purposes/26936?u=mikibakaiki). Sorry if it shouldn't be on these two platforms or if it's repetitive. I can take one of them down :) 

---
I Already got the mssql container running in docker, I got the server's Api and Identity projects running and also the web extension compiled and working. 

However, i cannot seem to complete any requests, always getting a 500 error. What do i have to setup in the connections setting in the extension?

Right now i have:

**Web Vault Server Url:** localhost:1433 (the db port that's running on docker)
**API Server Url:** localhost:4000
**Identity Server Url:** localhost:33656

What am I missing here?

I'm getting an exception on the server. 
```
Bit.Api.Utilities.ExceptionHandlerFilterAttribute[0]
      Cannot open database "vault" requested by the login. The login failed.
      Login failed for user 'sa'
```

Which is weird, since I start the DB with the command

```console
docker run -d -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=<pwd>" -p 1433:1433 --name bitwarden-mssql-dev \
   --mount type=bind,source="$(pwd)"/mssql/data,target=/var/opt/mssql/data \
   --mount type=bind,source="$(pwd)"/logs/mssql,target=/var/opt/mssql/log \
   --mount type=bind,source="$(pwd)"/mssql/backups,target=/etc/bitwarden/mssql/backups bitwarden/mssql
```
from inside the `/bwdata` folder, created by running the `bitwarden.sh` script suggested.

Even more weird, I can connect to the DB once it's up on docker through my terminal.

I already tried changing the `global.override.env` and the `mssql.override.env` and it's not working.

**Comment by mikibakaiki** [comment]
Tagging you here, @eliykat, just so you don't forget :) thanks for the help

**Comment by eliykat** [comment]
hey @mikibakaiki, not sure why you're encountering this problem, but the current setup guide instructions are a bit outdated. I've opened a PR to update them so they reflect our own internal documentation: #1222 or [direct link to updated doc](https://github.com/bitwarden/server/blob/update-contributing-guide/CONTRIBUTING.md).

You'll see that it no longer requires the full local deployment of Bitwarden, so I suggest you get rid of that and then try following these steps. I want to make sure our documentation is accurate (both internally and externally) so please let me know how you go either way.

Unfortunately it's a bit long-winded but I don't think there's much to be done about that!
