### ISSUE TITLE
Hide sharer Email on Bitwarden Send

### ISSUE THREAD

**Issue by FrozenVertx** [bitwarden/server#1212]
Hello Every1,
When I share information with new bitwarden send to anyone, A line showed up : Bitwarden user bob@email.com shared the following with you. My bitwarden email is shown there. I have request to give atleast an option to hide my bitwarden email or give option to show any friendly name so that my bitwarden email is not shown for any other user if I don't want.

**Comment by webkp** [comment]
I feel exactly the same way. I wish there was an option to not show the email address. Even better would be if there was a choice between displaying the email address, name of the organization, or nothing. Thank you for considering.

**Comment by kendratodd** [comment]
Hi @FrozenVertx & @webkp! We've definitely had some other folks express the same interest/request. Please feel free to sign up for our [Forums](https://community.bitwarden.com/) to add your upvotes and any other details you'd like to [the feature request](https://community.bitwarden.com/t/allow-hiding-bitwarden-email-from-send/26837) from the Community. That way we can properly track and prioritize an enhancement like this one. 

Thank you! This issue will now be closed.
