### ISSUE TITLE
unable to update self hosted docker 

### ISSUE THREAD

**Issue by martinorob** [bitwarden/server#1220]
I'm still unable to get the latest updated version 

```
/usr/bin/bash /home/martinorob/bitwarden.sh updateself
 _     _ _                         _
| |__ (_) |___      ____ _ _ __ __| | ___ _ __
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2021, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

bitwarden.sh version 1.40.0
Docker version 19.03.13, build 4484c46d9d
docker-compose version 1.26.2, build eefe0d31

Updated self.







/usr/bin/bash /home/martinorob/bitwarden.sh update

 _     _ _                         _
| |__ (_) |___      ____ _ _ __ __| | ___ _ __
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2021, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

bitwarden.sh version 1.40.0
Docker version 19.03.13, build 4484c46d9d
docker-compose version 1.26.2, build eefe0d31

```
```

curl -s https://hub.docker.com/v2/repositories/bitwarden/api/tags/ | /usr/local/bin/jq -r '."results"[]["name"]' | grep -Ev "latest|beta|dev|rc" |  sed -n '1p'
1.40.0
```

```
 /bin/curl -k -s http://192.168.3.50:8085/api/version | /usr/bin/jq -r .Version
1.39.4

```

_Originally posted by @martinorob in https://github.com/bitwarden/server/issues/1208#issuecomment-800073114_

**Comment by edermi** [comment]
What's the point in opening an issue every day? The maintainers explained the delay in the referenced ticket and are aware of this - intended - behavior. The images are on Docker Hub (https://hub.docker.com/r/bitwarden/server/tags?page=1&ordering=last_updated), if you need them ASAP you can modify the script to fetch the most up to date version. 

Please stop spamming the Github issue tracker.

**Comment by martinorob** [comment]
The point is that the #1208 is closed and the problem persist.
The script has updated and now contains this:

`
#!/usr/bin/env bash
set -e

cat << "EOF"
 _     _ _                         _
| |__ (_) |___      ____ _ _ __ __| | ___ _ __
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

EOF

cat << EOF
Open source password management solutions
Copyright 2015-$(date +'%Y'), 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

EOF

# Setup

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SCRIPT_NAME=`basename "$0"`
SCRIPT_PATH="$DIR/$SCRIPT_NAME"
OUTPUT="$DIR/bwdata"
if [ $# -eq 2 ]
then
    OUTPUT=$2
fi

SCRIPTS_DIR="$OUTPUT/scripts"
GITHUB_BASE_URL="https://raw.githubusercontent.com/bitwarden/server/master"
COREVERSION="1.40.0"
WEBVERSION="2.19.0"

echo "bitwarden.sh version $COREVERSION"
docker --version
docker-compose --version

echo ""

# Functions

function downloadSelf() {
    if curl -s -w "http_code %{http_code}" -o $SCRIPT_PATH.1 $GITHUB_BASE_URL/scripts/bitwarden.sh | grep -q "^http_code 20[0-9]"
    then
        mv $SCRIPT_PATH.1 $SCRIPT_PATH
        chmod u+x $SCRIPT_PATH
    else
        rm -f $SCRIPT_PATH.1
    fi
}

function downloadRunFile() {
    if [ ! -d "$SCRIPTS_DIR" ]
    then
        mkdir $SCRIPTS_DIR
    fi
    curl -s -o $SCRIPTS_DIR/run.sh $GITHUB_BASE_URL/scripts/run.sh
    chmod u+x $SCRIPTS_DIR/run.sh
    rm -f $SCRIPTS_DIR/install.sh
}

function checkOutputDirExists() {
    if [ ! -d "$OUTPUT" ]
    then
        echo "Cannot find a Bitwarden installation at $OUTPUT."
        exit 1
    fi
}

function checkOutputDirNotExists() {
    if [ -d "$OUTPUT/docker" ]
    then
        echo "Looks like Bitwarden is already installed at $OUTPUT."
        exit 1
    fi
}

function listCommands() {
cat << EOT
Available commands:

install
start
restart
stop
update
updatedb
updaterun
updateself
updateconf
renewcert
rebuild
help

See more at https://bitwarden.com/help/article/install-on-premise/#script-commands-reference

EOT
}

# Commands

case $1 in
    "install")
        checkOutputDirNotExists
        mkdir -p $OUTPUT
        downloadRunFile
        $SCRIPTS_DIR/run.sh install $OUTPUT $COREVERSION $WEBVERSION
        ;;
    "start" | "restart")
        checkOutputDirExists
        $SCRIPTS_DIR/run.sh restart $OUTPUT $COREVERSION $WEBVERSION
        ;;
    "update")
        checkOutputDirExists
        downloadRunFile
        $SCRIPTS_DIR/run.sh update $OUTPUT $COREVERSION $WEBVERSION
        ;;
    "rebuild")
        checkOutputDirExists
        $SCRIPTS_DIR/run.sh rebuild $OUTPUT $COREVERSION $WEBVERSION
        ;;
    "updateconf")
        checkOutputDirExists
        $SCRIPTS_DIR/run.sh updateconf $OUTPUT $COREVERSION $WEBVERSION
        ;;
    "updatedb")
        checkOutputDirExists
        $SCRIPTS_DIR/run.sh updatedb $OUTPUT $COREVERSION $WEBVERSION
        ;;
    "stop")
        checkOutputDirExists
        $SCRIPTS_DIR/run.sh stop $OUTPUT $COREVERSION $WEBVERSION
        ;;
    "renewcert")
        checkOutputDirExists
        $SCRIPTS_DIR/run.sh renewcert $OUTPUT $COREVERSION $WEBVERSION
        ;;
    "updaterun")
        checkOutputDirExists
        downloadRunFile
        ;;
    "updateself")
        downloadSelf && echo "Updated self." && exit
        ;;
    "help")
        listCommands
        ;;
    *)
        echo "No command found."
        echo
        listCommands
esac
`

but the `bitwarden.sh updateself and bitwarden.sh update` doesn't update nothing as show here:

```
/bin/curl -k -s http://192.168.3.50:8085/api/version | /usr/bin/jq -r .Version
1.39.4
```

**Comment by cscharf** [comment]
Did you have any other log output from the update operation? We're unable to reproduce this and have since updated all of our internal self-hosted instances we use for testing, demos, etc. w/o issue.

**Comment by martinorob** [comment]
How I can have a verbose output?
Thanks!

**Comment by cscharf** [comment]
That's a good question... I guess when I've done it I've always seen the detailed actions/steps it's taking during the update, status, etc. Let me circle back with the team and find out if there's just something I'm missing there.

**Comment by cscharf** [comment]
So the docker output should be showing at least during the update; do you have any output piping setup output, console redirects or something else going on which is redirecting that? The team and I are a little confused as to why you're not seeing anything there.

Someone from the team did also suggest to ensure that Bitwarden is actually running when doing the update, our setup assumes Bitwarden is running (they've experienced a similar issue before when it wasn't).

Also, could you potentially run with xtrace, `set -x` to troubleshoot further?

**Comment by martinorob** [comment]
It seems that my bitwarden.sh has update with the 

`COREVERSION="1.40.0"`
information inside before the update packages was released.

So the script think that I already have the 1.40.0 version and never update it really.

I think that the check current version will be really checked in some way like this:

`/bin/curl -k -s http://192.168.3.50:8085/api/version | /usr/bin/jq -r .Version`

So I have just really update running line by line the script and setting the 

`COREVERSION="1.39.4"`

so the "update" command worked.

**Comment by cscharf** [comment]
Glad you were able to figure that out, sorry it wasn't more obvious or I couldn't have been more help there.
