### ISSUE TITLE
There was an unexpected error during single sign-on

### ISSUE THREAD

**Issue by AMdew73** [bitwarden/server#1253]
I have a self-hosted installation of Bitwarden running on the latest build.  The Organization I have setup has SSO enabled through Azure AD.  I have 15 users running successfully in this Org using the SSO functionality, however, there is one user that cannot get registered to the Org through the Invitation.  Here is the error message that they receive when attempting to sign-up (sign-in):

"There was an unexpected error during single sign-on.  Please close this page and try again.  User, username@domain
.com, has already been invited to those organization, "**********".  Accept the invite in order to log in with SSO."

![Bitwarden-error1](https://user-images.githubusercontent.com/65198733/113217995-62ec0b00-9244-11eb-9a6a-395d516d5109.png)

**Comment by cscharf** [comment]
Hi @AMdew73 , it looks like our support team is helping you out on this issue, I'm going to go ahead and close this one here. I know this expected functionality but they should be able to help you get it sorted out for this user. Please feel free to re-open here if you feel or find that there's an additional technical issue that our engineering team needs to address.
