### ISSUE TITLE
Unable to create new folder

### ISSUE THREAD

**Issue by glass-w** [bitwarden/server#1277]
When trying to create a new folder on the web, desktop app, or iOS app I get the error:

```
An error has occurred.
An unhandled server error has occurred.
```
Web browser: Brave Version 1.23.71 Chromium: 90.0.4430.72 (Official Build) (x86_64)
Desktop app: Bitwarden Version 1.25.1 (518)
iOS app: Bitwarden 2.9.1

**Comment by jackom83** [comment]
I notice same behavior, API /folders return 
`Status 500 - Internal Server Error`

**Comment by Greenderella** [comment]
The team is aware of this issue, and it's currently working to solve it. We will inform you once the issue has been resolved.

You can also monitor the status here: https://status.bitwarden.com/

Thank you in advance for your understating and cooperation.

**Comment by Greenderella** [comment]
The team is aware of the issue, and it should be resolved by now. You will probably want to log out and log back in order to renew your session key and try again.
