### ISSUE TITLE
Error 500 on Folder Creation

### ISSUE THREAD

**Issue by jackom83** [bitwarden/server#1278]
When i try to create a new folder, either from desktop or web application, i receive exception with message"An unhandled server error has occurred."

I investigate it, and i discovery that the API  return, for: 
```
Request URL: https://api.bitwarden.com/folders
Request Method: POST
```
Response is with 
`Status Code: 500 (aka internal server error)`

**Comment by jackom83** [comment]
Duplicate of #1277

**Comment by Greenderella** [comment]
The team is aware of the issue, and it should be resolved by now. You will probably want to log out and log back in order to renew your session key and try again.
