### ISSUE TITLE
Add Folder not working

### ISSUE THREAD

**Issue by cmendible** [bitwarden/server#1279]
I'm trying to add a folder to my vault but all I get is an error message: "An unhandled server error has occurred". This is happening in any platform, browser or desktop.

Renaming or deleting existing folders is working as expected.

**Comment by jackom83** [comment]
see #1277

**Comment by Greenderella** [comment]
The team is aware of the issue, and it should be resolved by now. You will probably want to log out and log back in order to renew your session key and try again.

**Comment by cmendible** [comment]
It's working! 

Thanks!
