### ISSUE TITLE
"An unexpected error has occurred" when logging in with 2FA in vault.bitwarden.com, chrome and android apps

### ISSUE THREAD

**Issue by AugustoResende** [bitwarden/server#1332]
## Describe the Bug

I'm an active Premium user, with 2FA (TOTP AND FIDO) enabled. When i try to login in vault.bitwarden.com this appears:
Error: 
"An error has occurred
An unexpected error has occurred."

And I'm unable to login in any new chrome or android apps, this same error appears. I have 2FA in account (TOTP and FIDO)

## Steps To Reproduce

1. Have an old account with Premium, 2FA (TOTP AND FIDO) enabled.
2. Try to login in any (web vault.bitwarden.com, chrome or android apps)

## Expected Result

Successfully receive the 2FA page, and then login, and access all the credentials.

## Actual Result

Error: 
"An error has occurred
An unexpected error has occurred."

## Screenshots or Videos

![Screenshot_678](https://user-images.githubusercontent.com/10731727/118396079-2160c500-b624-11eb-86aa-d20c7a3622db.png)

## Environment

- Operating system: Cloud, Windows Chrome and Android Apps
- Build Version: Probably latest (?), it's in bitwarden official website and solution.
- Self Hosted: false
- Environment: NA
- Hardware: NA

**Comment by eliykat** [comment]
Hi @lrefra, it appears that the recent server update has locked a few people out of their accounts if they were using a premium 2FA option and their premium subscription lapsed. You didn't mention your subscription type, but I'm assuming it's probably related. Either way, please contact our Customer Success team here: https://bitwarden.com/contact/. You can include a link to this issue in your message content. They can help you re-gain access to your vault. (If anyone reading this has the same issue, please do the same.) Our dev team are working on a more permanent fix in the meantime.
