### ISSUE TITLE
502 Bad Gateway after update to v1.41.3 on self-hosted instance

### ISSUE THREAD

**Issue by BlackScreen** [bitwarden/server#1341]
## Describe the Bug

502 Bad Gateway after update to v1.41.3 on self-hosted instance
It seems to be, that only the web-intefcae is not working.
Connections via app (iOS or Windows) or via browser extension are working.

## Steps To Reproduce

./bitwarden.sh updateself
./bitwarden.sh update

After that, it did not work.
Downgrading to 1.41.2 did not solve the problem either.
I did not change anything on my setup, just updated Bitwarden, as I always do.

## Expected Result

Working instance of Bitwarden, as before.

## Actual Result

502 Bad Gateway error when visiting the normal domain.

## Environment

- Operating system: Ubuntu 20.04.2 LTS
- Build Version: 1.41.3
- Self Hosted: true
- Environment: Docker
- Hardware: 4 cores, 16 GB RAM

**Comment by castigo86** [comment]
Experienced the same issue, BW running in Alpine VM in TRUENas HV behind HA Proxy. HA proxy reporting BW as DOWN.

SSH into VM and BW is running normally. Restart doesn't not solve the issue.

Renewcert command made HA Proxy appear as UP, but web access to vault or sync over browser extensions and app still not functional.

Docker PS status reports **bitwarden_SSO stuck on STARTING**. 

Reverted to a snapshot of VM before update, everything resettled. 
At this point Docker PS status reports all containers as Healthy, SSO not stuck on Starting. This might be the underlying issue, given no other visible difference at the moment.

**Comment by castigo86** [comment]
Hy, could you check in your VM with 

`docker ps`

if all containers report healthy?

**Comment by BlackScreen** [comment]
> Hy, could you check in your VM with
> 
> `docker ps`
> 
> if all containers report healthy?

Yes, all containers are healthy and running.

**Comment by castigo86** [comment]
Ok, I had a similar issue but my PS reports a stuck container, but I had a 503 after the update ([forum post](https://community.bitwarden.com/t/503-service-unavailable-after-update-to-1-41-3/30083)). 
My only workaround was to rollback to a previous snapshot of the VM. 

Sorry I can't be more helpful, I'm just a user not a dev.

**Comment by BlackScreen** [comment]
Thanks. I have no snapshot, but at least the apps are working. „Just“ the Web-Interface is down. This is not cool, but not catastrophic. 
Hopefully a dev has an idea.

**Comment by BlackScreen** [comment]
A little update from my side:
The admin dashboard is working, the normal web-interface not.

This is the error:
![image](https://user-images.githubusercontent.com/17316492/118791736-4872fd00-b897-11eb-96f8-fbc40d143291.png)

**Comment by BlackScreen** [comment]
Any news or help? The problem still persists.

**Comment by eliykat** [comment]
Hey @BlackScreen, I don't have any ideas, but it sounds like it's probably an issue specific to your docker setup. Please contact our Customer Success team here: https://bitwarden.com/contact. You can include a link to this issue in the message content. They'll help you debug this, and if it is a bug they'll reopen this ticket.
