### ISSUE TITLE
Upload tells still 100MB only

### ISSUE THREAD

**Issue by Flol0** [bitwarden/server#1342]
## Bug
Still the message with 100MB only. Shouldn`t it be 500MB in the web Browser?
![image](https://user-images.githubusercontent.com/46406801/118625824-a2f25780-b7ca-11eb-8521-7018b6808f53.png)

## Steps To Reproduce

Update to latest version

## Expected Result
500MB Upload limit

## Actual Result

100MB Upload limit visually.

**Comment by cscharf** [comment]
Hi @Flol0 , which client is that a screenshot of? And what version of that client?

**Comment by cscharf** [comment]
Actually, so it is really 500MB (I promise), apparently our Crowin translations for DE did not change the numeric value from 100 to 500.

see: https://crowdin.com/translate/bitwarden-browser/26/en-de?filter=basic&value=0#q=maxFileSize
and: https://crowdin.com/translate/bitwarden-web/58/en-de?filter=basic&value=0#q=maxFileSize

I'm updating those now so this should be resolved when we do the next deployment.

**Comment by cscharf** [comment]
Also found a few dozen other languages across projects that needed updating, thanks again!
