### ISSUE TITLE
Adding second organization while being the owner of another one

### ISSUE THREAD

**Issue by notscottsmith** [bitwarden/server#1355]
Description:
While attempting to add a new organization via the web interface, I receive the error:

`
An error has occurred.
An unhandled server error has occurred.
`

Interrogating the logs, the error is:
`
Route  matched with {action = "PostLicense", controller = "Organizations"}.  Executing controller action with signature  System.Threading.Tasks.Task`1[Bit.Core.Models.Api.OrganizationResponseModel]  PostLicense(Bit.Core.Models.Api.OrganizationCreateLicenseRequestModel)  on controller Bit.Api.Controllers.OrganizationsController (Api).
fail: Bit.Api.Utilities.ExceptionHandlerFilterAttribute[0]
You may not create an organization. You belong to an organization  which has a policy that prohibits you from being a member of any other  organization.

System.Exception:  You may not create an organization. You belong to an organization which  has a policy that prohibits you from being a member of any other  organization.

at  Bit.Api.Controllers.OrganizationsController.PostLicense(OrganizationCreateLicenseRequestModel  model) in  /home/runner/work/server/server/src/Api/Controllers/OrganizationsController.cs:line  209

at lambda_method(Closure , Object )
`

The Single Organization policy is enabled, but I am the owner of the organization so should be excluded from this policy.

From the documentation:
**Single Organization**
Enabling the Single Organization policy will restrict non-Owner/non-Admin members of your Organization from being able to join other Organizations, or from creating other Organizations.

**Comment by Greenderella** [comment]
Hi @notscottsmith 

Are you attempting to add the second organization on our cloud or are you self-hosting? If you are self-hosting, what's your current server version?

**Comment by notscottsmith** [comment]
Self hosted

Server Version: 1.40.0
Web Version: 2.19.0

**Comment by Greenderella** [comment]
You may want to try updating your server to the latest version (1.41.3) and try again.

**Comment by notscottsmith** [comment]
I've upgraded all systems/services to 1.41.3 and the same error is occurring. No change in the error delivered at all.

**Comment by notscottsmith** [comment]
Any update to this at all?

**Comment by eliykat** [comment]
Looks like we had not applied the owner/admin exemption to self-hosted instances as well. I've just linked the PR that will resolve this issue.
