### ISSUE TITLE
Invalid GUIDs to API endpoints result in error code 500

### ISSUE THREAD

**Issue by Areedtz** [bitwarden/server#1362]
## Describe the Bug

Sending invalid GUIDs to API endpoints will cause them to return an error code "500 Internal Server Error". 

## Steps To Reproduce

1. HTTP DELETE to API endpoint such as /api/emergency-access/ with invalid GUID like "asd"

## Expected Result

Endpoint returns a "400 Bad Request"

## Actual Result

Endpoint returns a "500 Internal Server Error"

## Environment

- Operating system: Kali 2021.2 (running in Windows Subsystem for Linux)
- Build Version: 1.40.0
- Self Hosted: true
- Environment: Docker
- Hardware: Ryzen 7 5800X, 32 GB ram

## Additional Context

Found this bug while running a fuzzer locally. All endpoints which constructs a GUID using "new GUID(id)" doesn't have the constructor wrapped in a try-catch, which is why it returns a 500.

**Comment by alexanderhlee** [comment]
Hello. I would like to contribute to the project by working on this issue. I have my local dev environment up and running (both API and IDENTITY). However, I cannot seem to get the complete URL correct for the `emergency-access` endpoint correct. For example, I am using Postman to send an HTTP DELETE to `http://localhost:4000/api/emergency-access/delete/123` but I keep getting a 404. Apologies is this is documented somewhere and I missed it. Thanks.

**Comment by alexanderhlee** [comment]
Got it. Draft PR here: https://github.com/bitwarden/server/pull/1887
