### ISSUE TITLE
Some invalid emails are being accepted when registering

### ISSUE THREAD

**Issue by Areedtz** [bitwarden/server#1364]
## Describe the Bug
Some invalid emails are being accepted when registering. It's possible to register with an address like ``Email Example <email@example.com>``, where it still is possible to send emails to the address.

However, it's also possible to register with an address like ``<p>test</p> <email@example.com>``.
The server isn't able to actually send emails to that even though the user is registered successfully.

## Steps To Reproduce

1. HTTP POST to /api/accounts/register with ``"email": "<p>test</p> <email@example.com>"``

## Expected Result

Endpoint returns a "400 Bad Request"

## Actual Result

Endpoint returns a "200 Success"

## Environment

- Operating system: Kali 2021.2 (running in Windows Subsystem for Linux)
- Build Version: 1.40.0
- Self Hosted: true
- Environment: Docker
- Hardware: Ryzen 7 5800X, 32 GB ram

## Additional Context

Found this bug while running a fuzzer locally.

**Comment by panna-ahmed** [comment]
I was not able to reproduce it from web.

![image](https://user-images.githubusercontent.com/1288581/140714694-577ac8fd-ba13-480f-9690-bb2b568cb76a.png)

**Comment by eliykat** [comment]
We've increased our email address validation on the server and this should no longer be possible. Thank you @panna-ahmed for confirming.
