### ISSUE TITLE
After collapsing one or more collections in web vault loading does not complete 

### ISSUE THREAD

**Issue by andrewheberle** [bitwarden/server#1384]
## Describe the Bug

After collapsing one or more collections in the Web Vault loading of the collection list does not complete on next refresh/load of Vault.

## Steps To Reproduce

1. Open web vault
2. Collapse one or more collections
3. Refresh page or re-open Vault

## Expected Result

Vault completes loading with all collections visible.

## Actual Result

The collections "tree" does not complete loading, however search is still functional.

The following error is reported in the browser console:

```
ERROR Error: Uncaught (in promise): TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))
TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))
    at new Set (<anonymous>)
    at t.<anonymous> (groupings.component.ts:65)
    at main.8bb68b321ef3db0b700c.js:1
    at Object.next (main.8bb68b321ef3db0b700c.js:1)
    at a (main.8bb68b321ef3db0b700c.js:1)
    at t.invoke (zone.js:400)
    at Object.onInvoke (core.js:28591)
    at t.invoke (zone.js:399)
    at e.run (zone.js:160)
    at zone.js:1318
    at j (zone.js:1255)
    at zone.js:1162
    at s (main.8bb68b321ef3db0b700c.js:1)
    at t.invoke (zone.js:400)
    at Object.onInvoke (core.js:28591)
    at t.invoke (zone.js:399)
    at e.run (zone.js:160)
    at zone.js:1318
    at t.invokeTask (zone.js:434)
    at Object.onInvokeTask (core.js:28578)
```

## Environment

- Operating system: Ubuntu 20.04
- Build Version: 1.41.3 (Web Vault Version: 2.20.3)
- Self Hosted: true
- Environment: K8S
- Hardware: Intel 4-Core 16GB RAM

## Additional Context

When collapsing a collection a value such as `collapsedGroupings_UUID` with a value of `{}` is added to "Local Storage" for the Vault.  The issue can be resolved by deleting this key.

**Comment by eliykat** [comment]
Hi @andrewheberle, thanks for the bug report. This has already been reported [here](https://github.com/bitwarden/web/issues/1005) and will be fixed in the upcoming release.

Also FYI, the server repo is for the backend server. Any issues with the web vault (vault.bitwarden.com) can be reported in the [web vault repo](https://github.com/bitwarden/web).
