### ISSUE TITLE
Organization transactional emails display some characters as HTML character reference

### ISSUE THREAD

**Issue by tgreer-bw** [bitwarden/server#1395]
## Describe the Bug

Some characters are displayed in Organization emails as HTML character references

## Steps To Reproduce

1.  Add an ampersand, apostrophe, @, quote,  less than, or, greater than symbol to the name of your Organization
2. Invite a user to join the organization
3. Email recipient will notice the error in the body of the email - the subject containing the organization name remains accurate

## Expected Result

- Organization Name is represented with the correct character set.

## Actual Result

- Organization Name is represented with HTML character references.

## Screenshots or Videos

![OrgName](https://user-images.githubusercontent.com/61418192/121956911-af1cf680-cd2f-11eb-82c9-8ca9512241b7.png)

## Environment

- macOS 11.4
- Chrome 91.0.4472.101

## Additional Context

No further comment :-)

**Comment by Hinton** [comment]
@addisonbeck can you confirm if the PR resolved this issue? And if so close this issue.
