### ISSUE TITLE
Organization cannot use directory syncing

### ISSUE THREAD

**Issue by joych000** [bitwarden/server#1396]
## Describe the Bug

Hi Team, I was trying to sync our Directory Uses (Google Workspace) to Bitwarden. I did the steps indicated here: https://bitwarden.com/help/article/gsuite-directory/ but failed to Sync the users. "Test Now" works fine and was able to show the list of users in our Google Workspace account but when I tried to sync them the error "Organization cannot use directory syncing" shows.

I'm using the latest Bitwarden Directory Connector which is Version 2.9.2. 

## Screenshots or Videos
See screenshot attached
![image](https://user-images.githubusercontent.com/74773733/122029746-b7dcfd80-cdff-11eb-8a1f-dff03034faa5.png)

**Comment by Krychaz** [comment]
Problem is most likely caused by the org being on the 2019 Teams plan that did not offer said features. Upgrade to the new Teams plan is required to avail of all the features - more details here: https://bitwarden.com/pricing/business/

**Comment by joych000** [comment]
Thank you for your response!
