### ISSUE TITLE
Self Hosted - Users and Organizations Gone

### ISSUE THREAD

**Issue by glienhard** [bitwarden/server#1416]
OS - Ubuntu 20.04.2 LTS
Server Installed - 1.40.0 
Web Installed - 2.19.0
Licensed under family use.

This past week I discovered my Lets Encrypt cert failed to update this last time, so it expired. The server has been up and running for about six months, so I know that the cert has gone through one renewal.

After much research it appears that the certificate only renews on docker startup. (That would be good info to have in the Install and Deploy documentation.) 

I issued the "./bitwarden.sh restart" command to get it to renew the cert. It went through the entire script and finished with no errors.  After the restart I am not able to login with one of my user accounts and it fails to login. Checked the /admin portal and found that all user accounts (three in total) and the organization is gone. I restored the server from snapshot and tried again, only to have the same thing happen.

Please let me know if this is a bug or something I missed in documentation.

Cheers!
Garry

**Comment by SergeantConfused** [comment]
Hi @glienhard,

Please run 'updateself' and then 'update, and let me know how it behaves then. If it's still not starting up as expected, please create a support ticket here: https://bitwarden.com/contact/ and we'll proceed.

Thank you in advance,

**Comment by glienhard** [comment]
@SergeantConfused 

I did try the updateself/update commands after the restart. Then when that failed, I restored via the snapshot and tried the updateself/update commands first. Same thing happens, all users and the organization are deleted.

**Comment by alancivita** [comment]
not sure if it can help, but i've just upgraded to 1.41.5 from 1.41.3 and the nginx container failed to start due missing certificates. I've noticed that the update possibly deleted the directory containing the certs

docker logs of nginx container showed:
SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/ssl/mydir/ca.crt'

i've recreated the directory and copied over the certs and everything started working again

**Comment by clayadams5226** [comment]
Thanks for getting in touch! We use GitHub issues as a place to track bugs and other development related issues. If you'd like help using or configuring Bitwarden, please contact our Customer Success team here: https://bitwarden.com/contact. You can include a link to this issue in the message content. You can also search for an answer in our [help documentation](https://bitwarden.com/help/) or get help from other Bitwarden users on our [community forums](https://community.bitwarden.com/c/support/). The issue here will be closed.

**Comment by alancivita** [comment]
@clayadams5226 if this is not a bug what it is? explain please

**Comment by clayadams5226** [comment]
Hey @alancivita, it sounds more like a configuration issue than a defect in the code. If you wouldn’t mind reaching out to our CS team using the contact form above they would be more than happy to help.
