### ISSUE TITLE
Bitwarden performace very slow

### ISSUE THREAD

**Issue by pboatone** [bitwarden/server#1485]
## Describe the Bug

We currently have our own server with docker containers from bitwarden. There are now 2 VMs:
- Server1: 2 cores, 4GB Ram 250GB HHD
- Server2: 4 cores, 16GB Ram, 500GB HDD

on both VMs we need a long time until we are logged in (auth process) and passwords load very, very slowly. both VMs are underutilized. We currently have the assumption that the performance of the MSSQL is poor

## Steps To Reproduce

20.000 passwords
40 Groups
35 Users
--> this is that what we have

## Expected Result

fast loading

## Actual Result

long load times - sometimes over 2 min. if u want to edit a password

## Screenshots or Videos

https://user-images.githubusercontent.com/67209365/127153878-5b403777-a70c-486f-8d0e-d53cddd183d6.mp4

## Environment

- Operating system: Ubuntu 20.04
- Build Version: 1.41.6
- Self Hosted: true
- Environment: Vcenter VM with Vsan
- Hardware: 4Cores,16GB Ram, 500GB space / 2Cores, 4GB Ram, 250 GB space

**Comment by SergeantConfused** [comment]
Hi @pboatone,

Thank you for bringing this to our attention. Yes, this was reported to us also here: https://github.com/bitwarden/browser/issues/1597 in the browser extension's repository, with a note that it's also affecting the web vault and certain desktop clients. We are making updates and changes to address this, and I recommend you follow that GitHub Issue for any updates on this matter.

Please do not hesitate to let me know if you have any questions.

All the best,
