### ISSUE TITLE
Logging in through the web vault via SSO by Azure AD returns "There was an unexpected error during single sign-on" sporadically.

### ISSUE THREAD

**Issue by SergeantConfused** [bitwarden/server#1522]
## Describe the Bug
Organizational members would encounter the error below sporadically in an organization that has SSO configured with Azure AD. To remedy this, an Owner-type in the organization would deactivate SSO and then activate it again, and that would allow that member to then log in via SSO successfully.

_There was an unexpected error during single sign-on. Please close this page and try again. Cannot insert duplicate key row in object 'dbo.SsoUser' with unique index 'IX_SsoUser_OrganizationIdUserId'. The duplicate key value is (redacted). The statement has been terminated._

## Steps To Reproduce
1. Configure SSO with Azure AD.
2. Invite and confirm a member into your organization.
3. Ask that member to attempt to log in via Enterprise Single Sign-On through the web vault.

## Expected Result
To log in successfully in a consistent manner.

## Actual Result
The error message below is returned sporadically.

_There was an unexpected error during single sign-on. Please close this page and try again. Cannot insert duplicate key row in object 'dbo.SsoUser' with unique index 'IX_SsoUser_OrganizationIdUserId'. The duplicate key value is (redacted). The statement has been terminated._

## Screenshots or Videos
N/A.

## Environment
- Operating system: Windows 10 Pro 21H1.
- Browser: Firefox 91.0.
- Build Version: 2.21.1.

## Additional Context
N/A.

**Comment by eliykat** [comment]
This should be fixed by the linked PR. If anyone experiences this issue again after the next release, please let me know.
