### ISSUE TITLE
Identity/sso container cannot read certificate data

### ISSUE THREAD

**Issue by laugmanuel** [bitwarden/server#1528]
## Describe the Bug

I've tried to update to the latest release of Bitwarden but when starting the containers (I'm using the docker-stubs), the identity and sso containers are stuck at startup and complain about not being able to read the certificate data.

## Steps To Reproduce

- Take a working docker-stubs setup with 1.41.x
- Pull the latest docker images (using either `latest` or `1.42.x` as tag)
- Start the stack using docker-compose

## Expected Result

All containers should start up and be available.

## Actual Result

The identity and sso containers are restarting with the following error:
```
bitwarden-sso    | Unhandled exception. System.Security.Cryptography.CryptographicException: The certificate data cannot be read with the provided password, the password may be incorrect.
bitwarden-sso    |  ---> System.Security.Cryptography.CryptographicException: A certificate referenced a private key which was already referenced, or could not be loaded.
bitwarden-sso    |    at Internal.Cryptography.Pal.UnixPkcs12Reader.BuildCertsWithKeys(CertBagAsn[] certBags, AttributeAsn[][] certBagAttrs, CertAndKey[] certs, Int32 certBagIdx, SafeBagAsn[] keyBags, RentedSubjectPublicKeyInfo[] publicKeyInfos, AsymmetricAlgorithm[] keys, Int32 keyBagIdx)
bitwarden-sso    |    at Internal.Cryptography.Pal.UnixPkcs12Reader.Decrypt(ReadOnlySpan`1 password, ReadOnlyMemory`1 authSafeContents)
bitwarden-sso    |    at Internal.Cryptography.Pal.UnixPkcs12Reader.VerifyAndDecrypt(ReadOnlySpan`1 password, ReadOnlyMemory`1 authSafeContents)
bitwarden-sso    |    at Internal.Cryptography.Pal.UnixPkcs12Reader.Decrypt(SafePasswordHandle password)
bitwarden-sso    |    --- End of inner exception stack trace ---
bitwarden-sso    |    at Internal.Cryptography.Pal.UnixPkcs12Reader.Decrypt(SafePasswordHandle password)
bitwarden-sso    |    at Internal.Cryptography.Pal.PkcsFormatReader.TryReadPkcs12(OpenSslPkcs12Reader pfx, SafePasswordHandle password, Boolean single, ICertificatePal& readPal, List`1& readCerts)
bitwarden-sso    |    at Internal.Cryptography.Pal.PkcsFormatReader.TryReadPkcs12(ReadOnlySpan`1 rawData, SafePasswordHandle password, Boolean single, ICertificatePal& readPal, List`1& readCerts, Exception& openSslException)
bitwarden-sso    |    at Internal.Cryptography.Pal.OpenSslX509CertificateReader.FromFile(String fileName, SafePasswordHandle password, X509KeyStorageFlags keyStorageFlags)
bitwarden-sso    |    at System.Security.Cryptography.X509Certificates.X509Certificate..ctor(String fileName, String password, X509KeyStorageFlags keyStorageFlags)
bitwarden-sso    |    at System.Security.Cryptography.X509Certificates.X509Certificate2..ctor(String fileName, String password)
bitwarden-sso    |    at Bit.Core.Utilities.CoreHelpers.GetCertificate(String file, String password) in /home/runner/work/server/server/src/Core/Utilities/CoreHelpers.cs:line 230
bitwarden-sso    |    at Bit.Core.Utilities.CoreHelpers.GetIdentityServerCertificate(GlobalSettings globalSettings) in /home/runner/work/server/server/src/Core/Utilities/CoreHelpers.cs:line 710
bitwarden-sso    |    at Bit.Sso.Utilities.ServiceCollectionExtensions.AddSsoServices(IServiceCollection services, GlobalSettings globalSettings) in /home/runner/work/server/server/bitwarden_license/src/Sso/Utilities/ServiceCollectionExtensions.cs:line 24
bitwarden-sso    |    at Bit.Sso.Startup.ConfigureServices(IServiceCollection services) in /home/runner/work/server/server/bitwarden_license/src/Sso/Startup.cs:line 66
bitwarden-sso    |    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
bitwarden-sso    |    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
bitwarden-sso    |    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
bitwarden-sso    |    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
bitwarden-sso    |    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
bitwarden-sso    |    at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
bitwarden-sso    |    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
bitwarden-sso    |    at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
bitwarden-sso    |    at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
bitwarden-sso    |    at Microsoft.Extensions.Hosting.HostBuilder.Build()
bitwarden-sso    |    at Bit.Sso.Program.Main(String[] args) in /home/runner/work/server/server/bitwarden_license/src/Sso/Program.cs:line 13
```

## Environment

- Operating system: Ubuntu 20.04 LTS
- Build Version: 1.42.1
- Self Hosted: true
- Environment: Docker
- Hardware: 2 core AMD Epyc; 8GB RAM

## Additional Context

After specifying an older release (1.41.x) and restoring a MSSQL backup, the application starts up fine.
That's why I doubt there is a configuration error. I did not change anything in the compose file going from 1.41.x to 1.42.x.

Also, opening the PFX with the supplied password in the config works fine:
```sh
root@srv:/opt/docker/bitwarden# openssl pkcs12 -info -in ../identity/identity.pfx
Enter Import Password:
[...]
subject=CN = Bitwarden IdentityServer

issuer=CN = Bitwarden IdentityServer

-----BEGIN CERTIFICATE-----
[...]
```

**Comment by k-takkar** [comment]
I can also confirm that the same issue happened with me after the upgrade to 1.42.1.
I just rolled it back to 1.41.6.

**Comment by fresmo** [comment]
I can confirm it too. Same problem. The question is, should we pin all another images in docker-compose for specific version?
At the moment, a pinned only identity and sso image to version 1.41.6

-

**Comment by cscharf** [comment]
We have not yet officially released the self-hosted version. We are looking into this issue before that release happens. But it is suggested to stay on the official self-hosted release contained in the update script.

**Comment by KibosJ** [comment]
This is caused by the update to Dot Net Core 5.0 and the way it reads PFX files

In the documentation for self hosting generating the PFX is done with

`openssl pkcs12 -export -out ./identity/identity.pfx -inkey identity.key \
      -in identity.crt -certfile identity.crt -passout pass:IDENTITY_CERT_PASSWORD`

This has 2 inputs of `identity.crt` which means the PFX lists the certificate twice, which Dot Net Core 5.0 doesn't like.

If you re-create the PFX with the same password using the following it will work and boot (I've tested it and fixed it on my own hosted solution)

`openssl pkcs12 -export -out ./identity/identity.pfx -inkey identity.key \
    -in identity.crt -passout pass:IDENTITY_CERT_PASSWORD`

Notice there isn't the second `-certfile identity.crt`

**Comment by vgrassia** [comment]
@KibosJ You are correct.  When using the `bitwarden.sh` script to update an installation it will use the `setup` container to execute this [code](https://github.com/bitwarden/server/blob/18b597559aa795ad0117729297fbf2ab56e42e37/util/Setup/Program.cs#L139-L156) that removes the duplicate certificates from the PKCS12 bags.  The `bitwarden.sh` script will be updated when we officially release the self-hosted version of `v1.42.1`.

**Comment by cscharf** [comment]
Working on updating the documentation now. Thank you!

**Comment by cscharf** [comment]
@fschillingeriv , FYI, https://bitwarden.com/help/article/install-on-premise-manual/#installation-procedure will be getting a PR internally here shortly.

**Comment by vgrassia** [comment]
@laugmanuel @k-takkar @fresmo You can run the following commands to extract the current Identity certificate and key from the PFX file and then generate a new PFX without the duplicate certificate entry.  Just make sure to replace `IDENTITY_CERT_PASS_HERE` with the value of `globalSettings__identityServer__certificatePassword` from the `bwdata/env/global.override.env` file.

```
openssl pkcs12 -in /bwdata/identity/identity.pfx -nocerts -nodes -out identity.key -passin pass:IDENTITY_CERT_PASS_HERE
openssl pkcs12 -in /bwdata/identity/identity.pfx -clcerts -nokeys -out identity.crt -passin pass:IDENTITY_CERT_PASS_HERE
openssl pkcs12 -export -out /bwdata/identity/identity.pfx -inkey identity.key -in identity.crt -passout pass:IDENTITY_CERT_PASS_HERE
```

**Comment by haneef95** [comment]
Thanks @vgrassia. This worked nicely.

However, why do we need to regenerate the certificate?

Thanks

**Comment by niondir** [comment]
Just updated after roughly one year. The bug still appears, I did updated the pfx file as explained above to fix the issue. That worked wenn.

You should consider reopening this issue and find a way to automatically fix the certificate.

Regards
Tobias
