### ISSUE TITLE
Notification: Error when dispatching 'OnConnectedAsync' on hub

### ISSUE THREAD

**Issue by Supersonido** [bitwarden/server#1531]
## Describe the Bug
Reviewing the logs of the bitwarden-notifications container I have detected that it is generating the following error:
```
notifications_1  | fail: Microsoft.AspNetCore.SignalR.HubConnectionHandler[1]
notifications_1  |       => SpanId:a5cbca694eccb644, TraceId:31d55153e219784da314a2c5a9d30c49, ParentId:0000000000000000 => ConnectionId:0HMB65OU1RV7M => RequestPath:/hub RequestId:0HMB65OU1RV7M:00000002 => TransportConnectionId:SvYjXYXPwenZH2iTtfaVMw
notifications_1  |       Error when dispatching 'OnConnectedAsync' on hub.
notifications_1  |       System.InvalidOperationException: Unable to resolve service for type 'Bit.Core.Repositories.IProviderUserRepository' while attempting to activate 'Bit.Notifications.NotificationsHub'.
notifications_1  |          at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
notifications_1  |          at lambda_method77(Closure , IServiceProvider , Object[] )
notifications_1  |          at Microsoft.AspNetCore.SignalR.Internal.DefaultHubActivator`1.Create()
notifications_1  |          at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.OnConnectedAsync(HubConnectionContext connection)
notifications_1  |          at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.OnConnectedAsync(HubConnectionContext connection)
notifications_1  |          at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.RunHubAsync(HubConnectionContext connection)
```
Reviewing the nginx logs, it occurs when the following endpoint is called: `/notifications/hub?access_token=xxxxx`. 
To avoid this error I have turned off the container but I don't know if there is any long-term solution.

## Steps To Reproduce
1. View the nginx logs
2. View the notifications container logs
3. Login to the web version and look at the console. (It happens in all applications but the easiest way is from the browser console)

## Expected Result
That the websocket opens satisfactorily

## Actual Result
Error: Connection disconnected with error 'Error: Server returned an error on close: Connection closed with an error.'.

## Environment

- Operating system: Cloud
- Build Version: 1.42.1
- Self Hosted: true
- Environment: Docker
- Hardware: Dedicated Server

**Comment by shartge** [comment]
Just to let you know: you are not alone, I am seeing this as well, in my case behind an Apache proxying to the Bitwarden instance on localhost.

And another user reported https://github.com/bitwarden/server/issues/1539 as well.
