### ISSUE TITLE
Update script not updated to latest version

### ISSUE THREAD

**Issue by prodigy7** [bitwarden/server#1538]
If you follow the update instructions at https://bitwarden.com/help/article/updating-on-premise/, you do not get the latest version.
The update script contains an older version number: https://raw.githubusercontent.com/bitwarden/server/master/scripts/bitwarden.sh

Latest should be 1.42.1

**Comment by cscharf** [comment]
This is expected, see https://github.com/bitwarden/server/pull/1533
