### ISSUE TITLE
Single Organization policy is preventing owners from creating other Organizations, but not admins

### ISSUE THREAD

**Issue by tangowithfoxtrot** [bitwarden/server#1579]
### Steps To Reproduce

1. Create an Enterprise Organization. Be the owner of the Organization.
2. Enable "Single Organization" policy. For the purposes of testing, it does not matter if the policy is enabled from the Business Portal or the Web Vault.
3. Attempt to create a new Organization.

### Expected Result

[Be able to create another Organization](https://bitwarden.com/help/article/policies/#single-organization)

### Actual Result

You will be prevented from creating the Organization and receive the following error:
```
An error has occurred.
You may not create an organization.
You belong to an organization which
has a policy that prohibits you from
being a member of any other organization.
```

### Screenshots or Videos

![singleOrg](https://user-images.githubusercontent.com/5676771/132866556-d073c039-722c-420d-98b3-5eab68cda37e.png)

### Additional Context

Interestingly, this policy does not seem to prevent admins from creating new Organizations.

### Build Version

1.42.3

### Environment

Cloud (bitwarden.com)

**Comment by eliykat** [comment]
This will be fixed, not in the upcoming (September 2021) release, but in the following release.
