### ISSUE TITLE
Self-hosted: Update was not working

### ISSUE THREAD

**Issue by derritter88** [bitwarden/server#1589]
### Steps To Reproduce

1. Run Bitwarden for a couple of years with a daily cronjob for updating
`@daily /opt/bitwarden/bitwarden.sh updateself`
`@daily /opt/bitwarden/bitwarden.sh update`

### Expected Result

Bitwarden should stay up-to-date and run.

### Actual Result

mssql docker container did not start and therefore the Bitwarded stayed in a degraded statet.

### Additional Context

What I found out and finally solved the issue:
Within `./bwdata/docker/docker-compose.yml` there is an image version number (e.g. `image: bitwarden/mssql:1.42.3`).
I had to manually set it to "latest" so `docker-compose up` downloaded a lot of new images and Bitwarden was okay again.

### Build Version

Docker (can't remember as I have never checked it before)

### Environment

Self-Hosted

### Environment Details

- OS: Ubuntu 20.04
- VM: 8 cores, 24 GB RAM, 233 GB free space (ext4 filesystem)

**Comment by derritter88** [comment]
Okay I have additional crosschecked my former `docker-compose.yml` from a backup and the version numbers would be the same.
Althought it's strange why setting to `latest` is downloading a lot of docker containers.

**Comment by eglyn** [comment]
Same issue here, there is a new version 1.45, and my bitwarden selfhosted says there is no update: 
![image](https://user-images.githubusercontent.com/24936778/146143799-1c516a71-017e-4676-a373-95581ead9c95.png)

When you talk about changing the version to latest into the docker-compose.yml, you did it in all values ? And after this modifications you just launch /bitwarden update ?

**Comment by Scifire** [comment]
@eglyn The self hosted version is still on 1.44.1 until it´s changed here: https://github.com/bitwarden/server/blob/master/scripts/bitwarden.sh

The "why" is explained here: https://github.com/bitwarden/server/issues/1677

**Comment by derritter88** [comment]
> When you talk about changing the version to latest into the docker-compose.yml, you did it in all values ? And after this modifications you just launch /bitwarden update ?

Yes, you need to set every image version to "latest" so Docker knows which image to download.

**Comment by derritter88** [comment]
> @eglyn The self hosted version is still on 1.44.1 until it´s changed here: https://github.com/bitwarden/server/blob/master/scripts/bitwarden.sh
> 
> The "why" is explained here: #1677

Ahhhh thanks for the information!

**Comment by derritter88** [comment]
But my initial issue was that it was not update for a very long time and therefore I was unable to store/modifiy anything at Bitwarden.
