### ISSUE TITLE
Bitwarden 1.42.3 | Identity & Admin restarting every 15 seconds | Unhandled Server Exception

### ISSUE THREAD

**Issue by techwaynorth** [bitwarden/server#1601]
### Steps To Reproduce

After installing Bitwarden 1.42.3, I can't create any account.
Unhandled Server Exception

CONTAINER ID   IMAGE                            COMMAND            CREATED         STATUS                            PORTS                                                                                    NAMES
a5931f44ff33   bitwarden/nginx:1.42.3           "/entrypoint.sh"   5 minutes ago   Up 5 minutes (healthy)            80/tcp, 0.0.0.0:80->8080/tcp, :::80->8080/tcp, 0.0.0.0:443->8443/tcp, :::443->8443/tcp   bitwarden-nginx
2570415ea6df   bitwarden/portal:1.42.3          "/entrypoint.sh"   5 minutes ago   Up 5 minutes (healthy)            5000/tcp                                                                                 bitwarden-portal
80c281d53bb1   bitwarden/admin:1.42.3           "/entrypoint.sh"   5 minutes ago   Restarting (139) 18 seconds ago                                                                                            bitwarden-admin
d494b9747a06   bitwarden/icons:1.42.3           "/entrypoint.sh"   5 minutes ago   Up 5 minutes (healthy)            5000/tcp                                                                                 bitwarden-icons
5bad7b9bcb89   bitwarden/web:2.22.3             "/entrypoint.sh"   5 minutes ago   Up 5 minutes (healthy)                                                                                                     bitwarden-web
a92fe0da468d   bitwarden/api:1.42.3             "/entrypoint.sh"   5 minutes ago   Up 5 minutes (healthy)            5000/tcp                                                                                 bitwarden-api
851d677c68ae   bitwarden/attachments:1.42.3     "/entrypoint.sh"   5 minutes ago   Up 5 minutes (healthy)                                                                                                     bitwarden-attachments
24200f59689d   bitwarden/events:1.42.3          "/entrypoint.sh"   5 minutes ago   Up 5 minutes (unhealthy)          5000/tcp                                                                                 bitwarden-events
4af75d6de675   bitwarden/mssql:1.42.3           "/entrypoint.sh"   5 minutes ago   Up 5 minutes (healthy)                                                                                                     bitwarden-mssql
573cd984bcc8   bitwarden/sso:1.42.3             "/entrypoint.sh"   5 minutes ago   Up 5 minutes (unhealthy)          5000/tcp                                                                                 bitwarden-sso
e3d35391d173   bitwarden/identity:1.42.3        "/entrypoint.sh"   5 minutes ago   Restarting (139) 21 seconds ago                                                                                            bitwarden-identity
c3f15657752c   bitwarden/notifications:1.42.3   "/entrypoint.sh"   5 minutes ago   Up 5 minutes (healthy)            5000/tcp                                                                                 bitwarden-notifications

### Expected Result

Cannot create account

### Actual Result

CONTAINER ID   IMAGE                            COMMAND            CREATED         STATUS                            PORTS                                                                                    NAMES
a5931f44ff33   bitwarden/nginx:1.42.3           "/entrypoint.sh"   5 minutes ago   Up 5 minutes (healthy)            80/tcp, 0.0.0.0:80->8080/tcp, :::80->8080/tcp, 0.0.0.0:443->8443/tcp, :::443->8443/tcp   bitwarden-nginx
2570415ea6df   bitwarden/portal:1.42.3          "/entrypoint.sh"   5 minutes ago   Up 5 minutes (healthy)            5000/tcp                                                                                 bitwarden-portal
80c281d53bb1   bitwarden/admin:1.42.3           "/entrypoint.sh"   5 minutes ago   Restarting (139) 18 seconds ago                                                                                            bitwarden-admin
d494b9747a06   bitwarden/icons:1.42.3           "/entrypoint.sh"   5 minutes ago   Up 5 minutes (healthy)            5000/tcp                                                                                 bitwarden-icons
5bad7b9bcb89   bitwarden/web:2.22.3             "/entrypoint.sh"   5 minutes ago   Up 5 minutes (healthy)                                                                                                     bitwarden-web
a92fe0da468d   bitwarden/api:1.42.3             "/entrypoint.sh"   5 minutes ago   Up 5 minutes (healthy)            5000/tcp                                                                                 bitwarden-api
851d677c68ae   bitwarden/attachments:1.42.3     "/entrypoint.sh"   5 minutes ago   Up 5 minutes (healthy)                                                                                                     bitwarden-attachments
24200f59689d   bitwarden/events:1.42.3          "/entrypoint.sh"   5 minutes ago   Up 5 minutes (unhealthy)          5000/tcp                                                                                 bitwarden-events
4af75d6de675   bitwarden/mssql:1.42.3           "/entrypoint.sh"   5 minutes ago   Up 5 minutes (healthy)                                                                                                     bitwarden-mssql
573cd984bcc8   bitwarden/sso:1.42.3             "/entrypoint.sh"   5 minutes ago   Up 5 minutes (unhealthy)          5000/tcp                                                                                 bitwarden-sso
e3d35391d173   bitwarden/identity:1.42.3        "/entrypoint.sh"   5 minutes ago   Restarting (139) 21 seconds ago                                                                                            bitwarden-identity
c3f15657752c   bitwarden/notifications:1.42.3   "/entrypoint.sh"   5 minutes ago   Up 5 minutes (healthy)            5000/tcp                                                                                 bitwarden-notifications

### Build Version

1.42.3

### Environment

Self-Hosted

**Comment by 766F6964** [comment]
I am experiencing the exact same problem. Did you manage to figure out what is the cause for this?

**Comment by eliykat** [comment]
This may be related to https://github.com/bitwarden/server/issues/1546.

@techwaynorth, if you're still experiencing this issue and the suggestions in that Issue don't help, please contact our Customer Success team for further help. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
