### ISSUE TITLE
Duo 2FA only allows texting code, not push notifications

### ISSUE THREAD

**Issue by Natedude** [bitwarden/server#1640]
### Steps To Reproduce

On my mac (macOS 10.14.6), logging in on Chrome / Brave Bit Warden extension brings up this window:
![Screen Shot 2021-10-17 at 2 17 17 PM](https://user-images.githubusercontent.com/5846465/137645416-09d45e4b-3829-4ca9-bebf-9d6aca19461b.png)

It only allows for texting me codes to login with 2FA.

### Expected Result

I expect it to give me the option to send a push notification to my Duo app on my iPhone.

### Actual Result

No option for push notifications, only texting codes.

### Screenshots or Videos

Actual result:
![Screen Shot 2021-10-17 at 2 17 17 PM](https://user-images.githubusercontent.com/5846465/137645488-d93d51d7-01c5-4844-9158-3b86514ff9aa.png)

Expected something like this
![Screen Shot 2021-10-17 at 2 24 47 PM](https://user-images.githubusercontent.com/5846465/137645556-ca970da0-3137-4cca-be00-9037d2a0fe30.png)
:

### Build Version

Chrome/Brave Bit-Warden extension version: 1.53.0

### Environment

Cloud (bitwarden.com)

### Environment Details

- Mac macOS 10.14.6
- Brave browser V1.30.89
- Chrome browser Version 94.0.4606.81

**Comment by eliykat** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.

**Comment by janstadt** [comment]
Any updates here? I still see this and i was curious if its due to the fact that bitwarden hasnt implemented the universal prompt stuff and is still using the IFRAME technique? https://duo.com/docs/universal-prompt-update-guide#changes-to-support-the-universal-prompt

**Comment by janstadt** [comment]
https://github.com/bitwarden/server/issues/1189
