### ISSUE TITLE
Vault timeout policy requires single org ?!

### ISSUE THREAD

**Issue by Mart124** [bitwarden/server#1689]
### Steps To Reproduce

Hi,

The new _vault timeout_ policy requires the _single organisation_ policy to be enabled.
Why ? Rather strange.

For users in multiple organisation, you should enforce the most restrictive setting (the smallest timeout value) among all his organisations, which is expected from a security rule perspective...
@Hinton, @cscharf, any thoughts ?

Thank you very much 👍

### Expected Result

_Vault timeout_ policy can be enabled without having to enable _single organisation_ policy.

### Actual Result

_Vault timeout_ policy requires _single organisation_ policy to be enabled.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/37041094/140277474-1e385343-b511-4abc-aa74-45705496cd8f.png)

### Build Version

1.44.1

### Environment

Self-Hosted

**Comment by cscharf** [comment]
Hi @Mart124 , I believe this was the most prudent approach at the time to get the policy shipped (it's how we've resolved most policy conflicts). I've added a note to our product team to review adding this to the future backlog for consideration. Thanks for bringing it up, it's much appreciated!

**Comment by Mart124** [comment]
Hi @cscharf, once again, many thanks for your feedback, and your interest into this, really glad !
Let's then stay tuned 👍

**Comment by reliacon-dev** [comment]
This would also be very useful for families who use organizations to separate personal from work-related passwords

**Comment by Mart124** [comment]
Some news perhaps @cscharf from your product team regarding this ?
Many thanks again 👍

**Comment by dwbit** [comment]
Hey @Mart124, thanks for the follow-up. We're tracking this internally so we'll be closing the issue and asking everyone who wants to continue the chat to do so on the [Bitwarden Community Forums](https://community.bitwarden.com/).
