### ISSUE TITLE
Bitwarden queries DNS for mssql every second

### ISSUE THREAD

**Issue by oliverweidel** [bitwarden/server#1745]
### Steps To Reproduce

Not sure why this happens.

### Expected Result

Nothing, this query shouldnt happen.

### Actual Result

Bitwarden queries Pi-hole every second for the dns name "mssql".

### Screenshots or Videos

![Screenshot 2021-12-04 203317](https://user-images.githubusercontent.com/12188221/144722439-aca805d9-294c-4806-aa04-77b37faefe92.png)

### Build Version

1.44.1

### Environment

Self-Hosted

### Environment Details

Bitwarden Docker on Ubuntu 18.04 VM

**Comment by Hinton** [comment]
@oliverweidel That seems odd. Do you know if the mssql service is up and running correctly? I believe Docker falls back to the external dns resolver if it can't find the internal service.

**Comment by djsmith85** [comment]
Hi @oliverweidel, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.

**Comment by kaalph** [comment]
Hello, I'm facing the same issue. After updating my Bitwarden system yesterday, I'm seeing countless entries like this. What can I do about it?

![grafik](https://github.com/bitwarden/server/assets/138721439/f0913996-6b8f-46f5-9a02-063dc3ba2a95)
