### ISSUE TITLE
services.mssql.ulimits.stack.hard must be a integer error when trying to update.

### ISSUE THREAD

**Issue by trrbentley** [bitwarden/server#1757]
### Steps To Reproduce

1. ./bitwarden.sh updateself
2. ./bitwarden.sh update

### Expected Result

Bitwarden updates as expected...

### Actual Result

I get the following message:
services.mssql.ulimits.stack.hard must be a integer

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/30841872/145693382-b6a1f55b-2a36-43e0-84e6-f38cc0ca6016.png)
![image](https://user-images.githubusercontent.com/30841872/145693446-ad2c9c34-3cc9-431e-adf0-54e218f3c18a.png)

### Build Version

Server Version: 1.41.5 / Web version: 2.21.1

### Environment

Self-Hosted

### Environment Details

- Operating System: Unraid 6.9.2
- Environment: Docker

**Comment by djsmith85** [comment]
Hi @trrbentley,

This seems to be an issue with the Docker environment you are running on, which might be specific to UnRaid.
I found an old issue where a user was experiencing something similar while trying to create backups here https://github.com/bitwarden/server/issues/856. In that issue there is a link to a thread in the unraid-forums talking about setting ulimits (also while setting up Bitwarden). Please have a look here: https://forums.unraid.net/topic/82110-mssql-docker-on-unraid/

If you are able to resolve this via the links provided, please report back and close this issue.

Kind Regards,
Daniel

**Comment by trrbentley** [comment]
Daniel,

Thanks for the link, I don't think that's the issue I'm having, however.

I already added the memory limits for mssql when I was encountering the problem in the link, here's a snippet my docker-compose.override file:

![image](https://user-images.githubusercontent.com/30841872/145751635-5fd28ff3-e4c2-4ae9-86fb-120061ec918f.png)

It's almost as if the values that are being referenced are not considered an 'integer' when calling the bitwarden.sh script...

**Comment by trrbentley** [comment]
I should have figured the fix would be easy just by looking at the error...

Removed the quotes from the soft/hard values, script works okay now.

![image](https://user-images.githubusercontent.com/30841872/145915877-478707b0-6aca-4311-91e8-504dce6b04aa.png)
