### ISSUE TITLE
Web version mismatch

### ISSUE THREAD

**Issue by JensSpanier** [bitwarden/server#1769]
### Steps To Reproduce

1. Install latest update for selfhosted
2. Compare installed Docker version with version displayed in web UI

### Expected Result

Should be the same

### Actual Result

Docker version: `2.25.0`
Version printed in web UI: `2.24.4`

### Screenshots or Videos

`docker ps`:
![Bildschirmfoto 2021-12-15 um 17 53 51](https://user-images.githubusercontent.com/42373861/146229900-ed31d4fb-f8d3-4348-8aaf-c49409610a26.png)
Admin interface:
![image](https://user-images.githubusercontent.com/42373861/146229943-3c0bda29-88fd-4408-bc9c-afb97a217ab2.png)

### Build Version

Web: `2.25.0`

### Environment

Self-Hosted

### Environment Details

- OS: Ubuntu 20.04
- Environment: Docker

**Comment by tykisson** [comment]
Same issue here on two different installs I'm running. One a family account the other Enterprise.
The bitwarden.sh script shows the correct webversion 2.25.0 but it does not install.

**Comment by MonkeyTonk** [comment]
Same here on Enterprise account.

**Comment by anhyzer5525** [comment]
Reporting the same issue here as well. Same exact steps followed as the initial report.

VERSION
Server Installed
1.45.2 
Server Latest
1.45.2
Web Installed
2.24.4 
Web Latest
2.25.0

**Comment by Hinton** [comment]
Hi all,

We've confirmed that the docker container for web 2.25.0 incorrectly reported itself as 2.24.4. This should now be fixed and a new docker container has been released with the same tag. I believe restarting the server should resolve the issue.

Let me know if this works so we can close this issue.

**Comment by JensSpanier** [comment]
Thanks for the quick fix.

`./bitwarden.sh restart` resolved the issue.
