### ISSUE TITLE
Web doesn't update when Server is up to date

### ISSUE THREAD

**Issue by Flashbin** [bitwarden/server#1786]
### Steps To Reproduce

Try to update Bitwarden when Server is up to date, but there is a newer version of Web.

### Expected Result

Web version should get updated.

### Actual Result

bitwarden.sh tells me that update is not needed:

```
bitwarden.sh version 1.45.2
Docker version 20.10.12, build e91ed57
docker-compose version 1.28.6, build 5db8d86f

Update not needed
```

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/63650660/147405493-5b0919f8-e547-42b1-bf19-8af9691dfbb5.png)

### Additional Context

`updateself` was executed successfully before `update`, and bitwarden.sh has the new Web 2.25.0 version:

```
# Please do not create pull requests modifying the version numbers.
COREVERSION="1.45.2"
WEBVERSION="2.25.0"
```

Until now, every time I updated bitwarden, both Web and Server had a newer versions. So I don't now if this has ever worked or if it's even supposed to work.

### Build Version

bitwarden.sh version 1.45.2 Docker version 20.10.12, build e91ed57 docker-compose version 1.28.6, build 5db8d86f

### Environment

Self-Hosted

### Environment Details

- Operating system: Debian 10.11 (Kernel 4.19)
- Environment: Docker
- Hardware: bhyve VM (2 AMD Ryzen Cores, 3GB RAM)

**Comment by sso-bitwarden** [comment]
Could you please check the "docker ps" result whether you're running 2.25.0? Looks like there is an issue with the admin page.

**Comment by Flashbin** [comment]
```
CONTAINER ID   IMAGE                            COMMAND            CREATED       STATUS                PORTS                                                                                    NAMES
bc3c24642d77   bitwarden/nginx:1.45.2           "/entrypoint.sh"   2 weeks ago   Up 8 days (healthy)   80/tcp, 0.0.0.0:80->8080/tcp, :::80->8080/tcp, 0.0.0.0:443->8443/tcp, :::443->8443/tcp   bitwarden-nginx
eca3d5ef2d34   bitwarden/admin:1.45.2           "/entrypoint.sh"   2 weeks ago   Up 8 days (healthy)   5000/tcp                                                                                 bitwarden-admin
fd8d468891d1   bitwarden/sso:1.45.2             "/entrypoint.sh"   2 weeks ago   Up 8 days (healthy)   5000/tcp                                                                                 bitwarden-sso
50b450b41099   bitwarden/identity:1.45.2        "/entrypoint.sh"   2 weeks ago   Up 8 days (healthy)   5000/tcp                                                                                 bitwarden-identity
75e9c98eb966   bitwarden/api:1.45.2             "/entrypoint.sh"   2 weeks ago   Up 8 days (healthy)   5000/tcp                                                                                 bitwarden-api
0c9b30dab51f   bitwarden/icons:1.45.2           "/entrypoint.sh"   2 weeks ago   Up 8 days (healthy)   5000/tcp                                                                                 bitwarden-icons
64379d49408b   bitwarden/web:2.25.0             "/entrypoint.sh"   2 weeks ago   Up 8 days (healthy)                                                                                            bitwarden-web
632847647ddf   bitwarden/notifications:1.45.2   "/entrypoint.sh"   2 weeks ago   Up 8 days (healthy)   5000/tcp                                                                                 bitwarden-notifications
e95ef41b7dc1   bitwarden/events:1.45.2          "/entrypoint.sh"   2 weeks ago   Up 8 days (healthy)   5000/tcp                                                                                 bitwarden-events
0e4ef31c094c   bitwarden/attachments:1.45.2     "/entrypoint.sh"   2 weeks ago   Up 8 days (healthy)                                                                                            bitwarden-attachments
9f57b10adc88   bitwarden/mssql:1.45.2           "/entrypoint.sh"   2 weeks ago   Up 8 days (healthy)                                                                                            bitwarden-mssql
```
@sso-bitwarden You're right, i'm already running 2.25.0. Then there's an issue with the admin page.

**Comment by ilkevinli** [comment]
Hi,
     Just want to add I am seeing the same thing. I just spent the last 15 minutes trying to see why the admin page was showing version 2.24.0 even though I am getting the "update not needed" message. Then checked the issues section and found this post.

**Comment by Hinton** [comment]
It's possible this might be related to our incorrectly tagged web release that incorrectly identified itself as v2.44.4. See https://github.com/bitwarden/server/issues/1769 for more information.

Users reported suceess with running `./bitwarden.sh restart`.

**Comment by ilkevinli** [comment]
> It's possible this might be related to our incorrectly tagged web release that incorrectly identified itself as v2.44.4. See #1769 for more information. We released a fixed release on dockerhub which should be found by docker during the next restart.
> 
> Users reported success with running `./bitwarden.sh restart`.

After running the restart command, I am now seeing the proper version of 2.25.0. Thank you.

**Comment by Flashbin** [comment]
> It's possible this might be related to our incorrectly tagged web release that incorrectly identified itself as v2.44.4. See #1769 for more information. We released a fixed release on dockerhub which should be found by docker during the next restart.
> 
> Users reported success with running `./bitwarden.sh restart`.

For me too, thanks.
