### ISSUE TITLE
bitwarden.sh update, self hosted, no such service: key-connector

### ISSUE THREAD

**Issue by g1bs0nsg** [bitwarden/server#1788]
### Steps To Reproduce

./bitwarden.sh updateself
./bitwarden.sh update

### Expected Result

Bitwarden updates to latest version

### Actual Result

ERROR: No such service: key-connector

### Screenshots or Videos

`
bitwarden@docker:/opt/bitwarden$ ./bitwarden.sh updateself
 _     _ _                         _
| |__ (_) |___      ____ _ _ __ __| | ___ _ __
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2021, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

bitwarden.sh version 1.45.2
Docker version 20.10.12, build e91ed57
docker-compose version 1.27.4, build 40524192

Updated self.
bitwarden@docker:/opt/bitwarden$ ./bitwarden.sh update
 _     _ _                         _
| |__ (_) |___      ____ _ _ __ __| | ___ _ __
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2021, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

bitwarden.sh version 1.45.2
Docker version 20.10.12, build e91ed57
docker-compose version 1.27.4, build 40524192

ERROR: No such service: key-connector
`

### Additional Context

In config.yml:
enable_key_connector: false

I assume this is related to: https://github.com/bitwarden/server/pull/1784

and maybe this is expected behavior?  But I was thinking it should come back with "Update not needed" or continuing to execute the remaining commands in the function in run.sh, but it appears to just exit out right there. 

### Build Version

bitwarden.sh version 1.45.2

### Environment

Self-Hosted

### Environment Details

Debian Buster
bitwarden.sh version 1.45.2
Docker version 20.10.12, build e91ed57
docker-compose version 1.27.4 build 40524192

**Comment by ryanmaffit** [comment]
I also ran into this issue today, I was able to work around it by downloading the version of bitwarden.sh from the tagged git version for 1.45.2 using `wget https://raw.githubusercontent.com/bitwarden/server/v1.45.2/scripts/bitwarden.sh` (also need to `chmod +x` the file if you are on linux) and modifying the GITHUB_BASE_URL variable from `GITHUB_BASE_URL="https://raw.githubusercontent.com/bitwarden/server/master` to `GITHUB_BASE_URL="https://raw.githubusercontent.com/bitwarden/server/v1.45.2"`.

**Comment by joseph-flinn** [comment]
Patch in to fix this issue: https://github.com/bitwarden/server/pull/1789
