### ISSUE TITLE
Protocol uses bodies for responses to methods without response bodies.

### ISSUE THREAD

**Issue by Icelk** [bitwarden/server#1793]
### Steps To Reproduce

When editing an item, a `PUT` request is issued. Bitwarden depends on the body of the response.
According to [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT), a successful response shouldn't have a body.

### Expected Result

There should be no body.

### Actual Result

There is a body, which can cause issues for reverse-proxies which rely on the standards to optimize data transfer, as mine did.

### Screenshots or Videos

The request for changing an item:
![screenshot-2022-01-03-15:57:19](https://user-images.githubusercontent.com/62830417/147945656-c03bda7c-3876-451b-aae4-09369f58eb80.png)

The response, with data:
![screenshot-2022-01-03-15:58:02](https://user-images.githubusercontent.com/62830417/147945663-75f81d6e-00b1-4727-86ff-7db95000f8f1.png)

### Build Version

Actually Vaultwarden (v1.23.1), though, this is an issue with the protocol, which all clients & servers use.

### Environment

Self-Hosted

**Comment by Hinton** [comment]
Hi @Icelk,

Thanks for letting us know about this. From reading the [spec](https://httpwg.org/specs/rfc7231.html#PUT) there doesn't seem to be anything that forbids a PUT request to contain a response. It suggests using either 200 or 204, a 204 response should definitely not contain any content.

[RFC2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html#sec9.6) goes further into details and has the following statement:
>  The action performed by the POST method might not result in a resource that can be identified by a URI. In this case, either 200 (OK) or 204 (No Content) is the appropriate response status, depending on whether or not the response includes an entity that describes the result. 

Which lends credibility to PUT request being allowed to contain the entity.

**Comment by Icelk** [comment]
Thanks for the clarification!
