### ISSUE TITLE
Api key UI missing in self hosted web vault

### ISSUE THREAD

**Issue by lsim** [bitwarden/server#1804]
### Steps To Reproduce

1. Log into my self host web vault (v. 1.45.2)
2. Go to Settings -> My account
3. Scroll down to the bottom

### Expected Result

According to the [docs](https://bitwarden.com/help/article/personal-api-key/), I should see an 'API key' section at (or near?) the bottom.

### Actual Result

I do not see any api key section

### Screenshots or Videos

![CleanShot 2022-01-11 at 11 38 22](https://user-images.githubusercontent.com/5108355/148927680-c904ddc2-48f5-48b5-b041-f60d8fd45d78.png)

### Additional Context

I expect I am missing something obvious. Maybe it's a simple matter of updating the docs if the api key is now to be found somewhere else?

### Build Version

1.45.2

### Environment

Self-Hosted

### Environment Details

- Centos 7
- Docker (via standard bitwarden.sh setup)

**Comment by lsim** [comment]
Forgot to say - the screenshot shows the bottom of my 'My account' page.

**Comment by Greenderella** [comment]
Hi @lsim, you must log into your Web Vault: **https://vault.bitwarden.com/#/**, not into your Self Hosted Vault: https://bitwarden.YOURURL.com/#/ in order to retrieve your API Key.

Let us know how it goes.

**Comment by lsim** [comment]
Thank you for a quick reply. It probably confused me that the docs interchangeably refer to the global and my local backend as 'Bitwarden webvault'. 

It's been years since I set up my local instance and I forgot I even had a login to the global bitwarden server. Thankfully, I have a great mechanism for remembering such things :D

**Comment by lsim** [comment]
Incidentaly, if I obtain the api key on the global webvault - will it work against my self hosted backend? So far it doesn't appear so.

I'm trying to get the Bitwarden extension to the RayCast osx launcher working. 

I installed bitwarden cli (which it depends on) and configured it with my self host backend url

RayCast accepted my client id and client secret, but rejects my master password (both the one for my own and for the global webvaults) 🤷
