### ISSUE TITLE
Invite email vs registration email is case sensitive when creating account

### ISSUE THREAD

**Issue by Screemonster** [bitwarden/server#1805]
### Steps To Reproduce

1. Send invitation to an email address containing uppercase characters
2. Have invited user open invitation link and click "create account"
3. Fill out account creation form with email/password and submit

### Expected Result

For the registration to disregard uppercase characters in emails in all cases, for both the invitation email and registration email.

### Actual Result

The registration email is sanitised to lowercase (and becomes lowercase on the screen when the user hits "submit") but account creation fails with an error message stating that the registration email does not match the invite email, even where the email address field is automatically filled in.

### Operating System

Windows

### Web Browser

Firefox

### Build Version

2.21.1

**Comment by Hinton** [comment]
Moved to server.

**Comment by Hinton** [comment]
Hi @Screemonster,

I'm unable to replicate this. I've tried the following things:
* Invite a user with capital letter in email.
  * Create an account using the suggested email (all lowercase), login.
  * Create an account using the invited email (capital letter), login.
* Invite a user with lowercase email, create an account with capital letter in the email, login.

Can you please provide instructions on how to replicate this, which server version you are using, and is it self-hosted or cloud?

**Comment by Screemonster** [comment]
Unfortunately this was at work and I was only on the user end of things, so I'm not able to fully test it.

**Comment by Hinton** [comment]
Closing this as not reproduce-able, Version 2.21.1 is a fairly outdated version of the web vault as well.

If the problem still occurs with the latest version of the server and web vault please let me know along with steps to reproduce it.
