### ISSUE TITLE
1.45.3 not being pulled by bitwarden.sh

### ISSUE THREAD

**Issue by q7joey** [bitwarden/server#1823]
### Steps To Reproduce

./bitwarden.sh updateself
./bitwarden.sh update

### Expected Result

update to 1.45.3

### Actual Result

# ./bitwarden.sh  update
 _     _ _                         _
| |__ (_) |___      ____ _ _ __ __| | ___ _ __
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2022, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

bitwarden.sh version 1.45.2
Docker version 1.13.1, build 7d71120/1.13.1
docker-compose version 1.18.0, build 8dd22a9

Update not needed

### Additional Context

it has been two weeks since the release was made. seems like it should be available by now.

### Build Version

1.45.2

### Environment

Self-Hosted

### Environment Details

CentOS 7

**Comment by anhyzer5525** [comment]
This is known as they always delay updating self-hosted instances until they are sure there is no show stopping bugs.

**Comment by q7joey** [comment]
i haven't looked at all previous versions, but two weeks seemed longer than "normal". and now it is probably more like 3 weeks.

**Comment by anhyzer5525** [comment]
> i haven't looked at all previous versions, but two weeks seemed longer than "normal". and now it is probably more like 3 weeks.

I agree with you as they normally only wait a week. The most recent update may only apply to their hosted instance which could be why they did not push the update for us yet. Either way we just have to wait on them.

**Comment by gschoenberger** [comment]
We are currently having troubles with syncing LDAP groups to our self hosted bitwarden server.
I digged into some commits and I am thinking this should be fixed with 1.45.3?
- https://github.com/bitwarden/server/pull/1642
We cannot sync as the directory connector only returns with the error message "Cannot autoscale on self-hosted instance.".

I also tried to pull the 1.45.3 images via bitwarden.sh but as you said we do not get them right now.
This is really uncomfortable for us as we cannot update password/group mappings...

**Comment by haneef95** [comment]
the update script uses this line to check for the latest version:
https://github.com/bitwarden/server/blob/1b233370eb8c2887312376bbfceb7310e3aaf32b/scripts/bitwarden.sh#L37

Instead, it would be better if it could check the Github releases/Docker registry for the latest version, as many at times, that script doesn't have the latest version number.

**Comment by eliykat** [comment]
Server 1.45.3 is scheduled for release Thursday next week (US time).
