### ISSUE TITLE
Update Key - Error: "The PrivateKey field is required." [SELF-HOST]

### ISSUE THREAD

**Issue by darkson95** [bitwarden/server#1861]
### Steps To Reproduce

1. Go to Start-Page
2. Click on 'Update Encryption Key'
3. Enter Master Password
4. Click on 'Update Encryption Key'

### Expected Result

After the update to the last version Bitwarden wants to update the encryption scheme/key. I enter my Master Password and expect, that the key should change.

### Actual Result

After I entered my Master Password I get the following error message:
> The PrivateKey field is required.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/11984325/153559736-1bdb0952-d541-4557-896e-1742f180f702.png)
![image](https://user-images.githubusercontent.com/11984325/153559789-87703570-52aa-4778-b5ee-22682fd7a182.png)
![image](https://user-images.githubusercontent.com/11984325/153559870-9e51d8c2-150c-4e70-bffa-ed6d46bc27aa.png)

![image](https://user-images.githubusercontent.com/11984325/153559921-d0376880-e646-40bc-bfce-e1e7c5d66099.png)

### Additional Context

There is something weird too:
On the Bitwarden-StartPage it says "There are no items to list.", but on the mobile App and Browser Extension I can see all my entries. Even if I log out and re login.

### Build Version

Version 2.26.1

### Environment

Self-Hosted

### Environment Details

OS: Ubuntu 
Env: Docker

**Comment by Hinton** [comment]
Hi @darkson95,

Could you provide what server version you are using as well?

**Comment by darkson95** [comment]
I thought I have all containers on "latest", but bitwarden/web got one update 8 hours ago. After I pulled the new image and restarted all bitwarden containers, I was able to update the key.

After that the chrome extension did some problems, but after reinstall of the extension everything works fine again! :)
