### ISSUE TITLE
Cannot autoscale on self-hosted instance

### ISSUE THREAD

**Issue by gschoenberger** [bitwarden/server#1883]
### Steps To Reproduce

1. Go to 'Bitwarden Directory Connector'
2. Click on 'Sync now'

### Expected Result

LDAP users and groups should be synced

### Actual Result

Popup with error appears, users and groups are not synced

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/1648307/155474273-25a010f6-5416-4326-893e-875bf619841a.png)

### Build Version

1.46.2

### Environment

Self-Hosted

### Environment Details

REPOSITORY                TAG       IMAGE ID       CREATED         SIZE
bitwarden/identity        1.46.2    d87aa356dcf0   6 days ago      427MB
bitwarden/mssql           1.46.2    392936d1f84e   6 days ago      1.4GB
bitwarden/notifications   1.46.2    3b8dd235f088   6 days ago      429MB
bitwarden/admin           1.46.2    07128111ccd5   6 days ago      459MB
bitwarden/sso             1.46.2    b31b8dede02b   6 days ago      432MB
bitwarden/api             1.46.2    a0ebe8ea0f7f   6 days ago      433MB
bitwarden/icons           1.46.2    f04ac08db38b   6 days ago      281MB
bitwarden/nginx           1.46.2    5641636a475b   6 days ago      144MB
bitwarden/events          1.46.2    c51a3c8b0b95   6 days ago      427MB
bitwarden/setup           1.46.2    0fe8c4000380   6 days ago      269MB
bitwarden/attachments     1.46.2    28eb81b549cc   6 days ago      209MB
bitwarden/web             2.26.1    0fbfdc824610   12 days ago     243MB
bitwarden/setup           1.45.4    a9562ff82c34   2 weeks ago     283MB
bitwarden/setup           1.45.2    01e915e2e01f   2 months ago    283MB
bitwarden/setup           1.39.4    5d7e198fee12   12 months ago   279MB

**Comment by gschoenberger** [comment]
THX for the fast update!
As we are heavily using the password share feature over collections in connection with our LDAP groups, it is quite important for us having LDAP in sync.
Any chance to get the feature back if we change our subscription?
Or is there a time horizon we get the feature back on our self hosted instance?

**Comment by Hinton** [comment]
Hi @gschoenberger,

Just for clarification, the error message is to inform you that the organizaiton has run out of available seats, and that the auto scaling failed due to the organization being self-hosted. Increasing the seat count and updating the license manually same as before should stil work.

If you still encounter this issue with available seats please let us know.

**Comment by gschoenberger** [comment]
So all I have to do is add a new seat and update the license?
Currently we have all seats used - to get the LDAP sync feature working correctly I always have to keep one spare seat?

**Comment by Hinton** [comment]
This is a bit outside my expertise, but there should only need to to have available seats if the LDAP sync determines that it should invite additional users per https://github.com/bitwarden/server/blob/master/src/Core/Services/Implementations/OrganizationService.cs#L1111. Are you getting the error for a sync which is not attempting to add new users to the organization?

**Comment by gschoenberger** [comment]
OK great!
We now have a dedicated group for our bitwarden users which is matching our subscription users count.
Sync is working again =)
THX for your help
