### ISSUE TITLE
Server Error (self-hosted) when adding WebAuthn key to Web Vault on Firefox

### ISSUE THREAD

**Issue by Ayitaka** [bitwarden/server#1926]
### Steps To Reproduce

1. Open up latest version of Firefox (v98.0.2 64-bit) browser for Windows (10 Pro v21H2 Build 19044.1586), navigate to self-hosted Web Vault (v2.27.0) and login to your account on self-hosted Bitwarden Server (v1.47.1)
2. Go to 'Settings' and then "Two-step Login' in the Web Vault
3. Click on 'Manage' next to WebAuthn/FIDO2 WebAuthn and enter master password
4. Type a unique name in the 'Name' field.
5. Insert security key (I tried with 1x Yubikey 5 NFC, 2x Yubikey 5 Ci, and 2x Yubico Blue Security Key)
6. Click 'Read Key'
7. If Windows Hello popup appears, click 'Cancel'
8. Click 'OK' if Security Key Setup popup appears.
9. Touch metal key tabs (enter PIN if required and touch metal key tabs again)
10. WebAuthn screen will now display green check mark with 'Click the "Save" button below to enable this security key for two-step login. '
11. Click 'Save'

### Expected Result

New key name will be displayed in the next unused key slot and green success notification will be shown in upper right corner.

### Actual Result

No key is added to the list and red error notification is displayed in the upper right corner which reads:

``An error has occured.``
``An unhandled server error has occured.``

### Additional Context

Note: When I tried adding keys in Chrome it works just fine with my original settings, so I am inclined to believe this is either a Firefox-side problem with WebAuthn or a problem with Bitwarden specific to Firefox.

Not sure when this began since I have not had to add security keys in quite awhile.

At first I thought it was an error specific to me. I removed all Firefox extensions and tried again. Same result.

I searched Google, Issues here, Bitwarden Community Forums, and reddit for anything similar and the only matching problem/issues had to do with the global.override.env file using http instead of https for some settings, which was not applicable since all my settings used https. I also requested a new globalSettings__yubico__clientId and globalSettings__yubico__key, even though Yubico OTP worked just fine and it is my understanding that those settings have no relationship to WebAuthn. And finally, I used the On-Premise Hosting FAQ, step-by-step, to install a fresh copy of Bitwarden, with all default settings and newly generated IDs on a local VM running the latest stable version of Debian freshly installed and default as well, which had the same result.

Following are the available error messages/logs I could find. If there are any other places I should look please let me know and I will add the info (in spoiler form, click to view).

<details>
  <summary>Firefox Developer Console</summary>

- 11:43:51.357 Unchecked lastError value: Error: Could not establish connection. Receiving end does not exist. 2 background.js:1
    send moz-extension://e3c5bc6a-e27e-49c0-b630-95c141cf95b0/background.js:1
- 11:43:54.816 LoginRecipes: getRecipes: falling back to a synchronous message for: https://vault.XXXX.com LoginRecipes.jsm:295:9
- 11:43:54.816 TypeError: gRecipeManager is null LoginManagerParent.jsm:136:3
- 11:43:54.819 XHRPUThttps://vault.XXXX.com/api/two-factor/webauthn
[HTTP/2 500 Internal Server Error 2399ms]
- 11:43:57.222 Received API exception: [object Object] main.a65ba012eb7ad84a4c86.js:1:820925
- 11:43:57.224 <unavailable> main.a65ba012eb7ad84a4c86.js:1:820925

</details>

<details>
  <summary>Bitwarden docker logs</summary>

- bitwarden-api    | fail: Bit.Api.Utilities.ExceptionHandlerFilterAttribute[0]
- bitwarden-api    |       => SpanId:b748e424c879124d, TraceId:47c6c2e508d8024091f9b01b0fa12e17, ParentId:0000000000000000 => ConnectionId:0HMGF5ELM3M07 => RequestPath:/two-factor/webauthn RequestId:0HMGF5ELM3M07:00000002 => Bit.Api.Controllers.TwoFactorController.PutWebAuthn (Api)
- bitwarden-api    |       Specified argument was out of the range of valid values. (Parameter 'start')
- bitwarden-api    |       System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'start')
- bitwarden-api    |          at Fido2NetLib.Objects.AttestedCredentialData..ctor(ReadOnlyMemory`1 data, Int32& bytesRead)
- bitwarden-api    |          at Fido2NetLib.Objects.AuthenticatorData..ctor(Byte[] authData)
- bitwarden-api    |          at Fido2NetLib.AuthenticatorAttestationResponse.VerifyAsync(CredentialCreateOptions originalOptions, Fido2Configuration config, IsCredentialIdUniqueToUserAsyncDelegate isCredentialIdUniqueToUser, IMetadataService metadataService, Byte[] requestTokenBindingId)
- bitwarden-api    |          at Fido2NetLib.Fido2.MakeNewCredentialAsync(AuthenticatorAttestationRawResponse attestationResponse, CredentialCreateOptions origChallenge, IsCredentialIdUniqueToUserAsyncDelegate isCredentialIdUniqueToUser, Byte[] requestTokenBindingId)
- bitwarden-api    |          at Bit.Core.Services.UserService.CompleteWebAuthRegistrationAsync(User user, Int32 id, String name, AuthenticatorAttestationRawResponse attestationResponse)
- bitwarden-api    |          at Bit.Api.Controllers.TwoFactorController.PutWebAuthn(TwoFactorWebAuthnRequestModel model) in /home/runner/work/server/server/src/Api/Controllers/TwoFactorController.cs:line 248
- bitwarden-api    |          at lambda_method203(Closure , Object )
- bitwarden-api    |          at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
- bitwarden-api    |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
- bitwarden-api    |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
- bitwarden-api    |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
- bitwarden-api    |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
- bitwarden-api    |          at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
- bitwarden-api    |          at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
</details>

### Build Version

server 1.47.1, web vault 2.27.0

### Environment

Self-Hosted

### Environment Details

Debian GNU/Linux 10 (buster) running on VPS with docker
Debian GNU/Linux 11 (bullseye) running on Hyper-V VM with docker

Edit: Just wanted to add that trying on a different computer, running Windows 11 and fresh install of Firefox results in the same error.

**Comment by Hinton** [comment]
Hi @Ayitaka,

Do you know if the same WebAuthn keys works on the cloud environment? Should let us figure out if it's an environment issue or something different.

**Comment by Ayitaka** [comment]
@Hinton 

My apologies. It also does not work on the cloud environment. But upon further testing I believe this is an issue with Firefox and/or my installation of Firefox. Registering the same keys on Github and Gmail also does not work, but again works fine in Chrome. I also tried the most recent beta version of Firefox with the same results. I will need to look elsewhere for a solution to this, but it has nothing to do with Bitwarden.

**Comment by Hinton** [comment]
@Ayitaka Thanks for following that up. Hopefully you will find out whats wrong.
