### ISSUE TITLE
OFFLINE Self-Hosted Server Browser Extension Issue

### ISSUE THREAD

**Issue by robbie2121** [bitwarden/server#1946]
### Steps To Reproduce

1) Disable internet to Self-Hosted Bitwarden server (Mine is on VM)
2) Try to login on Chrome or Firefox Bitwarden extension add on (on any computer client or even on the same server)
3) First attempt will hang, then fail (fail to fetch error)
4) Second login attempt always works

### Expected Result

Successful login via the bitwarden browser extension on first attempy

### Actual Result

Hangs on first login attempt, then fails eventaully. Second attempt works every time.

### Build Version

Latest Version of docker, Bitwarden server, Chrome, Firefox and bitwarden extensions

### Environment

Self-Hosted

### Environment Details

Bitwarden server is installed on a proxmox virtual machine
Bitwarden Server is on latest Ubuntu version (But issue also occurs with Windows - as I previously had it server installed on Windows and had the same issue)
virtual machine has internet disabled via pfsense firewall rule

**Comment by PichlAlex** [comment]
Hi Robbie2121,

please provide all applicable pfSense Firewall rules.

i am assuming that you have it on "drop" -> change it to reject and this should be solved.
or remove the standard gateway and DNS in your VM.

Thanks a lot!

**Comment by robbie2121** [comment]
> Hi Robbie2121,
> 
> please provide all applicable pfSense Firewall rules.
> 
> i am assuming that you have it on "drop" -> change it to reject and this should be solved. or remove the standard gateway and DNS in your VM.
> 
> Thanks a lot!

I think that did it. Thanks PichlAlex!!!
