### ISSUE TITLE
MSSQL database is not starting

### ISSUE THREAD

**Issue by n-e-g** [bitwarden/server#2083]
### Steps To Reproduce

Creating self-hosted bitwarden installation fails due to database startup failure
Environment:
bitwarden.sh: 2022.5.2
Docker version 20.10.5+dfsg1, build 55c4c88,
Host OS: Linux 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux

### Expected Result

Installation script completes successfully,
License is accepted and whole environment is created
Expecting environment to run or at least show welcome screen

### Actual Result

Bitwarden fails to operate due to database startup failure.
The mssql image fails constantly with log message:

`This program has encountered a fatal error and cannot continue running at Sat Jun 25 18:44:51 2022
The following diagnostic information is available:

         Reason: 0x00000006
        Message: PROCESS_FAULT_FLAGS_UNHANDLED_EXCEPTION: The process [sqlservr.exe ] has encountered an unhandled exception.
        Address: 0x6bc0335e
    Stack Trace:
                 000000006bd358de
                 000000006bc535d7
                 000000006bc0335e
                 000000006bd74348
                 000000098012c33f
                 000000098012b443
                 000000098012aecd
                 00000009800f4f5b
                 00000009800dd6c6
                 00000009800f1ddd
                 0000000980056de6
                 00000009800f0cbe
                 0000000989b531f3
        Process: 36 - sqlservr
         Thread: 118 (application thread 0x154)
    Instance Id: d320f310-41d9-4601-9dff-aa030c35fb6e
       Crash Id: 985d2852-03f2-4c3e-a0b2-716b40a6d0fd
    Build stamp: dcb1eac7fc5581ee21b21e5ba567c25535309d02a31d13737fe4e671d070afe5
   Distribution: Ubuntu 16.04.6 LTS
     Processors: 4
   Total Memory: 16786255872 bytes
      Timestamp: Sat Jun 25 18:44:51 2022
     Last errno: 19
Last errno text: No such device`

### Build Version

 2022.5.2

### Environment

Self-Hosted

### Environment Details

bitwarden.sh: 2022.5.2
Docker version 20.10.5+dfsg1, build 55c4c88,
Host OS: Linux 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux

**Comment by dbosompem** [comment]
Hi @n-e-g , sorry to hear about this! Can you share any additional logs as the present logs does not seem to indicate where error could be?

**Comment by marek-budyn** [comment]
Please find attached all logfiles I have managed to get.
Sorry for sipfile but they take too much space to include directly.

[mssql.log.zip](https://github.com/bitwarden/server/files/9077321/mssql.log.zip)

**Comment by n-e-g** [comment]
> Hi @n-e-g , sorry to hear about this! Can you share any additional logs as the present logs does not seem to indicate where error could be?

Please find logs attached.
Sorry for zipfile, but uncompressed logs takes 2.5MB

[mssql.log.zip](https://github.com/bitwarden/server/files/9077325/mssql.log.zip)

**Comment by cnl25sys** [comment]
Same issue here, in a new installation.  Version 2022.6.2 (Docker 20.10.17, Compose 2.6.0)

Admin and SSO containers are Unhealthy, I see in their log files that they cannot reach the MSSQL 1433 port.  
MSSQL log file shows:
Service Master Key could not be decrypted using one of its encryptions. See sys.key_encryptions for details.
An error occurred during Service Master Key initialization. SQLErrorCode=33095, State=8, LastOsError=0.


Kind regards

**Comment by dbosompem** [comment]
Hello @cnl25sys, sorry for the inconvenience, could you kindly contact our [official support team](https://bitwarden.com/contact/) for further investigation?
