### ISSUE TITLE
MS SQL Database does not backup by default when you use a custom DB Name

### ISSUE THREAD

**Issue by fragglerock015** [bitwarden/server#2181]
### Steps To Reproduce

From a clean install when prompted for a DB Name (default being "vault") & enter a custom name e.g. "random_db" the automated nightly backup fails.

If you add a line to "mssql.override.env" 

DATABASE=random_db

it then works.

This should be set by default in the install and not randomly discovered that backups are not working.

### Expected Result

MS SQL Backups to work. 

### Actual Result

No backups.

### Build Version

2022.6.2 (and all prior)

### Environment

Self-Hosted

### Environment Details

Ubuntu 20.04

Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:02:57 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:03 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.7
  GitCommit:        0197261a30bf81f1ee8e6a4dd2dea0ef95d67ccb
 runc:
  Version:          1.1.3
  GitCommit:        v1.1.3-0-g6724737
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by djsmith85** [comment]
Hi @fragglerock015 and thank you for your report.

This is a known issue and is being tracked with https://github.com/bitwarden/server/issues/1811.

Closing this now, as duplicate.
