### ISSUE TITLE
Push notifications for organization items ?

### ISSUE THREAD

**Issue by Mart124** [bitwarden/server#220]
Hi,

Push notifications work like a charm for "private" items.

However, sounds like they do not handle organization items ?
For example when a collection password is added / removed / modified... collection is not refreshed in (for example) the iOS app.

Thx !

**Comment by kspearrin** [comment]
Push notifications should already work for organization items (logins, notes, etc) in your vault. They do not work for things like changing a collection name though. Is this not what you re seeing?

**Comment by Mart124** [comment]
Perhaps here is the explanation ?

https://github.com/bitwarden/core/blob/v1.19.0/src/Core/Services/Implementations/NotificationHubPushNotificationService.cs#L46 :
_We cannot send org pushes since access logic is much more complicated than just the fact that they belong to the organization. Potentially we could blindly send to just users that have the access all permission device registration needs to be more granular to handle that appropriately. A more brute force approach could me to send "full sync" push to all org users, but that has the potential to DDOS the API in bursts._
