### ISSUE TITLE
Inconsistent version on admin UI

### ISSUE THREAD

**Issue by ycecube** [bitwarden/server#2212]
### Steps To Reproduce

On the /admin page the version numbers are sometimes inconsistent.

After running "./bitwarden.sh update" it says "Update not needed".

### Expected Result

The admin page should show the actual current versions.

### Actual Result

Showing client/server versions inconsistently.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/7201339/186410484-aee9e91f-d9ee-4ea6-88b2-6517ebac1f1c.png)

### Build Version

2022.8.4

### Environment

Self-Hosted

### Environment Details

- Operating system: Ubuntu 22.04.1 LTS (`Linux icarus 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`)
- Environment: Docker

**Comment by djsmith85** [comment]
Hi @ycecube and thank you for your report. This issue has previously been reported with https://github.com/bitwarden/server/issues/2212 and has already received a fix, which will be included in a future release.

Closing this as duplicate.

**Comment by djsmith85** [comment]
@ycecube My bad, I obviously meant to link to https://github.com/bitwarden/server/issues/2146.
