### ISSUE TITLE
Bitwarden not started automatic after restart of docker service

### ISSUE THREAD

**Issue by TiminRo** [bitwarden/server#2217]
### Steps To Reproduce

1. Go to 'restart the docker service'
2. Click on 'restart or reboot the OS.'

### Expected Result

When stopping the docker service, the containers are automatic started after docker service gets started again. 

### Actual Result

When stopping the docker service, the containers are stopped but not automatic started after docker gets started again. 
Bitwarden is not adding automatic restart policy to their containers.

### Build Version

2022.8.1

### Environment

Self-Hosted

### Environment Details

Ubuntu 22.04.1 LTS

**Comment by kmlr05** [comment]
Hi @TiminRo ,

I checked docker compose file. All services restart policies are "always". Did you change anything on "./bwdata/docker/docker-compose.yml"?

**Comment by Larry-Sussman** [comment]
As we haven’t heard from you about this problem in some time, this issue will now be closed.

If this happens again or continues to be a problem, please respond to this issue with any additional detail to assist with reproduction and root cause analysis.
