### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by sfulham** [bitwarden/server#2240]
### Steps To Reproduce

1. Just start bitwarden through docker as usual.

### Expected Result

No 502 Error

### Actual Result

It now gives me a 502 Gateway Error from the nginx container.

### Additional Context

I'm running it behind traefik, but that it not the issue, as I can still access the admin page. 
I believe the issue is with the web container, as it has no ports open according to `docker-compose ps`.
I was unable to find any errors in the logs.
I did recently run out of storage on the disk, and I had to expand it, so that may have been the original cause of the issue.

### Build Version

2022.6.2

### Environment

Self-Hosted

### Environment Details

- OS: AlmaLinux 8 (VM from XCP-ng)
- Docker

**Comment by khaeljy** [comment]
Hi,

I have the same issue, do you have found a solution?

<img width="199" alt="image" src="https://user-images.githubusercontent.com/1810456/190338400-926e9ce1-dde7-4590-91ac-251566b80ca2.png">

**Comment by khaeljy** [comment]
I found a solution!

If I replace all the `http://web:5000` with ` http://bitwarden-web:5000` in the `bwdata/nginx/default.conf` file, then restart the nginx container, the web interface works fine.

<img width="333" alt="image" src="https://user-images.githubusercontent.com/1810456/190346047-0e88cb5e-22a6-4879-91c1-6494c328549e.png">

**Comment by sfulham** [comment]
Thank you! It all works now!
