### ISSUE TITLE
Bug? Self hosting doesn't work in rootless docker

### ISSUE THREAD

**Issue by gitwittidbit** [bitwarden/server#2321]
### Steps To Reproduce

1. Setup rootless docker
2. Download install script
3. run docker-compose up
4. Receive permission denied error

### Expected Result

Bitwarden starts normally, despite in rootless docker - well, I don't know whether I expect that because I can't find any info on whether this should work...

### Actual Result

Permission denied error

### Additional Context

My question really is: Can Bitwarden be deployed in Rootless Docker?

### Build Version

Latest (as downloaded by install script)

### Environment

Self-Hosted

### Environment Details

- Debian 11
- Rootless Docker

**Comment by Hinton** [comment]
Hi @gitwittidbit,

Unfortunately I don't believe we currently support rootless docker. But it's something we are looking into but at this point I can't provide an ETA.

**Comment by kdaveid** [comment]
Can we reopen this issue? It _is_ an issue. I only run docker in rootless mode and it's a pain to constantly reset permissions after calling `./bitwarden.sh rebuild`...
