### ISSUE TITLE
Export Functionality is missing some Login entries from the Vault

### ISSUE THREAD

**Issue by hassamchohan** [bitwarden/server#2329]
### Steps To Reproduce

1. Lets say you have around 50 Login entries in your Vault and out of those you have marked 20 as `Favourite`.
2. When you export your Vault as a csv, there are some missing Login entries which you have marked as `Favourite`. Ideally you should get 20 but you wont get 20 entries in the csv. 

### Expected Result

The export Vault functionality should show the same number of Favourites as shown in your Vault in the Bit warden account.

### Actual Result

Some login entries which you have marked as `Favourite` in your account are missing from the exported csv functionality.

### Build Version

Latest

### Environment

Cloud (bitwarden.com)

**Comment by Hinton** [comment]
Do any of the favorited items belongs to an organization? Organization data needs to be exported separately.

**Comment by hassamchohan-smava** [comment]
Yes, there were few which belongs to an organization ? Is this a feature, then ? Is there any way, I could export all my vault in one go (including the one which belongs to an organization) ?

**Comment by djsmith85** [comment]
Here's a link to our documentation on exporting your vaults: https://bitwarden.com/help/export-your-data/
