### ISSUE TITLE
SMTP authentication fails due to password restrictions

### ISSUE THREAD

**Issue by m1r0x** [bitwarden/server#2419]
### Steps To Reproduce

1. Setup Bitwarden according to https://bitwarden.com/de-DE/help/install-on-premise-linux/
2. Edit Environment variables './bwdata/env/global.override.env'
3. Set Variables: ![image](https://user-images.githubusercontent.com/24898244/202702122-117f837c-9afd-46a1-80de-3f2d01bfbf8a.png)
4. Rebuild './bitwarden.sh rebuild'
5. Start './bitwarden.sh start'
6. create a new user with the user registration form 
7. send yourself a confirmation e-mail with the built in button (appears on first login on the top right)

### Expected Result

Rebuilding without any issues. 
Bitwarden should start without any warnings.

The 'send mail' function should work without any issues.

### Actual Result

The password is regarded as declared variable. The value after the '$' is interpreted as variable.

In my example, the password is abcd$troll

During the build process the following warning appears: 
![image](https://user-images.githubusercontent.com/24898244/202702768-6d174d83-3590-4c02-a27f-f80782254517.png)

In the api logs i see the following error
![image](https://user-images.githubusercontent.com/24898244/202702844-93a77ddd-d2b4-4c9c-8b0b-8c50a642e428.png)

I couldn't find any information about password restrictions.
After removing any '$' from the password everything works as intended.

### Additional Context

This is my first ever issue report on GitHub. So please bare with me ;-)

### Build Version

2022.10.0

### Environment

Self-Hosted

### Environment Details

- Operating System: Ubuntu 22.04.1 LTS (Jammy Jellyfish)
- Installation exactly according to: https://bitwarden.com/de-DE/help/install-on-premise-linux/
- Environment variable Guide used: https://bitwarden.com/de-DE/help/install-on-premise-linux/#post-install-configuration

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by rohitkumarankam** [comment]
you should use escape sequence while using `$`
the right way to do it `abcd\$troll`

**Comment by Hinton** [comment]
The docker documentation describes a few scenarios to resolve the password being cut, https://docs.docker.com/compose/env-file/. `$` is usually used for variable substitution in Docker.
