### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by sea0302** [bitwarden/server#2488]
### Steps To Reproduce

"502 Bad Gateway" is prompted when the management site browser is opened
![image](https://user-images.githubusercontent.com/32325218/206839135-60c05ea5-aae9-4f34-99e5-7b516772e48f.png)

### Expected Result

1

### Actual Result

1

### Build Version

1

### Environment

Cloud (bitwarden.com)

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by justindbaur** [comment]
Hi @sea0302, can you please spend some time filling out the template we provided a bit more? It appears you are using self hosted but checked the `Cloud (bitwarden.com)` environment. Some logs from admin could be helpful too.
