### ISSUE TITLE
Bitwarden Unified - api (terminated by SIGABRT (core dumped); not expected)

### ISSUE THREAD

**Issue by Kizaing** [bitwarden/server#2493]
### Steps To Reproduce

1. Use docker compose to create the bitwarden unified and maria db containers
2. Check the logs to see it immediately failed due to (terminated by SIGABRT (core dumped); not expected) error

### Expected Result

The expected result was for the unified bitwarden container services to start

### Actual Result

All unified container services immediately fail (icons, notifications, admin, api, identiy) all fail with the error (terminated by SIGABRT (core dumped); not expected).

Looking inside the container to check the logs, each service has specifically failed with this error: 

`Unhandled exception. System.InvalidOperationException: Failed to convert configuration value at 'GlobalSettings:Installation:Id' to type 'System.Guid'.`

### Githash Version

N/A, the API service fails to start

### Environment Details

- Operating System: Ubuntu Server 22.04 via Hyper-V in Windows 11
- Environment: Docker
- Hardware: Core i7 1270P

### Database Image

mariadb:10

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by vgrassia** [comment]
Hi @Kizaing, along with the [docker-compose.yml](https://github.com/bitwarden/server/blob/master/docker-unified/docker-compose.yml) file, you'll need to provide a [settings.env](https://github.com/bitwarden/server/blob/master/docker-unified/settings.env) file which has required settings for the container to come up correctly.

**Comment by Kizaing** [comment]
Apologies, I did have the settings.env file but I missed putting in a variable, marking issue as closed. Thank you!
