### ISSUE TITLE
Custom MySQL port for BW unified

### ISSUE THREAD

**Issue by rusty1281** [bitwarden/server#2516]
### Steps To Reproduce

Hello,

was wondering if there is any way to run BW unified against an external DB running on a custom port? the `BW_DB_SERVER` when populated with an IP address and no port does not work, as well as with an added port in this format `IP:port`

### Expected Result

Connect BW to an external DB with custom port

### Actual Result

No DB connection/initial table creation

### Screenshots or Videos

fail: Bit.Admin.Jobs.DatabaseExpiredGrantsJob[2]
      Error performing DeleteSendsJob.
      MySqlConnector.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts.

### Githash Version

455d62e8-dirty

### Environment Details

Docket 20.10.3

### Database Image

MySQL 8

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by rusty1281** [comment]
Just wanted to add that using the `BW_DB_PROVIDER=sqlite` and `BW_DB_FILE=/etc/bitwarden/vault.db` as part of the stack, also results in an error:

```
fail: Bit.Admin.HostedServices.DatabaseMigrationHostedService[0]
      Database unavailable for migration. Trying again (attempt #2)...
      System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)
```

**Comment by justindbaur** [comment]
> Just wanted to add that using the BW_DB_PROVIDER=sqlite and BW_DB_FILE=/etc/bitwarden/vault.db as part of the stack, also results in an error:

Are you on the `beta` tag? I believe SQLite support is only on the `dev` tag right now and so it's falling back to SQL Server because it can't handle sqlite and that's why it's throwing a `SqlException`.

**Comment by rusty1281** [comment]
Tnx for the reply. Yes I am on beta and have not tried the DEV tag. 

So the question is can I use beta tag with external SQL on a custom port?

**Comment by justindbaur** [comment]
It should be able to but I won't have a chance to recreate it myself until the end of the week. @kspearrin any thoughts? We were using docker compose to orchestrate this setup and if so can you post it all redacting any sort of passwords so I can recreate it more closely?

**Comment by kspearrin** [comment]
Here is how we construct connection strings today:

```
MYSQL_CONNECTION_STRING="server=$BW_DB_SERVER;database=$BW_DB_DATABASE;user=$BW_DB_USERNAME;password=$BW_DB_PASSWORD"
POSTGRESQL_CONNECTION_STRING="Host=$BW_DB_SERVER;Database=$BW_DB_DATABASE;Username=$BW_DB_USERNAME;Password=$BW_DB_PASSWORD"
SQLSERVER_CONNECTION_STRING="Server=$BW_DB_SERVER;Database=$BW_DB_DATABASE;User Id=$BW_DB_USERNAME;Password=$BW_DB_PASSWORD;"
SQLITE_CONNECTION_STRING="Data Source=$BW_DB_FILE;"
```

According to [here](https://dev.mysql.com/doc/connector-net/en/connector-net-entityframework60.html), we need to add `;port=` to the connection string builder to support non-default ports. I will work on a PR for that.

@rusty1281 For now, you can just specify your own full connection string rather than using the `BW_DB_*` options. Just add this env variable and it will take precedence.

```
globalSettings__mysql__connectionString=server=db_server;port=1234;database=db_name;user=db_user;password=db_password
```

**Comment by rusty1281** [comment]
> @rusty1281 For now, you can just specify your own full connection string rather than using the `BW_DB_*` options. Just add this env variable and it will take precedence.

Thank you @kspearrin for this info. It works like a charm!
