### ISSUE TITLE
Inconsistency with docker volume name

### ISSUE THREAD

**Issue by GieltjE** [bitwarden/server#2527]
### Steps To Reproduce

https://bitwarden.com/help/install-and-deploy-unified-beta/#using-docker-compose specifies: 

```
    volumes:
      - bitwarden:/etc/bitwarden
```

AND

```
 -v ./bwdata/:/etc/bitwarden
```

Also https://bitwarden.com/help/install-and-deploy-unified-beta/#using-docker-run specfies: 

```
 -v ./bwdata/:/etc/bitwarden
```

### Expected Result

Both should specify the same directory so switching from one to the other doesn't cause issues.

Also we should add a note that (at least on windows?) the local directory isn't auto created.

### Actual Result

Missing logs and data protection keys

### Githash Version

455d62e8-dirty

### Environment Details

- OS: Win 11 insider
- Env: Docker
- Hardware: 3700X 64GB ram

### Database Image

Mariadb: 10.10.2

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by kspearrin** [comment]
I don't see an inconsistency. One is showing using it with a docker volume and the other is showing it with a mapped volume on the host.
