### ISSUE TITLE
https link generated for non https server

### ISSUE THREAD

**Issue by GieltjE** [bitwarden/server#2529]
### Steps To Reproduce

1: install using docker on localhost
2: configure BW_ENABLE_SSL=false for good measure
3: go to http://localhost/admin
4: enter your email
5: click on the link in the email

### Expected Result

The default browser opening the admin panel

### Actual Result

The default browser timing out on https://localhost which doesn't exist

### Githash Version

455d62e-dirty

### Environment Details

- OS: Win 11 insider
- Env: Docker
- Hardware: 3700X 64GB ram

### Database Image

Mariadb: 10.10.2

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Mariapori** [comment]
What your appsettings have?

"siteName" ?

**Comment by GieltjE** [comment]
Sorry I don't follow

**Comment by kspearrin** [comment]
https is required for Bitwarden. If you are using `BW_ENABLE_SSL=false` then you must front the instance with a https proxy.
