### ISSUE TITLE
Inconsistent volumes

### ISSUE THREAD

**Issue by GieltjE** [bitwarden/server#2532]
### Steps To Reproduce

https://bitwarden.com/help/install-and-deploy-unified-beta/#using-docker-compose specifies:

```
    volumes:
      - bitwarden:/etc/bitwarden
```
and

```
volumes:
  bitwarden:
  data:
```

While https://github.com/bitwarden/server/blob/master/docker-unified/docker-compose.yml (which is refered to on the previous page) specifies:
```
    volumes:
      - bitwarden:/etc/bitwarden
      - logs:/var/log/bitwarden
```
and

```
volumes:
  bitwarden:
  logs:
  data:
```

### Expected Result

Consistent documentation

### Actual Result

See above

### Githash Version

455d62e-dirty

### Environment Details

- OS: Win 11 insider
- Env: Docker
- Hardware: 3700X 64GB ram

### Database Image

Mariadb: 10.10.2

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by kspearrin** [comment]
There isn't an inconsistency here. The different examples are just showing different volumes that can be mapped. The only required volume to persist from the Bitwarden container is `/etc/bitwarden`.
