### ISSUE TITLE
Links in emails are sent without custom port number

### ISSUE THREAD

**Issue by karolszklarski** [bitwarden/server#2553]
### Steps To Reproduce

Configure bitwarden to listen on public ip on non-standard port, like https://host.name.com:12345/

Invoke any action that sends an email with confirmation link. Read the email.

### Expected Result

The confirmation link in an email should begin with https://host.name.com:12345/

### Actual Result

The confirmation link in an email begins with https://host.name.com/

### Additional Context

    image: bitwarden/self-host:beta@sha256:7e586dc66c016360fd56dcbea462a4c92828ea65324a08012501b6ec99dec7fd

### Githash Version

455d62e8-dirty

### Environment Details

settings.env
BW_ENABLE_SSL=true
BW_PORT_HTTPS=12345

docker-compose.yml
    ports:
      - 12345:12345

The edge router is forwarding external port 12345 to docker host machine port 12345.

### Database Image

mariadb  Ver 15.1 Distrib 10.5.18-MariaDB, for debian-linux-gnueabihf (armv8l) using  EditLine wrapper

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by kspearrin** [comment]
You would need to update your service URL env vars to include the port. I think the default configuration assumes a standard port being access from the frontend.

Try setting the following env var:

```
globalSettings__baseServiceUri__vault=https://host.name.com:12345
```

**Comment by karolszklarski** [comment]
It worked, thank you! :)
