### ISSUE TITLE
Bitwarden Unified - SSO (404) 

### ISSUE THREAD

**Issue by hegedussz** [bitwarden/server#2556]
### Steps To Reproduce

1. Go to 'https://bitwarden-unified/#/sso
2. Click on 'Login.'
3. Login with SSO (SAML 2)

### Expected Result

Successful Login

### Actual Result

Login not successful -  404 error 

Log:
```
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.0 GET http://bitwarden.xxxx.xx/sso-connector.html?code=Fxxxx&scope=api%20offline_access&state=xxxx_identifier%3DASD%C3%9C - - - 404 0 - 1.6649ms
```

### Screenshots or Videos

![bitwarden](https://user-images.githubusercontent.com/20745628/211410553-fac87add-2ba7-4ac8-9903-39e6084eedba.jpg)

### Githash Version

aa1f4435-dirty

### Environment Details

- Enviroment: K8S 1.23.14 - ingress-nginx

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by justindbaur** [comment]
Similar to #2536 I believe. We need to add some proxy pass throughs in the nginx config template.
