### ISSUE TITLE
Install and Deploy - Unified (Beta) - setup instructions incorrect - yubikey

### ISSUE THREAD

**Issue by amcusack** [bitwarden/server#2565]
### Steps To Reproduce

the setup instruction page at https://bitwarden.com/help/install-and-deploy-unified-beta/ has incorrect environment variables for yubikey setup

`globalSettings_yubico_clientId` should be `globalSettings__yubico__clientId`

`globalSettings_yubico_key` should be `globalSettings__yubico__key`

### Expected Result

to be able to add yubikey

### Actual Result

see https://github.com/bitwarden/server/issues/2557

### Githash Version

e7958609-dirty

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
@amcusack Thank you for your report. The documentation has been updated/
