### ISSUE TITLE
Security Issue - Minimum KDF iteration count too low

### ISSUE THREAD

**Issue by ArjanOnwezen** [bitwarden/server#2575]
### Steps To Reproduce

Set minimum KDF iteration count to 300.000+ in line with OWASP recommendation.

Also make sure this is done automatically through client/website for existing users (after they are logged in) to enforce that minimum.

https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#pbkdf2

### Expected Result

Set minimum KDF iteration count to 300.000+ in line with OWASP recommendation.

Also make sure this is done automatically through client/website for existing users (after they are logged in) to enforce that minimum.

https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#pbkdf2

### Actual Result

Currently minimum of 100.000 is set.

### Githash Version

N/A

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Petruchio96** [comment]
Per Steve Gibson's Security Now episode #905, I would like to see a switch from PBKDF2 to a memory-hard password key derivation such as "Scrypt"  See page for details: https://en.wikipedia.org/wiki/Scrypt

**Comment by dwbit** [comment]
Thanks for the feedback @ArjanOnwezen this has been passed along to the team.
