### ISSUE TITLE
Global domain equivalence list contains sonyentertainmentnetwork.com twice

### ISSUE THREAD

**Issue by nielsbasjes** [bitwarden/server#2585]
### Steps To Reproduce

The global domain equivalence list contains sonyentertainmentnetwork.com twice.
Once as being equivalent with sony.com and once with playstation.com

https://github.com/bitwarden/server/blob/master/src/Core/Utilities/StaticStore.cs

To me it seems that these 3 should be combined into a single list.
Is my assessment correct?

### Expected Result

I would have expected sony.com and playstation.com to be equivalent because both are equivalent to sonyentertainmentnetwork.com.

### Actual Result

sony.com and playstation.com are not considered equivalent

### Additional Context

The duplication was added here https://github.com/bitwarden/server/pull/1129
I checked and this is the only case of this problem.
Suggestion: Add a simple test to check for this.

### Build Version

Issue exists in master branch

### Environment

Self-Hosted

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

Thank you for your report! We were able to locate this issue, if you wish to add any information/screenshot/recording or so, please do it here and our engineering team will review it.

Thanks!
