### ISSUE TITLE
Bitwarden refusing to start on 443 since last update

### ISSUE THREAD

**Issue by robbevl** [bitwarden/server#2597]
### Steps To Reproduce

./bitwarden.sh start

### Expected Result

Bitwarden starting

### Actual Result

Error response from daemon: driver failed programming external connectivity on endpoint bitwarden-nginx (ee94d39633878e127a2986f40ed11c29a414b1eb358fd545f834cb73eb2422a3): Bind for 0.0.0.0:443 failed: port is already allocated

### Additional Context

Before attempting to start bitwarden:

```
[root@BEDTC1BITW01 ~]# netstat -tulpn | grep ':443'
[root@BEDTC1BITW01 ~]#
```

Nothing is listening to 443.

While starting Bitwarden we get the error that the 443 port is already in use (Bind for 0.0.0.0:443 failed: port is already allocated)

Afterwards, still nothing:

```
[root@BEDTC1BITW01 ~]# netstat -tulpn | grep ':443'
[root@BEDTC1BITW01 ~]#
```

This is happening since the update to 2023.1.0. Before, no issues at all.

Interestingly, it does work when using any other port. For example 44300, but also ports under 1023.

Possibly related, but non-breaking:

When stopping bitwarden via **./bitwarden.sh stop** we get the following error:

`failed to remove network docker_public: Error response from daemon: error while removing network: network docker_public has active endpoints`

Although we're not sure if this is since the last update, might be earlier.

And when running **./bitwarden.sh update** we get:
`no such service: admin`

### Build Version

bitwarden.sh version 2023.1.0

### Environment

Self-Hosted

### Environment Details

Docker version 20.10.22, build 3a2c30b
Docker Compose version v2.14.1
OS: Red Hat Enterprise Linux 8.7

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by robbevl** [comment]
Found the answers, in case anyone has the same issues.

`no such service: admin`

Bitwarden needs to be running while upgrading. 


`failed to remove network docker_public: Error response from daemon: error while removing network: network docker_public has active endpoints`

This seemed to be the issue. Once the stale networks were removed Bitwarden wanted to start on 443 again.
**docker network list
docker network prune**
or: **docker network rm _<network to remove>_**

Unsure why it got stuck in the first place. We're just doing a regular updateself && update every night, that's all.

**Comment by TroyBW** [comment]
Hi robbevl,
Thank you for documenting the resolution for the issue. I will mark this as closed.
