### ISSUE TITLE
Site icons not loading, defaults to NotFound icon

### ISSUE THREAD

**Issue by kevjett** [bitwarden/server#2598]
### Steps To Reproduce

1. Go to Vault
2. Click to Add a Login Vault Item
3. Enter info for new item, use https://www.google.com as URI
4. Click Save

### Expected Result

The new item icon should be a google.com icon.

### Actual Result

The new item icon is the NotFound icon of the grey world.

### Screenshots or Videos

I attached screenshots of the edit screen and the vault item list. As you can see, the image is the default image.

<img width="766" alt="Screen Shot 2023-01-18 at 4 52 24 PM" src="https://user-images.githubusercontent.com/2198452/213313219-67aaad10-a7e7-4ba7-93b5-030e8b37e1f9.png">
<img width="797" alt="Screen Shot 2023-01-18 at 4 52 15 PM" src="https://user-images.githubusercontent.com/2198452/213313220-219430d4-451a-4816-8863-d2ffea7eb236.png">

### Additional Context

 I checked the URL of the image in developer tools and it's set as "https://bitwarden.mydomain.com/icons/www.google.com/icon.png". When I load that URL separately, it returns the default image. 

For the logs, I checked the logs of the icon.log file and here is the log.

`[40m[1m[33mwarn[39m[22m[49m:` Bit.Icons.Services.IIconFetchingService[0]
      => SpanId:e8a0f8fb15b55610, TraceId:980ee061ae7a9e011f00059aeb513acf, ParentId:0000000000000000 => ConnectionId:0HMNP9UKPVJ85 => RequestPath:/www.google.com/icon.png RequestId:0HMNP9UKPVJ85:00000002 => Bit.Icons.Controllers.IconsController.Get (Icons)
      Couldn't load a website for www.google.com: null.
[40m[1m[33mwarn[39m[22m[49m: Bit.Icons.Controllers.IconsController[0]
      => SpanId:e8a0f8fb15b55610, TraceId:980ee061ae7a9e011f00059aeb513acf, ParentId:0000000000000000 => ConnectionId:0HMNP9UKPVJ85 => RequestPath:/www.google.com/icon.png RequestId:0HMNP9UKPVJ85:00000002 => Bit.Icons.Controllers.IconsController.Get (Icons)
      Null result returned for www.google.com.`

I also went into the console for the bitwarden-unified-bitwarden docker container to make sure I could ping www.google.com, and I was able to ping out from the docker container. 

So, I'm not sure why the Icon finder service cannot access external URLs. This is the same result for all URLs and it produces the same log for all of them.

### Githash Version

3997defe-dirty

### Environment Details

- Operating System: Windows 10
- Environment: Docker
- i7 Intel processor, 16 GB ram

### Database Image

mariadb:10

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by kspearrin** [comment]
I am not able to reproduce the issue. Are you fronting the installation with a proxy or something? Perhaps there is some caching going on that is holding a failed resolution of the image on a previous request? Could you try some other random domains like:

https://bitwarden.mydomain.com/icons/yahoo.com/icon.png
https://bitwarden.mydomain.com/icons/github.com/icon.png
https://bitwarden.mydomain.com/icons/reddit.com/icon.png
