### ISSUE TITLE
Use of btwrdn.co for setup script on Self Hosted Install

### ISSUE THREAD

**Issue by TastyDigits** [bitwarden/server#2604]
### Steps To Reproduce

Setup requests the following: 

curl -s -o bitwarden.sh \
    https://raw.githubusercontent.com/bitwarden/server/master/scripts/bitwarden.sh \
    && chmod +x bitwarden.sh
./bitwarden.sh install
./bitwarden.sh start

The script (/scripts/bitwarden.sh) is just a stub and actually fetches the setup script form domain "go.btwrdn.co/bw-sh"

BITWARDEN_SCRIPT_URL="https://go.btwrdn.co/bw-sh"

### Expected Result

The entirety of the script for setup, which can be fetched from the domain in question, should be hosted on Github and not an external host.

### Actual Result

The owner of the domain 'btwrdn.co' could very easily respond with a modified setup script.
Not that the owner (I assume @vgrassia ?) has any intention, but the supply chain attack is very real.

It could be targeted by public IP address for example and may be ran with high privileges on what will become a very sensitive system.

I see no reason why the entire script contents cannot be hosted on Github instead of just the 'stub' and relying on this outside host.
The manual installation guide on bitwarden.com does not use this 'rapid install' method and may be more appropriate for a secure system.

### Additional Context

I looked at registering this as a MITM potential on HackerOne and noticed that this host (btwrdn.co) is not part of the in-scope assets. 
I hope this is just an oversight.

### Build Version

All

### Environment

Self-Hosted

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by vgrassia** [comment]
Bitwarden owns the `btwrdn.co` domain. It is a link shortener that points to https://func.bitwarden.com/api/dl/?app=self-host&platform=linux which looks up and responds with the latest release of our [self-host](https://github.com/bitwarden/self-host/) scripts.  I've updated the README in this repository with the example commands using the proper URL.
