### ISSUE TITLE
Default "stop_grace_period" (docker compose) is too short

### ISSUE THREAD

**Issue by delightfuleagle** [bitwarden/server#2614]
### Steps To Reproduce

1. Start the container: `docker compose up --detach`
2. Wait till everything is up and running
3. Stop the container: `docker compose down or docker stop bitwarden`

### Expected Result

The container get enough time to gracefully shutdown.

### Actual Result

The container needs more time than the default 10 seconds, and is "stopped" with `SIGKILL` after 10 seconds, which is likely to cause data corruption.

### Additional Context

I don't know if this is because of the Raspberry Pi specs (or anything else) or if it affects "higher" spec systems too. My container needs around 15-25 seconds to shutdown.
> 2023-01-23 10:22:39,114 WARN received SIGTERM indicating exit request
> 2023-01-23 10:22:39,115 INFO waiting for identity, admin, api, icons, nginx, notifications to die
> 2023-01-23 10:22:42,153 INFO waiting for identity, admin, api, icons, nginx, notifications to die
> 2023-01-23 10:22:45,159 INFO waiting for identity, admin, api, icons, nginx, notifications to die
> 2023-01-23 10:22:48,725 INFO waiting for identity, admin, api, icons, nginx, notifications to die
> 2023-01-23 10:22:50,728 INFO stopped: notifications (terminated by SIGABRT (core dumped))
> 2023-01-23 10:22:52,541 INFO waiting for identity, admin, api, icons, nginx to die
> 2023-01-23 10:22:52,555 INFO stopped: nginx (exit status 0)
> 2023-01-23 10:22:53,665 INFO stopped: icons (exit status 0)
> 2023-01-23 10:22:55,762 INFO stopped: api (exit status 0)
> 2023-01-23 10:22:55,763 INFO waiting for identity, admin to die
> 2023-01-23 10:22:56,872 INFO stopped: admin (exit status 0)
> 2023-01-23 10:22:57,941 INFO stopped: identity (exit status 0)

I think setting `stop_grace_period: 30s` in the `docker-compose.yml` template file and documentation would be a good idea.

### Githash Version

266d426c-dirty

### Environment Details

- Raspberry Pi 4 (8 GB)
- Raspberry Pi OS (64-bit, bullseye)
- Docker Engine 20.10.23
- Docker Compose 2.15.1

### Database Image

sqlite:3

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by fdrw220** [comment]
Same here, SIGKIL each and every time for proxy and a few other containers for the past few months when bringing them down to update the images. 
2VCPU and 4Gb RAM solely for BitWarden

**Comment by kspearrin** [comment]
I think this might be resolved with https://github.com/bitwarden/server/pull/2654 . Can you try pulling latest `dev` tag and see if the issue persists?

**Comment by delightfuleagle** [comment]
Now, the container needs around 8.5 seconds to stop. Still a little too past 10 seconds for my liking, but probably okay.

Personally, I have set a higher limit for all my containers, because it is more important to me that the containers stop properly.

**Comment by kspearrin** [comment]
I am not sure this is necessary in our examples, but its worth knowing that this feature exists in docker that people can set.
