### ISSUE TITLE
Cant type accents in password without visualizing the password in mac

### ISSUE THREAD

**Issue by CodingNix** [bitwarden/server#2632]
### Steps To Reproduce

4. Click on '...'

### Expected Result

when trying to login into extensions or the desktoapp i should be able to type the password without needing to see it

### Actual Result

When i put the password its not accepted and when i visualize it shows the accent (´) was not added. I need to type it when the password is appearing to login.

### Screenshots or Videos

<img width="378" alt="image" src="https://user-images.githubusercontent.com/17912486/214770080-25f40f0b-6bdd-4764-bed6-119ac383aeaf.png">

### Additional Context

It happens in all the extensions i tried (Firefox, chrome, safari) and in the desktop app. Its just with bitwarden i dont have this problem with any other software.

### Githash Version

Sorry i dont know how can i see that

### Environment Details

Mac os monterey version 12.6
Macbook m1

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi @CodingNix 

I will close this issue as it is a duplicate from this one: https://github.com/bitwarden/clients/issues/2472

Have a nice day.
