### ISSUE TITLE
Client application and browser extension fail to fetch docker installation  

### ISSUE THREAD

**Issue by bhourlier** [bitwarden/server#265]
Hello, 
I test Bitwarden, I have install it with the given script (Docker + Docker Compose).
Everything is OK on the web interface, I can create account and login informations but when I try to connect with application (Linux) or web extension I have an error "fail to fetch".

Any error appear in log, I can see tcp with ssl packets with tcpdump come on the server when I tried to connect.

In appllication I configure my url server in "personnal environments" part. 
All docker container running in version 1.19

I miss some configuration or it's a premium functionality ?

**Comment by kspearrin** [comment]
Self signed cert?

**Comment by bhourlier** [comment]
Yes I use self signed certificate generate by Bitwarden

**Comment by kspearrin** [comment]
Did you follow the warning's advise when installing?

> You are using an untrusted SSL certificate. This certificate will not be
                              trusted by Bitwarden client applications. You must add this certificate to
                              the trusted store on each device or else you will receive errors when trying
                              to connect to your installation.

**Comment by bhourlier** [comment]
Yes I add the certificate to my web browser and in my "certficate center" but I have the same message.

**Comment by motorious1** [comment]
I am getting similar error in Brave (0.22.669) browser extension (v 1.25.5) on Windows 10 except I have no self-signed certificates.  Same extension works flawlessly in Firefox 52.7.4 ESR on same machine, same network.

Try to Login in Bitwarden extension on Brave browser...
Get a spinning wheel in top right corner of extension and eventually times out with: 
Errors have occurred
Failed to fetch
<then the message window disappears>

**Comment by kspearrin** [comment]
@motorious1 See here. Probably site isolation setting. https://community.brave.com/t/bitwarden-not-working/18195/3

**Comment by motorious1** [comment]
@kspearrin thanks, I saw that thread earlier it's not the issue.  I believe it's a network setting as I noticed I cannot view any external sites like reddit, etc. only internal company sites.  Looks like Brave needs to include network proxy settings for people trying to use it on a corporate network... guess I'm stuck with FF for now.  :(

**Comment by cyayung** [comment]
I am getting failed to fetch error with docker installation
