### ISSUE TITLE
default docker-compose project name collides with other project

### ISSUE THREAD

**Issue by shartge** [bitwarden/server#266]
While testing bitwarden I came across a collision with another project also not setting a project name, resulting in both wanting to use "docker_default" for their network and volumes, because docker-compose just uses the directory name the docker-compose.yml file is in. And to just name this "docker" seems quite common.

Could you please add something `--project-name bitwarden` to your docker-compose calls?

I tested this and it generally works, but people already using volumes will lose access to them if they are not renamed or the data migrated after changing the project name.

**Comment by kspearrin** [comment]
Is there not something we can set in the compose file rather than having to pass an argument every time?

**Comment by vedmant** [comment]
I have the same problem, and it looks really weird that I can not set project_name in the docker-compose.yml as it look very logical and strait forward solution. Actually taking name from the project folder in the first place is a bad idea.

**Comment by Mart124** [comment]
#290 proposes a solution defining `COMPOSE_PROJECT_NAME`, should then help 👍

**Comment by Mart124** [comment]
`COMPOSE_PROJECT_NAME` can also be set in a `.env` file in the current working directory.
https://docs.docker.com/compose/env-file/
Can be an easy fix 👍
