### ISSUE TITLE
SQLite informations missing in documentation

### ISSUE THREAD

**Issue by delightfuleagle** [bitwarden/server#2663]
### Steps To Reproduce

1. Go to [Install and Deploy - Unified (Beta)](https://bitwarden.com/help/install-and-deploy-unified-beta/)
2. Look for database solutions

### Expected Result

SQLite should be mentioned. Likewise the optional environment variable `BW_DB_FILE`.

### Actual Result

SQLite is not mentioned in the documentation. Even in this week's Bitwarden Brilliance Twitch stream it didn't show up as a possible database.

### Additional Context

I don't know if it's intentional that SQLite isn't explicitly mentioned, but for "small" environments it's perfectly adequate, being easier to manage and far more resource-efficient.

Also as a serious alternative to Vaultwarden, this 1-container-solution should be advertised more prominently.

At least I haven't found any problems with SQLite yet, but I also don't use any organization, which apparently can cause issues ([#2545](https://github.com/bitwarden/server/issues/2545), [#2561](https://github.com/bitwarden/server/issues/2561) [#2624](https://github.com/bitwarden/server/issues/2624)).
Are there any known instabilities with SQLite as database?

### Githash Version

e019f019-dirty

### Environment Details

- Raspberry Pi 4 (8 GB)
- Raspberry Pi OS (64-bit, bullseye)
- Docker Engine 23.0.0
- Docker Compose 2.15.1

### Database Image

sqlite:3

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by kspearrin** [comment]
It will be added after the next release (in a week or so). Right now it is only available in the dev tag. Once the beta tag contains it, docs will be updated.
