### ISSUE TITLE
Nginx reverse proxy returning oddly bare page instead of login page.

### ISSUE THREAD

**Issue by igor-semyonov** [bitwarden/server#2686]
### Steps To Reproduce

1. Deploy either bitwarden or bitwarden unified using docker.
2. Set up nginx as reverse proxy to bitwarden (not docker version) to
3. Go to my FQDN: bitwarden.example.com and go to http://localhost:docker-port and compare result.

### Expected Result

To get the full login page on the FQDN bitwarden.example.com

### Actual Result

It works on http://localhost:docker-port
but does not display a login page at bitwarden.example.com

### Screenshots or Videos

http://lolhost:docker-port
![image](https://user-images.githubusercontent.com/85591519/218291276-4bc2ecdc-9156-47df-ba02-00125c9e3a20.png)

bitwarden.example.com
![image](https://user-images.githubusercontent.com/85591519/218291266-13177797-7bda-4478-9eaa-e4b89ae7215b.png)

### Build Version

 Version 2023.1.0 

### Environment

Self-Hosted

### Environment Details

- Operating system: Gentoo
- Environment: docker

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by igor-semyonov** [comment]
Also, I noticed the same result when I put
`proxy-pass vault.bitwarden.com;` 
in my nginx instead pointing at my server.

**Comment by SergeantConfused** [comment]
Hi @igor-semyonov,

Thank you for this report. I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 


Thank you.

**Comment by igor-semyonov** [comment]
I found the problem. My nginx settings were too strict.

In case anyone else has a similar issue, here's my problem.

In particular, it was this line:

add_header Content-Security-Policy "default-src 'none'; frame-ancestors 'none'; script-src 'self'; img-src 'self'; style-src 'self'; base-uri 'self'; form-action 'self';";


I believe this tells the browser not to load external resources.
