### ISSUE TITLE
TwoFactorRecoveryCode not encrypted in the vault database

### ISSUE THREAD

**Issue by f-bader** [bitwarden/server#270]
The value of the Two Factor Recovery Key is stored unencrypted in the vault database and hence rendering the Two Factor Key Mechnism useless?
Should the database be exposed and one of the user masterkeys be cracked there wouldn't be any other security measurement to prevent the attacker from accessing the account.

Steps to reproduce
1. Connect to SQL Datebase "vault"
1. Execute Query 
`SELECT TOP (1000) [Id]
      [TwoFactorRecoveryCode]
  FROM [vault].[dbo].[User]`
1. Retrieve data

**Comment by kspearrin** [comment]
What key are you suggesting that it be encrypted with?

**Comment by f-bader** [comment]
Didn't thought about that.
And if you used the master password to encrypt it? And every time the user wants to view the recovery key he would have to enter it for decrypting purpose.

**Comment by kspearrin** [comment]
If we encrypted it with the uses master password we could not perform server side validation on it to disable 2FA when requested.

**Comment by kspearrin** [comment]
This still presents other problems we would have to overcome first. Implementing point 1 would mean we need to change several things with how the codes are correctly generated. It would have to always come from the client encrypted (like your vault data) and then be re-hashed. Essentially being treated the same as your master password, but randomly generated client side.

**Comment by amilopowers** [comment]
I don't get why you would show the recovery code a second time. I think you should show it once and state very clear bevore showing it that the user won't ever see it again and he should write it down.

If someone needs to see it again he simply should need to disable and re-enable two-factor auth.

**Comment by juriansluiman** [comment]
@amilopowers is right here. You should generate the codes once and show them to the users. Then store them as hashes to make validation possible. 

If a user wants to get to the backup codes again, simply regenerate the set. 

Another feature within this context, is to make sure users write down the code. 

1. Show generated codes
2. Have a confirm button ("I wrote them down")
3. Create a second dialog (codes aren't visible anymore) where users need to provide the first code on the list
4. If correct, then store (regenerated) codes in dB


This ensures users have written down the codes correctly. This is what Evernote does ATM.
