### ISSUE TITLE
Vault search using 'OR'

### ISSUE THREAD

**Issue by ByteBitten** [bitwarden/server#2702]
### Steps To Reproduce

1. Create a login entry called "AAA BBB"
2. Create a login entry called "BBB CCC"
3. Create a login entry called "AAA CCC"
4. Search for "AAA BBB"

### Expected Result

Result showing only "AAA BBB" login.

### Actual Result

Result showing "AAA BBB" and "BBB CCC" and "AAA CCC"

### Screenshots or Videos

![Screenshot from 2023-02-15 15-51-11](https://user-images.githubusercontent.com/3299710/219062158-a605fe5d-a8b6-4029-9a9d-661edb28f20f.png)

### Build Version

2023.2.0

### Environment

Cloud (bitwarden.com)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by dwbit** [comment]
Hey there, this  is currently working as expected, surfacing the result at the top like a search engine. Closing this one for now, but feel free to continue the discussion on the [community forums](https://community.bitwarden.com/t/search-combine-search-terms-rathen-than-add-them-up/4931).
