### ISSUE TITLE
Server keeps on redirecting to Bitwarden NO MATTER WHAT!

### ISSUE THREAD

**Issue by yuckdevchan** [bitwarden/server#2797]
### Steps To Reproduce

1. Set a bitwarden domain name at install
2. Change the bitwarden domain name for whatever reason

The first time I set the domain, I didn't understand properly and set it as just 'https://bitwarden'. I then changed it to the correct value. Now whenever I go to my server's IP address, it redirects to 'https://bitwarden'. I don't want the bitwarden software on my server any more, I just want it to stop haunting me.

Steps I took to stop this:
1. Stopped Bitwarden
2. Uninstalled Bitwarden

Nothing worked. Now my webserver is unusable as a webserver because it always redirects from its local IP to 'https://bitwarden'

### Expected Result

My webserver to give me the website I am hosting on apache or nginx.

### Actual Result

It always redirects to https://bitwarden.

### Additional Context

I would really appreciate if someone told me what network thing bitwarden changes to do this so I can remove that.

### Build Version

I was running the 2023-1 latest docker container I think

### Environment

Self-Hosted

### Environment Details

- Ubuntu Server 22.04.2 LTS x86_64
- Docker
- Running only on my local network with a normal local IP address (192.168.0....)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djchateau** [comment]
Hey there,

I attempted to reproduce your issue and was unable to do so. Can you please detail the process you took to uninstall your self-hosted Bitwarden instance so I can try to reproduce this behavior? If you're not able to please consider reaching out to our support for more detailed troubleshooting as we use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

Thanks!

**Comment by yuckdevchan** [comment]
To uninstall bitwarden I used this command:

`./bitwarden.sh uninstall`

It gave me questions like did I want to remove the database. I said yes.

Also, even if I stop nginx and apache, this still happens.

**Comment by djchateau** [comment]
Please reach out to our support on this for more detailed troubleshooting. This doesn't sound like a bug with the installation or uninstallation of the software.

You can contact us via this form: https://bitwarden.com/contact/

**Comment by yuckdevchan** [comment]
This has since been resolved.

**Comment by NaturalDevCR** [comment]
And what was the solution? I'm experiencing the exact same issue!

**Comment by yuckdevchan** [comment]
> What was the solution? I have the same issue.

I hate to say it, but the problem just seemingly disappeared.
