### ISSUE TITLE
Error: network docker_default has active endpoints

### ISSUE THREAD

**Issue by webmozart** [bitwarden/server#2805]
### Steps To Reproduce

1. Execute `bitwarden.sh stop` or `bitwarden.sh restart`

### Expected Result

Bitwarden should be stopped without errors.

### Actual Result

While stopping, the error `failed to remove network docker_default: Error response from daemon: error while removing network: network docker_default id 0d6c0300e3d8e46eb7ce0daaa95a5ab57c15999e61d82ccbf588a852409cdba3 has active endpoints` is returned and stopping fails.

```
$ /home/bitwarden/bitwarden.sh stop
 _     _ _                         _            
| |__ (_) |___      ____ _ _ __ __| | ___ _ __  
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \ 
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2023, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

bitwarden.sh version 2023.2.1
Docker version 23.0.1, build a5ee5b1
Docker Compose version v2.17.0-rc.1

[+] Running 13/13
 ✔ Container bitwarden-icons          Removed                                                                        1.6s 
 ✔ Container bitwarden-events         Removed                                                                        2.3s 
 ✔ Container bitwarden-attachments    Removed                                                                        1.1s 
 ✔ Container bitwarden-sso            Removed                                                                        3.6s 
 ✔ Container bitwarden-notifications  Removed                                                                        2.1s 
 ✔ Container bitwarden-nginx          Removed                                                                        0.7s 
 ✔ Container bitwarden-web            Removed                                                                        1.5s 
 ✔ Container bitwarden-admin          Removed                                                                        1.6s 
 ✔ Container bitwarden-api            Removed                                                                        3.6s 
 ✔ Container bitwarden-identity       Removed                                                                        3.1s 
 ✔ Container bitwarden-mssql          Removed                                                                       60.6s 
 ✘ Network docker_default             Error                                                                          0.0s 
 ✔ Network docker_public              Removed                                                                        0.1s 
failed to remove network docker_default: Error response from daemon: error while removing network: network docker_default id 0d6c0300e3d8e46eb7ce0daaa95a5ab57c15999e61d82ccbf588a852409cdba3 has active endpoints
```

### Build Version

2023.2.1

### Environment

Self-Hosted

### Environment Details

- OS: Ubuntu 20.04.6 LTS (GNU/Linux 5.15.0-1031-aws x86_64)
- Hardware: AWS EC2 t3a.medium (4 GB RAM, 2 vCPU, 2.2-2.5 GHz)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by MarsCandyBars** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration, does _docker ps_ show any unhealthy containers? Do you have any files open that you are editing when attempting to run these commands?

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by webmozart** [comment]
@MarsCandyBars Thanks a lot for your investigation!

We have Bitwarden up and running since 2019. Since then, we continuously updated the installation without changing any of the configuration and had no problems until this error popped up with the latest version. We have a cron job restarting Bitwarden every night, and that job didn't fail in the past. That doesn't sound like a configuration issue to me.

However, rebooting the server helped. I assume that the upgrade left over some artifacts (maybe containers were renamed?) that prevented Bitwarden from shutting down properly.

Thanks, case closed!
