### ISSUE TITLE
Login entries disappear after adding Organization when using SQLite

### ISSUE THREAD

**Issue by piece-o-cake** [bitwarden/server#2815]
### Steps To Reproduce

1. Stand up a fresh docker container (using SQLite as the DB) from the latest bitwarden/self-host:beta  (or dev, doesn't matter in this case)

Using Web Vault...
2. Create your account and verify your email address.
3. Add two fake login entries just to visually see there is an underlying problem.
4. +New Organization and upload the License file. (in my case it is a family org)
5. Log out and log back in.

### Expected Result

You should see the login entries you created and the organization you added.

### Actual Result

You don't see your login entries or the organization you added.  The client is receiving an HTTP 500 when attempting to sync.

### Additional Context

There is an API.log stack trace entry which I included below.  I pulled the latest Master and through some trial and error, I was able to isolate the issue to [Infrastructure.EntityFramework.Repositories.CollectionRepository.GetManyByUserIdAsync](https://github.com/bitwarden/server/blob/3d0ca908ff7c2bfb67d495ae263da69a822dfd6b/src/Infrastructure.EntityFramework/Repositories/CollectionRepository.cs#L308)

I did try mysql/mariadb and the the issue is not present in that configuration. (Though, I didn't go through all supported DB options...)

I refactored the code and built a new docker image/container and found that when the UserCollectionDetailsQuery is executed prior to the group by operation, it works.  **There could be a deeper underlying problem in the query, but I was able to get it to successfully execute by separately executing the group by.

This implementation executes:
`    public async Task<ICollection<CollectionDetails>> GetManyByUserIdAsync(Guid userId)
    {
        using (var scope = ServiceScopeFactory.CreateScope())
        {
            var dbContext = GetDatabaseContext(scope);
            var queryResult = await new UserCollectionDetailsQuery(userId).Run(dbContext).ToListAsync();

            var groupedResult = queryResult.GroupBy(c => new { c.Id, c.OrganizationId, c.Name, c.CreationDate, c.RevisionDate, c.ExternalId });

            return groupedResult.Select(cg => new CollectionDetails
            {
                Id = cg.Key.Id,
                OrganizationId = cg.Key.OrganizationId,
                Name = cg.Key.Name,
                CreationDate = cg.Key.CreationDate,
                RevisionDate = cg.Key.RevisionDate,
                ExternalId = cg.Key.ExternalId,
                ReadOnly = Convert.ToBoolean(cg.Min(c => Convert.ToInt32(c.ReadOnly))),
                HidePasswords = Convert.ToBoolean(cg.Min(c => Convert.ToInt32(c.HidePasswords))),
            }).ToList();
        }
    }`

Stack Trace:

2023-03-20 16:05:55.323 +00:00 [ERR] The LINQ expression 'GroupByShaperExpression:
KeySelector: new { 
    Id = c.Id, 
    OrganizationId = c.OrganizationId, 
    Name = c.Name, 
    CreationDate = c.CreationDate, 
    RevisionDate = c.RevisionDate, 
    ExternalId = c.ExternalId
 }, 
GroupingEnumerable:ShapedQueryExpression: 
    QueryExpression: 
        Projection Mapping:
            Outer.Outer.Outer.Outer.Outer.Outer -> EntityProjectionExpression: Collection
            Outer.Outer.Outer.Outer.Outer.Inner -> EntityProjectionExpression: OrganizationUser
            Outer.Outer.Outer.Outer.Inner -> EntityProjectionExpression: Organization
            Outer.Outer.Outer.Inner -> EntityProjectionExpression: CollectionUser
            Outer.Outer.Inner -> EntityProjectionExpression: GroupUser
            Outer.Inner -> EntityProjectionExpression: Group
            Inner -> EntityProjectionExpression: CollectionGroup
        SELECT 1
        FROM Collection AS c
        INNER JOIN OrganizationUser AS o ON c.OrganizationId == o.OrganizationId
        INNER JOIN Organization AS o0 ON c.OrganizationId == o0.Id
        LEFT JOIN CollectionUsers AS c0 ON ((o.AccessAll == 0) && (c.Id == c0.CollectionId)) && (o.Id == c0.OrganizationUserId)
        LEFT JOIN GroupUser AS g ON ((c0.CollectionId == NULL) && (o.AccessAll == 0)) && (o.Id == g.OrganizationUserId)
        LEFT JOIN Group AS g0 ON g.GroupId == g0.Id
        LEFT JOIN CollectionGroups AS c1 ON ((g0.AccessAll == 0) && (c.Id == c1.CollectionId)) && (g.GroupId == c1.GroupId)
        WHERE ((((o.UserId == @___userId_0) && (o.Status == 2)) && o0.Enabled) && (((o.AccessAll || (c0.CollectionId != NULL)) || g0.AccessAll) || (c1.CollectionId != NULL))) && ((((((c.Id == c.Id) && (c.OrganizationId == c.OrganizationId)) && (c.Name == c.Name)) && (c.CreationDate == c.CreationDate)) && (c.RevisionDate == c.RevisionDate)) && (c.ExternalId == c.ExternalId))
    ShaperExpression: new TransparentIdentifier<TransparentIdentifier<TransparentIdentifier<TransparentIdentifier<TransparentIdentifier<TransparentIdentifier<Collection, OrganizationUser>, Organization>, CollectionUser>, GroupUser>, Group>, CollectionGroup>(
            Outer = new TransparentIdentifier<TransparentIdentifier<TransparentIdentifier<TransparentIdentifier<TransparentIdentifier<Collection, OrganizationUser>, Organization>, CollectionUser>, GroupUser>, Group>(
                Outer = new TransparentIdentifier<TransparentIdentifier<TransparentIdentifier<TransparentIdentifier<Collection, OrganizationUser>, Organization>, CollectionUser>, GroupUser>(
                    Outer = new TransparentIdentifier<TransparentIdentifier<TransparentIdentifier<Collection, OrganizationUser>, Organization>, CollectionUser>(
                        Outer = new TransparentIdentifier<TransparentIdentifier<Collection, OrganizationUser>, Organization>(
                            Outer = new TransparentIdentifier<Collection, OrganizationUser>(
                                Outer = EntityShaperExpression: 
                                    Bit.Infrastructure.EntityFramework.Models.Collection
                                    ValueBufferExpression: 
                                        ProjectionBindingExpression: Outer.Outer.Outer.Outer.Outer.Outer
                                    IsNullable: False
                                , 
                                Inner = EntityShaperExpression: 
                                    Bit.Infrastructure.EntityFramework.Models.OrganizationUser
                                    ValueBufferExpression: 
                                        ProjectionBindingExpression: Outer.Outer.Outer.Outer.Outer.Inner
                                    IsNullable: False
                            ), 
                            Inner = EntityShaperExpression: 
                                Bit.Infrastructure.EntityFramework.Models.Organization
                                ValueBufferExpression: 
                                    ProjectionBindingExpression: Outer.Outer.Outer.Outer.Inner
                                IsNullable: False
                        ), 
                        Inner = EntityShaperExpression: 
                            Bit.Infrastructure.EntityFramework.Models.CollectionUser
                            ValueBufferExpression: 
                                ProjectionBindingExpression: Outer.Outer.Outer.Inner
                            IsNullable: True
                    ), 
                    Inner = EntityShaperExpression: 
                        Bit.Infrastructure.EntityFramework.Models.GroupUser
                        ValueBufferExpression: 
                            ProjectionBindingExpression: Outer.Outer.Inner
                        IsNullable: True
                ), 
                Inner = EntityShaperExpression: 
                    Bit.Infrastructure.EntityFramework.Models.Group
                    ValueBufferExpression: 
                        ProjectionBindingExpression: Outer.Inner
                    IsNullable: True
            ), 
            Inner = EntityShaperExpression: 
                Bit.Infrastructure.EntityFramework.Models.CollectionGroup
                ValueBufferExpression: 
                    ProjectionBindingExpression: Inner
                IsNullable: True
        )

    .AsQueryable()
    .Min(e => Convert.ToInt32(e.Outer.Outer.Outer.Outer.Outer.Inner.AccessAll || e.Outer.Inner.AccessAll || !((bool?)e.Outer.Outer.Outer.Inner.ReadOnly ?? (bool?)e.Inner.ReadOnly ?? False) ? False : True))' could not be translated. Additional information: Translation of method 'System.Convert.ToInt32' failed. If this method can be mapped to your custom function, see https://go.microsoft.com/fwlink/?linkid=2132413 for more information. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
System.InvalidOperationException: The LINQ expression 'GroupByShaperExpression:
KeySelector: new { 
    Id = c.Id, 
    OrganizationId = c.OrganizationId, 
    Name = c.Name, 
    CreationDate = c.CreationDate, 
    RevisionDate = c.RevisionDate, 
    ExternalId = c.ExternalId
 }, 
GroupingEnumerable:ShapedQueryExpression: 
    QueryExpression: 
        Projection Mapping:
            Outer.Outer.Outer.Outer.Outer.Outer -> EntityProjectionExpression: Collection
            Outer.Outer.Outer.Outer.Outer.Inner -> EntityProjectionExpression: OrganizationUser
            Outer.Outer.Outer.Outer.Inner -> EntityProjectionExpression: Organization
            Outer.Outer.Outer.Inner -> EntityProjectionExpression: CollectionUser
            Outer.Outer.Inner -> EntityProjectionExpression: GroupUser
            Outer.Inner -> EntityProjectionExpression: Group
            Inner -> EntityProjectionExpression: CollectionGroup
        SELECT 1
        FROM Collection AS c
        INNER JOIN OrganizationUser AS o ON c.OrganizationId == o.OrganizationId
        INNER JOIN Organization AS o0 ON c.OrganizationId == o0.Id
        LEFT JOIN CollectionUsers AS c0 ON ((o.AccessAll == 0) && (c.Id == c0.CollectionId)) && (o.Id == c0.OrganizationUserId)
        LEFT JOIN GroupUser AS g ON ((c0.CollectionId == NULL) && (o.AccessAll == 0)) && (o.Id == g.OrganizationUserId)
        LEFT JOIN Group AS g0 ON g.GroupId == g0.Id
        LEFT JOIN CollectionGroups AS c1 ON ((g0.AccessAll == 0) && (c.Id == c1.CollectionId)) && (g.GroupId == c1.GroupId)
        WHERE ((((o.UserId == @___userId_0) && (o.Status == 2)) && o0.Enabled) && (((o.AccessAll || (c0.CollectionId != NULL)) || g0.AccessAll) || (c1.CollectionId != NULL))) && ((((((c.Id == c.Id) && (c.OrganizationId == c.OrganizationId)) && (c.Name == c.Name)) && (c.CreationDate == c.CreationDate)) && (c.RevisionDate == c.RevisionDate)) && (c.ExternalId == c.ExternalId))
    ShaperExpression: new TransparentIdentifier<TransparentIdentifier<TransparentIdentifier<TransparentIdentifier<TransparentIdentifier<TransparentIdentifier<Collection, OrganizationUser>, Organization>, CollectionUser>, GroupUser>, Group>, CollectionGroup>(
            Outer = new TransparentIdentifier<TransparentIdentifier<TransparentIdentifier<TransparentIdentifier<TransparentIdentifier<Collection, OrganizationUser>, Organization>, CollectionUser>, GroupUser>, Group>(
                Outer = new TransparentIdentifier<TransparentIdentifier<TransparentIdentifier<TransparentIdentifier<Collection, OrganizationUser>, Organization>, CollectionUser>, GroupUser>(
                    Outer = new TransparentIdentifier<TransparentIdentifier<TransparentIdentifier<Collection, OrganizationUser>, Organization>, CollectionUser>(
                        Outer = new TransparentIdentifier<TransparentIdentifier<Collection, OrganizationUser>, Organization>(
                            Outer = new TransparentIdentifier<Collection, OrganizationUser>(
                                Outer = EntityShaperExpression: 
                                    Bit.Infrastructure.EntityFramework.Models.Collection
                                    ValueBufferExpression: 
                                        ProjectionBindingExpression: Outer.Outer.Outer.Outer.Outer.Outer
                                    IsNullable: False
                                , 
                                Inner = EntityShaperExpression: 
                                    Bit.Infrastructure.EntityFramework.Models.OrganizationUser
                                    ValueBufferExpression: 
                                        ProjectionBindingExpression: Outer.Outer.Outer.Outer.Outer.Inner
                                    IsNullable: False
                            ), 
                            Inner = EntityShaperExpression: 
                                Bit.Infrastructure.EntityFramework.Models.Organization
                                ValueBufferExpression: 
                                    ProjectionBindingExpression: Outer.Outer.Outer.Outer.Inner
                                IsNullable: False
                        ), 
                        Inner = EntityShaperExpression: 
                            Bit.Infrastructure.EntityFramework.Models.CollectionUser
                            ValueBufferExpression: 
                                ProjectionBindingExpression: Outer.Outer.Outer.Inner
                            IsNullable: True
                    ), 
                    Inner = EntityShaperExpression: 
                        Bit.Infrastructure.EntityFramework.Models.GroupUser
                        ValueBufferExpression: 
                            ProjectionBindingExpression: Outer.Outer.Inner
                        IsNullable: True
                ), 
                Inner = EntityShaperExpression: 
                    Bit.Infrastructure.EntityFramework.Models.Group
                    ValueBufferExpression: 
                        ProjectionBindingExpression: Outer.Inner
                    IsNullable: True
            ), 
            Inner = EntityShaperExpression: 
                Bit.Infrastructure.EntityFramework.Models.CollectionGroup
                ValueBufferExpression: 
                    ProjectionBindingExpression: Inner
                IsNullable: True
        )

    .AsQueryable()
    .Min(e => Convert.ToInt32(e.Outer.Outer.Outer.Outer.Outer.Inner.AccessAll || e.Outer.Inner.AccessAll || !((bool?)e.Outer.Outer.Outer.Inner.ReadOnly ?? (bool?)e.Inner.ReadOnly ?? False) ? False : True))' could not be translated. Additional information: Translation of method 'System.Convert.ToInt32' failed. If this method can be mapped to your custom function, see https://go.microsoft.com/fwlink/?linkid=2132413 for more information. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|15_0(ShapedQueryExpression translated, <>c__DisplayClass15_0& )
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.TranslateSubquery(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalSqlTranslatingExpressionVisitor.TranslateInternal(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberAssignment(MemberAssignment memberAssignment)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.VisitMemberInit(MemberInitExpression memberInitExpression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Bit.Infrastructure.EntityFramework.Repositories.CollectionRepository.GetManyByUserIdAsync(Guid userId) in /source/src/Infrastructure.EntityFramework/Repositories/CollectionRepository.cs:line 307
   at Bit.Api.Vault.Controllers.SyncController.Get(Boolean excludeDomains) in /source/src/Api/Vault/Controllers/SyncController.cs:line 82
   at lambda_method358(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

### Githash Version

e667908a-dirty

### Environment Details

Found on rbpi 4
Duplicated on Windows 10

### Database Image

SQLite

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djchateau** [comment]
Hey there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!
