### ISSUE TITLE
Wrong IP behind reverse proxy

### ISSUE THREAD

**Issue by taaem** [bitwarden/server#2908]
### Steps To Reproduce

1. Login in with wrong credentials
2. Look at `logs/identity/Identity/20230505.txt`

### Expected Result

Expected to find my real IP logged in the identity logs.

### Actual Result

Instead the following is logged:
```
2023-05-05 11:26:02.733 +00:00 [Warning] Failed login attempt. ::ffff:172.29.60.10
```
But my reverse proxy and nginx are properly configured, since I see in `logs/nginx/access.log`:
```
xxx.xxx.xxx.xxx - - [05/May/2023:11:28:20 +0000] "POST /identity/accounts/prelogin HTTP/1.1" 200 86 "https://url/" "Mozilla/5.0 (Android 13; Mobile; rv:109.0) Gecko/112.0 Firefox/112.0" "xxx.xxx.xxx.xxx "
```
where `xxx.xxx.xxx.xxx` is my actual IP.

### Additional Context

I run Bitwarden behind a Traefik server that correctly sets the headers and I configured bitwardens nginx to trust the reverse proxy in the `config.yml`:
```
real_ips:
- 172.16.0.0/12
```

### Build Version

2023.4.3

### Environment

Self-Hosted

### Environment Details

- Linux
- Docker & Docker Compose via the official `bitwarden.sh`

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there,

Looks like the header may not being properly passed through to the Bitwarden server. 

Have you  tried adding `TrustedProxy` to your config.yml

**Comment by taaem** [comment]
@Krychaz I don't see `TrustedProxy` in https://github.com/bitwarden/server/blob/master/util/Setup/Configuration.cs, I configured `RealIps` as noted in my original post. Is there another place to configure this?

**Comment by taaem** [comment]
If I check `<url>/api/ip` I can see:
```json
{
  "ip": "::ffff:172.29.60.10",
  "headers": {
    "X-Forwarded-For": {
      "key": "X-Forwarded-For",
      "value": [
        "xxx.xxx.xxx.xxx, xxx.xxx.xxx.xxx"
      ]
    }
  }
}
```
where `xxx.xxx.xxx.xxx` is again my real ip, but twice, maybe that's the issue?

**Comment by Krychaz** [comment]
Yes, this could be the issue. What is your reverse proxy solution? You can try and modify the configuration of your reverse proxy to only send a single IP address in the header.

**Comment by taaem** [comment]
If I see it correctly, I only send one IP in that address but the second one gets added by the bitwarden nginx. This is the behavior described in https://github.com/bitwarden/server/pull/486#issuecomment-487144227, so I guess its the correct behavior. If I understand the comment afterwards, bitwarden should use the first IP in that header as the originating IP address. I don't know if anything after this PR changed, breaking that functionality.

**Comment by taaem** [comment]
According to https://github.com/bitwarden/server/blob/5a850f48e2adf309a05741a43eb45eb390354677/src/Identity/appsettings.json#L72 the client IP is set from the `CF-Connecting-IP` and not `X-Forwarded-For` or `X-Real-IP` headers. But for selfhosted instances the `CF-Connecting-IP` header is not set.

**Comment by patrikgrill** [comment]
I have the same problem since I upgraded to version 2023.4.3. As a reverse proxy solution I use NetScaler, which sends the client IP as `X-Forwarded-For`.

**Comment by taaem** [comment]
Please ignore my comment before, I think the issue is, that I would need to configure `globalSettings__knownProxies=::ffff:172.29.0.10`, but I my reverse proxy doesn't actually have a static IP, instead I would like to allow the whole subnet. According to https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-7.0 I would need to be able to configure the `KnownNetworks`, to allow my whole docker subnet to be used as a proxy IP.

**Comment by GeoCookie** [comment]
I have the same problem. The logs still show the nginx container ip address, even if I access bitwarden directly (not through my reverse prox)
![image](https://github.com/bitwarden/server/assets/43962716/c0895085-5adc-4a1d-9653-4758455e8065)
![image](https://github.com/bitwarden/server/assets/43962716/0d7e1018-cc13-42e6-9ee5-9147b7d836b3)

It was working with previous version. I can't tell from which version the problem appeared

**Comment by Krychaz** [comment]
Thank you everyone for your feedback. 

We are currently looking into this. We will update you as soon as possible.

**Comment by vinnyperella** [comment]
Just wanted to note I'm seeing the same thing I'm using Bitwarden without a reverse proxy I think it has something to do with the "::ffff:" prefix which appears to be an "IPv6 prefix for an IPv4 address mapped into IPv6 space." This is breaking fail2ban integration for failed logins because it's not forwarding the actual client IP.

I don't know when this stopped working I only noticed it recently but I have not changed anything on my end other than upgrading Bitwarden and I have old fail2ban emails banning failed logins so I know it used to work.

**Comment by TotallyMonica** [comment]
Had this issue #3018 with successful logins as well. I hadn't checked failed attempts but given it's repeatable with successful suggests it's the same underlying issue

**Comment by tmknight** [comment]
This is clearly a regression over previous release; hopefully we can get a patch/point release to resolve this vs waiting for next full release.

**Comment by TotallyMonica** [comment]
While experimenting with the Bitwarden Unified variant, I found that the bug is present there as well, although it only uses the IPv4 address instead of the mixed addressing it was using previously.

**Comment by vinnyperella** [comment]
I believe this is resolved with the most recent update 2023.5.1 I'm now seeing the correct IP in the identity logs and my fail2ban is working as expected.

**Comment by tmknight** [comment]
Confirmed - 2023.5.1 resolves this issue

**Comment by djsmith85** [comment]
@vinnyperella and @tmknight Thank you for the updates. 

Closing this now.

**Comment by df503** [comment]
> Please ignore my comment before, I think the issue is, that I would need to configure `globalSettings__knownProxies=::ffff:172.29.0.10`, but I my reverse proxy doesn't actually have a static IP, instead I would like to allow the whole subnet. According to https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-7.0 I would need to be able to configure the `KnownNetworks`, to allow my whole docker subnet to be used as a proxy IP.

Confirming the addition of globalSettings__knownProxies=10.10.10.2 worked for me. I tried to update the config.yaml file first, but that didn't seem to work.

**Comment by Yannic92** [comment]
I'm currently running 2023.12.0 and I experience exactly the behavior described by @taaem.

```json
{
    "ip": "::ffff:172.30.0.9",
    "headers": {
        "X-Forwarded-For": {
            "key": "X-Forwarded-For",
            "value": [
                "xxx.xxx.xxx.xxx, xxx.xxx.xxx.xxx"
            ]
        }
    }
}
```

where xxx.xxx.xxx.xxx is my actual client IP. So it is forwarded correctly. I however feel suspicious about the value beeing an array with a single string containing comma separated values.
Is this an issue with parsing internally? Shouldn't it look like this?

```json
{
    "ip": "::ffff:172.30.0.9",
    "headers": {
        "X-Forwarded-For": {
            "key": "X-Forwarded-For",
            "value": [
                "xxx.xxx.xxx.xxx", 
                "xxx.xxx.xxx.xxx"
            ]
        }
    }
}
```

**Comment by bubuyu** [comment]
Since upgrading to version 2024.6.2 (including version 2024.7.2), the same problem has occurred again.

`{"ip":"::ffff:172.20.0.1","headers":{"X-Forwarded-For":{"key":"X-Forwarded-For","value":["xxx.xxx.xxx.xxx, xxx.xxx.xxx.xxx"]}}}`

**Comment by vinnyperella** [comment]
This may not be any help to the conversation but I'm using the latest self hosted (2024.7.1) instance WITHOUT a reverse proxy and I'm still getting the correct IP address when my fail2ban bans an IP for failed login attempts.

**Comment by threeputting** [comment]
I'm self-deploying on AWS ECS behind an ALB, seeing the exact same issue even when adding the private subnet ranges to the set_real_ip_from module in default.conf

Also tried adding the `globalSettings__knownProxies` env with a value to the Nginx, Identity, and API containers (figured API as well since I can see the JSON format of the header values at `url/api/ip`) and about 70% of requests show the correct IP while the other 30% shows the IPv4 in IPv6 space address.

This is with Nginx 2024.8.1, though I'm going to update to the latest tag now and test.

**Comment by hardwareadictos** [comment]
Same issue here on self-hosted v2025.12.1

**Comment by vinnyperella** [comment]
> Same issue here on self-hosted v2025.12.1

I'm still getting the correct IP address but Bitwarden AGAIN changed their logging format and my fail2ban filter broke. They changed it a month or so ago as well and I had to fix it and they changed it again with the latest update.

I've fixed my filter again here's what is working for me:

`failregex = ^%(__prefix_line)s\s*\[WRN\] Failed login attempt\. Is2FARequest: \S+ IpAddress: "<ADDR>"$`

**Comment by tl87** [comment]
I'm having the same issue with the version below:

**© 2026 Bitwarden Inc.
2025.12.2+82470bd**
