### ISSUE TITLE
Unable to spin up unified deployment (container image broken?)

### ISSUE THREAD

**Issue by skether** [bitwarden/server#2948]
### Steps To Reproduce

1. Create an environment variables file with the following content:
```
BW_DOMAIN=test.bitwarden.example.com

BW_INSTALLATION_ID=<id>
BW_INSTALLATION_KEY=<key>

BW_PORT_HTTP=8080
BW_PORT_HTTPS=8443

BW_DB_PROVIDER=sqlite

BW_ENABLE_SSL=False

BW_ENABLE_ADMIN=True
BW_ENABLE_API=True
BW_ENABLE_EVENTS=False
BW_ENABLE_ICONS=True
BW_ICONS_PROXY_TO_CLOUD=False
BW_ENABLE_IDENTITY=True
BW_ENABLE_NOTIFICATIONS=True
BW_ENABLE_SCIM=False
BW_ENABLE_SSO=False

globalSettings__mail__replyToEmail=bitwarden-noreply@example.com
globalSettings__mail__smtp__host=smtp.gmail.com
globalSettings__mail__smtp__port=587
globalSettings__mail__smtp__ssl=False
globalSettings__mail__smtp__username=<username>
globalSettings__mail__smtp__password=<password>

adminSettings__admins=<email-address>
```
2. Start the container in docker with the following command:
```docker run -d --env-file ./env-sqlite -p8080:8080 docker.io/bitwarden/self-host:beta```
3. Access the site locally using `127.0.0.1:8080`.

### Expected Result

Working Bitwarden installation. Being able to register new users and start using the site.

### Actual Result

Accessing `127.0.0.1:8080` loads up the UI as expected. According to the version marker at the bottom of the page, it is 2023.4.0.
However, when trying to create a new account it fails with the following error dialog.
![image](https://github.com/bitwarden/server/assets/22418558/4aeb4e97-c706-4e9f-b665-295ed4b50176)
Trying to log in also fails.
![image](https://github.com/bitwarden/server/assets/22418558/285b8d2a-509e-4e40-9ca0-d5bfb488552d)
Taking a look at the network tab in the dev tools also indicates that every request to an API endpoint fails with a 404 error.
![image](https://github.com/bitwarden/server/assets/22418558/8129f4f5-babe-460f-9574-b674c1cb4c99)

Having a look at /var/log/nginx/error.log in the container it has the following output:
```
2023/05/20 09:02:35 [error] 90#90: *21 open() "/app/Web/identity/accounts/register" failed (2: No such file or directory), client: 172.17.0.1, server: test.bitwarden.example.com, request: "POST /identity/accounts/register HTTP/1.1", host: "127.0.0.1:8080", referrer: "http://127.0.0.1:8080/"
2023/05/20 09:03:15 [error] 90#90: *23 open() "/app/Web/api/devices/knowndevice" failed (2: No such file or directory), client: 172.17.0.1, server: test.bitwarden.example.com, request: "GET /api/devices/knowndevice HTTP/1.1", host: "127.0.0.1:8080", referrer: "http://127.0.0.1:8080/"
2023/05/20 09:03:19 [error] 90#90: *23 open() "/app/Web/identity/accounts/prelogin" failed (2: No such file or directory), client: 172.17.0.1, server: test.bitwarden.example.com, request: "POST /identity/accounts/prelogin HTTP/1.1", host: "127.0.0.1:8080", referrer: "http://127.0.0.1:8080/"
2023/05/20 09:09:14 [error] 90#90: *25 open() "/app/Web/api/config" failed (2: No such file or directory), client: 172.17.0.1, server: test.bitwarden.example.com, request: "GET /api/config HTTP/1.1", host: "127.0.0.1:8080"
```
This seems to suggest a possible packaging error or nginx misconfiguration?

### Additional Context

This problem seems to have existed for some time. I originally run into this when I tried to upgrade my unified setup in the middle of February, which is still running on 2022.11.2.
This problem however is also reproducible with a completely new setup without any preexisting data.
The image used was pulled during the writing of this issue and according to the pull command has the following hash:
`sha256:9c6ef1fc1d4587ab35d8effa3e2d11d5d619e848cd2223508ced2a7390533a40`

### Githash Version

404 - Error

### Environment Details

Tested on Windows 10/Docker WSL, also on Ubuntu/Kubernetes.

### Database Image

sqlite

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djchateau** [comment]
Hey there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by justindbaur** [comment]
Can you switch using `true` and `false` (all lowercase) for all your `BW_ENABLE_` settings. We are [comparing against](https://github.com/bitwarden/server/blob/0bdc4c3902dc8346e8cceb2da77b22efb4393ffa/docker-unified/hbs/nginx-config.hbs#L107) `"true"` to turn on the services so I think it's thinking you don't want any services on.
