### ISSUE TITLE
./bwdata from container not mapped to host/server for easy backup / restore

### ISSUE THREAD

**Issue by santosantosanto** [bitwarden/server#2950]
### Steps To Reproduce

1. follow the official install instructions for bitwarden unified beta
2. follow the official backup instructions for selfhostet bitwarden

### Expected Result

find the data directory (which should be mapped to the server) 

### Actual Result

did not find any mapped directory for easy backup or rsync to another server

### Additional Context

maybe I am missing something then just give me a hint

### Githash Version

8d9ca424-dirty

### Environment Details

ubuntu 22.04 lts, 1GB Ram, 25GB disk, 1 CPU

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by justindbaur** [comment]
Hi @santosantosanto unified is using a "bring your own database" model which also means that you must bring your own backup strategy for the database. We are not currently planning on building a solution to do that for you with unified as of now.

**Comment by santosantosanto** [comment]
thx for your fast response, so I just save the directories according to the path of the container (inspect)  with rsync in a cronjob to another server of min.
