### ISSUE TITLE
Server isn't starting after install (MSSQL)

### ISSUE THREAD

**Issue by AngryKiller** [bitwarden/server#296]
´´´
Docker version 18.03.1-ce, build 9ee9f40
docker-compose version 1.21.2, build a133471

Removing network docker_default
WARNING: Network docker_default not found.
Pulling mssql       ... 
Pulling web         ... done
Pulling attachments ... done
Pulling api         ... done
Pulling identity    ... done
Pulling admin       ... done
Pulling icons       ... done
Pulling nginx       ... done

ERROR: for mssql  failed to register layer: Error processing tar file(exit status 1): operation not permitted
ERROR: failed to register layer: Error processing tar file(exit status 1): operation not permitted
´´´
I tried on 2 different servers, I don't know why it does that

**Comment by kspearrin** [comment]
What OS are these servers?

**Comment by AngryKiller** [comment]
Debian 8 and 9

**Comment by kspearrin** [comment]
Not sure. Never seen this. Quick google search shows: https://stackoverflow.com/questions/42784396/docker-error-error-processing-tar-fileexit-status-1-unexpected-eof

Maybe try one of these?

**Comment by AngryKiller** [comment]
It's a clean install of Docker so I don't think this is the issue but I'm gonna try later

**Comment by djsmith85** [comment]
Hi @AngryKiller, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
