### ISSUE TITLE
Custom Role User with Admin Permissions Unable to create Send

### ISSUE THREAD

**Issue by cksapp** [bitwarden/server#3000]
### Steps To Reproduce

1. Previously the `Custom role` type members with Admin level permissions were not subject to Organization Enterprise Policies similar to other Owner/Admin users
2. Create Custom role User with Admin permissions, joined to Organization with Enterprise policy enabled. Specifically in this case tested with **Send**
3. Standard User and Managers members have **Send** policy restricting creating send with banner notice of Organizational policy affecting **Send** capability
4. Custom role member with Admin permissions previously would be able to create **Send** without being subject to Org policy. Now does not allow creating new **Send** and gives error of Org policy but does not show banner notice as other member types.

### Expected Result

Minimum should stay consistent with **User** and **Manager** type member roles and display banner notice of Organizational Policy affecting **Send**.

Ideally should return to original state before changes to allow for Organization members who are a custom role type with Admin permissions to not be subject to Organization policies similar to current Admin members.

### Actual Result

No banner notice for Custom role members, and now cannot create new **Sends**

## Standard User
![2023-06-05_12h54_18](https://github.com/bitwarden/server/assets/66083310/50d5377e-0c7b-4ed3-ad3d-183e9738d286)
![2023-06-05_12h59_19](https://github.com/bitwarden/server/assets/66083310/7b10ee61-a30a-497b-9b98-af94c118d778)

## Custom role w/ **Admin** permissions

![2023-06-05_12h54_27](https://github.com/bitwarden/server/assets/66083310/4071eb82-f8b4-40b4-9d4f-335452918a8c)
![2023-06-05_12h55_22](https://github.com/bitwarden/server/assets/66083310/b664240d-680a-4384-9354-f5e99214620a)
![2023-06-05_12h59_24](https://github.com/bitwarden/server/assets/66083310/640c6cb6-d102-4313-8c36-b664b5027530)
![2023-06-05_12h59_46](https://github.com/bitwarden/server/assets/66083310/0f31e243-6f04-4aed-939b-ec0f38704e76)

### Additional Context

My best guess is that this was due to a recent change from the refactor of https://github.com/bitwarden/server/pull/2537

### Build Version

2023.5.0

### Environment

Cloud (bitwarden.com)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by TroyBW** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by micahblut** [comment]
Custom roles should have equivalent behavior to a user role for policies and are not exempt from policies. Only the Owner and Admin roles are exempt from certain policies. All custom roles should see the same banner as user roles do in Send, when the Remove Send policy is on.
