### ISSUE TITLE
Successful login email shows container IP address

### ISSUE THREAD

**Issue by TotallyMonica** [bitwarden/server#3018]
### Steps To Reproduce

1. Go to the self hosted instance's login page
2. Log in with a valid email, password and 2FA code (if applicable)
3. Check the email address for a successful login email

### Expected Result

Successful login email should show the IP address from where the successful login was from

### Actual Result

Shows the container's IP address

### Screenshots or Videos

![IMG_2840](https://github.com/bitwarden/server/assets/19542257/33906d22-27a2-4b2e-ada6-7a1ceefdd6ef)
![docker-network](https://github.com/bitwarden/server/assets/19542257/c68519a8-276a-419a-bb9f-038b765175cf)

### Additional Context

This is hosted on a Linode VM with a public facing IPv4 and IPv6 address, Bitwarden instance is behind a reverse proxy (Nginx Proxy Manager), although I suspect the reverse proxy to not be an issue as the IP address reported is a mixed addressing IP pointing to the `bitwarden-nginx` container. Network I'm connecting from has public IPv4 (no CG-NAT) and no public IPv6, only link-local IPv6

### Build Version

2023.5.0

### Environment

Self-Hosted

### Environment Details

- Operating System: Ubuntu 22.04
- Environment: Docker v20.10.21 via Docker Compose v1.29.2
- Hardware: Linode 4GB RAM Shared CPU (2 cores "EPYC 77", 4GB RAM, 80GB SSD

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by sammbw** [comment]
Hi there,

Thank you for your report! 

I was able to reproduce this issue, and I have flagged this to our engineering team.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time - our engineering team will be happy to review these.

Thanks once again!

**Comment by sammbw** [comment]
Hi there!

Thank you for your report, it seems like it is a duplicate of this one https://github.com/bitwarden/server/issues/2908.

If you wish to add any further information/screenshots/recordings etc., please feel free to do so at any time in there - our engineering team will be happy to review these.

This issue will now be closed.

Thanks!

**Comment by TotallyMonica** [comment]
Yep, this looks like a duplicate issue.
