### ISSUE TITLE
no device login authentification possible (2FA activated)

### ISSUE THREAD

**Issue by lastphoenx** [bitwarden/server#3029]
### Steps To Reproduce

1. Go to iOS App enable device login
2. go to chrome browser plugin bitwarden  
3. Type your email and click login with device
4. go to device check  fingerprint and accept login request
5. screen on browser extension of bitwarden change to "send push notification again"
6. 

### Expected Result

to proceed without masterpassword till 2FA-Key is requestet

### Actual Result

push notification is sent to device but next step for login does not appear even to request is accepted on device

### Githash Version

1202a670-dirty

### Environment Details

ubuntu lts

### Database Image

bitwarden latest stable version

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there,

You tagged this issue as Bitwarden Unified. If you are self-hosting Bitwarden, login in with device is not available on self-hosted instance as of yet. More information can be found here - Logging in with a device is currently only available on the Bitwarden cloud server (https://vault.bitwarden.com/).
