### ISSUE TITLE
Log in with device not working on 2023.7.0

### ISSUE THREAD

**Issue by rusty1281** [bitwarden/server#3103]
### Steps To Reproduce

When trying to use the log in with device feature I have an issue. Both the server docker and the iOS app are on 2023.7.0 version. The setup is behind a working nginx RP.

After activating the log in with device on the mobile phone I get the option to click it on the web page as well. The challenge comes to the mobile device but after accepting it, nothing happens and the login into the vault does not occur.

### Expected Result

Log in to the web vault after successful authorization on the device

### Actual Result

The web vault stays on the challenge screen offering other ways to log into the vault. Manual log in with the master password does work with no issues

### Additional Context

When using the master password, behind a reverse proxy, the web console is reporting:

 `Information: WebSocket connected to wss://bitwarden.mydomain.com/notifications/hub?access_token=eyJhbGciOiJSU...`

When trying to use the log in with the device, and right after I push the button, the notification and challenge land on the phone, but the browser console is reporting:

`Error: WebSocket failed to connect. The connection could not be found on the server, either the endpoint may not be a SignalR endpoint, the connection ID is not present on the server, or there is a proxy blocking WebSockets. If you have multiple servers check that sticky sessions are enabled.`

Resending the challenge works every time, but after allowing it, nothing happens.

**The account is running with no 2FA atm.**

### Githash Version

"version":"2023.7.0","gitHash":"c13446ed-dirty"

### Environment Details

Docker 20.10.23
iOS: iPhone 11 (16.5)
MacStudio M1 Max (Ventura); happens on multiple web browsers.

### Database Image

mysql:latest (8.0.29)

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by benftrex** [comment]
I'm having the exact same issue, with the latest version of  /self-host:beta docker container.
The phone app receives the prompt correctly and the fingerprint phrase is the right one etc.. But then after accepting the login there, nothing happens on the clients where i wnat to login (tried with both mac desktop and web vault). 

Does something else needs to be changed in the config for this to work with a self hosted server ? 
Thanks

**Comment by rusty1281** [comment]
> I'm having the exact same issue, with the latest version of /self-host:beta docker container. The phone app receives the prompt correctly and the fingerprint phrase is the right one etc.. But then after accepting the login there, nothing happens on the clients where i wnat to login (tried with both mac desktop and web vault).
> 
> Does something else needs to be changed in the config for this to work with a self hosted server ? Thanks

haven’t found anything in the official docs on unified that needs to be added apart from the notification variable. But even with it the result is the same. Everything related to ssl is covered by reverse proxy in my case so I guess we need to wait for some more replies and inputs.

**Comment by justindbaur** [comment]
Hey all, I have just linked a PR that I believe would resolve this.

**Comment by benftrex** [comment]
Hi, I'm still getting the same issue with the latest version. The PR hasn't solved it at least for me. 
I try to login from a macos desktop app, i  receive the prompt correftly on my phone, then after accepting it, nothing happens.

**Comment by rusty1281** [comment]
> Hi, I'm still getting the same issue with the latest version. The PR hasn't solved it at least for me.
> I try to login from a macos desktop app, i receive the prompt correftly on my phone, then after accepting it, nothing happens.

I tested the .1 version the other day, and got the same error as before. I was also not clear is this solved or not considering the issue is still open

**Comment by benftrex** [comment]
Still not working on  2023.8.2 
Tried with many different combinations of apps, but the result is always the same: receiving the prompt to approve login correctly, but then nothing happening after having approved the login. 

Is there any extra configuration that needs to be set (via env. variable or other way) ?

**Comment by rusty1281** [comment]
Same here. Considering the release notes are not referring to this (including the .3 version from yesterday), I guess this is still a work in progress...

**Comment by 00WhengWheng** [comment]
Same here. How do I change my login authentication process?

**Comment by Tigo72** [comment]
I'm having the same behavior as Dianast21: it works when logging in with full masterpw, not when the login is with face-id.

**Comment by rusty1281** [comment]
@trmartin4 Hi there. So is this considered fixed and working? Asking as this seems to not work in the new upcoming self-host solution, at least not for me. Same issues as reported. FaceID unlock of the client does not work.

Thank you!
