### ISSUE TITLE
Bitwarden queries DNS for mssql every second

### ISSUE THREAD

**Issue by kaalph** [bitwarden/server#3115]
### Steps To Reproduce

Not sure why this happens. After updating my Bitwarden system yesterday, I'm seeing countless entries like this (screenshot). What can I do about it?

### Expected Result

Nothing, this query shouldnt happen.

### Actual Result

Bitwarden queries Pi-hole every second for the dns name "mssql".

### Screenshots or Videos

![grafik](https://github.com/bitwarden/server/assets/138721439/85a1dca1-3c95-488f-a51c-ddf46b9bc50b)

### Additional Context

No response

### Build Version

COREVERSION="2023.7.0" WEBVERSION="2023.7.0" KEYCONNECTORVERSION="2023.5.0"

### Environment

Self-Hosted

### Environment Details

Bitwarden Docker on Debian 11 (Proxmox)

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by notnamed** [comment]
Hi @kaalph - while this query is normal, the Docker internal resolver is supposed to respond to it, and not forward it upstream to your configured system-level resolver (your Pi-Hole). One reason this might occur is if the `mssql` container is crashlooping; this would obviously cause other issues unless you are using an external DB (https://bitwarden.com/help/external-db/). Does `docker ps` report that the `mssql` service is unhealthy or restarting? You may wish to reach out to our support team to troubleshoot this in more detail as you can share log entries etc with us via email: https://bitwarden.com/contact/
