### ISSUE TITLE
(Not really a Bug) No difference between US and EU version

### ISSUE THREAD

**Issue by craeckor** [bitwarden/server#3191]
### Steps To Reproduce

1. Download docker-stub-EU.zip and docker-stub-US.zip  (do this on a windows machine)
2. Unzip both docker-stub files
3. Create a folder outside e.g. in Downloads (name doesn't matter)
4. Inside this folder create two folders called us and eu
5. Put all files (no folders) from the two docker-stubs in the right folder, so all -US files  goes into us and all -EU into eu
6. Open powershell and go into the folder created in step 3
7. Run this little powershell script i made from the folder created in step 3
```powershell
Get-ChildItem -Path .\eu\|ForEach-Object{
$hasheu = Get-FileHash -Path .\eu\$($_.Name) -Algorithm SHA256
$hashus = Get-FileHash -Path .\us\$($_.Name) -Algorithm SHA256
if ($hasheu.Hash -ne $hashus.Hash) {
echo "false: $_"
echo "hash eu: $($hasheu.Hash)"
echo "hash us: $($hashus.Hash)"
}
else {
echo "true: $_"
echo "hash eu: $($hasheu.Hash)"
echo "hash us: $($hashus.Hash)"
}
}
```
8. Look at the exact same SHA256 Hash in every single file

### Expected Result

These files should be different in any kind of way.

### Actual Result

They all have the exact same content in it.
Powershell result (on my windows machine):
```text
true: app-id.json
hash eu: CA25F29C3466B4D8BC884EA94E20EA2066E148779DB2AB75299B5933FFF8B424
hash us: CA25F29C3466B4D8BC884EA94E20EA2066E148779DB2AB75299B5933FFF8B424
true: default.conf
hash eu: EBD35A0285E8309B33CAF1DA30D0F520D50E27BA861D90DA9ED382BB1786C71E
hash us: EBD35A0285E8309B33CAF1DA30D0F520D50E27BA861D90DA9ED382BB1786C71E
true: docker-compose.yml
hash eu: 6D6FFA2208B255502390BCF89248363291691F0EC36855844A888000F70F6DF5
hash us: 6D6FFA2208B255502390BCF89248363291691F0EC36855844A888000F70F6DF5
true: global.env
hash eu: E561369A155234FFF9D28EC15E5FFE0E3B81A8144FB080F6F49BD17CB73C18EF
hash us: E561369A155234FFF9D28EC15E5FFE0E3B81A8144FB080F6F49BD17CB73C18EF
true: global.override.env
hash eu: DBAB0504B5EF687B527AD3133429CFF246B08836941108E1E6813D3FA10D622C
hash us: DBAB0504B5EF687B527AD3133429CFF246B08836941108E1E6813D3FA10D622C
true: mssql.env
hash eu: 5413E94AEB5998CAAD7A7930CF10FA687F58830241E4C65423C01A15772A618F
hash us: 5413E94AEB5998CAAD7A7930CF10FA687F58830241E4C65423C01A15772A618F
true: mssql.override.env
hash eu: 34BC079BB54C8A44B98C49587202742D46FA10D02FE5F0A6BAB6B1A80AE43EE7
hash us: 34BC079BB54C8A44B98C49587202742D46FA10D02FE5F0A6BAB6B1A80AE43EE7
true: uid.env
hash eu: E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855
hash us: E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855
```

### Build Version

v2023.7.2

### Environment

Self-Hosted

### Environment Details

Doesn't matter for this "Bug"

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by craeckor** [comment]
The only thing which maybe should be different is in the global.override.env file. The second line says globalSettings__baseServiceUri__cloudRegion=US, which in my eyes should be globalSettings__baseServiceUri__cloudRegion=EU in docker-stub-eu.zip, maybe they forgot to change that only line, but what do i know.

**Comment by trmartin4** [comment]
Hello @craeckor.  This no longer appears to be the case, as I'm able to confirm that the SHA hashes for the ZIP files for our [latest release](https://github.com/bitwarden/server/releases) are different.  I am closing this report, but please feel free to re-open if your script indicates differently.
