### ISSUE TITLE
BountySource

### ISSUE THREAD

**Issue by indolering** [bitwarden/server#323]
Funding for an audit came up in another ticket, which led to some speculation as to how to organize it.

In the past, I've used [BountySource](https://www.bountysource.com/), which integrates nicely with  GitHub and supports cryptocurrencies.

- [ ] Setup BountySource Account
- [ ] Integrate with GitHub?

**Comment by fforbeck** [comment]
https://gitcoin.co/ integrates nicely with GitHub and supports crypto/tokens as well :)

**Comment by lordraiden** [comment]
This has to be pushed by @kspearrin 
Anyway paying premium is a way to fund this project, who would pay more for a bug bounty program?

**Comment by sNiXx** [comment]
I think this would be incredibly useful - whether bountysource or any other solution - as some people need specific features and want to support development in a direction that fits their needs. Setting up a bounty does not rule out paying for premium. I personally would require a few additional features that are currently missing and that would help me move away from closed-source software.

Thanks for reconsidering this!

**Comment by rogersachan** [comment]
shouldn't this be closed since an audit has been done?
