### ISSUE TITLE
Unified image only pushed for amd64

### ISSUE THREAD

**Issue by ChrisSlashNull** [bitwarden/server#3295]
### Steps To Reproduce

1. Open Docker Hub
2. Search for „bitwarden/self-host“

### Expected Result

The :beta image is the newest version of bw unified (as documented).

### Actual Result

The :beta image doesn‘t get updated.
Instead there are tags with <version>-beta only for amd64, not for arm.

### Screenshots or Videos

![IMG_1221](https://github.com/bitwarden/server/assets/128401608/e3a650c7-8fe4-4bd1-8f26-90c7d1951315)

### Githash Version

269539c5-dirty

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by notnamed** [comment]
Hello, thank you for raising this! We're aware that due to some changes we've implemented the build process, the past few releases did not get built for ARM. We're tracking this internally and will have a subsequent release and Help Center updates available in the near future.

**Comment by notnamed** [comment]
@holow29 Both the introduction of the versioned tags not updating the `beta` tag as well and the lack of an ARM image are part of the same workflow issue that was introduced recently. The intent was to also update `beta` alongside a versioned `beta` image; that did not happen. The current state is not the desired one, and temporarily the `beta` tag does not contain the latest code. However, the plan going forward is a return to the documented workflow.
