### ISSUE TITLE
Setting URI Match Detection to Host Results in Error and Dropped Session 

### ISSUE THREAD

**Issue by bgshacklett** [bitwarden/server#341]
# Steps to Reproduce
1. Edit an entry.
2. Modify the Match Detection for the URI to be "Host".
3. Save the entry.

# Expected Behavior
The entry is saved successfully

# Actual Behavior
* I receive an error: "An error has occurred: An unexpected error has occurred"
* Session is logged out

Other notes:
* Similar behavior was seen with the main web site, the Chrome extension and the desktop app for Windows.
* After reproducing the issue about 6 times, it eventually worked as expected.

**Comment by kspearrin** [comment]
Is this using self-hosted server or Bitwarden cloud?

**Comment by kspearrin** [comment]
Do you have a timestamp on when the issue occurred? It is likely this had no relation to changing the value to Host, and just the fact that you were actually trying to save something.

**Comment by bgshacklett** [comment]
Not that I can remember, honestly. Would the desktop client save logs in a location that I can find? For what it's worth, I've only ever seen this behavior when changing that specific value and it's been largely reproducible.

**Comment by kspearrin** [comment]
No, I don't think so. The next time it occurs please let me know the timestamp and I can look it up on the server to see what happened.

**Comment by bgshacklett** [comment]
I'll do my best to repro as soon as I have a moment. Thanks.

**Comment by bgshacklett** [comment]
I finally got a repro on this with an exact time: 15:01 UTC. The cause was slightly different: modifying the URI rather than changing its type.
