### ISSUE TITLE
Bitwarden Unified says Organization expired , but it is not

### ISSUE THREAD

**Issue by florie1706** [bitwarden/server#3412]
### Steps To Reproduce

1. Go to 'Organization'
2. Click on 'License'

### Expected Result

A valid license is provided so it just should work.

### Actual Result

Got mail notification that my family organisation is expired, cannot use the data inside the organisation.

### Screenshots or Videos

<img width="998" alt="SCR-20231105-hxds" src="https://github.com/bitwarden/server/assets/26010442/1e363dbb-4736-4586-9326-91bc6b0db683">

### Additional Context

This happens to my family organisation since the image bitwarden/self-host:2023.10.0-beta but also persists in bitwarden/self-host:2023.10.1-beta

Prior that two images I had no issues. 

### Githash Version

55ecec6f-dirty

### Environment Details

- OS Ubuntu Server 23.10
- Environment: Docker

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by GuillaumeHullin** [comment]
Same here. I tried uploading the original license file but it did not work. I redownloaded the license file and reuploaded it on my self-hosted instance, then it worked for a few days and it happened the same today again.

@florie1706, I'm not sure if I'm on "Bitwarden Unified"... how do you see that?

**Comment by florie1706** [comment]
I would say self hosted is unified 😉

**Comment by sammbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a license compatibility issue. Please try updating your instance and applying the latest license from the Bitwarden web vault. If that doesn't resolve it, please contact us using the form below.

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our contact form, so we can continue troubleshooting: https://bitwarden.com/contact/ 

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation (https://bitwarden.com/help/) or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!

**Comment by kolja1507** [comment]
@sammbw Our company faces the same issue with a self-hosted Bitwarden instance. Happened first on November 2nd after we updated our server to v2023.10.0. Fixed it by re-downloading our org license file from bitwarden.com (which wasn't suspended) and re-uploading it to our installation. November 3rd, the issue reoccurred after updating our server to v2023.10.1. Fixed it again as before. Both times, our organization was suspended although the expiration date of our Enterprise subscription was and still is way in the future. The suspension led to ~200 employees not being able to access any collection, TOTP etc.

**Comment by GuillaumeHullin** [comment]
@sammbw I understand that you cannot reproduce it, but it doesn't mean that it is not a bug. Please re-open this issue so that we can work to find out what is going on.

**Comment by florie1706** [comment]
That is what Bitwarden Support answered this morning ( I reuploaded the newly downloaded license file twice before I opened this issue here). For now it works but it worked before as well for let's say half a day / a day as mentioned by @kolja1507 

```

Hi
​
I apologize for the inconvenience. Please follow the below steps which should resolve this issue:

If you haven’t already, please update your self-hosted server to the latest version following these steps: https://bitwarden.com/help/updating-on-premise/

Have an Owner log into the Cloud Org at https://vault.bitwarden.com  or https://vault.bitwarden.eu  and download a new license file.

Have an Owner log into the self-hosted organization (which may not be the same user as the cloud one) and apply the new license file.

Please note that the server must be updated to the latest version for the new licence to be applied.  This is not normal, and is due to a bug.

#2 - Disable billing sync

Remove the following line from ./bwdata/env/global.override.env:
globalSettings__enableCloudCommunication=true

Run bitwarden restart command from Bitwarden shell script.

Re-download the licence from https://vault.bitwarden.com or https://vault.bitwarden.eu 

Re-apply this to the server manually once again


Full documentation on this feature can be found here:

https://bitwarden.com/help/families-for-enterprise-self-hosted/#step-1-enable-cloud-communication 
​
I can confirm that there was a bug in the 2023.10 release that caused this issue and that in most instances re-applying the licence file resolved this.

We have since released version 2023.10.1, which solves the issue.

The root cause was a change in the licence file format for the 2023.10 release.  I apologise once again for the inconvenience and can confirm that the team will take every effort to ensure that a similar error never reoccurs.

```

They speak about a bug ;)

**Comment by GuillaumeHullin** [comment]
> @sammbw Our company faces the same issue with a self-hosted Bitwarden instance. Happened first on November 2nd after we updated our server to v2023.10.0. Fixed it by re-downloading our org license file from bitwarden.com (which wasn't suspended) and re-uploading it to our installation. November 3rd, the issue reoccurred after updating our server to v2023.10.1. Fixed it again as before. Both times, our organization was suspended although the expiration date of our Enterprise subscription was and still is way in the future. The suspension led to ~200 employees not being able to access any collection, TOTP etc.

I guess you are using Docker Compose right?

**Comment by GuillaumeHullin** [comment]
> That is what Bitwarden Support answered this morning ( I reuploaded the newly downloaded license file twice before I opened this issue here). For now it works but it worked before as well for let's say half a day / a day as mentioned by @kolja1507
> 
> ```
> 
> Hi
> ​
> I apologize for the inconvenience. Please follow the below steps which should resolve this issue:
> 
> If you haven’t already, please update your self-hosted server to the latest version following these steps: https://bitwarden.com/help/updating-on-premise/
> 
> Have an Owner log into the Cloud Org at https://vault.bitwarden.com  or https://vault.bitwarden.eu  and download a new license file.
> 
> Have an Owner log into the self-hosted organization (which may not be the same user as the cloud one) and apply the new license file.
> 
> Please note that the server must be updated to the latest version for the new licence to be applied.  This is not normal, and is due to a bug.
> 
> #2 - Disable billing sync
> 
> Remove the following line from ./bwdata/env/global.override.env:
> globalSettings__enableCloudCommunication=true
> 
> Run bitwarden restart command from Bitwarden shell script.
> 
> Re-download the licence from https://vault.bitwarden.com or https://vault.bitwarden.eu 
> 
> Re-apply this to the server manually once again
> 
> 
> Full documentation on this feature can be found here:
> 
> https://bitwarden.com/help/families-for-enterprise-self-hosted/#step-1-enable-cloud-communication 
> ​
> I can confirm that there was a bug in the 2023.10 release that caused this issue and that in most instances re-applying the licence file resolved this.
> 
> We have since released version 2023.10.1, which solves the issue.
> 
> The root cause was a change in the licence file format for the 2023.10 release.  I apologise once again for the inconvenience and can confirm that the team will take every effort to ensure that a similar error never reoccurs.
> ```
> 
> They speak about a bug ;) BTW never had billing sync enabled

Interesting. Did you have `globalSettings__enableCloudCommunication=true` ? I don't.

**Comment by kolja1507** [comment]
> BTW never had billing sync enabled

We neither.

**Comment by kolja1507** [comment]
> I guess you are using Docker Compose right?

@GuillaumeHullin Right.

**Comment by kolja1507** [comment]
> Did you have globalSettings__enableCloudCommunication=true ? I don't.

We neither.

**Comment by GuillaumeHullin** [comment]
Trying to find a common point between us... 

In the link: https://bitwarden.com/help/families-for-enterprise-self-hosted/#step-1-enable-cloud-communication
There is the following mentioned:
> Enabling automatic sync requires communication with Bitwarden's cloud systems. If your environment uses a firewall to block outbound traffic, you will need to allow https://api.bitwarden.com and https://identity.bitwarden.com.

I do use pfBlocker to filter traffic (IP filtering and DNS blacklist)... both of the above domain work for me but could it be that Bitwarden would make an other external check for license?

Do you guys use network filtering?

**Comment by florie1706** [comment]
As I use a paid Family License I do not have CloudSync enabled, I think I do not need / cannot use it anyways, see here: [](https://bitwarden.com/help/licensing-on-premise/)

> Update organization license
Organizations may need to update the license file on their self-hosted server, for example to add user seats or when your license expires. When your license expires and your organization renews, you have 60 days to apply the updated license file to your self-hosted organization.

There are two methods for doing so, **however Families organizations may only update manually**:

**Comment by GuillaumeHullin** [comment]
@florie1706 same, I use Families organizations.

**Comment by shofutex** [comment]
Hello. This started happening to me when I upgraded to the latest version of Bitwarden unified last night. I updated the license file last night and this morning received the same error.

**Comment by shofutex** [comment]
> Hello. This started happening to me when I upgraded to the latest version of Bitwarden unified last night. I updated the license file last night and this morning received the same error.

Seems to happen 7:30 am and 7:30 pm now in the latest version.
