### ISSUE TITLE
1password dates imported as integers

### ISSUE THREAD

**Issue by jpaas** [bitwarden/server#362]
Any 1password date field is imported as an integer (seconds from epoch). If BW doesn't have a date field type, then these should at least come across as a string representation of the date.

**Comment by kspearrin** [comment]
What are the names of the date fields?

**Comment by jpaas** [comment]
Using a 1p passport record as an example... date of birth, issued on, expiry date

**Comment by jpaas** [comment]
Other cases:
* all the date fields on driver's license type records: expiry date, issue date, date of birth
* "member since" on rewards and membership type records goes from 11/1994 => 199411. Yet expiration date on credit cards works perfectly.

**Comment by hoborm** [comment]
I've created a random example export from 1Password with a Credit card in it: 
[data.txt](https://github.com/bitwarden/server/files/5397640/data.txt) I'm not quite sure the intention behind the serialization of these data but it seems like all the Cypher fields are String/EncryptedString (in this case: Bit.Core.Models.Api.CipherCardModel. I think changing these serialization processes would be the solution. I can take a look at it if you don't mind @kspearrin but it does not seem a quick-one to implement.
