### ISSUE TITLE
1password import treats router wireless network password as text

### ISSUE THREAD

**Issue by jpaas** [bitwarden/server#363]
If you import a router type item from 1password, the base station password comes across as a password, but the wireless network password comes across as text type field instead of a hidden type.

**Comment by jpaas** [comment]
Another similar case is the number field on Social Security Number type records

**Comment by mahyar** [comment]
Also want to add that concealed fields are not imported as concealed fields in bitwarden, even though the 1pif format specifies that they are concealed.  For example one of my credit cards had a custom? concealed field that wasn't imported as such:

`{"k":"concealed","v":"1234","n":"pin","inputTraits":{"keyboard":"NumberPad"},"t":"PIN"}`

**Comment by kbipp** [comment]
I can take this if no one else is working on it.

**Comment by djsmith85** [comment]
As Bitwarden only supports one password field, all additional fields are created as custom fields. If they are marked as `concealed` they are also `hidden` in Bitwarden. 

As 1Password is moving away from `.1pif` in favour of `.1pux` - we've started work on an importer for the new format at bitwarden/jslib#594

Closing this now.
