### ISSUE TITLE
No Author in License

### ISSUE THREAD

**Issue by DavidFrings** [bitwarden/server#3630]
### Steps To Reproduce

1. Go to 'AGPL License File'
2. Scroll down to 'End of File'

### Expected Result

There is no author

### Actual Result

There is no author

### Build Version

Version 2023.12.1

### Environment

Cloud (bitwarden.com)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by SergeantConfused** [comment]
Hi @CoolerTyp99,

Thank you for this report.
1. Could you please specify the exact (AGPL License File) you're referring to? A link to it would be helpful.
2. Could you please clarify why there should be an author? A link to the specification/standard document or an example of a similar document would be helpful.

Thank you in advance,

**Comment by CoolerTyp99** [comment]
Thats the Permalink:
https://github.com/bitwarden/server/blob/08d380900b540f8d1a734c7abccaf80e59a91ced/LICENSE_AGPL.txt#L621C1-L621C1

I am currently writing my project with the AGPL License and saw that there is a `How to Apply These Terms to Your New Programs` at the end of the file. I wanted to see how others have made this and I searched online for big projects with the AGPL License and found bitwarden, but when I looked there there was nothing, only the Template with `<name of author>` & etc.

**Comment by Neonwarden** [comment]
Thank you for your feedback! We will review this information further.

**Comment by EquiSource** [comment]
By reading through this a bit further.  It looks like the line that OP is pointing to is just to be used as a reference of the line/s that should be put in source code files as the header.  Doing these lines in the header usually protects the file with the license.   If the header files in the source code are not updated - than you have a problem.
