### ISSUE TITLE
2FA error: Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: g.Id'.

### ISSUE THREAD

**Issue by averkiev** [bitwarden/server#3648]
### Steps To Reproduce

1. Open BW login page
2. Enter 2FA code
3. Error is shown

### Expected Result

Login into the application

### Actual Result

Error is shown after entering 2FA code: An error has occurred. An unexpected error has occurred.

logs\identity.log shows the following error.
An unhandled exception was thrown by the application.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: g.Id'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)

### Additional Context

Version 2023.12.0

### Githash Version

919d759f-dirty

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there,

Based on other reports this seems to be a new issue. I have passed this to our engineering team.

**Comment by brambaars** [comment]
As discussed with support via email, I experience the same. Logfiles were shared, in my case it's **MySQL**, but also _no such column: g.Id_ in identity.log.

**Comment by brambaars** [comment]
For the time being, reverting to the previous version (tag 2023.12.0-beta) resolved the issue.
(spin up the container with _bitwarden/self-host:2023.12.0-beta_ instead of _bitwarden/self-host:beta_)

**Comment by withinfocus** [comment]
@brambaars can you pull the latest from `main` and give this a try? We made a modification to the database migration.

**Comment by brambaars** [comment]
I spun up _bitwarden/self-host:beta_ again, and am back to 2024.1.0. The latest files were pulled from bitwarden/self-host.
(I'm not sure how else I would perform your exact request, pulling latest from main; I may be in over my head here...)

Now, logging in on the web vault, results in the "unknown error" immediately after entering my password, before entering the 2FA code. 

identity.log shows:
```
An unhandled exception was thrown by the application.
MySqlConnector.MySqlException (0x80004005): Unknown column 'g.Id' in 'field list'

```

@averkiev 's log mentions Sqlite though, while I'm running from MySql, as you can see in my log.

**Comment by averkiev** [comment]
@withinfocus , my container has been upgraded to the latest version of bitwarden/self-host:beta. Now I'm seeing the following error in the admin.log

`2024-01-13 06:56:26.693 +00:00 [INF] Migrating database.
2024-01-13 06:56:29.019 +00:00 [ERR] Failed executing DbCommand (2ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
INSERT INTO "ef_temp_Grant" ("Id", "ClientId", "ConsumedDate", "CreationDate", "Data", "Description", "ExpirationDate", "Key", "SessionId", "SubjectId", "Type")
SELECT "Id", IFNULL("ClientId", ''), "ConsumedDate", "CreationDate", IFNULL("Data", ''), "Description", "ExpirationDate", "Key", "SessionId", "SubjectId", IFNULL("Type", '')
FROM "Grant";`

**Comment by potrusil** [comment]
I also have the unified deployment with SQLite and went through the same loop (upgraded to 2024.1.0-beta and then back to 2023.12.0-beta). Today I tried the latest beta (which I assume is 2024.1.1) and everything works flawlessly. I can log in and edit entries, and there are no errors in the logs!

**Comment by averkiev** [comment]
Upgrading to 2024.1.1 has fixed the issue for me.

**Comment by brambaars** [comment]
Can't confirm, @potrusil. I'm now also on 2024.1.1, and this is a quote from my identity.log:
> 2024-01-21 09:43:32.875 +01:00 [FTL] Unhandled exception: Unknown column 'g.Id' in 'field list'
> MySqlConnector.MySqlException (0x80004005): Unknown column 'g.Id' in 'field list'

And I also see the timeout message in admin.log.

Next best thing (work-around) I'm tempted to do, would be to export the Vault, perform a clean install, re-set settings, and import Vault. I'm the only user of my instance.
