### ISSUE TITLE
Cannot register on HTTP site / HTTPS site not working

### ISSUE THREAD

**Issue by Lammiwinks** [bitwarden/server#3660]
### Steps To Reproduce

1. Deploy fresh using docker compose
2. Go to IP address https://ipaddress:port (I specified port 90 instead of 80)
3. Fill in the form
4. Click register

### Expected Result

User registration works

### Actual Result

Button won't click

### Screenshots or Videos

<img width="815" alt="Screenshot 2024-01-11 at 11 14 18 am" src="https://github.com/bitwarden/server/assets/101758754/a53bf307-3edb-468b-ac4a-d6188f0c48b8">

https://github.com/bitwarden/server/assets/101758754/8c325480-b324-4db2-b252-67dd868242ee

### Additional Context

So I've found that the error is related to the web-crypto-function.service.ts. Googling this shows that this service only supports HTTPS. So I try and browse to the same IP using the HTTPS port (I've set it to 442) and it won't load the page. 

So I think the https portal may also not be working? 

### Githash Version

can't load this

### Environment Details

self hosted on raspberry pi via docker image.

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Lammiwinks** [comment]
Update: enabled SSL and now can use HTTPS and the button works! getting a DB migration error now but troubleshooting that separately. I think the recommend settings.env should have this enabled as user registration is broken without it.

**Comment by sammbw** [comment]
Hello @Lammiwinks - thanks for getting in touch, and I'm glad to hear your environment is now working as expected. SSL is an optional setting - but the recommended default in **settings.env** is for SSL to be enabled - this provides flexibility for deployments where an SSL proxy may be used.
