### ISSUE TITLE
Log in with passkey does not support decrypting the vaults of multiple Bitwarden accounts via the prf extension using a single hardware security key

### ISSUE THREAD

**Issue by forrestwparker** [bitwarden/server#3682]
### Steps To Reproduce

Using a web browser and security key that support the prf extension:
1. Create a passkey for account 1 on the security key.
2. Continue the process to use that security key to decrypt account 1's vault at log in (via the prf extension).
3. Repeat steps 1 and 2 for account 2.
4. Attempt to log into account 1's vault via the passkey held by the security key.

### Expected Result

Account 1 is logged in and the vault is decrypted automatically during the authentication process.

### Actual Result

The user is prompted for account 1's master password in order to decrypt the vault.

### Build Version

2024.1.1

### Environment

Cloud (bitwarden.com)

### Environment Details

Client Specs

CPU: M1 Pro
Memory: 16 GB
OS: macOS Sonoma 14.2.1
Google Chrome 120.0.6099.216 (arm64)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by kpiris** [comment]
[I was told](https://community.bitwarden.com/t/login-with-passkey-use-for-vault-encryption/62085/63?u=kpiris) [that this is an issue with chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=1520646).

**Comment by coroiu** [comment]
Fixed in Chrome Version 123.0.6296.0 (Official Build) canary (arm64)
