### ISSUE TITLE
License: AGPL-3.0-only or AGPL-3.0-or-later

### ISSUE THREAD

**Issue by zacknewman** [bitwarden/server#3693]
### Steps To Reproduce

Read the license.

### Expected Result

Either AGPL-3.0-only or AGPL-3.0-or-later license.

### Actual Result

Use of the [deprecated AGPL-3.0 license](https://github.com/bitwarden/server/blob/main/LICENSE_AGPL.txt).

### Additional Context

[According to the Software Package Data Exchange (SPDX)](https://spdx.github.io/license-list-data/), AGPL-3.0 is deprecated. Instead one should use [AGPL-3.0-only](https://spdx.github.io/license-list-data/AGPL-3.0-only.html) or [AGPL-3.0-or-later](https://spdx.github.io/license-list-data/AGPL-3.0-or-later.html).

[Issue 23](https://github.com/bitwarden/server/issues/23) briefly explains why AGPL should be used, but I would like clarification on which license this project is using so that my project can follow suit: AGPL-3.0-only or AGPL-3.0-or-later?

### Build Version

All

### Environment

Self-Hosted

### Environment Details

All

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Greenderella** [comment]
Hi there,

Thank you for your report! I have flagged this to our engineering team.

Have a nice day.

**Comment by withinfocus** [comment]
Hello -- GitHub doesn't support the display of this distinction and [merely has AGPL-3.0](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#searching-github-by-license-type), so there's nothing we can do in the repository itself. That said, we are AGPL-3.0-only.
