### ISSUE TITLE
Bitwarden unified - repeat core dumps if updating beyond 2024.1.0

### ISSUE THREAD

**Issue by KeithB** [bitwarden/server#3707]
### Steps To Reproduce

Update docker-compose to move bitwarden unified image from 2024.1.0 to 2024.1.1 or 2024.1.2

### Expected Result

Bitwarden runs

### Actual Result

Few behaviours:
* Login fails on password entry with unexpected error pop up.
* Repeat logs indicating admin core dump - nothing more on docker log/syslog:
`2024-01-26 12:44:56,036 INFO exited: admin (terminated by SIGABRT (core dumped); not expected)`

Also see the following repeatedly in admin.log:
```
2024-01-26 13:15:01.699 +00:00 [INF] Migrating database.
2024-01-26 13:15:02.894 +00:00 [ERR] Failed executing DbCommand (4ms) [Parameters=[], CommandType='"Text"', CommandTimeout='30']
CALL POMELO_BEFORE_DROP_PRIMARY_KEY(NULL, 'Grant');
ALTER TABLE `Grant` DROP PRIMARY KEY;
```

The failed DB command in the admin log seems consistent between versions - continues to occur when rolling back to 2024.1.0.

### Githash Version

dca8d00f-dirty

### Environment Details

Hardware: AMD 4500U, 32GB memory
OS: Ubuntu server
Docker: 24.0.2 build cb74dfc
Docker compose: v2.18.1

### Database Image

MariaDB 10.5 - Linuxserver image

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by holow29** [comment]
https://github.com/bitwarden/server/issues/3651
Seems like devs are done trying to implement a fix in migrations, so you might be better off to just run the SQL in that issue.

**Comment by KeithB** [comment]
Missed that one some how :(.  Slightly confusing but sorted now with the manual SQL and starting up the 2024.1.2 container. Closing this ticket.
