### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by cjs182** [bitwarden/server#374]
Hello,
I did an update yesterday and now I can not reach my vault because I am running into a timeout when I try to load it.

`
Open source password management solutions
Copyright 2015-2018, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

Docker version 17.05.0-ce, build 9f07f0e-synology
docker-compose version 1.14.0, build c7bdf9e

Removing network docker_default
WARNING: Network docker_default not found.
Pulling web (bitwarden/web:2.3.0)...
2.3.0: Pulling from bitwarden/web
Digest: sha256:3533224e3e8951aa2134d7de27b0db40d6aad4e64616379623671436b263535d
Status: Image is up to date for bitwarden/web:2.3.0
Pulling attachments (bitwarden/attachments:1.24.0)...
1.24.0: Pulling from bitwarden/attachments
`

**Comment by kspearrin** [comment]
Please post relevant information such as server logs or `docker ps` output.

**Comment by cjs182** [comment]
Here is the log and the docker ps output.

[docker_ps.txt](https://github.com/bitwarden/core/files/2453831/docker_ps.txt)
[errorlog.txt](https://github.com/bitwarden/core/files/2453832/errorlog.txt)

**Comment by kspearrin** [comment]
Post the identity and api logs from bwdata/logs from when you get the error.

**Comment by cjs182** [comment]
There are no logs in these directories.

**Comment by djsmith85** [comment]
Hi @cjs182, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.

**Comment by cjs182** [comment]
Hi @djsmith85 well I forgot about the thread. After I created the log directory myself the it worked. 
In the initial installation the directors where not created.
