### ISSUE TITLE
Getting 502 error / nginx won't start as config file does not exists

### ISSUE THREAD

**Issue by jsiobj** [bitwarden/server#3820]
### Steps To Reproduce

Deploy a brand new instance.

### Expected Result

I am not sure nginx is required if I disabled SSL as I use another proxy providing SSL communications.

If not required, nginx should not even try to start.
If required, config file should be generated I guess.

### Actual Result

I can't login onto the server. I get a 502 error.

Digging a bit, I noticed nginx is not starting.

Container log shows :
`2024-02-18 18:39:18,994 WARN exited: nginx (exit status 1; not expected)
2024-02-18 18:39:22,203 INFO spawned: 'nginx' with pid 149
2024-02-18 18:39:22,214 WARN exited: nginx (exit status 1; not expected)
2024-02-18 18:39:23,150 INFO gave up: nginx entered FATAL state, too many start retries too quickly`

nginx logs shows :
`2024/02/18 18:39:22 [emerg] 149#149: open() "/etc/nginx/http.d/bitwarden.conf" failed (2: No such file or directory) in /etc/nginx/nginx.conf:37
`

File is not present withing the container

### Additional Context

I followed the steps in the documentation.

It used to work up until recently. Unfortunately, I can't say when it stopped to work. It seems one of the latest upgrade caused the issue.

I tried to deploy a brand new environment but I get the same error : that is 502 error and nginx not starting (I guess both are linked).

Also, in the unified deployment doc, BW_ENABLE_SSL should default to false, but the .env example file on github seems to indicated it is true.  Doc states : "SSL is required for Bitwarden to function properly. If you are not using SSL configured in the Bitwarden container you should front Bitwarden with a SSL proxy." As I understand it, I can use my own proxy to provided SSL. Am I correct ?

Is nginx required if I disable SSL ?

### Githash Version

can't access it

### Environment Details

Synology NAS with Portainer (not using built in manager)

### Database Image

postgres:16

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by mikensan** [comment]
Just in case others aren't reading the several other reports of the exact same thing (different thread titles) - the fix is to roll back to January's release: 2024.1.2-beta.

**Comment by kannasama** [comment]
Latest dev build appears to address it.

**Comment by holow29** [comment]
Unfortunately, the latest beta tag (shared with [2024.2.1-beta](https://hub.docker.com/layers/bitwarden/self-host/2024.2.1-beta/images/sha256-887d2f789485815af9620afbefe55368a65cea600a6ba8578e5a462d159b3f1f?context=explore)) still has this issue.

**Comment by GitTimeraider** [comment]
Switched to dev version to test, 0 issues there.
Hopefully it will soon be classified as stable enough and be ported over to the beta version :P

**Comment by holow29** [comment]
Latest `beta` tag now working.

**Comment by shofutex** [comment]
Latest beta tag works for me too.

**Comment by djsmith85** [comment]
Thanks everyone for your patience and the reports of this being fixed.

Closing this now.

**Comment by made4this** [comment]
Although others reported a cure, this is still broken for me on a Raspberry Pi 4. I can only run 2024.1.2-beta and nothing newer.
