### ISSUE TITLE
404 error trying to download updated bitwarden.sh

### ISSUE THREAD

**Issue by moucho** [bitwarden/server#3847]
### Steps To Reproduce

When I try to selfupdate/update using bitwarden.sh, the script starts but after showing first lines, it stays for some time and then ends without updating.

Seems that Cloudflare is showing an 404 error when trying to download the latest bitwarden.sh script from my server

### Expected Result

It should update/selfupdate the server

### Actual Result

Seems that Cloudflare is showing an 404 error when trying to download the latest bitwarden.sh script from my server

### Screenshots or Videos

All the output for bitwarden.sh, after showing all this waits for some time and ends without doing anyting else:

```
# ./bitwarden.sh update
 _     _ _                         _            
| |__ (_) |___      ____ _ _ __ __| | ___ _ __  
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \ 
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2024, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

bitwarden.sh version 2023.12.0
Docker version 20.10.12, build e91ed57
docker-compose version 1.24.1, build 4667896b
```

Seems that Cloudflare is showing an 404 trying to download the latest script:

```
curl -LI 'https://func.bitwarden.com/api/dl/?app=self-host&platform=linux'
HTTP/1.1 404 Not Found
Date: Wed, 28 Feb 2024 10:41:40 GMT
Connection: keep-alive
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, PUT, POST, DELETE, PATCH, OPTIONS
Access-Control-Allow-Headers: DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization
Access-Control-Max-Age: 1728000
CF-Cache-Status: DYNAMIC
Set-Cookie: __cf_bm=DQgzpPJG1U3fdxz7ykB2tjEWnVR7ZkOWT7HbiLUMADw-1709116900-1.0-Adoym8qmP7bvBYt7W7XvLTz9FlZhrgPD3IGj5rJQOY+Wr/JTJz7CpTjZV4FLVGdlrO3cdC87DxigTInO0VeYinQ=; path=/; expires=Wed, 28-Feb-24 11:11:40 GMT; domain=.bitwarden.com; HttpOnly; Secure; SameSite=None
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Content-Type-Options: nosniff
Set-Cookie: _cfuvid=rsVhy6vM1gEV5V5fBZ69FjCTcz2xe5pEOVx2EtGoKNw-1709116900827-0.0-604800000; path=/; domain=.bitwarden.com; HttpOnly; Secure; SameSite=None
Server: cloudflare
CF-RAY: 85c80e757b046f88-CDG
```

### Build Version

2023.12.0

### Environment

Self-Hosted

### Environment Details

CentOS 7 with docker

### Issue Tracking Info

- [x] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by NovaSilentium** [comment]
Hi there, 
 
 
 I attempted to reproduce your issue and was unable to do so. 

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
