### ISSUE TITLE
Already org-premium users can now still upgrade to premium

### ISSUE THREAD

**Issue by Mart124** [bitwarden/server#387]
Hi,

Since version 1.25.0, new organization users, which get premium access, are still given the choice to upgrade to premium :

![screen shot 2018-10-29 at 11 14 05](https://user-images.githubusercontent.com/37041094/47647486-724c6300-db77-11e8-82a2-f0943d239278.png)

This situation is quite confusing for both the admin, as it seems strange, and even more for these users.
Could it then be possible to avoid displaying the "Go Premium" sub-menu for users which already have a premium access ?

Thank you !

**Comment by kspearrin** [comment]
This is expected at the moment, since it would be possible that a user would want to upgrade to premium independently of being in an organization that offers premium (maybe they are only temporarily in this organization?). I think the proper fix would be to just offer the server admin the ability to toggle this off/on via server configuration.

**Comment by Mart124** [comment]
> I think the proper fix would be to just offer the server admin the ability to toggle this off/on via server configuration.

Yes, I agree, would be a perfect solution 👍

**Comment by Mart124** [comment]
Hi @kspearrin, and happy new year :)
Do you perhaps have some news regarding this new toggle switch ?
Many thanks 👍

**Comment by Mart124** [comment]
@kspearrin, some news perhaps regarding this toggle switch ?
Thank you again 👍

**Comment by Mart124** [comment]
May I ask you @kspearrin if you had time to look at a fix for this please ?
Thank you very much 👍

**Comment by Mart124** [comment]
1 year old birthday, may I ask you some news regarding this tiny enhancement Kyle please ?
Thank you very much for your support !

**Comment by Mart124** [comment]
Of course, goal would also be to disable these "Go Premium" / "Premium Membership" menu entries from the other applications (Mobile, Desktop, Browser...).
Thank you again !

**Comment by Mart124** [comment]
Perhaps this could be part of the new organization policies, we could have an option there to disable / remove these "Go Premium" / "Premium Membership" menu entries.

**Comment by Mart124** [comment]
Bitwarden folks, any update on this tiny request please ?
Many thanks 👍

**Comment by pgumeniuk** [comment]
+1 org expects to see this option switchable via server configuration.
Any update?

**Comment by cscharf** [comment]
We have it on our radar and will be circling around to organization/enterprise policies here soon during Q4, 2020. No promises on this one but we'll consider it as we look to tackle myriad policy requests on behalf of org admins.

**Comment by Mart124** [comment]
Yes, keep this under radar, as seen with @cscharf above :)
Still waiting for a fix :)
Many thanks 👍

**Comment by Mart124** [comment]
Yes, keep this under radar, as seen with @cscharf and @kspearrin above :)
Still waiting for a fix :)
Many thanks 👍

**Comment by dwbit** [comment]
Thanks for flagging @Mart124, the team is tracking the request internally so I'll be closing this issue. Feel free to continue the discussion on the [Bitwarden Community Forums.](https://community.bitwarden.com/)
