### ISSUE TITLE
Bitwarden nginx docker keeps restarting

### ISSUE THREAD

**Issue by RealMabuse** [bitwarden/server#3880]
### Steps To Reproduce

Now for 3 days the nginx docker is making some trouble in my self hosted environment.

Multiple times a day the nginx-docker begins to restart itself again and again, not coming up.

The nginx error.log just throws this message:
```
...
2024/03/08 05:42:58 [emerg] 1#1: host not found in upstream "api" in /etc/nginx/conf.d/default.conf:86
2024/03/08 05:43:58 [emerg] 1#1: host not found in upstream "api" in /etc/nginx/conf.d/default.conf:86
2024/03/08 05:44:59 [emerg] 1#1: host not found in upstream "api" in /etc/nginx/conf.d/default.conf:86
2024/03/08 05:45:59 [emerg] 1#1: host not found in upstream "api" in /etc/nginx/conf.d/default.conf:86
2024/03/08 05:47:00 [emerg] 1#1: host not found in upstream "api" in /etc/nginx/conf.d/default.conf:86
2024/03/08 05:48:00 [emerg] 1#1: host not found in upstream "api" in /etc/nginx/conf.d/default.conf:86
2024/03/08 05:49:00 [emerg] 1#1: host not found in upstream "api" in /etc/nginx/conf.d/default.conf:86
2024/03/08 05:50:01 [emerg] 1#1: host not found in upstream "api" in /etc/nginx/conf.d/default.conf:86
2024/03/08 05:51:02 [emerg] 1#1: host not found in upstream "api" in /etc/nginx/conf.d/default.conf:86
2024/03/08 05:52:02 [emerg] 1#1: host not found in upstream "api" in /etc/nginx/conf.d/default.conf:86
2024/03/08 05:53:02 [emerg] 1#1: host not found in upstream "api" in /etc/nginx/conf.d/default.conf:86
2024/03/08 05:54:03 [emerg] 1#1: host not found in upstream "api" in /etc/nginx/conf.d/default.conf:86
2024/03/08 05:55:03 [emerg] 1#1: host not found in upstream "api" in /etc/nginx/conf.d/default.conf:86
2024/03/08 05:56:11 [emerg] 1#1: host not found in upstream "web" in /etc/nginx/conf.d/default.conf:43
2024/03/08 05:56:13 [emerg] 1#1: host not found in upstream "web" in /etc/nginx/conf.d/default.conf:43
2024/03/08 05:56:15 [emerg] 1#1: host not found in upstream "web" in /etc/nginx/conf.d/default.conf:43
2024/03/08 05:56:17 [emerg] 1#1: host not found in upstream "web" in /etc/nginx/conf.d/default.conf:43
2024/03/08 05:56:20 [emerg] 1#1: host not found in upstream "web" in /etc/nginx/conf.d/default.conf:43
2024/03/08 05:56:23 [emerg] 1#1: host not found in upstream "web" in /etc/nginx/conf.d/default.conf:43
2024/03/08 05:56:27 [emerg] 1#1: host not found in upstream "web" in /etc/nginx/conf.d/default.conf:43
...
```

./bitwarden.sh restart will not solve the trouble.  
I have to bitwarden.sh stop and bitwarden.sh start to bring the server up again.
Then it will work for some time and the trouble starts again.

I have looked over any logs in the logs directory but cannot find any hint when and why there is some trouble.

### Expected Result

The server should keep running stable.

### Actual Result

The server quits multiple times a day.

### Build Version

2024.2.2

### Environment

Self-Hosted

### Environment Details

Ubuntu 22.04.4 LTS
bitwarden.sh version 2024.2.2
Docker version 25.0.3, build 4debf41
Docker Compose version v2.24.6

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so. I think your error could have its origin in a misconfiguration and a potential certificate mismatch(https://bitwarden.com/help/certificates/#use-an-existing-ssl-certificate)

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).
You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.

Thanks!
