### ISSUE TITLE
move from org to org via admin vault.

### ISSUE THREAD

**Issue by quadcom** [bitwarden/server#3939]
### Steps To Reproduce

More clarity of the situation is outlined in the context field.

In the web vault/organizations section, it is not possible to move an item from one organization to another. An error message states that "at least one collection needs to be selected," but the UI does not show any collections in the target org to choose from.

### Expected Result

a move or copy from one organization to another should complete.

### Actual Result

I am unable to move an item from one org to another. The only workaround currently is to clone it to the personal vault and then move that clone to the desired org. This is time-consuming and a security concern.

### Additional Context

I am using the Vaultwarden project as the backend server. That project is locked to the functionality of the Bitwarden server code.

I ran into this problem a couple of days ago and found this thread on the Vaultwarden git

https://github.com/dani-garcia/vaultwarden/discussions/3016#discussioncomment-8936336

The author of that project would like to fix that issue, but it is within the source of this primary project.

### Build Version

1.30.5 

### Environment

Self-Hosted

### Environment Details

Unraid/Docker

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Neonwarden** [comment]
Hi there,

It is important to note that Vaultwarden is not associated with Bitwarden. Vaultwarden is a re-writing of the Bitwarden server code in Rust, that is not contributed to or supported by the Bitwarden team or organization. 

I recommend reaching out to Vaultwarden's support for further assistance. 

This issue will be closed.
