### ISSUE TITLE
docker-compose.yml: `version` is obsolete

### ISSUE THREAD

**Issue by itkfm** [bitwarden/server#3952]
### Steps To Reproduce

1. Go to your Bitwarden installation
2. Run `./bitwarden.sh update`
3. Read the log output

### Expected Result

No warnings.

### Actual Result

```
Building docker environment files.
Building docker environment override files.
Building nginx config.
Building FIDO U2F app id.
Building docker-compose.yml.

WARN[0000] /opt/bitwarden/bwdata/docker/docker-compose.yml: `version` is obsolete 
WARN[0000] /opt/bitwarden/bwdata/docker/docker-compose.yml: `version` is obsolete 
```

### Build Version

2024.3.0 (setup) resp. 2024.2.3 (most other components)

### Environment

Self-Hosted

### Environment Details

- Operating system: Debian 12
- Environment: Docker
- Hardware: QEMU/KVM Virtual Machine

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hello there, 

Our team is aware of this and is working to resole this. Overall this does not impact functionality.
