### ISSUE TITLE
No Mails since 2024.3.0-beta

### ISSUE THREAD

**Issue by florie1706** [bitwarden/server#3968]
### Steps To Reproduce

1. Go to Admin Page or log in as user with mail as 2FA
2. Request Mail
3. No Mail will arrive

### Expected Result

Mail should be sent

### Actual Result

No Mail

### Additional Context

Reverted back to 2024.2.2-beta where it just runs as expected.

### Githash Version

e7658192-dirty

### Environment Details

- Ubuntu Server 22.04 LTS
- Docker 24.0.7
- Intel Xeon
- 48 GB RAM

### Database Image

mariadb:latest

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by daniellbw** [comment]
Hi there,

I am unable to reproduce this issue, it has been escalated for further investigation. If you have more information that can help us, please add it below. 

Thanks!

**Comment by florie1706** [comment]
Is there any logfile for mails in the container? So I would check then ;)

**Comment by florie1706** [comment]
@daniellbw Any news on that, even the current dev image with Bitwarden 2024.4.0 does not work. Would provide logs if you could tell me where to find them.

**Comment by darkson95** [comment]
Hey there,
Unfortunately, I have the same issue. First I thought the smtp-config has changed, but after I checked, the mails are not sent. I had a look on the log files, but I cannot find any useful entry.

**Comment by florie1706** [comment]
Latest dev from today which points to 2024.4.1 works again without changing anything.
