### ISSUE TITLE
Self Hosting - Custom Ports - URL seems independent of custom ports/override (possibly should be changed?)

### ISSUE THREAD

**Issue by ventz** [bitwarden/server#406]
Very small issue - In the self hosting `bitwarden.sh`, if you customize the ports, at the end of the install it doesn't display them:

```
...

Bitwarden is up and running!
===================================================

visit https://domain.tld       <-- missing from here
to update, run `./bitwarden.sh updateself` and then `./bitwarden.sh update`
```

When not using https via tcp/443, the ```https://domain.tld``` should have the custom https port at the end. Same with the same message later for any updates.

**Comment by ventz** [comment]
Actually, it seems that it's related to the "url" in the config.yml, but the issue is that it doesn't tack-on the ports automatically if they are not the default. If you specify the port manually in the "url" param, it works as expected.

Another effect of this is around the `/admin` section. If you specify ```https://domain.tld:port/admin```, it will redirect you to ```https://domain.tld/admin/login?returnUrl=%2Fadmin```, and then you need to re-specify the port, and at that point it will work. I would think having the ports be independently checked/added would be ideal, but possibly even a simple comment in the config.yml above the ```url:```might be really helpful.

**Comment by kspearrin** [comment]
URL is independent of port configurations because many people will run on alternate ports, but reverse proxy to a URL without ports. In this case the URL in config.yml should not have ports added.

**Comment by ventz** [comment]
@kspearrin If that's the case, I think there's a bug then.

Just to summarize:

* If I change the standard http+https ports, rebuild, and re-deploy, it doesn't show the "text" to the correct ports, but it responds on the correct ports

* If I don't add the https port to the URL, things like `/admin` do not work correctly/do not redirect without manually specifying the port in the re-direct.

**Comment by ventz** [comment]
Another place where this rose as an issue -- when you add a new user to the self-hosted organization, the email they get when they log-in and hit the "confirm their email" (and get the 2nd email) - It came as the fqdn without the ports, even though the ports were added and the config was re-built.

**Comment by kspearrin** [comment]
I am confused as to your setup then. If you want ports included in those emails then you need to add them to the `url` property in the config.yml.

**Comment by darc1** [comment]
I'm facing the same issue with the` /admin` redirect. I used the custom port: `8443`
when trying to access `https://<mydomain>:8443/admin` I get the redirected to: `https://<mydomain>/admin/login?returnUrl=%2Fadmin`
if I go directly to `https://<mydomain>:8443/admin` it works as expected.

**Comment by Caligatio** [comment]
Chiming in here, I'm experiencing the same /admin redirect issue mentioned above with v1.33.1.

The correct URL (with port) is listed as `url` in `config.yml` and as `globalSettings__baseServiceUri__admin` in `env/global.override.env`.  I've tried start/stop/rebuild and it doesn't help.

**Comment by DennisSkov** [comment]
I experience the exact same thing as everyone else mentioned here. Every url in `env/global.override.env` has been updated to include the port.
