### ISSUE TITLE
Can't register account, when using Plesk

### ISSUE THREAD

**Issue by Chicken-DEV** [bitwarden/server#410]
### **About my server:** 

- 16GB Ram
- Intel Core i7-2600
- 2x HDD SATA 3,0 TB
- Plesk Onyx 17.8.11 Update No. 31
- OS: ‪Debian 9.6
- Unlimited Traffic

### **About my Bitwarden installation:**
- I had to change the docker compose version to 2 in the docker-compose.yml (was 3), after that no errors with docker.
-  I had to change all ports to automatic in Plesk, because nginx had some problems.
- I can't seem to access the website I configured in the installer, it just opens this Plesk default page.
- I can use the Plesk interface to access some kind of port on my main page with bitwarden running
- I also have tried bitwarden_rs, same problem there

### **The Bug I'm running into:**
If I understood everything right, I have to create my account using the create account button on my bitwarden page. I can access the page, fill out all the boxes, but when I click send, there happens this weird bug:

**Using Chrome:** Nothing happens, still on that register site, all boxes still filled out, in the console I get this error in the console: 
`ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'importKey' of null
TypeError: Cannot read property 'importKey' of null
    at n.<anonymous> (webCryptoFunction.service.ts:49)
    at search.service.ts:14
    at Object.next (search.service.ts:14)
    at search.service.ts:14
    at new t (zone.js:891)
    at t (search.service.ts:14)
    at n.pbkdf2 (webCryptoFunction.service.ts:29)
    at n.<anonymous> (crypto.service.ts:301)
    at container.service.ts:3
    at Object.next (container.service.ts:3)
    at n.<anonymous> (webCryptoFunction.service.ts:49)
    at search.service.ts:14
    at Object.next (search.service.ts:14)
    at search.service.ts:14
    at new t (zone.js:891)
    at t (search.service.ts:14)
    at n.pbkdf2 (webCryptoFunction.service.ts:29)
    at n.<anonymous> (crypto.service.ts:301)
    at container.service.ts:3
    at Object.next (container.service.ts:3)
    at P (zone.js:814)
    at zone.js:724
    at i (register.component.html:59)
    at t.invoke (zone.js:388)
    at Object.onInvoke (core.js:3824)
    at t.invoke (zone.js:387)
    at e.run (zone.js:138)
    at zone.js:872
    at t.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:3815)`

**Using Brave:** I have the same behavior, like Chrome and this error in the console:
`Error: Uncaught (in promise): TypeError: Cannot read property 'importKey' of null
TypeError: Cannot read property 'importKey' of null
    at n.<anonymous> (webCryptoFunction.service.ts:49)
    at search.service.ts:14
    at Object.next (search.service.ts:14)
    at search.service.ts:14
    at new t (zone.js:891)
    at t (search.service.ts:14)
    at n.pbkdf2 (webCryptoFunction.service.ts:29)
    at n.<anonymous> (crypto.service.ts:301)
    at container.service.ts:3
    at Object.next (container.service.ts:3)
    at n.<anonymous> (webCryptoFunction.service.ts:49)
    at search.service.ts:14
    at Object.next (search.service.ts:14)
    at search.service.ts:14
    at new t (zone.js:891)
    at t (search.service.ts:14)
    at n.pbkdf2 (webCryptoFunction.service.ts:29)
    at n.<anonymous> (crypto.service.ts:301)
    at container.service.ts:3
    at Object.next (container.service.ts:3)
    at P (zone.js:814)
    at zone.js:724
    at i (register.component.html:59)
    at t.invoke (zone.js:388)
    at Object.onInvoke (core.js:3824)
    at t.invoke (zone.js:387)
    at e.run (zone.js:138)
    at zone.js:872
    at t.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:3815)`

**Using Firefox:** I get an error message saying: `An unexpected error occurred`, but no error in the console

**In the Docker console in Plesk I get this(bitwarden-web):** [https://gist.github.com/Chicken-DEV/c28d6c187a644d6aa33c7e22b77e3ba0](https://gist.github.com/Chicken-DEV/c28d6c187a644d6aa33c7e22b77e3ba0)

### If you need any other logs, tell me where I find them and I'll upload them.

Thanks in advance.

**Comment by kspearrin** [comment]
You should not use docker-compsoe version 2. If you change that there is no telling what other issues you are going to run into.

Unfortunately I do not know anything about Plesk and how things are configured with it.

The other `importKey` errors you are posting seem related to the fact that you are not using HTTPS, which is a requirement for the web vault.

**Comment by Chicken-DEV** [comment]
> You should not use docker-compsoe version 2. If you change that there is no telling what other issues you are going to run into.

OK, how do I update?



> The other `importKey` errors you are posting seem related to the fact that you are not using HTTPS, which is a requirement for the web vault.

Yeah, the Installer said something about that. I always get an error when I try to use the Lets Encrypt. That's why I didn't install it. I will try using Lets Encrypt again tomorrow, when I get an error I'm going to post it here, if not I'm going to close this thread.

Anyway, thanks for helping me out.

**Comment by Chicken-DEV** [comment]
> Yeah, the Installer said something about that. I always get an error when I try to use the Lets Encrypt. That's why I didn't install it. I will try using Lets Encrypt again tomorrow, when I get an error I'm going to post it here, if not I'm going to close this thread.

OK, It's a new day for me and after some rest I got the idea, that nginx is already using my ports 80 & 443 for Plesk. 
Here is the reason I think that this could be the problem (read the whole thing [Here](https://help.bitwarden.com/article/install-on-premise).)

`Bitwarden can generate and maintain renewal of a trusted SSL certificate for your domain for completely free provided by Let’s Encrypt and Certbot. Certificate renewal checks occur each time Bitwarden is restarted. Use of the automated Let’s Encrypt certificate requires ports 80 and 443 to be available. Alternatively, you can manage your own Let’s Encrypt certificate outside of the Bitwarden setup script and provide it using the “bring your own SSL certificate” method as described below. `

So I think I'll need to use the "bring your own SSL certificate" method as mentioned above.
At the moment I have an issue with my Plesk installation, so I'll have to do it tomorrow.

**Comment by Chicken-DEV** [comment]
> So I think I'll need to use the "bring your own SSL certificate" method as mentioned above.
> At the moment I have an issue with my Plesk installation, so I'll have to do it tomorrow.

OK, I fixed my Plesk issue. SSL is working now.

> I had to change the docker compose version to 2 in the docker-compose.yml (was 3), after that no errors with docker.

This error still occurs, I know this has nothing to do with the SSL thing, but it still annoys me and as you mentioned before:
> You should not use docker-compsoe version 2. If you change that there is no telling what other issues you are going to run into.

I should not just change the version in the config to 2. So I need to downgrade my docker Version, from 3 to 2, if I understand this right. But how do I do that?

**Comment by kspearrin** [comment]
> I should not just change the version in the config to 2. So I need to downgrade my docker Version, from 3 to 2, if I understand this right. But how do I do that?

No, you need to upgrade your docker-compose version to 3 or greater.

**Comment by djsmith85** [comment]
Hi @Chicken-DEV, it looks like there is a viable workaround or resolution for the issue you're experiencing. Please let us know if this resolves the originally posted issue.
