### ISSUE TITLE
Self hosting - docker container - IOS app can't login using https

### ISSUE THREAD

**Issue by ghost** [bitwarden/server#417]
IOS does not support self signed certificate. According to this file: https://github.com/bitwarden/core/blob/master/util/Setup/CertBuilder.cs
When user user choose using Bitwarden only in local network self signed certificate is created but after this can't access to server from IOS Bitwarden up "There is a problem connecting to the server"

**Comment by kspearrin** [comment]
You need to install the certificate to the trusted store on the iOS device.

**Comment by Haxy89** [comment]
I did. I have certificate.crt and private.key
I send certificate.crt via mail to my iphone i install it
During setup as CN I enter my server IP

**Comment by Hinton** [comment]
I believe this issue belongs to mobile, and https://github.com/bitwarden/mobile/issues/465 seems to capture the essence.

I did some quick research, and you apparently iOS does not trust self-signed certs, but it should be possible to setup a CA to sign it instead, and add that CA to iOS as a trusted cert which "should work".
