### ISSUE TITLE
Secure note length incorrectly detected

### ISSUE THREAD

**Issue by rumenavramov** [bitwarden/server#420]
It seems that when a new secure is added, the length is incorrectly detected and if you are too close to the limit, Bitwarden displays an error that your note is too long even if it is not. Consider this example:

- The file [lorem ipsum.txt](https://github.com/bitwarden/core/files/2733348/lorem.ipsum.txt) contains some generated text that is less than 10K characters.
- Notepad++ reports that the file has:
  - File length (in byte): 9,714
  - Characters (without blanks): 9,666
  - Current document length: 9,714
- Microsoft Word reports that the file has:
  - Characters (no spaces) 8,236
  - Characters (with spaces) 9,666

Clearly there is some difference in how NPP and MS Word calculate the length of the file contents, however, neither considers it to be more than 9714 characters. If I paste that same contents in a Bitwarden Secure Note, BW will display the error message "An error has occurred
The field Notes exceeds the maximum encrypted value length of 10000 characters."

I initially experienced this in the Firefox extension, however, the same thing happens in the web vault as well.

**Comment by kspearrin** [comment]
Hi,
This is occurring because the limit is based on the encrypted value length that is sent to the server, not the plaintext value length that you see in word/notepad.

I would guess that somewhere around 6000-7000 plaintext characters would result in an encrypted value length of 10k or more.

**Comment by rumenavramov** [comment]
Ok, I see what you mean.
Since that error message is meant for end-users who are not always technically inclined, can you consider changing the message to be based on the plain-text data that the field can hold rather than ciphertext? It is more natural and user-friendly even for those that completely understand what is happening under the hood.

**Comment by 92VV3M42d3v8** [comment]
Don't you think it should be closed.
