### ISSUE TITLE
oneprovider.com, op-net.com should be equivalent domains

### ISSUE THREAD

**Issue by theel0ja** [bitwarden/server#421]
oneprovider.com is used to buy stuff.
op-net.com is used for the panel.

**Comment by gbursson** [comment]
I am not sure what you mean by "equivalent". Are you referring to:
_Domain Rules_ -> _Custom Equivalent Domains_?

**Comment by theel0ja** [comment]
@gbursson this: https://github.com/bitwarden/server/blob/master/src/Core/Utilities/StaticStore.cs

**Comment by gbursson** [comment]
@theel0ja can you open a pull request?

**Comment by Neustradamus** [comment]
Any news?
