### ISSUE TITLE
Cannot accept organization Invite

### ISSUE THREAD

**Issue by shackrock** [bitwarden/server#424]
My wife and I are trying to create an organization so we can share some of our logins.  Free account tiers for each of us at this time.

She has created an account, and created an organization on her account.  She invites me via my email (existing Bitwarden account).  I have one organization already that I share with a friend, too.  

I get the email, click join.  It asks me to login.  After login, this error shows on the site: https://imgur.com/VSFVnD0

I can resend as many times as I want but the error is always the same.  She has tried changing my role to owner, admin, and it doesn't affect this error.  We did have success when she changed my role to "user" and resent the invite.

Seems like a bug to me.

Thanks.

**Comment by kspearrin** [comment]
Are the the owner of another free organization already? There is a restriction there to where you can only be the owner of one free organization account. Otherwise you would have to be a regular user.

**Comment by shackrock** [comment]
While I am the owner of a free org already, my wife only had this one created.  

So you think because I was already an owner of one, that is why it wouldn't share properly?  If nothing else, this still warrants a better error message being displayed in my eyes - so it's clear and not ambiguous as to why it failed.

**Comment by gelbbauch** [comment]
Can confirm the problem. No prior Organization experience or usage. Created org, invited another user as Admin privileges, fails without reason. Re-invites results in same output. 

I can confirm the fix as well. Deleted user, re-invited new user with "User" permissions but able to modify all objects, and that worked.

**Comment by lnmunhoz** [comment]
I had the same issue.  @shackrock 

The fix was, I asked my friend to invited my just as a regular user, and then after accepting the invitation he changed my role to Admin.

**Comment by NicolasDionB** [comment]
Thanks @lnmunhoz for your solution but is there any fix coming for this issue?

**Comment by kingcoconut** [comment]
Just ran into this issue. If you add someone as Admin it fails to work

**Comment by addisonbeck** [comment]
This is on the radar, but I'm having trouble locally recreating the issue. Can anybody here provide the email clients (gmail, etc.) being used? Does using a different email address with a different email client work as expected?

**Comment by NicolasDionB** [comment]
Me and my girlfriend both have Gmail accounts.

**Comment by micahstrube** [comment]
I’m experiencing this issue as well, both Gmail accounts.

**Comment by yookoala** [comment]
I've just experiencing this issue. I'm using Gmail as well.

**Comment by jlizakowski** [comment]
Same here.  Email client is webmail, but not gmail.

**Comment by apurvis** [comment]
+1
