### ISSUE TITLE
Custom field priorty

### ISSUE THREAD

**Issue by neilmcd** [bitwarden/server#426]
I've been having an issue using Bitwarden with my bank login form (Santander). They require a few characters from my password rather than the whole thing and I've saved each individual character in Bitwarden using custom fields. 

The form uses the following **ID** attributes for the password input fields: id1, id2, id3, id6, id5, id6

However, the 3 required character fields always have **name** attributes id1, id2 and id3. 

This means that although they can be asking for characters 2, 4, and 6, the input field **names** for the 3 chars are always id1, id2 and id3, but the **ID**s are id2, id4 and id6.

The fill seems to be using the priority Name > ID > Label rather than ID > Name > Label as specified here - https://help.bitwarden.com/article/custom-fields, so the wrong characters are entered

I've made a quick demo page to show the problem [here](http://licenseer.com/test/bwtest.html) 

If you save custom fields pw1 - pw6 and then fill in the page, you'll see that it's correct on the top row where the IDs match the name, but incorrect on the bottom row where the IDs and names do not match e.g. [this](https://imgur.com/a/dCCE0WJ)

Is it possible to get it to obey the ID > Name priority, or even specify the attribute to match in the custom field setup? e.g. id=pw1

**Comment by kspearrin** [comment]
The priority is HTML Id > HTML Name, however, the custom field names are evaluated in the order of their appearance in the custom fields listing, which is causing the unexpected behavior.

I've added a new feature in the next version which will allow you to use other prefixes for targeting certain HTML attributes.

For example, you can now do `id=pw1`, `name=pw2`, `label=Some Label`, or `placeholder=password`.
