### ISSUE TITLE
Bitwarden Self-hosted without a domain

### ISSUE THREAD

**Issue by LegendaryB** [bitwarden/server#427]
Hello Guys,

I'm using zerotier. If you don't know it it is a virtual network layer which I'm using instead of forwarding ports and using a vpn to access my home services.
I have my server which should host bitwarden over docker in a virtual network. Also all my mobile devices are part of this network.

And becaus I only have a ip and no domain I can't get the ssl stuff to work. How could I use bitwarden without loosing the mobile apps and so on?

Hope somebody can dig me into the right direction.

Greetings and keep this awesome project running!

Kind Regards,
Daniel

**Comment by kspearrin** [comment]
Is it possible to issue a SSL cert to an IP? I don't know...

**Comment by dbelz** [comment]
Seems to work with the self signed certificate. My firefox is accepting it. Will try to go with that.

**Comment by dbelz** [comment]
okay not with the apps..

**Comment by techdev5521** [comment]
@dbelz, you might try adding the self-signed certificate to the certificate store on your mobile device.

**Comment by dbelz** [comment]
Thanks, will try that 👍

**Comment by Ruffythemonkey** [comment]
You can use a DynDns and Let's Encrypt !

**Comment by dbelz** [comment]
Its working with the self signed certificate. Thanks, can be closed! 👍

**Comment by dustindauncey** [comment]
Self-signed would be the only option when no domain is available, and seems to be validated above. :-)
