### ISSUE TITLE
Attachments broken

### ISSUE THREAD

**Issue by lehuizi** [bitwarden/server#428]
Hi!

I have updated and moved my bitwarden instance to another hypervisor. After logging in i have seen many defect attachments. There is a button who says "Restore", but this isn't working because of a permission error.

**Comment by lehuizi** [comment]
Currently i'm getting "Failed to fetch".
Before it was "Not allowed by ContentSecurityPolicy"

**Comment by lehuizi** [comment]
For me it was veeery late yesterday.
I will try to write a better report of my problem.

I bought a new server and wanted to move my bitwarden instance over. So i copied the whole virtual machine and restored it on the new vhost. After this, i have changed the IP address of the machine, set up a reverse proxy and wanted to login. All was working fine but some attachments had an orange call sign right to the name. 

I tried to restore mssql backups (what a mess 😆) and my own backups, nothing was working.

I have just added some screenshots to take a look about what I mean.

*Orange call sign*
![bildschirmfoto 2019-01-20 um 11 58 08](https://user-images.githubusercontent.com/16189604/51438322-0af00c00-1cab-11e9-9c7d-c91cece0d479.png)

*Attachments*
![bildschirmfoto 2019-01-20 um 11 58 24](https://user-images.githubusercontent.com/16189604/51438323-0af00c00-1cab-11e9-9c5b-e7bb7079f6bf.png)

*Error message when I try to repair an attachment:*
![bildschirmfoto 2019-01-20 um 11 58 27](https://user-images.githubusercontent.com/16189604/51438324-0b88a280-1cab-11e9-95f3-eb89d7df112f.png)

I also can't download attachments without callsign.
To check if it is working in my VM i have booted up this one, but it's also not working there so I think it's maybe a update problem.

**Comment by kspearrin** [comment]
Looks like you have a problem with your CSP. Does your proxy send the Content Security Policy header?

**Comment by lehuizi** [comment]
I have now reconfigured my proxy with the following config:

```
add_header Strict-Transport-Security "max-age=15768000; includeSubdomains; preload" always;

location / {
  proxy_intercept_errors off;
  proxy_http_version 1.1;
  proxy_set_header        Host            $http_host;
  proxy_set_header        X-Real-IP            $remote_addr;
  proxy_set_header        X-Forwarded-For            $proxy_add_x_forwarded_for;
  proxy_set_header        X-Forwarded-Proto            $scheme;
  proxy_pass http://1.2.3.4:80;
}
```

Now i am getting the following message:
![bildschirmfoto 2019-01-20 um 20 20 19](https://user-images.githubusercontent.com/16189604/51443933-fb93b180-1cf0-11e9-84a9-cbaa8e31875a.png)

**Comment by lehuizi** [comment]
Does nobody have an idea?

**Comment by Hinton** [comment]
This sounds like a configuration issue outside of the Bitwarden server.

If you are still experiencing the issue please please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
