### ISSUE TITLE
Get rid of the installer

### ISSUE THREAD

**Issue by BoxedBrain** [bitwarden/server#429]
Installing Bitwarden as advanced user is such a pain.
Why you don't stick to basic things like Docker Volumes, Port Mapping (-p 4443:443 -p 8080:80), and other stuff?
I have my own reverse proxy, let's encrypt container, etc.

Imagine running Bitwarden in Docker Swarm..
Please don´t get me wrong! Installer Scripts are ok, but it should be documented and possible to do it without picking the script apart.

**Comment by kspearrin** [comment]
Could you explain what you are trying to do, specifically, and maybe I can help? Most things should be editable from the ./bwdata/config.yml file.

**Comment by BoxedBrain** [comment]
Thanks for your fast reply.

- Using Docker Volumes (local bindings in swarm won´t work if I need to move to another host)
- Set the Docker Network
- Set the Network Port(s)
- Use my own ENV variables for my revproxy

**Comment by kspearrin** [comment]
All of this should be doable. Have you looked at the options available in ./bwdata/config.yml? You could go as far as disabling docker-compose.yml generation and setup everything you want manually.

**Comment by BoxedBrain** [comment]
I just found #307
Could not get more in detail than @blackwind

**Comment by kspearrin** [comment]
OK, we'll close this issue as a duplicate. in favor of that one.
