### ISSUE TITLE
On premise Two Factor Authentication

### ISSUE THREAD

**Issue by ictinc** [bitwarden/server#430]
After having lots of issues receiving email from my on premise setup I was finally able to verify my account.
I'm now trying to enable Two Factor Authentication without success.
I've scanned the QR code with the Authy android app. When I try to verify the code in Bitwarden I'm prompted with an error "Invalid Token".
Is this a known issue? Or did I forget to set some option?

**Comment by kspearrin** [comment]
Maybe your device's system time is not correct and is generating invalid codes?

**Comment by ictinc** [comment]
I feel stupid for not thinking of this myself. :) Thank you, this solved the issue,
