### ISSUE TITLE
Sending mail with implicit TLS is not supported

### ISSUE THREAD

**Issue by alelapeyre** [bitwarden/server#431]
Hi,

I had an exception about sending an email on port 465 (implicit TLS). Looking a bit, it looks like it comes from a bug in `SmtpClient`.
https://stackoverflow.com/questions/8878309/c-sharp-send-email-using-implicit-ssl
https://blogs.msdn.microsoft.com/webdav_101/2008/06/02/system-net-mail-with-ssl-to-authenticate-against-port-465/

[In the documentation](https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient?view=netcore-2.2), `SmtpClient` is marked as obsolete in benefit to other libraries such as MailKit.

My problem has been solved by opening port 587 but what do you think about using MailKit as a replacement for sending mail?

The [RFC 8314](https://tools.ietf.org/html/rfc8314) recommends the use of implicit TLS.

**Comment by kspearrin** [comment]
I honestly had no idea `SmtpClient` was deprecated. I'll look into replacing it. Thanks.

**Comment by kspearrin** [comment]
Should be resolved next version with https://github.com/bitwarden/server/commit/17cc1d6543f7d57b46dd0b294bf5e858d14a92b7
