### ISSUE TITLE
Can't find config.yml

### ISSUE THREAD

**Issue by Svarto** [bitwarden/server#432]
Hi,

After install using docker and dockercompose on Linux host, I have the ~/bwdata folder, but inside it there is no config.yml?

Nor is there a .bwdata folder, neither in the folder where bitwarden.sh script is nor inside the /bwdata folder...

**Comment by kspearrin** [comment]
Is there anything inside `./bwdata`?

**Comment by Svarto** [comment]
Sorry, figured it out. Somehow my install was stuck on an old version. I uninstalled and pulled everything fresh and jumped like 9 versions. The config is there now! Thanks for the help!
