### ISSUE TITLE
image operating system "linux" cannot be used on this platform

### ISSUE THREAD

**Issue by hubgitbb** [bitwarden/server#433]
Hi
i try to install bitwarden on docker / windows server 2019 like here https://help.bitwarden.com/article/install-on-premise/
and i get the followig error:

Docker version 18.09.1, build 20b67756d0
docker-compose version 1.23.2, build 1110ad01

(!) Enter the domain name for your Bitwarden instance (ex. bitwarden.company.com): mydomain.com

(!) Do you want to use Let's Encrypt to generate a free SSL certificate? (y/n): y

(!) Enter your email address (Let's Encrypt will send you certificate expiration reminders): my@email.com

Using default tag: latest
latest: Pulling from certbot/certbot
image operating system "linux" cannot be used on this platform
Unable to find image 'certbot/certbot:latest' locally
latest: Pulling from certbot/certbot
C:\Program Files\Docker\docker.exe: image operating system "linux" cannot be used on this platform.
See 'C:\Program Files\Docker\docker.exe run --help'.
1.29.0: Pulling from bitwarden/setup
image operating system "linux" cannot be used on this platform
Unable to find image 'bitwarden/setup:1.29.0' locally
1.29.0: Pulling from bitwarden/setup
C:\Program Files\Docker\docker.exe: image operating system "linux" cannot be used on this platform.
See 'C:\Program Files\Docker\docker.exe run --help'.

whats wrong with the script?

regards

**Comment by kspearrin** [comment]
As far as I know, Docker Linux container do not work on Windows Server since it lacks HyperV. Only Windows 10 would work.

**Comment by hubgitbb** [comment]
ok thx

**Comment by techdev5521** [comment]
@hubgitbb, Did you try it on Windows 10? Did it work?

**Comment by hubgitbb** [comment]
i setup a Ubuntu server
