### ISSUE TITLE
start bitwarden container on system startup

### ISSUE THREAD

**Issue by hubgitbb** [bitwarden/server#435]
i want to start bitwarden when my ubuntu 16.04 comes up 
i created the file /etc/init/bitwarden.sh with content

start on startup
task
exec /home/username/bitwarden.sh start 

but it doesent work.
is this with bitwarden not possible ?

**Comment by techdev5521** [comment]
On my own system, I use the Docker deployment for Bitwarden and start it on reboot with cron. To do this, login as the user you intend to run Bitwarden and run:

`crontab -e`

Now add the cron command to the end of the file:

`@reboot /path/to/bitwarden.sh start`

Now when you reboot your machine, this command will execute. However, if you would like a log of the command for debugging you can write the output of `bitwarden.sh start` to a log file like this:

`@reboot /path/to/bitwarden.sh start > /path/to/cron.log 2>&1`

**Comment by hubgitbb** [comment]
that works. thx
