### ISSUE TITLE
HELO issues

### ISSUE THREAD

**Issue by ricardomlm6** [bitwarden/server#4436]
### Steps To Reproduce

4. Click on '...'

### Expected Result

adc

### Actual Result

ase

### Screenshots or Videos

adh

### Additional Context

bgtr

### Build Version

dg

### Environment

Cloud (bitwarden.com)

### Environment Details

hh

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by WspieMobile7** [comment]
[➡️ Contratarhackers profesionales: https://www.wspiemobile.info/](https://www.wspiemobile.info/)
 
[➡️ Contratarhackers profesionales: https://www.wspiemobile.info/](https://www.wspiemobile.info/)

[➡️ Contratarhackers profesionales: https://www.hacktivus.xyz//](https://www.hacktivus.xyz//)
 

[➡️ Contratarhackers profesionales: https://www.hacktivus.xyz//](https://www.hacktivus.xyz//)

 
![IMG_7352](https://github.com/microsoft/vscode/assets/173863764/09278df0-083f-4b94-aa77-f8c380ba6ab4)

 
TELEGRAM Chat Directo: https://telegram.me/WspieMobile
 
[WHITE HAT]
OFRECEMOS SERVICIOS INFORMATICOS PROFESIONALES 
COBERTURA A NIVEL MUNDIAL 
TOTAL DISCRECION Y CONFIDENCIALIDAD
NO ES UN SERVICIO GRATUITO
