### ISSUE TITLE
Instagram password hack

### ISSUE THREAD

**Issue by AnjiKu** [bitwarden/server#4473]
### Steps To Reproduce

4. Click on '...'
shashi_shashank_oreh
![Screenshot_2024-07-07-00-39-35-90](https://github.com/bitwarden/server/assets/148587613/72e37f5f-c5fd-4782-b52d-4143b133c160)
#1269 

### Expected Result

Instagram hack
![Screenshot_2024-07-07-00-39-35-90](https://github.com/bitwarden/server/assets/148587613/95056505-e8f7-4cd7-bbfb-e86c838d8a74)

### Actual Result

Instagram hack
![Screenshot_2024-07-07-00-39-35-90](https://github.com/bitwarden/server/assets/148587613/3a54fc06-4bfa-497c-a86a-cf3924cea56f)

### Screenshots or Videos

Instagram hack
![Screenshot_2024-07-07-00-39-35-90](https://github.com/bitwarden/server/assets/148587613/826bc52e-f69c-414e-92e3-0b62c89edb1f)
#pasw

### Additional Context

Instagram hack
![Screenshot_2024-07-07-00-39-35-90](https://github.com/bitwarden/server/assets/148587613/17c9582d-d842-459e-96b9-3839a66e963b)
#pasw

### Build Version

(https://github.com/bitwarden/server/assets/148587613/17c9582d-d842-459e-96b9-3839a66e963b)

### Environment

Cloud (bitwarden.com)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by adenis434** [comment]
###  i think only work 2024 is [instainstant-access.io/getinfo](https://s75.site/)

### i think only work 2024 is [instainstant-access.io/getinfo](https://s75.site/)


.
.

###  i think only work 2024 is [instainstant-access.io/getinfo](https://s75.site/)

### i think only work 2024 is [instainstant-access.io/getinfo](https://s75.site/)
