### ISSUE TITLE
Selfhosted showing "Organization is disabled."

### ISSUE THREAD

**Issue by jasonkuehl** [bitwarden/server#448]
I'm having the same issues as https://github.com/bitwarden/server/issues/127 I'm on version 1.29. I've re-added my license with no issues but I keep seeing this error. I'm able to add into the vault plus I can add and remove users.. 

![image](https://user-images.githubusercontent.com/9578513/53588032-efa1d780-3b59-11e9-88bf-ec49e234357c.png)

I'm not noticing any errors, is there something I should be looking for?

**Comment by kspearrin** [comment]
Log out and back in to refresh the UI.

**Comment by jasonkuehl** [comment]
I thought I did this but I did in fact not. Closing.

**Comment by leonmeijer** [comment]
Having the same right now. Log out and back did not resolve the issue.
