### ISSUE TITLE
Verification email link do not include port

### ISSUE THREAD

**Issue by npodbielski** [bitwarden/server#450]
I have bitwarden setup at the port different then default HTTPS port. In verification email that I got from bitwarden link lacks this port. 
`https://my.domain.com/#/verify-email?userId=31947101-0ca1-43c6-9b27-aa04016a0611&token=CfDJ8HcUv39K%...`
And with port i.e. 4433 it should be:
`https://my.domain.com:4433/#/verify-email?userId=31947101-0ca1-43c6-9b27-aa04016a0611&token=CfDJ8HcUv39K%...`
It is not a big idea for me (I can just add it), but I guess it could be for someone else (i.e. not tech proficient member of some family).

**Comment by BetaLeaf** [comment]
Can confirm this. Was going to make a report and found @npodbielski has already made one. In my case, my https port is 8443 and installed via script at `https://github.com/nextcloud/vm/blob/master/apps/tmbitwarden.sh`

**Comment by Theprim0** [comment]
Same here, same problem

**Comment by npodbielski** [comment]
I noticed today that bitwarden shell script `bitwarden.sh` also do not know about port: it displays message: 'visit your installation at https://example.com' without a port.

**Comment by fkahhaleh** [comment]
I noticed all my auto-generated emails/links from BW self-hosted implementation didn't have the port number.
Editing the **global.override.env** file (/path/to/bwdata/scripts)
_globalSettings__baseServiceUri__vault=http://localhost:1234_
Fixed it for me.

**Comment by Hinton** [comment]
I'm unable to replicate this issue. Setting the `baseServiceUri__vault` with a port resolves it for me. I also tried running the installer which configured it for me.

Going to close this, but feel free to re-open it if the problem persists.
