### ISSUE TITLE
Port is already allocated

### ISSUE THREAD

**Issue by ClepToManix** [bitwarden/server#460]
Hello,

i'd tried to install bitwarden on my "docker server". I already use mailcow in a container. 
If i use ./bitwarden.sh install he asekd me the domain name, lets encrypt yes or no and my e-mail. After this step i get the following error:

`docker: Error response from daemon: driver failed programming external connectivity on endpoint certbot (93732d1ad3ce87f8d8f261cf252190b6d888901d87f836ffe23cf5e0f45b7986): Bind for 0.0.0.0:80 failed: port is already allocated.`

I tried to stop the container which is bind on 0.0.0.0:80 but nothing changed. I think this is a very simple issue, but im to stupid to solve them 😄 
I think my issue relateds to this container, but i have no idea how to change this port in bitwarden. May anyone can help me, i'm fresh with docker so please be patient 😈 

Thanks a lot!

**Comment by kspearrin** [comment]
If you are using the LetsEncrypt integration with Bitwarden, we don't support configuring the port used (it uses 80). You would need to modify the run.sh script to use some other available port or acquire and manage the cert on your own.

**Comment by ClepToManix** [comment]
Hello, thank for your fast reply. Do you know how to issue a certificate manually for a docker container?

**Comment by kspearrin** [comment]
You can read about how to use certbot here: https://certbot.eff.org/
