### ISSUE TITLE
Bitwarden Server Problem

### ISSUE THREAD

**Issue by Nisutec** [bitwarden/server#462]
On ./bitwarden.sh start i receive this:

===================================================

Docker version 18.09.3, build 774a1f4
docker-compose version 1.23.2, build 1110ad01

Removing network docker_default
WARNING: Network docker_default not found.
Pulling mssql         ... extracting (100.0%)
Pulling web           ... done
Pulling attachments   ... done
Pulling api           ... done
Pulling identity      ... done
Pulling admin         ... done
Pulling icons         ... done
Pulling notifications ... done
Pulling nginx         ... done

ERROR: for mssql  failed to register layer: no space left on device
ERROR: failed to register layer: no space left on device

But df -h say
Filesystem      Size  Used Avail Use% Mounted on
/dev/loop207     25G   16G  7.7G  67% /
none            492K     0  492K   0% /dev
tmpfs            63G     0   63G   0% /dev/shm
tmpfs            63G   17M   63G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            63G     0   63G   0% /sys/fs/cgroup
tmpfs            13G     0   13G   0% /run/user/0

Why i receive this error ?

**Comment by kspearrin** [comment]
> ERROR: for mssql failed to register layer: no space left on device
> ERROR: failed to register layer: no space left on device

Sounds like you need more space on the device.

**Comment by Nisutec** [comment]
how many space require the mysql module ?

**Comment by kspearrin** [comment]
![image](https://user-images.githubusercontent.com/1190944/54603077-cddd9700-4a19-11e9-9c03-e4310e34c646.png)

Looks like 1.32 gb

**Comment by Nisutec** [comment]
ok thx
