### ISSUE TITLE
On-Prem Email Notification with Gmail

### ISSUE THREAD

**Issue by drummingrocks** [bitwarden/server#464]
I recently set up an on-premise Bitwarden installation, but so far I've been unable to get the email notification to work.  I've seen where others have had problems getting Gmail to work, but in my case, I'm using a GSuite for Education email address (not sure if that makes a difference).  

I've tried almost every combination I've run across; different ports, enabling SSL, disabling SSL, using smtp.gmail.com, using smtp-relay.gmail.com, changing the mail_smtp_authType, etc.  What else can I try?  I'm open to any suggestions at this point.  Thanks!

Another question: when I modify the global.override.env file, do those changes take effect immediately, or is there a service that I should be starting and stopping to make sure the changes are applied?

Current settings:
`globalSettings__mail__replyToEmail=my.name@mydomain.org
globalSettings__mail__smtp__host=smtp.gmail.com
globalSettings__mail__smtp__username=my.name@mydomain.org
globalSettings__mail__smtp__password=password
globalSettings__mail__smtp__ssl=true
globalSettings__mail__smtp__port=587
globalSettings__mail__smtp__useDefaultCredentials=false
globalSettings__disableUserRegistration=false
adminSettings__admins=
globalSettings__mail__smtp__authType=Login
`

**Comment by kspearrin** [comment]
Is this v1.30.0?

If you are using portal 587, ssl should be false.

Also, did you enable "less secure apps" for your gmail account?  https://support.google.com/accounts/answer/6010255?hl=en

**Comment by drummingrocks** [comment]
> Is this v1.30.0?
> 
> If you are using portal 587, ssl should be false.
> 
> Also, did you enable "less secure apps" for your gmail account? https://support.google.com/accounts/answer/6010255?hl=en

It's version 2.8.0 according to the web GUI.  My gmail account is set to allow less secure apps.

**Comment by kspearrin** [comment]
Can you please update to the latest version and try again?

**Comment by drummingrocks** [comment]
Upgraded to 1.30.1 and changed SSL to 'false'.  Now I get an "Unhandled server error occurred" when I try to send the verification email.

**Comment by kspearrin** [comment]
And what are the logs in ./bwdata/logs/Api associated with that error? That will tell you the problem.

**Comment by drummingrocks** [comment]
"An error occurred while attempting to establish an SSL or TLS connection."

Also,, looking at the global.override.env file, the globalSettings_logDirectory is set to etc/bitwarden/logs, but that folder doesn't exist.  There's no bitwarden folder in /etc.  Is that normal?

**Comment by kspearrin** [comment]
What if you try a regular gmail account. Does it work there?

**Comment by drummingrocks** [comment]
No luck with a regular gmail account.  I got the same error: "An error occurred while attempting to establish an SSL or TLS connection."  Here's the settings I tried: 

`globalSettings__mail__replyToEmail=email@gmail.com
globalSettings__mail__smtp__host=smtp.gmail.com
globalSettings__mail__smtp__port=587
globalSettings__mail__smtp__ssl=false
globalSettings__mail__smtp__username=email@gmail.com
globalSettings__mail__smtp__password=password
globalSettings__disableUserRegistration=false
adminSettings__admins=
globalSettings__mail__smtp__useDefaultCredentials=false
globalSettings__mail__smtp__authType=Login
`

**Comment by kspearrin** [comment]
I am not sure. Unfortunately, I cannot reproduce the problem on my test server with gmail.

**Comment by Luc3as** [comment]
Hi, Use port 25 with ssl, Don't know why but it works in my case.

**Comment by mickkael** [comment]
Hi,

I have the following and it works:

smtp_host=smtp.gmail.com

smtp_from= <your_gmail_user_email>

smtp_user= <your_gmail_user_email>

smtp_password= <password>

smtp_port=587

smtp_ssl=true

 

(from the admin panel, just tick SSL, and don't tick explicit TLS)

 

About the user and password, you have some config to do in Gmail:

 

If you use 2FA, you have to create an App Password.

https://security.google.com/settings/security/apppasswords

 

If you don't use 2FA, you can simply activate Access for less secure apps

**Comment by djsmith85** [comment]
Hi @drummingrocks, it looks like there is a viable workaround or resolution for the issue you're experiencing. Please let us know if this resolves the originally posted issue.
