### ISSUE TITLE
On-premise: FIDO U2F Error 4 after renaming Bitwarden FQDN

### ISSUE THREAD

**Issue by rmuehl** [bitwarden/server#465]
Running  On-premise docker installation on RHEL7:
> COREVERSION="1.30.1"
WEBVERSION="2.10.0"

Now I had to rename the FQDN of Bitwarden, so I changed 
* config.yml
* global.override.env

and executed `./bitwarden.sh rebuild`

All containers were up and running, and the webservice was reachable on the new URL.

But none of the enabled FIDO U2F were working afterwards. All users had to login with an alternate second factor, remove the security keys and add them again.

All users with no additional 2-step-login who didn't save their restore keys lost their vault.

Screenshot:
![U2F-error-screenshot](https://user-images.githubusercontent.com/22004345/55139775-de3af380-5136-11e9-8dc2-73d0c96e633f.png)

**Comment by kspearrin** [comment]
This is expected since the U2F keys are signed with the app-id.json at https://yourdomain.com/app-id.json. If you change that, all existing keys will be invalidated and not work.
