### ISSUE TITLE
On-premises new device login email has wrong IP

### ISSUE THREAD

**Issue by rmuehl** [bitwarden/server#466]
Running On-premise docker installation on RHEL7:
> COREVERSION="1.30.1"
WEBVERSION="2.10.0"

Every time I restart the docker service the docker-IP gets changed.
When users logging in to the Bitwarden WebUI from Chrome Browser this email gets send to them:

![mail-screenshot](https://user-images.githubusercontent.com/22004345/55140934-82259e80-5139-11e9-8076-87d9abd038ce.png)

And not just once. You get this email from every PC you login.

**Comment by kspearrin** [comment]
This is due to an issue with Docker, seen here for more info: https://github.com/docker/for-mac/issues/180

Workaround on some systems is to use host networking, but I am unsure the impacts of doing so.

**Comment by Lalufu** [comment]
Is there a way to disable these notifications in the mean time? They're just adding confusion as is.

**Comment by kspearrin** [comment]
@Lalufu Added a new env variable in the next version to disable these emails:

```
globalSettings__disableEmailNewDevice=true
```

**Comment by Lalufu** [comment]
Thanks! Much appreciated.
