### ISSUE TITLE
Icons are revealing users activities.

### ISSUE THREAD

**Issue by tchich** [bitwarden/server#470]
The clients (the browser extension at least) are trying to get the icon of the site. There is an HTTP request that look like that:

`GET /icons/url-of-the-site-i-want-to-log-in.com/icon.png HTTP/1.1`

The URL of the sites are ciphered in the json files but are visible on the server with this request. This is unsecure, because you have both a clear text and its ciphered version. 
Furthemore, it is not GDPR compliant. I think it reveal a lot of the activity of users using bitwarden.

I suggest that the name of the icon and its contenu should be ciphered.

**Comment by kspearrin** [comment]
This is covered in details here: https://help.bitwarden.com/article/website-icons/
