### ISSUE TITLE
There are no items to list.

### ISSUE THREAD

**Issue by rbrowning85** [bitwarden/server#4728]
### Steps To Reproduce

I am not sure when the error occurred, but I logged into the vault warden web portal this morning to do some maintenance, and I noticed that my "Family Passwords" organizations indicates that "There are no items to list." However, My Vault and my other organization both have passwords listed. 

I got scared, so I imported a known good backup. The items were imported successfully, but they still do not show up. 

However, using the android app and the desktop app, I am able to see the passwords in the Family Passwords organization (even the duplicates from the above import). 

Why are the passwords showing up in the apps, but not the web application? 

### Expected Result

I expected to see all of the passwords associated with my Family Passwords organization listed.

### Actual Result

There are no items to list.

### Build Version

1.32.0  

### Environment

Self-Hosted

### Environment Details

Unraid

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by jtodddd** [comment]
Hi there,

For this issue we ask that you please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/). Someone will be able to gather more information and help from there.

The issue here will be closed.

Thanks!
