### ISSUE TITLE
Possible to register multiple accounts with gmail addresses

### ISSUE THREAD

**Issue by Jofairden** [bitwarden/server#474]
So, not 100% sure if it's really an _issue_ or bug, but I thought I'd report it anyways.

Actually, the whole reason why I tried this was after trying out Bitwarden for the first time, I could no longer login to my account and it was saying my password was incorrect. I'm 100% sure it's the right password. Unfortunately I didn't have my browser remember any credentials so I'm logged out for good.

Anyways, the problem is as follows:
Gmail allows adding any dots to the mail address, so for example:
`john.doe@gmail.com` is the same as `johndoe@gmail.com` ([see also](https://support.google.com/mail/answer/7436150?hl=en))
Additionally, nobody else can claim that address (if you register `johndoe@gmail.com`, then nobody can register any permutation with dots of that address anymore on gmail)

So this isn't an issue per se, in which let's say, another person could register a permutation address and try to claim the original account. But, it is possible to register multiple accounts this way on Bitwarden, with the emails going to the same address.

So I'm not 100% sure if it's really something that should be changed, it could actually be useful if someone wanted to split their vault for some reason, but technically use the same email address for it.

(Also, it would be cool if my account issue could be resolved. I have two accounts now, but I'd really only like to use one)

**Edit**: Soooo.. actually something interesting just happened in the web vault. I was logged into the secondary account (where I didn't use the dot permutation in the email), and it was showing an empty vault before I made this issue. (Makes sense, I just made that account). After just refreshing the vault, I was suddenly logged back into my original account (with the dot permutation) where I can see the one password I generated again.  Also it displayed the box to send a verification email, even though I had just verified it. Strange indeed.

I tried changing an account setting and then it locked me out of the account again, and saying my master password is incorrect (it isn't!). After refreshing, it's prompting me again to log into the other account, which works with my master pass.

**Comment by kspearrin** [comment]
Yes, this is expected. You can also register other permutations with `+suffix`.

I am not really sure why we would want to place any limitations here.

Regarding your other account, you can use the self-delete options mentioned here:
https://help.bitwarden.com/article/delete-your-account/

**Comment by Jofairden** [comment]
@kspearrin alright, good to know, but did you read my edit note as well? That was a really weird occurrence, and I don't understand how I could've suddenly went back to the session for the other account.

**Comment by Jofairden** [comment]
Ok so I deleted both accounts, all went good. I registered with the original account again and it seems to work fine now. Though it said all my data was deleted, though preferences weren't? It still knows that I toggled on the setting to allow gravatar. Also feel a bit uneasy on how easy it was to delete the entire vault. Having access to the email is so powerful. Does Bitwarden have a native functionality to perform automated exports of my vault securely ?

**Comment by kspearrin** [comment]
I am not sure how you would have mixed sessions since that information is stored using the browser's `sessionStorage`, which applies to each tab individually.

Some settings are stored on the client, rather than the account, which would explain your gravatar setting persisting.

You can view information here about exporting:
https://help.bitwarden.com/article/export-your-data/

**Comment by Jofairden** [comment]
Hey thanks for the support. Deleting the old accounts and making an entire new one seemed to fix any issues I had. I hope this article proves useful for future readers as well.
