### ISSUE TITLE
Doing less mssql backups?

### ISSUE THREAD

**Issue by AdrienPoupa** [bitwarden/server#482]
Hello,
I am doing a backup of the bwdata everyday. However, it would include the DB from the last 30 days each day... That's wasteful. Is there a way to modify this, like doing it only for 7 days ?

**Comment by kspearrin** [comment]
It is not configurable at this time. Maybe just exclude that mssql backup folder from you backups?

**Comment by AdrienPoupa** [comment]
Ok, thanks for the answer. I guess I could but in the unexpected event of a crash I guess it's better to have a true dump rather than the raw live data?

**Comment by kspearrin** [comment]
I’m sure you could run some script as part of your backup procedure to delete all mssql backups older than 7 days before your backup runs.

**Comment by AdrienPoupa** [comment]
Good call, I just wanted to know if something was already there in Bitwarden. Thanks!

**Comment by AdrienPoupa** [comment]
Delete everything but the latest file in case anybody is interested:

`/bwdata/mssql/backups$ ls -1tr | head -n -1 | xargs -d '\n' rm -f --`
