### ISSUE TITLE
Can this server be used as notification server?

### ISSUE THREAD

**Issue by LightVolk** [bitwarden/server#483]
Can this server be used as notification server?
I want to send some notifications from one client to another.

**Comment by kspearrin** [comment]
Sorry, but I do not understand the question.

**Comment by djsmith85** [comment]
Hi @LightVolk , it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
