### ISSUE TITLE
Fails install - "Unable to validate installation id" might be proxy related

### ISSUE THREAD

**Issue by IronWolve** [bitwarden/server#484]
Fails on install, with error 
"Unable to validate installation id. Problem contacting Bitwarden server." on a fresh ubuntu 19.04 with docker from ubuntu repo. 

I am behind a proxy and use a proxy config for the os and docker, docker works behind the proxy, and I have bash environmental settings for the proxy, so apps work. 

I don't know where this error is coming, this is my office network, so I don't/can't use lets encrypt, my workstation is not on the Internet.   I think something might be trying to reach the Internet, and not using the bash environmental settings. 

I see the docker image installed for bitwarden/setup, I can launch it with /bin/bash with user root, it keeps changing me to nobody, so I can't grep for the code to debug it. 

```
# docker run -it -u 0 bitwarden/setup  /bin/bash
nobody@d17f53cc7b4d:/app$ 
```

```
# ./bitwarden.sh install
 _     _ _                         _            
| |__ (_) |___      ____ _ _ __ __| | ___ _ __  
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \ 
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2019, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

Docker version 18.09.5, build e8ff056
docker-compose version 1.21.0, build unknown

(!) Enter the domain name for your Bitwarden instance (ex. bitwarden.company.com): bharty-laptop.sonosite.com

(!) Do you want to use Let's Encrypt to generate a free SSL certificate? (y/n): n

1.30.1: Pulling from bitwarden/setup
Digest: sha256:018d3be93bc5c8c3c79586cd92461b324d692f0f76ece331f87294abd4de109d
Status: Image is up to date for bitwarden/setup:1.30.1

(!) Enter your installation id (get at https://bitwarden.com/host): <snip>

(!) Enter your installation key: <snip>

Unable to validate installation id. Problem contacting Bitwarden server.

```

**Comment by kspearrin** [comment]
Yes, we make a call to api.bitwarden.com to validate the installation id.

Can you confirm docker is configured for the proxy, as described here? https://docs.docker.com/network/proxy/

**Comment by IronWolve** [comment]
That was it. ~/.docker/config.json 

It wasnt reading my dockers systemd or environmental docker settings.  

Thanks!

**Comment by dan-christensen** [comment]
I think I'm having the same issue as you did. What exactly did you put in the ~/.docker/config.json? And was it as the root use or in the container?

**Comment by orome70** [comment]
Hi!
I don't know if it is the same issue, but I'm getting the same message:
```Unable to validate installation id. Problem contacting Bitwarden server.```

I configured docker to have the same proxy parameters as in the example:
```
{
 "proxies":
 {
   "default":
   {
     "httpProxy": "http://127.0.0.1:3001",
     "httpsProxy": "http://127.0.0.1:3001",
     "noProxy": "*.test.example.com,.example2.com"
   }
 }
}
```
It is in this file:  `~/.docker/config.json`
And docker takes these parameters into account.

I assume there should be specific parameters for bitwarden.

**Comment by dan-christensen** [comment]
I assume its running in docker? I fixed it by giving the BitWarden container internet access. It sounds similar to what I was experiencing.

**Comment by orome70** [comment]
Indeed, it is running in docker... well, I thought that container had access to internet...  by default.
Since it's a fresh docker install I'm going to check that.

**Comment by dan-christensen** [comment]
I had cockpit installed at the time, but if you have a docker manager like portainer I'm sure you could do it through that.

**Comment by orome70** [comment]
Well, it does not work. And docks seems to have correct internet access. In any case, since we are downloading the setup scripts from bitwarden, and docker is running well, I assume it should work out of the box.

**Comment by dokime7** [comment]
I have the same problem and there is no internet access restriction and no proxy on my server...

**Comment by dan-christensen** [comment]
So the way I fixed it was installing portainer and then joining dockers network to the host network. I'm sure there's a way to do that through the CLI too I just don't know how.

**Comment by orome70** [comment]
:-)
In my case, I dropped bitwarden altogether. 
It may be related to some reverse proxy configuration, it is always tricky.

**Comment by dokime7** [comment]
I have a reverse proxy in front of my server but it has nothing to do with, All my other containers have access to internet without any custom network config.

**Comment by orome70** [comment]
Yeah, but specific configuration is needed when there are unusual ports or protocols. But it is documented when it is the case.

**Comment by dokime7** [comment]
OK, so which password manager do you use instead? :p

**Comment by orome70** [comment]
Well, none at the moment. :'-(
