### ISSUE TITLE
Bitwarden Firefox entension no longer unlocks using biometrics

### ISSUE THREAD

**Issue by godfrey62** [bitwarden/server#4847]
### Steps To Reproduce

1) In Firefox (version 131.0 aarch64, macOS Sonoma) go to a web page that requires a login
2) Bitwarden Extension icon has a padlock (i.e. it's locked)
3) Click the Bitwarden Extension 
4) The Extension opens, the options are to enter Master Password or unlock with biometrics
5) Click "Unlock with biometrics" - nothing happens, usually another window opens requestion touch ID to unlock
6) This problem happens even when Bitwarden Desktop app (version 2024.8.0 (28594)) is running and has been unlocked.
7) This problem was first observed on 25-Sep-2024

### Expected Result

When "Unlock with biometrics" is clicked another window (from macOS) requests Touch ID

### Actual Result

When "Unlock with biometrics" is clicked nothing happens and Bitwarden Extension remains locked. It can only be opened using Master Password even when Bitwarden Desktp app is running and unlocked.

### Screenshots or Videos

https://github.com/user-attachments/assets/fc9af65b-0327-407e-9bf4-82eae6138921

### Githash Version

I don't have a GitHub domain

### Environment Details

macOS Sonoma 14.7 on M1 MacBook Air

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Krychaz** [comment]
Hey,

Can you please confirm which version of Bitwarden Unified you are running?

**Comment by godfrey62** [comment]
Hello,

I am running:

Desktop app version 2024.8.0 (28594)

Firefox extension version 2024.9.1

on macOS Sonoma 14.7

**Comment by Krychaz** [comment]
You've marked this issue as Bitwarden Unified. Can you confirm if you are indeed running a self-hosted Unified deployment?

**Comment by godfrey62** [comment]
I don’t understand what Bitwarden Unified is, I don’t know what a “self-hosted Unified deployment” is, I’m a tech savvy home user but I don’t have servers or any self-hosting gear at home. If I marked it as self-hosting then it was in error.

GitHub is not a great place to raise Bitwarden issues, it assumes a level of technical expertise that I do not have.

**Comment by Krychaz** [comment]
Hi,

We use GitHub issues as a place to track bugs and other development related issues. If your issue persists, please write us back using our “Contact support” form located on our Help Center (https://bitwarden.com/help/).

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other Bitwarden users on our community forums (https://community.bitwarden.com/c/support/). 

The issue here will be closed.
