### ISSUE TITLE
How to disable the built-in mssql in docker?

### ISSUE THREAD

**Issue by abctaylor** [bitwarden/server#487]
Quite simply - can I disable the dockerised mssql? I'm using an external SQL Server cluster and am looking to conserve a bit of resources across the Bitwarden servers running.

Andrew

**Comment by kspearrin** [comment]
Just edit the docker-compose.yml file under ./bwdata/docker and remove the mssql container. You would need to edit ./bwdata/config/yml as well to not re-generate the compose file, however, or else your changes would be overwritten on updates.

**Comment by abctaylor** [comment]
@kspearrin sorry to bother you, I'm getting this following the above:

`WARNING: Found orphan containers (bitwarden-mssql) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.`

That flag isn't working at all with anything I can think of.

**Comment by abctaylor** [comment]
Resolved for anyone wondering: run docker-compose build in bwdata/docker
