### ISSUE TITLE
503 Error on Sign in With Specific Account

### ISSUE THREAD

**Issue by z0t0b** [bitwarden/server#4904]
### Steps To Reproduce

Seems to only be happening to one of my accounts. My personal account can sign in just fine. I've tried multiple browsers, incognito mode, being on a VPN and using the desktop application. All result in an error message saying "an unexpected error has occurred". The networking tab in the developer tools of Chrome shows I'm getting a 503 error on the knowndevice and token API calls. I also receive this same 503 error when attempting to download the BitWarden application for Windows from the official website. It says "Error 503 Backend unavailable, connection timeout" and gives me error message 54113. The details say "cache-pdk-kpdk1780147-PDK 1729088738 1479419917"

### Expected Result

Not getting an error message or 503 error, being allowed to enter my MFA code instead of the application hanging for a while at the password input.

### Actual Result

An error message after entering the password, no prompt for MFA.

### Screenshots or Videos

![503Error](https://github.com/user-attachments/assets/1bfc03ba-12fc-4181-b734-960409f08856)

### Additional Context

Need this fixed ASAP because my work is critical and requires me to have access to this password manager

### Build Version

2024.9.0

### Environment

Cloud (bitwarden.com)

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by djsmith85** [comment]
Thanks @z0t0b for your report. This is currently likely to some temporary service issues. Up to date information can be found at https://status.bitwarden.com

**Comment by z0t0b** [comment]
> Thanks @z0t0b for your report. This is currently likely to some temporary service issues. Up to date information can be found at https://status.bitwarden.com

Thanks for that information. When I previously checked the status page nothing was listed to show there was an issue, but I do see it's up-to-date now. I'll check back later to see if I can access my account again.

**Comment by z0t0b** [comment]
Yep looks like it's fixed now, thanks for looking into this so quickly!
