### ISSUE TITLE
New installation fails with permission denied

### ISSUE THREAD

**Issue by marklai1998** [bitwarden/server#491]
I'm getting an error while doing
```
sudo ./bitwarden.sh install
```
It pulls and builds the image successfully but it ends up with
```
/bin/bash: /entrypoint.sh: Permission denied
```
I'm fresh to docker and have no idea where entrypoint.sh is

ps. I'm running ubuntu server

**Comment by marklai1998** [comment]
did some research and the entrypoint.sh is located at
/var/snap/docker/common/var-lib-docker/ovverlay2/<somehash>
maybe some kind of temp folder
any way to solve it?

**Comment by kspearrin** [comment]
Was docker installed with snap or something? Why is it under /var/snap ?

**Comment by QuantumRads** [comment]
Did you ever figure out the solution to this? I am having the same issue, but my server has been running for months until I rebooted it.

**Comment by djsmith85** [comment]
Hi @marklai1998, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
