### ISSUE TITLE
An error occurred while attempting to establish an SSL or TLS connection

### ISSUE THREAD

**Issue by adrianolucas** [bitwarden/server#492]
I've read all related posts on this forum, but with no luck this far.

- The server runs Ubuntu 16.04.
- All certs are issued by Letsencrypt and are valid.
- Emails are successfully sent/received via SSL over port 993 using clients such as Apple Mail, Thunderbird, etc; openssl on 993 returns positive results.
- All certs have been copied in bwdata/ca-certificates and are imported successfully into the docker container.

`Docker version 18.09.5, build e8ff056`
`docker-compose version 1.24.0, build 0aa59064`

`1.30.1: Pulling from bitwarden/setup`
`Status: Image is up to date for bitwarden/setup:1.30.1`
`Updating certificates in /etc/ssl/certs...`
`2 added, 0 removed; done.`
`Running hooks in /etc/ca-certificates/update.d...`
`done.`

from inside the docker app

`root@30a394cbbe21:/# ls /etc/bitwarden/ca-certificates`
`mail.server.com.crt  server.com.crt`
`root@30a394cbbe21:/# ls /usr/local/share/ca-certificates`
`mail.server.com.crt  server.com.crt`

`root@30a394cbbe21:/# openssl s_client -connect mail.server.com:993`
`CONNECTED(00000003)`
`depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3`
`verify return:1`
`depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3`
`verify return:1`
`depth=0 CN = mail.server.io`
`verify return:1`
`---`
`Certificate chain`
` 0 s:/CN=mail.server.io`
`   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3`
` 1 s:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3`
`   i:/O=Digital Signature Trust Co./CN=DST Root CA X3`
`---`
`Server certificate`
`-----BEGIN CERTIFICATE-----`
`...`
`-----END CERTIFICATE-----`
`subject=/CN=mail.server.io`
`issuer=/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3`
`---`
`No client certificate CA names sent`
`Peer signing digest: SHA512`
`Server Temp Key: ECDH, P-256, 256 bits`
`---`
`SSL handshake has read 3396 bytes and written 302 bytes`
`Verification: OK`
`---`
`New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384`
`Server public key is 2048 bit`
`Secure Renegotiation IS supported`
`Compression: NONE`
`Expansion: NONE`
`No ALPN negotiated`
`SSL-Session:`
`    Protocol  : TLSv1.2`
`    Cipher    : ECDHE-RSA-AES256-GCM-SHA384`
`    Session-ID: ...`
`    Session-ID-ctx: `
`    Master-Key: ...`
`    PSK identity: None`
`    PSK identity hint: None`
`    SRP username: None`
`    TLS session ticket lifetime hint: 300 (seconds)`
`    TLS session ticket:`
`    0000 - ff f4 be d0 eb 35 c9 fb-d5 3e 8e eb ea 7e c5 33   w....5...>...~.3`
`    ...`
`    0090 - 77 f4 be d0 eb 35 c9 fb-d5 3e 8e eb ea 7e c5 33   w....5...>...~.3`

`    Start Time: 1557028690`
`    Timeout   : 7200 (sec)`
`    Verify return code: 0 (ok)`
`    Extended master secret: no`
`---`
`* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=LOGIN] Dovecot ready.`

current settings in `global.override.env`:

`globalSettings__mail__replyToEmail=no-reply@server.com`
`globalSettings__mail__smtp__host=mail.server.com`
`globalSettings__mail__smtp__port=993`
`globalSettings__mail__smtp__ssl=true`
`globalSettings__mail__smtp__username=admin.user`
`globalSettings__mail__smtp__password=*password*`

i've tried with TLS over port 25 after checking out [451](https://github.com/bitwarden/server/issues/451):

`globalSettings__mail__replyToEmail=no-reply@server.com`
`globalSettings__mail__smtp__host=mail.server.com`
`globalSettings__mail__smtp__port=25`
`globalSettings__mail__smtp__ssl=false`
`globalSettings__mail__smtp__username=admin.user`
`globalSettings__mail__smtp__password=password`
`globalSettings__mail__smtp__startTls=true`

but the result is desperately the same:

`2019-05-05 05:02:38.147 +00:00 [Error] An error occurred while attempting to establish an SSL or TLS connection.`
`...`
`MailKit.Security.SslHandshakeException: An error occurred while attempting to establish an SSL or TLS connection.`

`---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.`
`   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)`

the mail log shows:

`May  5 01:20:30 server postfix/smtpd[13087]: connect from unknown[111.111.111.111]`
`May  5 01:20:31 server postfix/smtpd[13087]: lost connection after AUTH from unknown[111.111.111.111]`
`May  5 01:20:31 server postfix/smtpd[13087]: disconnect from unknown[111.111.111.111] ehlo=1 auth=0/1 commands=1/2`

I'm running out of ideas, any idea on how to debug it further?

**Comment by kspearrin** [comment]
There are known problems validating LE certs in .NET Core 2. There are supposed to be fixes in .NET Core 3, but that is likely some time off. The only known workaround is to use `globalSettings__mail__smtp__trustServer=true`.

**Comment by adrianolucas** [comment]
That explains a lot... Thanks @kspearrin for the input.
