### ISSUE TITLE
bitwarden/mssql restart loop after upgrade 1.30.1

### ISSUE THREAD

**Issue by Orgoth** [bitwarden/server#493]
After updating to version 1.30.1, the MSSQL server restarts again and again.
A check of the log file showed that a file is defective.

docker logs bitwarden-mssql
```
/opt/mssql/bin/sqlservr: The file archive [/opt/mssql/lib/sqlservr.sfp] is invalid.  Please resolve and try again.
```

Is it possible to reinstall the container "bitwarden/mssql"?
With apt I would use --reinstall, unfortunately I couldn't find something like this for Docker.
Would it work if I deleted the container and then do the installation again using bitwarden.sh?

docker ps
```
CONTAINER ID        IMAGE                            COMMAND             CREATED             STATUS                          PORTS                                                 NAMES
c1fc66404516        bitwarden/nginx:1.30.1           "/entrypoint.sh"    2 days ago          Up 2 days                       80/tcp, 0.0.0.0:80->8080/tcp, 0.0.0.0:443->8443/tcp   bitwarden-nginx
21834159eb53        bitwarden/admin:1.30.1           "/entrypoint.sh"    2 days ago          Up 2 days                       5000/tcp                                              bitwarden-admin
62b2dca7fae4        bitwarden/attachments:1.30.1     "/entrypoint.sh"    2 days ago          Up 2 days                       5000/tcp                                              bitwarden-attachments
53b1fd5f0010        bitwarden/mssql:1.30.1           "/entrypoint.sh"    2 days ago          Restarting (1) 14 seconds ago                                                         bitwarden-mssql
b14220ce79f0        bitwarden/notifications:1.30.1   "/entrypoint.sh"    2 days ago          Up 2 days                       5000/tcp                                              bitwarden-notifications
1c85a33aefcc        bitwarden/api:1.30.1             "/entrypoint.sh"    2 days ago          Up 2 days                       5000/tcp                                              bitwarden-api
b52ad7fda045        bitwarden/identity:1.30.1        "/entrypoint.sh"    2 days ago          Up 2 days                       5000/tcp                                              bitwarden-identity
7a5fd3e85ffe        bitwarden/icons:1.30.1           "/entrypoint.sh"    2 days ago          Up 2 days                       5000/tcp                                              bitwarden-icons
cdbecac6c710        bitwarden/web:2.10.0             "/entrypoint.sh"    2 days ago          Up 2 days                       5000/tcp                                              bitwarden-web
```

**Comment by kspearrin** [comment]
Docker containers are mostly stateless, so there isn't really anything to reinstall. The only state for the mssql container is contained in `./bwdata/mssql`. This is mapped to `/var/opt/mssql/data`. Maybe something was corrupted in there? You could delete `./bwdata/mssql` if you wanted, but be aware that this is where all of the databases actual data resides, so it would be lost.

**Comment by Orgoth** [comment]
The problem lies in the container "bitwarden-mssql".
There the file "/opt/mssql/lib/sqlservr.sfp" is defective, so mssql keeps restarting.

So my question was how can I reinstall the container?
Sorry if my question wasn't clear.

I don't have any experience with Docker, so I don't know exactly how to reinstall the container.
My guess would be this.
I delete the container "docker container rm 53b1fd5f0010".
But now I don't have the command to install the container "bitwarden-mssql" again.
Is it enough if I do a "docker pull bitwarden/mssql:1.30.1"?

**Comment by kspearrin** [comment]
> Docker containers are mostly stateless, so there isn't really anything to reinstall.

Reinstalling would just be re-creating the container, which happens each time you stop and start with `bitwarden.sh`.

**Comment by Orgoth** [comment]
Okay, thanks for a quick response.
Unfortunately this doesn't explain why the error in the sfp file in the container still exists, even if I restart with bitwarden.sh.

I'll delete the folder you suggested and let you know if it helped.
I can't imagine it, because the error message clearly says that there is a defective file in the container itself.

**Comment by Orgoth** [comment]
Even after deleting the mentioned folder, the problem persists.
docker ps
```
CONTAINER ID        IMAGE                            COMMAND             CREATED              STATUS                                  PORTS                                                 NAMES
65b7306873ee        bitwarden/nginx:1.30.1           "/entrypoint.sh"    About a minute ago   Up About a minute                       80/tcp, 0.0.0.0:80->8080/tcp, 0.0.0.0:443->8443/tcp   bitwarden-nginx
2b6128afa757        bitwarden/admin:1.30.1           "/entrypoint.sh"    About a minute ago   Up About a minute                       5000/tcp                                              bitwarden-admin
a0927fb15cd4        bitwarden/icons:1.30.1           "/entrypoint.sh"    About a minute ago   Up About a minute                       5000/tcp                                              bitwarden-icons
2a997afea99b        bitwarden/identity:1.30.1        "/entrypoint.sh"    About a minute ago   Up About a minute                       5000/tcp                                              bitwarden-identity
5b9a0c90fcf1        bitwarden/mssql:1.30.1           "/entrypoint.sh"    About a minute ago   Restarting (1) Less than a second ago                                                         bitwarden-mssql
4f07d7580ef0        bitwarden/notifications:1.30.1   "/entrypoint.sh"    About a minute ago   Up About a minute                       5000/tcp                                              bitwarden-notifications
b00d3467b742        bitwarden/attachments:1.30.1     "/entrypoint.sh"    About a minute ago   Up About a minute                       5000/tcp                                              bitwarden-attachments
53844f8a712b        bitwarden/web:2.10.0             "/entrypoint.sh"    About a minute ago   Up About a minute                       5000/tcp                                              bitwarden-web
715205542c8d        bitwarden/api:1.30.1             "/entrypoint.sh"    About a minute ago   Up About a minute                       5000/tcp                                              bitwarden-api
```
The error message from the container is also the same.
docker logs bitwarden-mssql
```
/opt/mssql/bin/sqlservr: The file archive [/opt/mssql/lib/sqlservr.sfp] is invalid.  Please resolve and try again.
```

**Comment by kspearrin** [comment]
Are there any other logs? Have a look at ./bwdata/mssql

**Comment by Orgoth** [comment]
Running "docker pull bitwarden/mssql" also has no effect.
The problem is unfortunately still the same.

There are no files in the folder bwdata/mssql except the backups folder.

**Comment by Orgoth** [comment]
I have discovered the folder with the logfiles and will contact you as soon as I have found something useful.
Thanks

**Comment by Orgoth** [comment]
The log files in the folder /bwdata/logs/mssql/ are unfortunately not helpful, because they were last written on 26.04.
Directly before the update to the new version.
The last entry in errorlog only says that the MSSQL server will be shut down.
```
2019-04-26 06:35:23.13 spid6s      Always On: The availability replica manager is going offline because SQL Server is shutting down. This is an informational message only. No user action is required.
2019-04-26 06:35:23.13 spid6s      SQL Server is terminating in response to a 'stop' request from Service Control Manager. This is an informational message only. No user action is required.
2019-04-26 06:35:23.56 spid17s     Service Broker manager has shut down.
2019-04-26 06:35:23.87 spid6s      .NET Framework runtime has been stopped.
2019-04-26 06:35:29.83 spid6s      SQL Trace was stopped due to server shutdown. Trace ID = '1'. This is an informational message only; no user action is required.
```

**Comment by Orgoth** [comment]
I think I found a solution.
A downgrade to bitwarden/mssql:1.21.0 brought the database back up and running.

Since version 1.22.0 a new MSSQL version is used.
This seems to have a special prerequisite, which is no longer met under Ubuntu 16.04.
A version check or dependency check should be implemented so that all higher versions are only used when all dependencies are fulfilled.

https://hub.docker.com/r/bitwarden/mssql/tags

**Comment by kspearrin** [comment]
There are no known compat issues with Ubuntu 16 and our latest tags, so I am not sure what may be going on here. Could you try re-installing a whole new installation under a new directory and see if the same problem persists with that?

**Comment by Orgoth** [comment]
The problem does not occur with a complete new installation.
I updated the container bitwarden/mssql:1.21.0 in the main folder to 1.30.1 again.
This time there were no problems and Mssql starts normally.
It actually seems to have been a temporary problem with the last upgrade.

Thank you so much for your help.
It might also help someone else who might encounter the same problem.
