### ISSUE TITLE
Psql -c lowercase my table

### ISSUE THREAD

**Issue by Pedroacn** [bitwarden/server#498]
Hello,

I'm trying to use the following command:

psql -d copia-local -U postgres -c "COPY "Questions" FROM '/home/pedro/Documents/PostGre/data/cooked/Questions_cooked.txt' WITH DELIMITER '|' NULL AS ''"

But it returns ERROR:  relation "questions" does not exist

The thing is, if i run what is inside the -c parameter in the database itself it works:

copia-local=# COPY "Questions" FROM '/home/pedro/Documents/PostGre/data/cooked/Questions_cooked.txt' WITH DELIMITER '|' NULL AS '';
COPY 1342

So it seems that when i run a psql -c it sets the name of my table to lowercase by default, i tried looking for another parameter to respect the table name but found nothing.

Anyone knows if something like this exists ?

**Comment by kspearrin** [comment]
I'm sorry, but I do not know what psql is. Postgres? This application uses SQL Server, not Postgres.
