### ISSUE TITLE
Switch to nginx:stable-alpine docker image for TLS 1.3 support

### ISSUE THREAD

**Issue by karelvanhecke** [bitwarden/server#499]
`nginx:stable` is based on Debian Stretch, which comes with `openssl 1.1.0j-1` and doesn't yet support `TLSv1.3`.
`nginx:stable-alpine` is based on Alpine and comes with `openssl 1.1.1b-r1`, which does support `TLSv1.3`.

A variable in `config.yml` could be used to let the user define which image should be used?

**Comment by kspearrin** [comment]
I'd rather not have to make this configurable since I imagine nginx stable will eventually have support for 1.3 as well. Any idea on when they plan to support it there?

**Comment by karelvanhecke** [comment]
https://tracker.debian.org/pkg/openssl

Openssl 1.1.1 is now in testing, which means that it'll be included the next release, Debian 10 (code name Buster).
Buster will be released in 2019, but no specific date has been given yet. The docker image will also have to migrate to Buster when it is released, but I do not know how quickly that'll happen.

Perhaps permanently switching to the Alpine Linux based image should be considered?

Alpine Linux is heavily used for containers because of its resource efficiency is (for example, +-8mb container images, compared to 45mb+ for the Debian-based images).

Security wise, it's definitely on-par with Debian, if not more secure. 
It uses a hardened kernel and compiles all user space binaries as position-independent executables with stack-smashing protection.

For a complete overview, take a look at:
https://wiki.alpinelinux.org/wiki/Alpine_Linux:Overview

**Comment by 92VV3M42d3v8** [comment]
Do you now use TLS 1.3

**Comment by karelvanhecke** [comment]
@92VV3M42d3v8 I've been using it since the Debian Buster docker container released. This issue should be closed.
