### ISSUE TITLE
Directory Connector Import: Report an error when there are not enough seats available

### ISSUE THREAD

**Issue by tgermain** [bitwarden/server#500]
Hi,

I struggle with user and groups import. 
I'm using the directory connector and it is working fine.

What is misleading is that the import API (`organization/{orgID}/import`) [check if there are enough seats available](https://github.com/bitwarden/server/blob/master/src/Core/Services/Implementations/OrganizationService.cs#L1245) (enough licenses for the newly imported users) but do not return an error when there are not.

From a API user point of view, there is no way to tell if your import succeed or failed because of the license shortage as you get an HTTP 200 in anycases.

It would be better to get an HTTP error (400) in that case. 

As a user I'm totally fine with the current behavior : 
If there are not enough seats available, do not add any user aka reject the whole import.
Let say you have 3 seats left and 5 user to add, bitwarden do not try to add 3 user then fail to add the 4th one because no more seats are available.
Imports are meant to be idempotent so it's not an issue if your retry later.

**Comment by djsmith85** [comment]
Closing this as it was fixed with https://github.com/bitwarden/server/pull/1241
