### ISSUE TITLE
Infinite Loading on webserver

### ISSUE THREAD

**Issue by Profited** [bitwarden/server#503]
Today, I did a `sudo apt update && sudo apt upgrade` and I got a notice about docker? It told me it should be restarted if updated or else my docker containers could run into complications. 

I selected yes and finished the update. 

I go on my bitwarden site and it is stuck on the loading icon and can't access anything. 

Would this be something wrong with docker? I'm not an expert at identifying this.

**Comment by Profited** [comment]
I'm using cloudflare for my nameserver and the dns handling. 
Not sure if this would help but just extra info.

**Comment by Profited** [comment]
Syncing from the app and extension works, but the site is stuck on loading. 

![firefox_sHm7i0unFC](https://user-images.githubusercontent.com/46958955/58319683-a20bd280-7e09-11e9-96e6-f1803d529313.png)

**Comment by kspearrin** [comment]
Are there errors in developer tools console?

**Comment by lamka02sk** [comment]
I just updated my server too and MSSQL stopped working completely. RIP

**Comment by Profited** [comment]
Now it just isn't working. I restarted the bitwarden server and now my host wont resolve the ip. Can't access the website

**Comment by Profited** [comment]
2019/04/18 06:00:56 [warn] 31#31: *560 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/1/00/0000000001 while reading upstream, client: 

in the nginx error log

**Comment by Profited** [comment]
> 
> 
> I'm getting a similar issue, most of the time I'll get an infinite loading wheel as described above, and other times I'll just get the Bitwarden logo with no formatting (see photo below).
> 
> I'm also unable to sync using either the app or the Chrome extension, and when I visit my self-hosted site I get the following error in Chrome developer tools:
> 
> Failed to load resource: net::ERR_CONTENT_LENGTH_MISMATCH /app/main.8f8dc206a8cb64b757e1.css
> 
> I've tried updating both Docker and Bitwarden but can't seem to resolve it.
> 
> <img alt="Screenshot 2019-06-14 at 12 09 44" width="1021" src="https://user-images.githubusercontent.com/46993815/59498297-d0774d80-8e9d-11e9-950e-e408b844367f.png">

I temporarily moved everything to a different server and moved the bwdata/ over. It worked flawlessly.

**Comment by banjoboy96** [comment]
> I temporarily moved everything to a different server and moved the bwdata/ over. It worked flawlessly.

I've tried doing this to no avail. I'm pretty much stuck for ideas here, it seems that the page can't load that .css file, along with a couple of .js files, and my nginx logs show me several permission denied errors. However if I navigate directly to that file on my Bitwarden server's domain it opens up perfectly in Chrome (e.g. https://www.mybitwarden.com/app/main.8f8dc206a8cb64b757e1.css)

I'm not really well versed enough in nginx and the like to know what to do next, but I'll keep fiddling and update if and when I can solve things.

**Comment by Ventrue** [comment]
I'm hitting this issue as well, after a distribution upgrade. From the error.log:

`2019/07/25 14:45:17 [crit] 1776#1776: *116 open() "/var/cache/nginx/proxy_temp/3/04/0000000043" failed (13: Permission denied) while reading upstream, client: 50.224.7.234, server: <bw_hostname>, request: "GET /app/main.8f8dc206a8cb64b757e1.css HTTP/1.1", upstream: "https://127.0.0.1:8443/app/main.8f8dc206a8cb64b757e1.css", host: "<bw_hostname>", referrer: "https://<bw_hostname>/"
2019/07/25 14:45:17 [crit] 1776#1776: *121 open() "/var/cache/nginx/proxy_temp/4/04/0000000044" failed (13: Permission denied) while reading upstream, client: 50.224.7.234, server: <bw_hostname>, request: "GET /app/vendor.8f8dc206a8cb64b757e1.js HTTP/1.1", upstream: "https://[::1]:8443/app/vendor.8f8dc206a8cb64b757e1.js", host: "<bw_hostname>", referrer: "https://<bw_hostname>/"
2019/07/25 14:45:17 [crit] 1776#1776: *120 open() "/var/cache/nginx/proxy_temp/5/04/0000000045" failed (13: Permission denied) while reading upstream, client: 50.224.7.234, server: <bw_hostname>, request: "GET /app/main.8f8dc206a8cb64b757e1.js HTTP/1.1", upstream: "https://127.0.0.1:8443/app/main.8f8dc206a8cb64b757e1.js", host: "<bw_hostname>", referrer: "https://<bw_hostname>/"
2019/07/25 14:45:17 [crit] 1776#1776: *119 open() "/var/cache/nginx/proxy_temp/6/04/0000000046" failed (13: Permission denied) while reading upstream, client: 50.224.7.234, server: <bw_hostname>, request: "GET /app/polyfills.8f8dc206a8cb64b757e1.js HTTP/1.1", upstream: "https://[::1]:8443/app/polyfills.8f8dc206a8cb64b757e1.js", host: "<bw_hostname>", referrer: "https://<bw_hostname>/"
2019/07/25 14:45:18 [crit] 1776#1776: *125 open() "/var/cache/nginx/proxy_temp/7/04/0000000047" failed (13: Permission denied) while reading upstream, client: 50.224.7.234, server: <bw_hostname>, request: "GET /app/vendor.8f8dc206a8cb64b757e1.js HTTP/1.1", upstream: "https://[::1]:8443/app/vendor.8f8dc206a8cb64b757e1.js", host: "<bw_hostname>", referrer: "https://<bw_hostname>/"
2019/07/25 14:45:18 [crit] 1776#1776: *128 open() "/var/cache/nginx/proxy_temp/8/04/0000000048" failed (13: Permission denied) while reading upstream, client: 50.224.7.234, server: <bw_hostname>, request: "GET /app/main.8f8dc206a8cb64b757e1.js HTTP/1.1", upstream: "https://127.0.0.1:8443/app/main.8f8dc206a8cb64b757e1.js", host: "<bw_hostname>", referrer: "https://<bw_hostname>/"
`

**Comment by AlexKalopsia** [comment]
> 
> 
> I hit this issue as well, and thought it might be related to the others posted here.
> 
> However, I conflated the distribution update with a change to my server's nginx.conf, which caused the reverse proxy to fail. Sorry for the confusion.

@Ventrue would you mind sharing your nginx configuration? Experiencing the same problem here

**Comment by Profited** [comment]
It seems to be working after I did a full reinstall action with the migrated files. If you guys want I can share anything with you still

**Comment by AlexKalopsia** [comment]
@Profited what do you exactly mean with a full reinstall? I am running bw in a docker container and I am still experiencing this issue :(

**Comment by Profited** [comment]
@AlexKalopsia I don't recommend running it on a docker container as it would cause some problems. I told my users to backup their credentials and just did a full reinstall.
