### ISSUE TITLE
Web GUI throws login error: mobile/desktop app fine

### ISSUE THREAD

**Issue by abctaylor** [bitwarden/server#504]
**Problem**
Web GUI fails on valid login only from a web browser (incl. Bitwarden plugins) - _Windows desktop/iOS app is fine_. This makes it bizarre.

**Details**
Logging in via the iPhone app to the server works fine. Same for Desktop app. However when going through a web browser - e.g. Chrome or mobile iOS - the following is presented:

![image](https://user-images.githubusercontent.com/30197206/58596647-c71a9e00-826c-11e9-8305-c9f1b725f0f5.png)

Example of desktop app working fine:
![image](https://user-images.githubusercontent.com/30197206/58596982-f7af0780-826d-11e9-9e80-59384b38f1c8.png)

**Things tried**
- checked link to external mssql server is fine
- checked login to mssql server from SSMS works fine; can see tables
- created test password on desktop app and it successfully reflects on iOS app (network -> bitwarden -> db link is fine)
- restarted the VM running Bitwarden
- ./bitwarden.sh stop
- ./bitwarden.sh start
- ./bitwarden.sh update

**Helpful messages or logs**
*From nginx:*
*Server IP of a general load balancer (handling many web apps incl. this) is 10.1.7.1 on the network, URL is passwords.example.com for the sake of my post*

2019/05/29 22:36:11 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.1.7.1, server: passwords.example.com, request: "HEAD / HTTP/1.1", upstream: "http://172.19.0.8:5000/", host: "localhost"
2019/05/29 22:39:42 [warn] 29#29: *641 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp/1/00/0000000001 while reading upstream, client: 10.1.7.1, server: passwords.example.com, request: "GET /app/vendor.bbd65ec7501159b30189.js HTTP/1.1", upstream: "http://172.19.0.8:5000/app/vendor.bbd65ec7501159b30189.js", host: "passwords.example.com", referrer: "https://passwords.example.com/"
2019/05/29 22:41:25 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.1.7.1, server: passwords.example.com, request: "HEAD / HTTP/1.1", upstream: "http://172.20.0.5:5000/", host: "localhost"
2019/05/29 22:43:41 [error] 29#29: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 10.1.7.1, server: passwords.example.com, request: "HEAD / HTTP/1.1", upstream: "http://172.21.0.8:5000/", host: "localhost"
2019/05/29 22:43:43 [error] 29#29: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 10.1.7.1, server: passwords.example.com, request: "HEAD / HTTP/1.1", upstream: "http://172.21.0.8:5000/", host: "localhost"
2019/05/29 22:43:45 [error] 29#29: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 10.1.7.1, server: passwords.example.com, request: "HEAD / HTTP/1.1", upstream: "http://172.21.0.8:5000/", host: "localhost"

**Environment**
Standard docker setup with mssql outsourced to my own production database server

**Comment by abctaylor** [comment]
Note: deliberately entering an invalid password will result in:

![image](https://user-images.githubusercontent.com/30197206/58597210-d3075f80-826e-11e9-98ec-24eaa97d2472.png)

so the link is definitely in-tact between everything: it seems opening the front-end application through nginx is causing issues.

**Comment by abctaylor** [comment]
Loading a completely fresh Bitwarden image and only copying over the config (which has never changed for well over a month while working well) also failed. Killed all running docker images to be safe.

**Comment by abctaylor** [comment]
If running with `docker-compose` to see output, I get the following the moment I click "login" on the website in a browser:

bitwarden-web    |       Request finished in 0.1218ms 200 text/html
bitwarden-api    | info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
bitwarden-api    |       Request starting HTTP/1.0 POST http://passwords.example.com/accounts/prelogin application/json; charset=utf-8 35
bitwarden-api    | info: Microsoft.AspNetCore.Cors.Infrastructure.CorsService[4]
bitwarden-api    |       Policy execution successful.
bitwarden-api    | info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
bitwarden-api    |       Route matched with {action = "PostPrelogin", controller = "Accounts"}. Executing action Bit.Api.Controllers.AccountsController.PostPrelogin (Api)
bitwarden-api    | info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
bitwarden-api    |       Executing action method Bit.Api.Controllers.AccountsController.PostPrelogin (Api) with arguments (Bit.Core.Models.Api.PreloginRequestModel) - Validation state: Valid
bitwarden-api    | info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
bitwarden-api    |       Executed action method Bit.Api.Controllers.AccountsController.PostPrelogin (Api), returned result Microsoft.AspNetCore.Mvc.ObjectResult in 3.7084ms.
bitwarden-api    | info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
bitwarden-api    |       Executing ObjectResult, writing value of type 'Bit.Core.Models.Api.PreloginResponseModel'.
bitwarden-api    | info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
bitwarden-api    |       Executed action Bit.Api.Controllers.AccountsController.PostPrelogin (Api) in 6.1661ms
bitwarden-api    | info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
bitwarden-api    |       Request finished in 6.5902ms 200 application/json; charset=utf-8

**Doesn't seem to show anything weird.**
*Those last two lines just repeat forever as the server polls itself*

**Comment by kspearrin** [comment]
What on-set this? Has it ever worked in the past? I am not sure at the moment. Sounds really weird. This is only a problem on an iOS device with the web vault? What version of iOS?

**Comment by abctaylor** [comment]
> What on-set this?

It turns out, an AD account Bitwarden was using to log into Exchange had the default password policy for the domain - expire after three months. The password expired the day I had these issues. Embarrassing to say, but somewhat hard to find.

This is why Bitwarden was able to say that the password was invalid if it was entered incorrectly. However if correct, it would proceed to email the 2FA code and hit an authentication error with Exchange.

**Below - the embarrassingly simple fix for the SMTP account in AD:**
![image](https://user-images.githubusercontent.com/30197206/58742898-09381100-8420-11e9-9645-47d58d48171f.png)

Mystery solved.
