### ISSUE TITLE
How to suggest new Global Equivalent Domains?

### ISSUE THREAD

**Issue by rogersachan** [bitwarden/server#508]
I have amassed a number of custom equivalent domains that I think should be added to the global list. These are sites with high alexa ranks like protonmail/protonvpn, epicgames/unreal, and minecraft. I read in an earlier issue that wiki domains would be implemented but google search does not surface this.

**Comment by kspearrin** [comment]
You can just post them as an issue here. This is not other formal way of suggesting them.
