### ISSUE TITLE
Internal IP in new Device mail

### ISSUE THREAD

**Issue by RR3US** [bitwarden/server#509]
I have my self-hosted Bitwarden instnance behind a NGINX reversed proxy, and in the email is see the IP of the reversed proxy. What settings do i need to add to my nginx reversed config to log the wan ip in the mail?
I tried the following nginx config:

proxy_set_header Host $host;
real_ip_header X-Real-IP;
real_ip_recursive on;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;

Example:
![image](https://user-images.githubusercontent.com/51372890/58885831-294b2700-86e3-11e9-8128-aad76beab616.png)

**Comment by dieterblocher** [comment]
Hi, all you have to do is to adopt the config.yaml file at the least few lines:

```yaml
# Defines "real" IPs in nginx.conf. Useful for defining proxy servers that forward the 
# client IP address.
# Learn more: https://nginx.org/en/docs/http/ngx_http_realip_module.html
real_ips:
- 192.168.1.100 
- 192.168.1.0/24
```

192.168.1.100 is the ip address of the nginx reverse proxy. 
192.168.1.0/24 is the network where the reverse proxy lives.

Hope that will work for you.

Cheers,
Dieter

**Comment by RR3US** [comment]
Worked like a charm! Thank you!

**Comment by JurgenKuyper** [comment]
hey, 
Sorry to open this issue again, but I cannot seem to find the config.yml in my nginx webserver. do you might know where it is located?
Kind regards,
Jurgen

**Comment by kyberorg** [comment]
@JurgenKuyper  it is bwdata/config.yml (part of Bitwarden installation)
