### ISSUE TITLE
Unable to set up dev env

### ISSUE THREAD

**Issue by Wengiel31** [bitwarden/server#5098]
### Steps To Reproduce

Follow the instructions on https://contributing.bitwarden.com

### Expected Result

-

### Actual Result

When trying to set up dev env by following the steps on the contributing page, after logging in I get the following error in the Www-Authenticate response header of the /api/accounts/profile request: 
Bearer error="invalid_token", error_description="The issuer 'http://localhost' is invalid"

After which I get logged out.

### Build Version

Newest

### Environment

Self-Hosted

### Issue Tracking Info

- [ ] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by Biradar007** [comment]
Hey @Wengiel31,
I’d like to work on this issue. Could you please assign it to me? Let me know if there are any specific requirements or guidelines I should follow while implementing the solution.

Thank you!

**Comment by SergeantConfused** [comment]
Hello @Wengiel31,

Could you please clarify what steps you've completed successfully, and at which exact step you're encountering that error message?

Thank you in advance,
