### ISSUE TITLE
Dev Env Information

### ISSUE THREAD

**Issue by 552062283** [bitwarden/server#510]
I am wondering if there is a more detailed dev environment setup of the server as the current instructions in the readme are lacking in detail. 

I notice there is a lot of fields to fill in SECRETS in various appsetting files however am unsure where I am supposed to find these.

**Comment by kspearrin** [comment]
There are several Azure dependencies for certain features, however, you can sub them for Noop services if you are just trying to get things running.

Let me know which ones you are having trouble understanding.

**Comment by djsmith85** [comment]
@552062283 I know this is a really old issue but thanks to @eliykat we now have an awesome revised guide in the [SETUP.md](../blob/master/SETUP.md).

Please close this issue
