### ISSUE TITLE
[BUG] 2FA Email does not change when I change my email

### ISSUE THREAD

**Issue by npmSteven** [bitwarden/server#513]
Hello,

I am not sure if this is an issue, but I think it is. So the issue is, I have a 2FA email setup with let's say an email called example@domain.com, but I want to change the email of my account to example1@domain.com, So I change my email when I go to log in, I do not receive the email on the account changed the email to, I get it on the old email example@domain.com.

I do not think this should be the case, the system should see that the email has changed and change it on the 2FA for email, or at least notify me that the old email will still be used for 2FA.

Thanks
Steven

**Comment by kspearrin** [comment]
This is by design since a user can configure a different 2fa email than the email that they use to log in.

**Comment by dere** [comment]
@kspearrin Then perhaps it's not a bug per se, but maybe asking the user if they'd also like to change their 2FA email address would be a UX improvement?
