### ISSUE TITLE
[Selfhosted] "Organization is disabled" (expired) on enterprise plan

### ISSUE THREAD

**Issue by papiermumie** [bitwarden/server#515]
Version: 2.10.1
Environment: selfhosted
Licence: Enterprise (monthly)

Last week we had the problem that bitwarden says our "Organization is disabled" caused by an expired license. 

Is there a chance to get a notification for licence renewal before disabling the organization or any kind of self renewal?

I made an appointment in my calendar for the licence renewal but this seems not to be rock solid :)

Best regards from Germany
Sascha

**Comment by kspearrin** [comment]
The organization billing contact should get an email 2 weeks prior to your license renewal date. The license stays valid for several weeks after as a grace period.

**Comment by sjoswig** [comment]
Hi Kyle,

expire date: 07th of june
disabled organization: 07th of june

Can't confirm any grace period. 
Further we could not find any mail. I will write you a private message with details.

Sascha

**Comment by kspearrin** [comment]
The expiration date includes the grace period. If it expired in June, your bill was likely paid in April.

**Comment by sjoswig** [comment]
Hi Kyle, thanks for your information. Trying to find any reminder in my logs (filterd by 'bitwarden.com') but can't find anything. To verify this can you please give me the 'subject' or a special 'from' to filter april and may mail logs?

Sascha

**Comment by kspearrin** [comment]
@sjoswig See https://github.com/bitwarden/server/blob/master/src/Core/Services/Implementations/HandlebarsMailService.cs#L221

It goes to the "Billing email" associated with the org.

**Comment by sjoswig** [comment]
Grepped through all the logs but I'm only able to find mails with "New Device Logged In From". No mails containing "Subscription" or "InvoiceUpcoming". I keep on with appointment based trigger :)

**Comment by kspearrin** [comment]
Is your billing email set to the appropriate inbox?

**Comment by sjoswig** [comment]
The billing email is set under "my organization" in selfhosted environment and on bitwarden.com for the official licencing part. Same address in both environments.

Or are we talking about different things?

**Comment by kspearrin** [comment]
Yes, it goes to the "Billing Email" set under "My Organization" on vault.bitwarden.com.

The subject is "Your Subscription Will Renew Soon".

**Comment by sjoswig** [comment]
See https://github.com/bitwarden/server/issues/515#issuecomment-502666540

**Comment by westende** [comment]
We also experienced this problem. Even after updating the license file. Logging out and logging in again into the web interface resolved the issue.
