### ISSUE TITLE
[Selfhosted] Change NGINX configuration and save permanently

### ISSUE THREAD

**Issue by valeriones** [bitwarden/server#519]
Hi all, we've installed Bitwarden using Docker (On-premises Hosting), all work fine.
But now we'd like to change nginx configuration and save permanently all changes; How can We do this?

Version: 2.10.1
Environment: selfhosted

**Comment by kspearrin** [comment]
Set `generate_nginx_config` to false in `./bwdata/config.yml`.

```
# 
# Auto-generate the `./nginx/default.conf` file.
# WARNING: Disabling generated config files can break future updates. You will be
# responsible for maintaining this config file.
# Template: https://github.com/bitwarden/server/blob/master/util/Setup/Templates/NginxConfig.hbs
generate_nginx_config: false
```
