### ISSUE TITLE
WARNING: Network docker_default not found.

### ISSUE THREAD

**Issue by TrackRunny** [bitwarden/server#522]
Hello, When I ever I try to run the bitwarden server I get this error. Also I am getting this error on docker which I don't know how to fix. I tried doing many things on the internet, but none of them are working. Any help with this?

`WARNING: Network docker_default not found.`
`Couldn’t connect to Docker daemon at http+docker://localhost – is it running?`

![image](https://user-images.githubusercontent.com/45835198/60410031-05142600-9b7b-11e9-90f4-a3510bc94d95.png)

**Comment by kspearrin** [comment]
This is a normal warning for docker compose since it creates the `docker_default` network each time.

**Comment by TrackRunny** [comment]
Yeah, then it does not work though. The website for my Bitwarden hosting won't load. @kspearrin

**Comment by Cheatyx** [comment]
you found a solution?

**Comment by HoseinMohamadi68** [comment]
for resolve this problem enter following command :
systemctl restart docker.service
