### ISSUE TITLE
Docs on Hosting without docker?

### ISSUE THREAD

**Issue by MrMEEE** [bitwarden/server#523]
Hi

Any documentation on how to setup bitwarden without using docker??

**Comment by kspearrin** [comment]
Hosting without docker is not officially supported. There is no documentation on hosting it this way.

**Comment by MrMEEE** [comment]
When I get it to run and packaged, will you be interested?

**Comment by kspearrin** [comment]
Sure. Please do share your efforts.

**Comment by MrMEEE** [comment]
Anywhere that I can get any hints?? Right now I have the web interface, the api, the identity and the admin interface running.. but when trying to create users in the admin interface I get a "Exception: Invalid licensing certificate."..

I have put in the licensing file from here: https://github.com/bitwarden/server/blob/master/src/Core/licensing.cer

But probably not the right one?

**Comment by sevillaarvin** [comment]
@MrMEEE Hey, have you hosted bitwarden without docker? I'm interested in this as well.

**Comment by MrMEEE** [comment]
https://github.com/MrMEEE/bitwarden_rs_rpm/blob/master/README.md

I did this:

https://github.com/MrMEEE/bitwarden_rs_rpm/blob/master/README.md

**Comment by sevillaarvin** [comment]
Oh nice, forgot about the rust implementation. Thank you!
