### ISSUE TITLE
Problem: Correct admin E-Mail address leaves a blank white page, wrong doesn't.

### ISSUE THREAD

**Issue by PT400C** [bitwarden/server#528]
Hey,

on my Bitwarden installation, using a valid E-Mail address (listed in the global env) for the admin panel login page shows a white page after pressing continue. When it's not valid, there is this string shown: `If a valid admin user with this email address exists, we've sent you an email with a secure link to log in.`

**Comment by kspearrin** [comment]
Sounds like maybe an error sending the email. What do the server logs show?

**Comment by PT400C** [comment]
@kspearrin There is a lot in there, I'll send a pastebin: https://pastebin.com/54hXBuyX

The time is also wrong as I noticed. It's 17:30 here, the log shows 15:30

**Comment by kspearrin** [comment]
Server time is always UTC

**Comment by PT400C** [comment]
So that's no problem, alright. I use LE-certs just that you know. May that be the problem? SSL is enabled in the config of bitwarden and also for nginx.

**Comment by kspearrin** [comment]
Maybe you need to install the LE CA certs.

To verify that it is a cert issue, you can try setting `globalSettings__mail__smtp__trustServer=true`

**Comment by PT400C** [comment]
Yes it's indeed a problem with the certs. With that line added, it works just fine.

How do I install the LetsEncrypt CA certs though?

**Comment by kspearrin** [comment]
Your mail server is using LE certs?

**Comment by PT400C** [comment]
Exactly. I use a LE cert for the mailserver.

**Comment by kspearrin** [comment]
You could try providing the LE CA cert to ./bwdata/ca-certificates. This will install the CA on the OS cert store.

**Comment by PT400C** [comment]
I'll close this as your workaround (globalSettings__mail__smtp__trustServer=true) works. Placing the core certificates of LE on the other hand doesn't.
