### ISSUE TITLE
Address family not supported by protocol: need to be able to edit nginx.conf permanently

### ISSUE THREAD

**Issue by gianks** [bitwarden/server#529]
Hi in our environment we decided to disable IPv6 and the nginx configuration is not allowing the service to start.
How can i nicely override the default nginx configuration file provided with the docker image of bitwarden?

**Comment by kspearrin** [comment]
You will need to edit ./bwdata/config.yml and then update `generate_nginx_config: false`. You can then make edits to nginx.conf without them being overwritten.

**Comment by gianks** [comment]
Hi, it worked flowlessly!
Thank you for the quick reply!





Il giorno gio 11 lug 2019 alle ore 21:08 Kyle Spearrin <
notifications@github.com> ha scritto:
