### ISSUE TITLE
LetsEncrypt Cloudflare DNS Verification

### ISSUE THREAD

**Issue by heywoodlh** [bitwarden/server#530]
Out of the box, `bwdata/scripts/run.sh` doesn't support using Cloudflare's DNS verification for LetsEncrypt -- obviously it just uses HTTP for verification. This doesn't work for me since I don't expose my Bitwarden instance to the WAN. So when I needed `certbot` to renew certs I had to temporarily expose ports 80/443 to the WAN until it renewed. It was super annoying because if a renewal came up and the ports weren't exposed it would just bring Bitwarden instance offline.

So I re-wrote `bwdata/scripts/run.sh` to use a different Certbot Docker container and use the proper arguments to use Cloudflare as the DNS authentication method.

Here's the `diff`:

```
$ diff run.sh bw-cloudflare-run.sh 
87,89c87,89
<             docker pull certbot/certbot
<             docker run -it --rm --name certbot -p 80:80 -v $OUTPUT_DIR/letsencrypt:/etc/letsencrypt/ certbot/certbot \
<                 certonly --standalone --noninteractive  --agree-tos --preferred-challenges http \
---
>             docker pull certbot/dns-cloudflare
>             docker run -it --rm --name certbot -p 80:80 -v ~/.cloudflare:/tmp/.cloudflare -v $OUTPUT_DIR/letsencrypt:/etc/letsencrypt/ certbot/dns-cloudflare \
>                 certonly --standalone --noninteractive --dns-cloudflare --dns-cloudflare-credentials /tmp/.cloudflare --agree-tos \
134c134
<         docker pull certbot/certbot
---
>         docker pull certbot/dns-cloudflare
136,137c136,137
<             -v $OUTPUT_DIR/letsencrypt:/etc/letsencrypt/ certbot/certbot \
<             renew --logs-dir /etc/letsencrypt/logs
---
>             -v $OUTPUT_DIR/letsencrypt:/etc/letsencrypt/ -v ~/.cloudflare:/tmp/.cloudflare certbot/dns-cloudflare \
>             renew --dns-cloudflare --dns-cloudflare-credentials /root/.cloudflare --logs-dir /etc/letsencrypt/logs
```

Obviously, this assumes that your credentials are placed in `~/.cloudflare` using the following format:

```
dns_cloudflare_email=[email]
dns_cloudflare_api_key=[API key]
```

I also had to modify my `bwdata/letsencrypt/renewal/*.conf` file with the following:

```
# renew_before_expiry = 30 days
version = 0.31.0
archive_dir = /etc/letsencrypt/archive/<omitted>
cert = /etc/letsencrypt/live/<omitted>/cert.pem
privkey = /etc/letsencrypt/live/<omitted>/privkey.pem
chain = /etc/letsencrypt/live/<omitted>/chain.pem
fullchain = /etc/letsencrypt/live/<omitted>/fullchain.pem

# Options used in the renewal process
[renewalparams]
authenticator = dns-cloudflare
logs_dir = /etc/letsencrypt/logs
account = <omitted>
pref_challs = http-01,
server = https://acme-v02.api.letsencrypt.org/directory
dns_cloudflare_credentials = /tmp/.cloudflare
```

I didn't make the code modular since I rewrote the script to only use Cloudflare authentication since that's all I need at the moment for my own personal use.

But I wanted to ask what the best way would be to add this to `run.sh` and what the best way would be to get `bitwarden.sh` to use the Cloudflare DNS method for renewing and generating LetsEncrypt certs.

Any guidance or suggestions on how to get this merged into the main project would be much appreciated! Or if this isn't a desired feature I would also like to know. But it definitely helps for me since I don't want my Bitwarden instance exposed to the world. 

I would be happy to submit a pull request after some guidance is offered on these things:
1. How should the commands be added to `bwdata/scripts/run.sh`? Again, my additions assume that Cloudflare will be the only method for verification, it doesn't have any if/then statements in case one doesn't want to use Cloudflare verification.
2. Where would it be best to store the Cloudflare credentials in `bwdata`? 
3. What would be the best way to get `bitwarden.sh` to know that Cloudflare should be the authentication method not the default?

Thanks for any help!

Attached is a copy of the modified script.

[bw-cloudflare-run.sh.gz](https://github.com/bitwarden/server/files/3390681/bw-cloudflare-run.sh.gz)

**Comment by kspearrin** [comment]
If users need custom certbot implementations like this, I would suggest that they just write their own certbot management script and avoid using Bitwarden's altogether (go the "bring your own cert" route when setting up). We just support the basic LE registration and renewal that most users need. It's difficult to try to support all use cases like this.

**Comment by heywoodlh** [comment]
Sure, that makes sense.

I guess a natural follow-up is what the recommended Bitwarden update process should be with a custom run.sh script? Because each update could wipe it out, right?

At the moment I have a cron job that updates and then one that replaces the updated run.sh with a copy of my modified run.sh before restarting Bitwarden. Is there a better method you would recommend?

**Comment by kspearrin** [comment]
It is not recommended to change run.sh for this reason. I am referring to writing your own separate certbot scripting.

**Comment by heywoodlh** [comment]
So if I don't change run.sh, where should I modify the Certbot certificate deployment method?

**Comment by heywoodlh** [comment]
Ah, wait, I understand now. I didn't know this section of the documentation existed:

<img width="890" alt="image" src="https://user-images.githubusercontent.com/18178614/61393844-5d546300-a8b1-11e9-92d6-9f5ddc4a6eda.png">
