### ISSUE TITLE
Network issue with new self-host install...

### ISSUE THREAD

**Issue by stsanford** [bitwarden/server#533]
Hi, I had posted this on the Bitwarden forums, but realized maybe I'm looking in the wrong spot... Hope you can help me through this... 
New to this, and trying to setup a self-hosted instance. Docker finally got installed and allowed me to run -install and it finished… mostly. I am getting the following and wonder if there is a way to correct.

Using default tag: latest
latest: Pulling from certbot/certbot
Digest: sha256:ec4383b768b6a162889adcdce2d60cb4c760d2fa48287a354c0182c5e2330fed
Status: Image is up to date for certbot/certbot:latest
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: driver failed programming external
connectivity on endpoint certbot (08dd6ea8e06ecff09e477c6d36c6b8f579b893c3817965a53ece1bc50cc0a301): Error starting user
land proxy: Bind for 0.0.0.0:80: unexpected error Permission denied.
Creating network “docker_default” with the default driver
Creating bitwarden-identity … done
Creating bitwarden-icons … done
Creating bitwarden-mssql … done
Creating bitwarden-notifications … done
Creating bitwarden-attachments … done
Creating bitwarden-api … done
Creating bitwarden-web … done
Creating bitwarden-admin … done
Creating bitwarden-nginx … error

ERROR: for bitwarden-nginx Cannot start service nginx: driver failed programming external connectivity on endpoint bitw
arden-nginx (d1fcc930b70d5a5d912b25077f09b6ec6d80f8a5d5cf5c58b517c637337d3c59): Error starting userland proxy: Bind for
0.0.0.0:80: unexpected error Permission denied

ERROR: for nginx Cannot start service nginx: driver failed programming external connectivity on endpoint bitwarden-ngin
x (d1fcc930b70d5a5d912b25077f09b6ec6d80f8a5d5cf5c58b517c637337d3c59): Error starting userland proxy: Bind for 0.0.0.0:80
: unexpected error Permission denied
ERROR: Encountered errors while bringing up the project.
Total reclaimed space: 0B
1.30.4: Pulling from bitwarden/setup
Digest: sha256:d31e966681f1c0a44773eb4a5dd0d79ececacf46bc67cee6a0dc3e5112b57778
Status: Image is up to date for bitwarden/setup:1.30.4

Thanks for any help you can provide!

**Comment by kspearrin** [comment]
> C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: driver failed programming external

Sounds like something is wrong with your docker installation. Does a simple hello world image work?

https://hub.docker.com/_/hello-world

**Comment by stsanford** [comment]
When I run the cmd docker pull hello-world
I do get a download of the image, is that what you're talking about? Sorry, this is my first experience with Docker.

**Comment by kspearrin** [comment]
`docker run hello-world`

**Comment by stsanford** [comment]
Think it worked:
PS C:\Windows\system32> docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
    (amd64)
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://hub.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/get-started/

**Comment by greecemunky** [comment]
> Bind for 0.0.0.0:80: unexpected error Permission denied.

"Permission denied" when attempting to bind to a port can be due to another process already listening on the same port.

From a Command Prompt window, run:
`netstat -ano | find "LISTENING" | find ":80 "`

If no output is returned, then nothing else is listening on it and it could be another cause.

**Comment by stsanford** [comment]
Thank you. I can't see exactly what is using 80, but something definitely is... I'm going to try moving it onto a different computer and will see if I can have more success. Thank you for the advice!

**Comment by greecemunky** [comment]
The last column of the output is the Process ID (PID), so if you open Task Manager and go its Details or Processes tab, you should be able to determine the process.  You may also be able to right-click the process and "Go to Service(s)" to pinpoint the culprit.

**Comment by tukusejssirs** [comment]
In my case, port 80 is used by Apache (`httpd` service; I am using CentOS 7). Is there a way to change the port or or make both `httpd` and Bitwarden use the same port?

**Comment by felix-d-git** [comment]
I am having the same problem. Running apache on (80, 443). Starting bitwarden using ./bitwarden.sh start throws an error, that address is already in use. what am I doing wrong?
