### ISSUE TITLE
Memory requirements for self hosted are more than 2 Gig

### ISSUE THREAD

**Issue by pwd3** [bitwarden/server#534]
When doing a trial deployment of Bitwarden self-hosted I built a KVM VM on Centos with
Docker and deployed without problem but when I tried to run I got very slow response and exceptions. As soon as I increased the memory from 2 Gig to 8 Gig, Bitwarden worked like  charm. I had misread MS Sql as mysql (and therefor assumed that the 2 Gig was a good value. The instructions for self-hosting should be changed to at least 4 Gig of memory (until Postgresql is supported, I run VMs with 1 Gig and live Postgres system all the time). 

(I am not sure where to file this so I put it here in the core project)

**Comment by kspearrin** [comment]
I have been able to deploy this on Ubuntu VMs with 2GB of ram, which is what MSSQL lists as its minimum requirements.

See https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-2017&pivots=cs1-bash#requirements

I am not sure why the same would not work for you.

**Comment by pwd3** [comment]
I had imported a rather large set of items from another password manager
Not sure but it ran without error with > 2 Gig.

On our product when using MSSQL with a fair amout of stored procedures
we see something like the same thing, you can start up with 2 Gig but trying
to do anything much will bog down and stop.


--
This email, and any files transmitted with it, are confidential
and intended solely for the use of the individual or entity to
whom they are addressed.  If you have received this email in error,
please advise postmaster@mdtsoft.com <mailto:postmaster@mdtsoft.com>.

3480 Preston Ridge Road
Suite 450
Alpharetta, GA 30005

Philip W. Dalrymple III <pwd@mdtsoft.com>
MDT Software - Automation Management Company
+1 678 297 1001
Fax +1 678 297 1003

________________________________________

**Comment by ML-Marco** [comment]
It is inscrutable why a simple application like this needs more than 512 MB of memory. There must have been made some very wrong decisions on which software is used.
