### ISSUE TITLE
New user, change usertype to owner, needs to logout before permissions given

### ISSUE THREAD

**Issue by durd** [bitwarden/server#536]
Hi,

We are running a completely new Enterprise setup and noticed that when a new user (User type) is changed to Owner type with access to all collections, the user in question needs to logout before seeing all the items. Menu access is given however.  
There is only the waiting icon rolling, Firefox Devtools tells us that the json to be downloaded is 404.

When trying to replicate this with the same user, it is not repeatable and works perfectly. So probably has to be an entirely new user.

Thanks!

**Comment by durd** [comment]
Just recreated this by going User -> Owner (as above) -> User (Logout to update permission) -> Admin.

**Comment by kspearrin** [comment]
This is a known issue at the moment due to the way org types/roles are propagated to users via JWT token. The JWT token refreshes every <= 1 hour. So, currently, user role changes may not update for a user with an active session for up to 1 hour or if they log out and back in.
