### ISSUE TITLE
Removing an item from all collections does not put item in Default collection

### ISSUE THREAD

**Issue by durd** [bitwarden/server#537]
Hi,

New to the Enterprise version, we noticed that if an item is removed from all assigned Collections, it is moved to an Owner/Admin-only handled Unassigned collection.  
This is very confusing, and I'm sure it will be prone to errors and owner/admin involvement.

Expected behavior would be to have it moved to the Default collection, else why have a default.

Thanks!

**Comment by kspearrin** [comment]
The default collection has no special meaning. It's just created so that you have a collection ready after organization creation. It is delectable.

If an item is orphaned it goes into the "Unassigned" grouping.
