### ISSUE TITLE
unable to check update version 

### ISSUE THREAD

**Issue by martinorob** [bitwarden/server#540]
Hi, 
I know that I have to use 
./bitwarden.sh updateself
./bitwarden.sh update

to update my bitwarden on docker.
But I need to only check if an updated version exist, then notify me and then manually update.
I read on GitHub and googled it but I can't find any way.

May some one know how I can accomplish this?

thanks

**Comment by kspearrin** [comment]
You'd have to check dockerhub or github releases.

**Comment by martinorob** [comment]
Thanks @kspearrin su you give me some link where i can find nel to create a cromato script? Thank you a lot

**Comment by kspearrin** [comment]
https://hub.docker.com/v2/repositories/bitwarden/api/tags/

https://yourdomain.com/api/version

**Comment by martinorob** [comment]
@kspearrin thank you!

**Comment by martinorob** [comment]
for the community this is my script:

```
#!/bin/bash
current=$(curl -s https://my.domain.com/api/version | jq .Version)
last=$(curl -s https://hub.docker.com/v2/repositories/bitwarden/api/tags/ |jq '."results"[]["name"]' | sed -n '2p')
if [ "$current" != "$last" ]
then
   	/volume1/docker/bitwarden.sh updateself && /volume1/docker/bitwarden.sh update 
fi
```
