### ISSUE TITLE
exposed password report error

### ISSUE THREAD

**Issue by martinorob** [bitwarden/server#541]
Hi,
when I click on "submit" on the exposed password report page,
I've and error sending the report.

i have only this log

nginx/access.log <==
172.18.0.1 - - [30/Jul/2019:15:52:28 +0000] "GET /api/hibp/breach?username=myusername HTTP/1.1" 400 177 "https://my.domain.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15" "127.0.0.1"
172.18.0.1 - - [30/Jul/2019:15:52:30 +0000] "POST /notifications/hub?id=MYID HTTP/1.1" 200 0 "https://my.domain.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15" "127.0.0.1"
127.0.0.1 - - [30/Jul/2019:15:52:41 +0000] "GET /alive HTTP/1.1" 200 5 "-" "curl/7.52.1" "-"

how I can troubleshooting more?
Thanks

1.31.1

**Comment by kspearrin** [comment]
That doesn't look like the exposed password report to me. Is this the data breach report? Did you obtain an API key from HIBP?

**Comment by martinorob** [comment]
That is! Thank you
