### ISSUE TITLE
User not added to organization when user completes registration on second try

### ISSUE THREAD

**Issue by vxmn** [bitwarden/server#544]
I used the AD sync to invite new users to join an organization. When the user follows the link and creates an account, the user gets added to the organization. The admin just has to confirm the user again. Every seems to be fine.

However, if the invited user opens the invitation link, closes the browser and decides to create the account later, he is able to create a new account using the invitation link. His status in the organization stays as "invited". When I choose to resend the invitation, he will be added to the organization after clicking the link in the mail and logging in to his now existing vault.

Is it possible, that the organization assignment gets lost after visiting the invitation link without performing any action?

**Comment by kspearrin** [comment]
The user has to create the account in the same session as when they clicked the link. If they create their account outside of that session, they would need to re-click the link and log in with the existing account to accept the invitation.

**Comment by djsmith85** [comment]
Hi @vxmn, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
