### ISSUE TITLE
Can't change email on self-hosted install

### ISSUE THREAD

**Issue by ChrisShire** [bitwarden/server#547]
I was wondering if it is possible to change the admin email address on my self hosted install? When I try to it update it an error notification pops up saying "An Unhandled Server Error has Occured."

Has anyone got any ideas? I was worried as it's the admin account, so I'm not sure if I can just recreate a new account as it won't necessarily be an admin one...?

Any help gratefully received, thanks!

**Comment by kspearrin** [comment]
What is the server error? Look in ./bwdata/logs/Api

**Comment by ChrisShire** [comment]
Just [information] messages stating that it is starting and finishing a job called "AliveJob", no error. I couldn't find an error in the other log files in the folder either.

**Comment by kspearrin** [comment]
Are you able to receive any mail from your server? Try doing a password hint action or something that spawns an email.

**Comment by ChrisShire** [comment]
That did it! I changed my smtp server password and didn't update it in Bitwarden. D'oh!
Thank you so much for the help and the most brilliant and useful self-hosted software I run!
