### ISSUE TITLE
docker-compose error

### ISSUE THREAD

**Issue by derritter88** [bitwarden/server#551]
According to the manual I use following commands for update:
```
./bitwarden.sh updateself 
./bitwarden.sh update
```

The first one works without any issue but for the second one I get following error:

```
ERROR: Version in "/opt/bitwarden/bwdata/docker/docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

Everytime the version is set to "3" and this is causing the issue.
If I modify the file to "2" again I can at least start Bitwarden.
If I lower it to "1" I would also get an error message.

**Comment by jackkdev** [comment]
Hi @derritter88 whats your version of docker-compose, and have you tried updating it? This commonly happens to me and the root cause is because I am using an older version.

**Comment by kspearrin** [comment]
Looks like your compose version is outdated. Try updating.

**Comment by derritter88** [comment]
Hi there, thanks for the comments - it solved my problem as I had installed the regular repostiory version of it.
After upgrading it to the newest one the error dissappeared.
