### ISSUE TITLE
Version history of updated entries disappeared

### ISSUE THREAD

**Issue by pbinksma** [bitwarden/server#552]
When I update an entry (e.g. change username or password), I can see that the "update"-timestamp has changed, but I cannot find anymore the version-number nor do I see a way to get back to an old version of the entry. I am sure that this worked earlier this year. It seem to be the same behavior in the Browser-Addon (Firefox) as well as with the webpage.
![image](https://user-images.githubusercontent.com/1667719/63450393-30601680-c442-11e9-9c13-6457a2da1164.png)
Do I miss something or is this a bug?

Best regards
Patrick

**Comment by kspearrin** [comment]
There is only history on the password field if it changes.

**Comment by pbinksma** [comment]
Oh yes. Thank you. You are absolutely right!
