### ISSUE TITLE
Admin users page has no button for adding users

### ISSUE THREAD

**Issue by jakubgs** [bitwarden/server#554]
I've installed BitWarden and all containers are running and healthy, but when I login into the Admin panel and visit the Users section I see no buttons for adding/inviting users:
![bitwarden_users](https://user-images.githubusercontent.com/2212681/63534263-c3e62580-c4dc-11e9-97b4-8489f79294bc.png)
Am I missing something? How can I add new users?

**Comment by kspearrin** [comment]
This is the system administrator panel. Users register themselves through the application.

**Comment by jakubgs** [comment]
Okay, so if the public registration is disable using `globalSettings__disableUserRegistration` does that also block registration through the App?
Does this mean I should open registration first, let people open account, and then close it?

**Comment by jakubgs** [comment]
Yep, if registration is disabled I cannot register through the app.
So there is no way to restrict who can actually register in BitWarden while registration is open?
Could I for example restrict registration to a specific email domain?

**Comment by kspearrin** [comment]
If you have an organization, users that are invited to the organization account can still register through their invitation link. Otherwise, you have to open registration.

**Comment by jakubgs** [comment]
Oh, that makes more sense.
Then I have to figure out how to get the organization license file to create it.
