### ISSUE TITLE
Can't connect to my self hosted server after update

### ISSUE THREAD

**Issue by Catskan** [bitwarden/server#558]
Hi guys,

After the last update (bitwarden.sh updateself  && update), I can"t connect to my web vault.
When I enter my credentials, I have the message "An handled server error ..."
![image](https://user-images.githubusercontent.com/17289964/64109160-06322100-cd7f-11e9-8470-0e4905f74922.png)

My bitwarden logs (notifications & identity) : 
[Bitwarden logs.zip](https://github.com/bitwarden/server/files/3565686/Bitwarden.logs.zip)

My certificat is ok because it was worked after the update.

In the ssl folder I have : 
- folder "mydomain.fr"
                  - ca.crt
                  - certificate.crt
                  - private.key

In the ca-certificate : 
 - ca.crt
 - certificate.crt
 - private.key

Bitwarden.sh script : 

Creating network "docker_default" with the default driver
Creating bitwarden-notifications ... done
Creating bitwarden-mssql         ... done
Creating bitwarden-events        ... done
Creating bitwarden-api           ... done
Creating bitwarden-attachments   ... done
Creating bitwarden-identity      ... done
Creating bitwarden-icons         ... done
Creating bitwarden-web           ... done
Creating bitwarden-admin         ... done
Creating bitwarden-nginx         ... done
Total reclaimed space: 0B
1.31.1: Pulling from bitwarden/setup
Digest: sha256:846d5c1fd83dc00f0bd2994c1a6f0cea4d246200a7311e01f3bf103078b92a92
Status: Image is up to date for bitwarden/setup:1.31.1
Updating certificates in /etc/ssl/certs...
2 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.

Bitwarden is up and running!

visit https://vault.mapn.fr:4343
to update, run `./bitwarden.sh updateself` and then `./bitwarden.sh update`

Pausing 60 seconds for database to come online. Please wait...
1.31.1: Pulling from bitwarden/setup
Digest: sha256:846d5c1fd83dc00f0bd2994c1a6f0cea4d246200a7311e01f3bf103078b92a92
Status: Image is up to date for bitwarden/setup:1.31.1
Updating certificates in /etc/ssl/certs...
2 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.

Migrating database.
Migration successful.
Database update complete

Thanks you in advance for your help.

Regards,

PS : My server is on Linux.

**Comment by kspearrin** [comment]
What is the status of `docker ps`?

**Comment by Catskan** [comment]
My docker ps : 

> CONTAINER ID        IMAGE                            COMMAND                  CR                                                                                                                                                                                                                                             EATED             STATUS                            PORTS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     NAMES
990a635f9ce7        bitwarden/nginx:1.31.1           "/entrypoint.sh"         4                                                                                                                                                                                                                                              hours ago         Up 4 hours (healthy)              80/tcp, 8080/tcp, 0.0.0.0:43                                                                                                                                                                                                                                             43->8443/tcp                                                                                                                                                                                                                                                                                                                     bitwarden-nginx
8ceab055b5e1        bitwarden/admin:1.31.1           "/entrypoint.sh"         4                                                                                                                                                                                                                                              hours ago         Up 4 hours (healthy)              5000/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  bitwarden-admin
b17a5b851121        bitwarden/icons:1.31.1           "/entrypoint.sh"         4                                                                                                                                                                                                                                              hours ago         Up 4 hours (healthy)              5000/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  bitwarden-icons
ec90fc3f4cd3        bitwarden/web:2.11.0             "/entrypoint.sh"         4                                                                                                                                                                                                                                              hours ago         Up 4 hours (healthy)              5000/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  bitwarden-web
2f2de1a2cb74        bitwarden/events:1.31.1          "/entrypoint.sh"         4                                                                                                                                                                                                                                              hours ago         Up 4 hours (unhealthy)            5000/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  bitwarden-events
89cca4d53cf7        bitwarden/identity:1.31.1        "/entrypoint.sh"         4                                                                                                                                                                                                                                              hours ago         Restarting (139) 20 seconds ago                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             bitwarden-identity
3eaf994145bf        bitwarden/attachments:1.31.1     "/entrypoint.sh"         4                                                                                                                                                                                                                                              hours ago         Up 4 hours (healthy)              5000/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  bitwarden-attachments
02b60b6c1a73        bitwarden/api:1.31.1             "/entrypoint.sh"         4                                                                                                                                                                                                                                              hours ago         Up 4 hours (healthy)              5000/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  bitwarden-api
7ac061c280a0        bitwarden/notifications:1.31.1   "/entrypoint.sh"         4                                                                                                                                                                                                                                              hours ago         Up 4 hours (unhealthy)            5000/tcp                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  bitwarden-notifications
e97dd63b96ad        bitwarden/mssql:1.31.1           "/entrypoint.sh"         4                                                                                                                                                                                                                                              hours ago         Up 4 hours (unhealthy)            1433/tcp

**Comment by kspearrin** [comment]
Is this a Synology host?

**Comment by Catskan** [comment]
Yes, run with Docker official package

**Comment by kspearrin** [comment]
Seems like a duplicate of https://github.com/bitwarden/server/issues/555

**Comment by Catskan** [comment]
Hi,

Thanks. Finaly, I've downgraded Docker version to 17 and Bitwarden works now.

Regards,

Aurelien
