### ISSUE TITLE
Update setup 1.32

### ISSUE THREAD

**Issue by graeberit** [bitwarden/server#565]
After update Bitwarden 1.31.1 to 1.32 selfhosted.

i become this error: 

docker.io/bitwarden/setup:1.32.0
error: exec: "dotnet": executable file not found in $PATH

can somewhere help me?

**Comment by kspearrin** [comment]
Seems like the container is having a hard time resolving the path to dotnet runtime for whatever reason. How are you executing this?

**Comment by djsmith85** [comment]
Hi @graeberit , it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
