### ISSUE TITLE
Premium account on self hosted server

### ISSUE THREAD

**Issue by Yzord** [bitwarden/server#566]
Dear developers,

I have installed Bitwarden on my CentOS7 server and everything seems to work fine. I bought a premium license on Bitwarden website and imported it into my account on my own server. 

I have a few issues:

- When i do a databreach report i get the following error: An error occurred trying to load the report. Try again...
But when i try this on the Bitwarden website it works. What am i doing wrong?

- Why is there no storage integration on the self hosted version?

- I signed up for a free organization as i would expected to download a new json file for my self hosted version, but i cant find a license file for it. How do i use that?

**Comment by kspearrin** [comment]
Hi,

1. You need a API key from HaveIBeenPwned. It is set in the environment variables file. See https://www.troyhunt.com/authentication-and-the-have-i-been-pwned-api/

2. Not sure what you mean.

3. You need a families or enterprise license for on-prem organizations. See https://help.bitwarden.com/article/licensing-on-premise/

**Comment by Yzord** [comment]
1. of course, stupid of me
2. When i upgraded to premium on the Bitwarden vault i got 1GB of encrypted storage. But i can’t find this option for the self hosted version when i upgraded to premium
3. i have made a family organization, but i cannot seem to find the license i need to integrate it into my self-hosted version

**Comment by kspearrin** [comment]
2. You get unlimited storage with premium on your own server. You should be able to add attachments.

3. See here: https://help.bitwarden.com/article/licensing-on-premise/#organization-account-sharing

**Comment by Yzord** [comment]
Hmm, seems legit haha. Sorry for taking your time and thanks for the help.

**Comment by talentsystem** [comment]
If I self-host Bitwarden do I get user limitations like in the family plan that I can only add 4 users? or I can add as many users as I need to?
