### ISSUE TITLE
does not sync consistently

### ISSUE THREAD

**Issue by githubaccount11111** [bitwarden/server#568]
I don't know what this is caused by, but when I add a login to Bitwarden, then exit Firefox immediately or shortly after the data is not always saved. Is this by design or a bug? In any case, this is very frustrating. Does exiting the browser not trigger the sync? Does adding a new login not trigger a sync?

Additionally, at least on iOS, new passwords are not always synced to the client. Again, unreliable and frustrating (although less so, since I can still get access to the password my going into the app and manually triggering sync).

My FF is in permanent strict mode and does not save any site data or history, but that shouldn't stop extensions from syncing to the server, should it?

**Comment by kspearrin** [comment]
Data is saved to the server first, then the local device if that succeeds. All immediately. If you get a success message on saving, them the data was properly saved. Do you have a way to reproduce the problem reliably?
