### ISSUE TITLE
Build: identity publish - The "TransformWebConfig" task failed unexpectedly.

### ISSUE THREAD

**Issue by amenk** [bitwarden/server#576]
I tried building with dotnet 2.2 and 3.0 but I get 

"In process hosting is not supported for AspNetCoreModule. Change the AspNetCoreModule to at least AspNetCoreModuleV2."

Command:
     /src/Identity$ ./build.sh 

<details>
		/usr/share/dotnet/sdk/3.0.100/Sdks/Microsoft.NET.Sdk.Publish/targets/TransformTargets/Microsoft.NET.Sdk.Publish.TransformFiles.targets(50,5): error MSB4018: The "TransformWebConfig" task failed unexpectedly. [/home/develop/bitwarden-core/src/Identity/Identity.csproj]
		/usr/share/dotnet/sdk/3.0.100/Sdks/Microsoft.NET.Sdk.Publish/targets/TransformTargets/Microsoft.NET.Sdk.Publish.TransformFiles.targets(50,5): error MSB4018: System.Exception: In process hosting is not supported for AspNetCoreModule. Change the AspNetCoreModule to at least AspNetCoreModuleV2. [/home/develop/bitwarden-core/src/Identity/Identity.csproj]
		/usr/share/dotnet/sdk/3.0.100/Sdks/Microsoft.NET.Sdk.Publish/targets/TransformTargets/Microsoft.NET.Sdk.Publish.TransformFiles.targets(50,5): error MSB4018:    at Microsoft.NET.Sdk.Publish.Tasks.WebConfigTransform.SetAspNetCoreHostingModel(String aspNetCoreHostingModelValue, String aspNetCoreModuleName, XElement aspNetCoreElement) [/home/develop/bitwarden-core/src/Identity/Identity.csproj]
		/usr/share/dotnet/sdk/3.0.100/Sdks/Microsoft.NET.Sdk.Publish/targets/TransformTargets/Microsoft.NET.Sdk.Publish.TransformFiles.targets(50,5): error MSB4018:    at Microsoft.NET.Sdk.Publish.Tasks.WebConfigTransform.TransformAspNetCore(XElement aspNetCoreElement, String appName, Boolean configureForAzure, Boolean useAppHost, String extension, String aspNetCoreModuleName, String aspNetCoreHostingModelValue, String projectFullPath) [/home/develop/bitwarden-core/src/Identity/Identity.csproj]
		/usr/share/dotnet/sdk/3.0.100/Sdks/Microsoft.NET.Sdk.Publish/targets/TransformTargets/Microsoft.NET.Sdk.Publish.TransformFiles.targets(50,5): error MSB4018:    at Microsoft.NET.Sdk.Publish.Tasks.WebConfigTransform.Transform(XDocument webConfig, String appName, Boolean configureForAzure, Boolean useAppHost, String extension, String aspNetCoreModuleName, String aspNetCoreHostingModel, String environmentName, String projectFullPath) [/home/develop/bitwarden-core/src/Identity/Identity.csproj]
		/usr/share/dotnet/sdk/3.0.100/Sdks/Microsoft.NET.Sdk.Publish/targets/TransformTargets/Microsoft.NET.Sdk.Publish.TransformFiles.targets(50,5): error MSB4018:    at Microsoft.NET.Sdk.Publish.Tasks.TransformWebConfig.Execute() [/home/develop/bitwarden-core/src/Identity/Identity.csproj]
		/usr/share/dotnet/sdk/3.0.100/Sdks/Microsoft.NET.Sdk.Publish/targets/TransformTargets/Microsoft.NET.Sdk.Publish.TransformFiles.targets(50,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/home/develop/bitwarden-core/src/Identity/Identity.csproj]
		/usr/share/dotnet/sdk/3.0.100/Sdks/Microsoft.NET.Sdk.Publish/targets/TransformTargets/Microsoft.NET.Sdk.Publish.TransformFiles.targets(50,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/home/develop/bitwarden-core/src/Identity/Identity.csproj]
</details>

Is it incompatible with the latest dotnet 2.2 and 3.0 version?

**Comment by kspearrin** [comment]
I build and deploy with dotnetcore 2.2

**Comment by amenk** [comment]
Not working here with 2.2.402 as well -- any idea?

**Comment by amenk** [comment]
Build is working, but not publish...

**Comment by amenk** [comment]
Would it be correct to use AspNetCoreModuleV2 or disable inprocess hosting?

I am building on Ubuntu by the way.

**Comment by kspearrin** [comment]
I am not sure how or why you would need to do that. This repo builds on Ubuntu 18 in our CI without issue. See https://ci.appveyor.com/project/bitwarden/server/build/job/fw5y33vcjykj0cqt

**Comment by cromefire** [comment]
For me removing the `bin` and `obj` folders helped

**Comment by amenk** [comment]
We are building on Ubuntu 16 ... maybe that is the problem? We will try to upgrade...

**Comment by amenk** [comment]
@kspearrin We are wondering if we should do our builds on Ubuntu 18.04 or if you plan to switch to 20.04 soon?

**Comment by kspearrin** [comment]
WE are now using github actions, ubuntu-latest. See https://docs.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources

**Comment by amenk** [comment]
Not really relevant anymore, we kind of got a workaround; and also we are on 20.04 in the meantime :-)
