### ISSUE TITLE
mssql database backup in container fails with 'failed to create' error

### ISSUE THREAD

**Issue by wbjrpub** [bitwarden/server#583]
My bitwarden-mssql docker container shows this
2019-10-17 23:59:01.42 spid52      BackupDiskFile::CreateMedia: Backup device '/etc/bitwarden/mssql/backups/vault_FULL_20191017_235901.BAK' failed to create. Operating system error 2(The system cannot find the file specified.).

I checked that within the docker container I could create this file using 'touch',
and I can see this file appear on the host filesystem.
I tried running the backup command manually in the container, same error message.
chmod the backup directory to 777, no difference.
Am at a loss to why this is happening.
Running docker.io/bitwarden/mssql:1.32.0

**Comment by kspearrin** [comment]
What is the host OS?

**Comment by wbjrpub** [comment]
Host OS is Centos Linux, 3.10.0-957.12.2.el7.x86_64 #1 SMP
Docker version 1.13.1, build b2f74b2/1.13.1

**Comment by wbjrpub** [comment]
When I run a backup manually, but specify the output file to be container local,
it generates a backup OK.
I'm suspecting that its the xfs filesystem type of the /etc/bitwarden/mssql/backups volume
(although mssql 2017 says it supports xfs).
We've had similar issues with 32-bit nfs clients mounting an exported xfs directory.
Unfortunately I cannot test my theory by making an ext4 partition and using that
to mount /etc/bitwarden/mssql/backups on as I do not have spare diskspace :(

I could workaround it by doing the export to a temp file,
then moving it into the volume.
