### ISSUE TITLE
Invalid user error on install

### ISSUE THREAD

**Issue by ruppert92** [bitwarden/server#586]
I am getting the following error when trying to install bitwarden on Debian 10 w/ a 5.0 kernel.

1.32.0: Pulling from bitwarden/setup
9fc222b64b0a: Pull complete
f033c4f65cdb: Pull complete
7405f9e6a7ae: Pull complete
f4b7599512c4: Pull complete
97821114cca7: Pull complete
d4af2992c3be: Pull complete
1724ff73d932: Pull complete
53423e888769: Pull complete
cf9e1e658adf: Pull complete
Digest: sha256:e88f1611ff88c77a6255c49189ac3c965aaa3576fa6980ba54f2be10a96907b5
Status: Downloaded newer image for bitwarden/setup:1.32.0
docker.io/bitwarden/setup:1.32.0
chown: invalid user: 'bitwarden:bitwarden'
chown: invalid user: 'bitwarden:bitwarden'
error: failed switching to "bitwarden:bitwarden": unable to find user bitwarden: no matching entries in passwd file

**Comment by ruppert92** [comment]
I ended up just blowing up my server & now have it running on ubuntu.

**Comment by bilogic** [comment]
@pawelma i have the same problem as @ruppert92 but ```./bitwarden.sh updateself``` did not fix it

**Comment by bilogic** [comment]
I solved the issue through trial and error by modifying ```./bwdata/env/uid.env``` so that the values of ```LOCAL_UID``` and ```LOCAL_GID``` changed from ```bitwarden``` to the integer value of ```bitwarden``` found in ```/etc/passwd```, in my case, ```1000```
