### ISSUE TITLE
No timeout after failed login attempt

### ISSUE THREAD

**Issue by aw-jansen** [bitwarden/server#588]
Hi, I recently started to self-host Bitwarden and so far I'm really happy with it. My only concern is that there currently is no real rate limiting mechanism in place on the web-vault (or at least as far as I was able to tell); I can repeatedly try different combinations of usernames and passwords without any noticeable restrictions or delays which kind of disturbs me. Is this intended behavior?

**Comment by kspearrin** [comment]
Yes, rate limiting is only built into the cloud-hosted version at this time.

**Comment by aw-jansen** [comment]
Allright, Then I'll have to look for a different solution. Is there any way to implement fail2ban to prevent multiple logins in the dockerized version? So far I haven't been able to find a log file containing ip adresses in relation to a failed login attempt.

**Comment by Mart124** [comment]
> Is there any way to implement fail2ban to prevent multiple logins in the dockerized version? So far I haven't been able to find a log file containing ip adresses in relation to a failed login attempt.

https://community.bitwarden.com/t/external-log-file-containing-failed-accesses-to-fail2-ban/194
