### ISSUE TITLE
fail2ban not working due to missing log files (selfhosted)

### ISSUE THREAD

**Issue by totti4ever** [bitwarden/server#590]
Apparently the dockers don't write appropiate log files. I was expecting them from server

**Comment by thomiczecks** [comment]
The bitwarden-nginx docker is writing them inside the container. You can access them using something like: docker exec -it bitwarden-nginx /bin/bash and then navigating into /var/log/nginx.

**Comment by Mart124** [comment]
See this request :
https://community.bitwarden.com/t/external-log-file-containing-failed-accesses-to-fail2-ban/194

**Comment by uebergucken** [comment]
Shouldn't failed login attempts be in bwdata/logs/identity ?
The events/ icons/ and identity/ folders are completely empty. Shouldn't they contain something?
