### ISSUE TITLE
Disabling healthcheck does not disable "GET /admin" (healthcheck?) requests

### ISSUE THREAD

**Issue by thomiczecks** [bitwarden/server#591]
Hi,
I'm running a selfhosted install of bitwarden 1.32.0. on Ubuntu server 18.04. Due to #563 I disabled the healtchchecks of all containers similar to https://github.com/bitwarden/server/issues/563#issuecomment-531566303 but noticed that i still get an hourly `"GET /admin HTTP/1.1"` request which originates from the bitwarden-admin container. I think this should also be disabled.

**Comment by kspearrin** [comment]
Fixed in https://github.com/bitwarden/server/commit/9da83cbdc3f744c84256accce443cd9b7011d314

**Comment by Mart124** [comment]
@kspearrin thanks to this commit did you globally disable healthcheck ?
Or do we still need the #563 workaround for CPU issues ?
Thx 👍
