### ISSUE TITLE
On premise installation: cant create account /login in Google Chrome

### ISSUE THREAD

**Issue by PhillWide** [bitwarden/server#592]
Hi,

I'm trying to install bitwarden on premise using docker, however I cannot create a user (The login page is running). I'm installing it on Debian 10 image with 2VCPUs, 3.5GB RAM.

` ./bitwarden.sh install:
     Domain: no
     Do you have ssl: no
     Do you want to generate: no
`
`./bitwarden.sh start`
and I even did 
`./bitwarden.sh update db`

I also looked at all docker logs and mssql logs and found no errors.

Docker version 19.03.4, build 9013bf583a

docker-compose version 1.24.1, build 4667896

Any idea what could be wrong?

**Comment by kspearrin** [comment]
Is it all running? Check `docker ps`

**Comment by PhillWide** [comment]
> Is it all running? Check `docker ps`

Yes it is.
`CONTAINER ID        IMAGE                            COMMAND             CREATED             STATUS                 PORTS                                                 NAMES
eaecfc06c2a8        bitwarden/nginx:1.32.0           "/entrypoint.sh"    2 hours ago         Up 2 hours (healthy)   80/tcp, 0.0.0.0:80->8080/tcp, 0.0.0.0:443->8443/tcp   bitwarden-nginx
798f1f58f290        bitwarden/admin:1.32.0           "/entrypoint.sh"    2 hours ago         Up 2 hours (healthy)   5000/tcp                                              bitwarden-admin
3c9ab2dac225        bitwarden/events:1.32.0          "/entrypoint.sh"    2 hours ago         Up 2 hours (healthy)   5000/tcp                                              bitwarden-events
07fab7d7f985        bitwarden/notifications:1.32.0   "/entrypoint.sh"    2 hours ago         Up 2 hours (healthy)   5000/tcp                                              bitwarden-notifications
50618848e068        bitwarden/api:1.32.0             "/entrypoint.sh"    2 hours ago         Up 2 hours (healthy)   5000/tcp                                              bitwarden-api
a2a96ebace3b        bitwarden/icons:1.32.0           "/entrypoint.sh"    2 hours ago         Up 2 hours (healthy)   5000/tcp                                              bitwarden-icons
c7bd8a88cee7        bitwarden/web:2.12.0             "/entrypoint.sh"    2 hours ago         Up 2 hours (healthy)   5000/tcp                                              bitwarden-web
6d97a72212a3        bitwarden/attachments:1.32.0     "/entrypoint.sh"    2 hours ago         Up 2 hours (healthy)   5000/tcp                                              bitwarden-attachments
910007ad3b66        bitwarden/mssql:1.32.0           "/entrypoint.sh"    2 hours ago         Up 2 hours (healthy)   1433/tcp                                              bitwarden-mssql
739979e99cf0        bitwarden/identity:1.32.0        "/entrypoint.sh"    2 hours ago         Up 2 hours (healthy)   5000/tcp                                              bitwarden-identity
`

**Comment by kspearrin** [comment]
Sounds like a networking issue then.

**Comment by PhillWide** [comment]
> Sounds like a networking issue then.

Ok, will have a look at whats going on between the server and client on Monday.

**Comment by PhillWide** [comment]
> Sounds like a networking issue then.

I looked and when I press submit at registration, no packets are sent except occasional tcp ACK (capturing on client). When I try to login, some packets are sent.

**Comment by PhillWide** [comment]
So I have figured out it is an issue with Google chrome, In Mozilla I was able to create the account.
My google chrome: Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by PhillWide** [comment]
Also cant login to the chrome extention (claims password error), but can login to the chrome one.

**Comment by kspearrin** [comment]
Are you using http rather than https?

**Comment by PhillWide** [comment]
> Are you using http rather than https?

Yes, I'm just preparing installation with ansible, so I have done just a basic installation as described previously.

**Comment by kspearrin** [comment]
As the installer indicates, https is required Hey o use Bitwarden. Chrome will not allow the use of crypto APIs without https, which is what you are seeing here.
