### ISSUE TITLE
Error when accessing Bitwarden behind a SSL VPN

### ISSUE THREAD

**Issue by jkellogg90** [bitwarden/server#603]
I have a self hosted Bitwarden server on my LAN. I can login when on the LAN without any issues.

When I access Bitwarden through my Cisco SSL VPN from the internet, I get the following error

An error has occurred.
Username or password is incorrect. Try again.

Login credentials are correct. I verified many times.

Nothing relevant in the nginx logs. Any ideas?

**Comment by kspearrin** [comment]
I am not sure why that would occur. Are you able to proxy the traffic through MITM and see if there is anything different with the requests?

**Comment by jkellogg90** [comment]
This is what I see when running captures. I'm still trying a few more things. I'll update if I find a solution. :D

POST /connect/token HTTP/1.0
Host: 192.168.10.230
X-Real-IP: 192.168.10.1
X-Forwarded-For: 192.168.10.1
X-Url-Scheme: https
X-Forwarded-Proto: https
Connection: close
Content-Length: 238
Cache-Control: max-age=0
accept: application/json
device-type: 9
Sec-Fetch-Dest: empty
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.100 Safari/537.36
content-type: application/x-www-form-urlencoded; charset=utf-8
Origin: https://mysslvpnhere:8443
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Referer: https://192.168.10.230/
Accept-Encoding: 
Accept-Language: en-US,en;q=0.9,ru;q=0.8

grant_type=password&username=redacted&password=redacted&scope=api%20offline_access&client_id=web&deviceType=9&deviceIdentifier=redacted&deviceName=chrome

HTTP/1.1 400 Bad Request
Connection: close
Date: Wed, 26 Feb 2020 19:11:36 GMT
Content-Type: application/json; charset=UTF-8
Server: Kestrel
Cache-Control: no-store, no-cache, max-age=0
Pragma: no-cache
Access-Control-Allow-Origin: https://mysslvpnhere:8443
Server-Version: 1.32.0

{"error":"invalid_grant","error_description":"invalid_username_or_password","ErrorModel":{"Object":"error","Message":"Username or password is incorrect
. Try again.","ValidationErrors":null,"ExceptionMessage":null,"ExceptionStackTrace":null,"InnerExceptionMessage":null}}
