### ISSUE TITLE
Return HTTP/401 on wrong credentials

### ISSUE THREAD

**Issue by Mart124** [bitwarden/server#604]
Hi,

For now, HTTP/400 is returned when user provides a wrong username and / or password.
As an example, the following nginx log :
```
192.168.16.1 - - [20/Nov/2019:13:52:05 +0000] "POST /identity/connect/token HTTP/1.1" 400 36 "-" "Bitwarden_Mobile/2.2.5 (iOS 13.2.2; Model iPhone)" "1.2.3.4"
```

However, doing a simple `GET` request on `/identity/connect/token` also returns HTTP/400.
Could it then be possible to return HTTP/401 in case of wrong username / password please ?

This would allow to easily write a [Fail2Ban](https://github.com/fail2ban/fail2ban) jail, filtering on
`"POST /identity/connect/token HTTP\d\.\d" 401`

And to answer [this community topic](https://community.bitwarden.com/t/external-log-file-containing-failed-accesses-to-fail2-ban/194).

In addition, according to the [API doc](https://help.bitwarden.com/article/public-api/), sounds like HTTP/401 should be expected in this case.

Thank you very much 👍

**Comment by kspearrin** [comment]
I added a log message for login failure. See here https://github.com/bitwarden/server/commit/d022517762d41f92e4238db0b73af9e513f41b48

**Comment by Mart124** [comment]
Really good news @kspearrin :+1:
Thank you very much !
I then assume a new logfile will be available in `bwdata/logs/identity/`, right ?
For now, as of 1.32.0, no logfile there yet, so I wonder :)
Many thanks again.

**Comment by kspearrin** [comment]
Yes, it should be there.

**Comment by Mart124** [comment]
I just gave your commit a try @kspearrin thanks to the dev images.
```
# cat bwdata/logs/identity/Identity/20191122.txt 
2019-11-22 14:08:26.530 +00:00 [Warning] Failed login attempt.""
2019-11-22 14:08:57.873 +00:00 [Warning] Failed login attempt.""
```

2 remaining things if I may :
- we miss the client IP in the log lines, ban tools such as Fail2Ban need it ;
- as you can see logfile name is not constant but timestamped, which will lead to issues with Fail2Ban as logfile paths _containing * and ? or [0-9] -- can be used however only the files that exist at start up matching this glob pattern will be considered_. Any way then to make the logfile name constant (and rotate it for example) ?

Thank you !

**Comment by kspearrin** [comment]
I added the IP address to the log. https://github.com/bitwarden/server/commit/2693ffeab02b10f3fd885ee910401c3eb437b083

I added a new env variable that you can configure that will allow you to roll log files by size limit rather than timestamp (daily). See https://github.com/bitwarden/server/commit/d270311393891215a7d93337f2f9d6071628e3c7 and https://github.com/bitwarden/server/commit/c7d34a7ac6d62ce3c0be6929cde36e60a2304ff9

Just set `globalSettings__logRollBySizeLimit=1073741824` to roll on 1GB, for example.

**Comment by Mart124** [comment]
I just gave this a try, using `globalSettings__logRollBySizeLimit=1024`.

Here is the log file :
```
# ls -l bwdata/logs/identity/Identity/
total 4
-rw-r--r-- 1 nobody nogroup 1040 Nov 22 12:08 log-20191122.txt
```

Strangely it is not correctly named.
Additionally, its size is correctly limited to 1024 bytes (for the test), but log file is not rotated and does not accept any further log message 😕 Perhaps it is only rotated at a certain time of the day ?

**Comment by kspearrin** [comment]
Try the latest dev build whenever it finishes building, please.

**Comment by Mart124** [comment]
Thank you Kyle.
Looks better.
Content is now OK :
```
2019-11-26 01:04:49.008 +08:00 [WRN] Failed login attempt. 192.168.0.16
2019-11-26 01:04:51.709 +08:00 [WRN] Failed login attempt. 192.168.0.16
2019-11-26 01:04:56.051 +08:00 [WRN] Failed login attempt. 192.168.0.16
```
Filename is also ok, `log.txt`.

But look at how it is rotated :
```
# ls -l bwdata/logs/identity/Identity/
total 8
-rw-r--r-- 1 nobody nogroup  360 Nov 25 12:05 log_001.txt
-rw-r--r-- 1 nobody nogroup 1080 Nov 25 12:04 log.txt
```
`log.txt` goes up to the limit, then new log lines go into `log_001.txt`.
We would rather expect moving `log.txt` to `log_001.txt`, and logging again into `log.txt`.

Thank you again !

**Comment by Mart124** [comment]
Here's then the Fail2Ban jail for Bitwarden : https://github.com/fail2ban/fail2ban/pull/2567

**Comment by kspearrin** [comment]
@Mart124 For point number 2, see https://github.com/bitwarden/server/commit/9e470c1f7a71b80f32c96a9dc63e52bba6ac2e35

**Comment by Mart124** [comment]
```
# cat bwdata/logs/identity/Identity/log.txt 
2019-11-27 21:17:39.358 +01:00 [INF] Identity started.
```
Thank you very much @kspearrin :+1:

**Comment by stephen-azure** [comment]
Just deployed a bitwarden server but bwdata/logs/identity is empty and does not contain Identity/log.txt. Installed server version is 1.32.0 and web app 2.12.0. Is this not deployed to the GA server version yet?

Very new to bitwarden and really excited about it. So far I'm very impressed.

-Stephen

**Comment by Mart124** [comment]
This feature will be available in next server version (1.33.0 ?).

**Comment by uebergucken** [comment]
Do we know what version this will be delivered in?

**Comment by Mart124** [comment]
Available now in 1.33.0 👍

**Comment by Mart124** [comment]
Available now in 1.33.0 👍
_I think @kspearrin you can then close the 5 related requests mentioned in the [first post](https://github.com/bitwarden/server/issues/604#issue-527119652)._

**Comment by Mart124** [comment]
For those who would ask, you then need to perform the following tasks to enable Fail2Ban for Bitwarden.

Add the following to `bwdata/env/global.override.env` :
`globalSettings__logRollBySizeLimit=1073741824`

Add the following to `bwdata/config.yml` :
```
real_ips:
- 10.0.0.0/8
- 172.16.0.0/12
- 192.168.0.0/16
```

Restart Bitwarden.
Be sure `bwdata/logs/identity/Identity/log.txt` is there.

Enable the Fail2Ban Bitwarden jail : https://github.com/fail2ban/fail2ban/pull/2567

**Comment by darkrain-nl** [comment]
Thank you very much for this detailed description. Works fine!

**Comment by Mart124** [comment]
Now that Bitwarden [supports syslog](https://github.com/bitwarden/server/pull/742), Fail2Ban jail has been updated to support both logging methods :
https://github.com/fail2ban/fail2ban/pull/2778

**Comment by piotrkochan** [comment]
my td-agent config:

```
<source>
  @type tail
  @id bitwarden_identity
  <parse>
    @type regexp
    expression /^(?<time>[^(\[)]*)\s\[(?<level>[^\]]*)\]\s(?<message>[^\.]*)\.(?:\s(?<ip>[0-9\.]+))?$/
    time_format %F %T
  </parse>
  path /home/piotr/bwdata/logs/identity/Identity/*.txt
  pos_file /var/log/td-agent/bitwarden-identity.txt.pos
  tag bitwarden.identity
</source>
```
