### ISSUE TITLE
Problem with logging in to PayPal account using the Firefox plugin

### ISSUE THREAD

**Issue by KamilGadawski** [bitwarden/server#611]
There is a problem with logging in to PayPal via Firefox plugin. By entering the PayPal website and going to the login, clicking on the auto fill in the login fields in the plugin, the field data complement each other, however, does not recognize the password. 

Copying the password manually and pasting the login works.

**Comment by Mart124** [comment]
I think you should close this and look at https://github.com/bitwarden/browser/issues/982 :)
