### ISSUE TITLE
Email not being sent

### ISSUE THREAD

**Issue by deligatedgeek** [bitwarden/server#614]
I "manually installed" Bitwarden, approx 2 months ago, it worked first time no issues.

Recently we have noticed that it has stopped sending emails, for example admin logins, new accounts

I have installed swaks in the api container and can send emails.

I see no dns lookups (when the mail server was an FQDN)

application and docker logs show nothing remotely related to sending emails, apart from the back and forth for the html /admin authentication request

Even rolled admin and api back to 1.31.1, no difference

**Comment by ollien** [comment]
I'm having this issue as well. I was trying to use these settings (that I found in another thread) in my `global.override.env` to no avail.

```
globalSettings__mail__smtp__host=smtp.gmail.com
globalSettings__mail__smtp__port=587
globalSettings__mail__smtp__ssl=true
globalSettings__mail__smtp__username={redacted}
globalSettings__mail__smtp__password={redacted}
globalSettings__mail__smtp__useDefaultCredentials=false
```

**Comment by TheEagle13** [comment]
Try this : 
https://github.com/bitwarden/server/issues/457#issuecomment-483088216

**Comment by ollien** [comment]
In case this issue is being actively tracked, I'm not sure what fixed it, but eventually, this started working. I _THINK_ the problem was that the file wasn't being updated unless I did a full `docker-compose down` and `docker-compose up`, not just a restart.

**Comment by ryaniskira** [comment]
I still can't get this to work with my email server. Is there a way to just go into the database and change the email address of an account to be "verified" instead?

**Comment by deligatedgeek** [comment]
#457 worked for me, even though we don't use ssl on email.
Admin emails starting being sent after I used the correct delimiter in the global overrides env file :pensive:
