### ISSUE TITLE
Duo security keeps loading

### ISSUE THREAD

**Issue by mosaelnile** [bitwarden/server#617]
Hi there I'm not able to get duo security to work on my hosted bitwarden, it keeps loading, I was not sure where to find the aKey in the global.env file.

**Comment by kspearrin** [comment]
Is there an error message in the browser console? Need more information to be able to debug the issue.

**Comment by mosaelnile** [comment]
I just figured it out when I checked the browser console, the key was less than 4o character, I thought 20 was enough, it's working now. cheers mate
