### ISSUE TITLE
/identity/connect/token 400 (Bad request)

### ISSUE THREAD

**Issue by Nufan1121** [bitwarden/server#619]
**Setup:**

Bitwarden on premise Version 2.12.0 within Docker containers behind HAproxy

**Issue:**

I'm experiencing a problem since i updated my Let's Encrypt certificate when trying to log in from multiple devices using Google Authenticator 2FA leads to a 400 error.

I have been manually upgrading my LE certs every 3 months for over a year now using the on-premise, Docker Bitwarden without any issues, for some reason this time (potentially coincidental) it caused an issue.

I'm doing my best to troubleshoot the issue, from restarting all docker containers to updating them and going over the configuration files but to little progress. From what i can see, requests are hitting the identity service because i'm getting log output suggesting this:

User authentication failed: invalid_username_or_password, details: {
        "ClientId": "web",
        "GrantType": "password",
        "Scopes": "api offline_access",
        "UserName": "email@gmail.com",
        "Raw": {
          "grant_type": "password",
          "username": "email@gmail.com",
          "password": "***REDACTED***",
          "scope": "api offline_access",
          "client_id": "web",
          "deviceType": "9",
          "deviceIdentifier": "8862af9b-9e79-4a18-be92-cf3dffc68698",
          "deviceName": "chrome",
          "twoFactorToken": "806667",
          "twoFactorProvider": "0",
          "twoFactorRemember": "0"
        }
      }

I can confirm that the username and password are not incorrect as the error above suggests as it let's me get to the 2FA screen. If i enter a purposefully incorrect password it will not let you progress to 2FA.

**What i have tried:**

I've checked most of the logs i can find both within /bwtdada/logs and Docker logs, none of which are pointing to anything substantial but i may be missing some. The most valuable log i found was the identity docker log above which i'm currently trying to troubleshoot but coming to a stand still.

As mentioned above i made sure everything was on the latest version

I have tried to correct the timezones of my host and server to make sure they are in sync though i wasn't too sure what the best practice is here. To be clear, i did not change the time zone on my system or within docker containers prior to this problem beginning.
Since then, from reading common 'invalid_token' issues for 2FA, i found that the times should be checked to make sure they are in sync. From checking each container they seem to be a mix of GMT and some are UTC. My server is GMT. Is this correct? should i be fixing these, if so, any specific containers priority or should they all be in the same time zone.
The time itself is already synced between all containers and host.

Apologies if this has been answered elsewhere. I have tried to the best of my ability to find a similar issue on the web, but the only similar problems i have found suggest updating (done) and correcting the time (done, kind of).

To be clear, i don't even need to enter a 2FA code in order to get the console error (attached) simply progressing past the initial username+password screen will log that in the console.
<img width="403" alt="Screenshot 2019-12-03 at 21 34 59" src="https://user-images.githubusercontent.com/26150802/70091965-2048fd00-1615-11ea-9feb-08c6de85fa22.png">
<img width="1319" alt="Screenshot 2019-12-03 at 21 35 12" src="https://user-images.githubusercontent.com/26150802/70091966-2048fd00-1615-11ea-9cc4-f1b330c99b6b.png">
Entering a correct 2FA code from Google Authenticator produces the Bitwarden error box of 'invalid token'.

Any help much appreciated!

**Comment by kspearrin** [comment]
Are you sure the problem is not on your client device itself? This usually occurs whenever the system time is not correct.

**Comment by Nufan1121** [comment]
Hi Kyle, 

Thank you for the reply. I did check thy the time was correct up to the minute on my device - my questions are: 

How correct does the time have to be is it down to a second? I couldn't find this information regarding Google 2FA when I searched online so apologies if this is easily available somewhere. 

Does the timezone on say my phone or laptop have to be UTC also? Or is the timezone itself irrelevant as long as the time is correct? 

Regards. 

⁣Get BlueMail for Android ​

**Comment by kspearrin** [comment]
The timezone is irrelevant as long as the time is correct. The time just needs to be accurate within 30 seconds for TOTP generation to function correctly.

**Comment by Nufan1121** [comment]
Thank you once again for the reply.

I can only assure you that to the best of my ability i have manually checked the time on the Host, all containers (focusing primarily on the identity container as i assume this is where the conflict is coming from) and on both devices which are failing to authenticate with the 2FA token (My Macbook and my Android). The issue is persisting.

Today, i ran out of ideas and killed all of the containers, rebuilt the the assets and regenerated the containers. Before starting the containers, i went through the config.yml to make sure all data looked correct. The issue persists even after this.

I appreciate the help so far, is there any method of confirming the time is definitely correct alternative to what i have already outlined that you would personally attempt? 

The issue to me doesn't seem to be with the tokens themselves, as the browser console logs the 400 error upon completing the password field and before i even attempt the password. Is this an expected error at that point? Is there any method you could advise on how i could debug this outside of the browser or confirm that the identity service is behaving as intended?

**Comment by kspearrin** [comment]
I am a little confused here. In your original post you said:

> I can confirm that the username and password are not incorrect as the error above suggests as it let's me get to the 2FA screen. If i enter a purposefully incorrect password it will not let you progress to 2FA.

But now, you say:

> The issue to me doesn't seem to be with the tokens themselves, as the browser console logs the 400 error upon completing the password field and before i even attempt the password.

You cannot get the 2FA screen if you have not attempted the password.

Can you clarify?

**Comment by Nufan1121** [comment]
Hi Kyle, 

Apologies I see how that is a slight contradiction, please allow me to explain. 

The error appears in the console of the browser as soon a I've hit enter on the username an password screen. This is also reflected in the logs for the identity container. 

In my original statement there quoted, the very last word 'password' should actually have been 'token'. The error appeara in the console after submitting the credentials but before the 2FA token has been submitted. 

This is what is leading me to believe thee is an issue with a connection or certificate somewhere, rather than an issue with system times etc.

I hope this makes more sense now? Apologies for the confusion, it appears to have been a mix of word on my part.

**Comment by Nufan1121** [comment]
I went through the config file yesterday evening in more granular detail to lake sure all paths to certificates were correct and the system itself seems to be operating correctly and securely albeit failing the token every time when attempted.

As mentioned previously, I believe I cab predict the failure of the token entered before even attempting it due to the 400 error in console upon submitting credentials. These 400 errors appear in the logs for the identity container also. 

Do you know a way I could completely restart the identity container end config 'from scratch'? Assuming that as the DB is separate there would theoretically be no issue with removing all containers and re initiating, but is the same true for the configuration files?

**Comment by kspearrin** [comment]
If you have 2FA configured on the account, a 400 is expected on the first /token request. Whenever you provide the correct verification code, another request to /token is made, which should be a 200 if successful.

**Comment by Nufan1121** [comment]
Hi Kyle, 

Is there anywhere else in the container that the timezone could be incorrect from? For example the php ini time? I have only checked the time of the container itself using the 'date' command. 

I have used other container where the time of the service depended on configuration file times. 

I'm at a bit of a loss here… a the workflow you have described with a 400 followed by 200 on success is not happening. Its very beneficial for me to know it's expected to 400 on first process with 2FA enabled though, as I can now focus my efforts elsewhere

**Comment by Nufan1121** [comment]
Hi Kyle,

Thank you finally for your help with this.

I'm closing this issue as luckily i had an open session with Bitwarden on my Laptop so i was able to export my passwords as JSON and import them into a working instance on the same server after reinstalling Bitwarden. I've no idea what was wrong, but unfortunately i had to take the quickest available option to resolving the issue which in this case was a re install and re import
