### ISSUE TITLE
Turn off Google Analytics

### ISSUE THREAD

**Issue by jkellogg90** [bitwarden/server#620]
Is there a way to turn off Google Analytics? 

I see over 35,000 DNS queries for Google from my onprem Bitwarden host within the past 24 hours. 

count	query	src_ip
23474	google.com	10.0.10.235
11742	www.google.com	10.0.10.235

I apologize if this is well documented somewhere. I couldn't find how to do this.

**Comment by kspearrin** [comment]
Bitwarden doesn’t use google analytics.

**Comment by jkellogg90** [comment]
Interesting. Maybe I just didn't install Bitwarden right. I just see this over and over. 

root      5739  0.8  0.0   4280   716 ?        Ss   21:33   0:00 /bin/sh -c curl -f http://localhost:5000/google.com/icon.png |
root      5744  0.0  0.2 157964  8248 ?        S    21:33   0:00 curl -f http://localhost:5000/google.com/icon.png

**Comment by kspearrin** [comment]
Those are requests for website icons. See https://help.bitwarden.com/article/website-icons/
