### ISSUE TITLE
Import: Fully numeric usernames or passwords gets corrupted

### ISSUE THREAD

**Issue by tandr** [bitwarden/server#621]
If passwords or usernames that were exported from LastPass were fully numeric, they got corrupted and become some number with exponent. For example, in a browser extension  password or user name 251167076377 displayed and filled as 2.9065E+13. Logging in into vault shows the same problem.

I have checked export file from LastPass and it contains a correct info. There is a possibility that corruption occurred later on a server,  I did import about a month or so ago.

Now  I wonder if it actually is corrupted on a server too, and how many of these I have now. Passwords are not big deal - they are recoverable and replaceable. But the user names are not.

Searching for E+ in a vault shows 6 usernames that became corrupted. I wonder how many passwords did become corrupted there too.

**Comment by tandr** [comment]
There is a non-zero probability it is a work of Excel -- I have opened a file before importing it into bitwarden...

**Comment by aarontheman** [comment]
Happened to me too from my recent import.
