### ISSUE TITLE
how to change default 443 for bitwarden-nginx

### ISSUE THREAD

**Issue by gzsmhf** [bitwarden/server#622]
my port 443 has been used, so I need another port instead. When I start docker image, it returns an error "ERROR: for bitwarden-nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint bitwarden-nginx (5597cf2d0ef8bcf91fc6ccddf22a2f354e65f58779bb06aae7af6bd76daeff3d): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use".

Just wondering how could I change https port for bitwarden-nginx ?

**Comment by kspearrin** [comment]
Ports can be changed in bwdata/config.yml

**Comment by gzsmhf** [comment]
> 
> 
> Ports can be changed in bwdata/config.yml

Yes, I did modify config.yml:
# Learn more: https://docs.docker.com/compose/compose-file/#ports
http_port: 817
#
# Docker compose file port mapping for HTTPS. Leave empty to remove the port mapping.
# Learn more: https://docs.docker.com/compose/compose-file/#ports
https_port: 326

but when I run ./bitwarden.sh start, it still return the same error:
ERROR: for bitwarden-nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint bitwarden-nginx (4eb1500055c19cbc7f709481a9b58d149fea15a76077afffbbbb9a108774a0c0): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use

ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint bitwarden-nginx (4eb1500055c19cbc7f709481a9b58d149fea15a76077afffbbbb9a108774a0c0): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use

**Comment by kspearrin** [comment]
Did you rebuild?

**Comment by gzsmhf** [comment]
no, I didn`t rebuild, but I have fixed the issue. I run bitwarden on Synology server, settings for nginx docker can be edited via official tools. Thanks a lot anyway.

**Comment by houserockr** [comment]
@kspearrin the hint on rebuild saved my day. I didn't know you had to call bitwarden rebuild after making changes to the yaml config. <3

**Comment by retroip** [comment]
Same here, rebuild does not help.
I leaved config like (empty), with same results

`# Docker compose file port mapping for HTTPS. Leave empty to remove the port mapping.
# Learn more: https://docs.docker.com/compose/compose-file/#ports
https_port:
#
# Docker compose file ve...`

**Comment by Lavizrap** [comment]
> > Ports can be changed in bwdata/config.yml
> 
> Yes, I did modify config.yml:
> 
> http_port: 817 https_port: 326
> 
> but when I run ./bitwarden.sh start, it still return the same error: ERROR: for bitwarden-nginx Cannot start service nginx: driver failed programming external connectivity on endpoint bitwarden-nginx (4eb1500055c19cbc7f709481a9b58d149fea15a76077afffbbbb9a108774a0c0): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use
> 
> ERROR: for nginx Cannot start service nginx: driver failed programming external connectivity on endpoint bitwarden-nginx (4eb1500055c19cbc7f709481a9b58d149fea15a76077afffbbbb9a108774a0c0): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use

Hi, I believe you have to change the ports in your docker-composer.yml file as well. You can find it in your /home/user/bwdata/docker/ directory. Hope that helps.
