### ISSUE TITLE
User not getting MFA2 authentication code

### ISSUE THREAD

**Issue by nmoiseykin** [bitwarden/server#623]
Hello, one of my users stopped receiving MFA2 email codes yesterday. 
I deleted the user and created again, the user received an invitation email. Clicked Join the Company.
On a new page there is LOGIN and CREATE ACCOUNT.

If the user click on login and puts OLD password, it redirects to a page to enter MFA2 code, that user never receives.

If the user clicks on Create Account, it says account has been created.

We tried deleting the user using this link https://vault.bitwarden.com/#/recover-delete but the user never receives a Delete Email. 

We use a hosted version. The user uses the same domain as all others in the company.

Any clues?

Much appreciated, Nick

**Comment by kspearrin** [comment]
> We use a hosted version

Cloud-hosted (bitwarden.com) or self-hosted?

**Comment by nmoiseykin** [comment]
Thanks, we have added Bitwarden domain to trusted domains and email started
coming through

Cheers
