### ISSUE TITLE
Stop organisations entries showing In personal vault 

### ISSUE THREAD

**Issue by robina80** [bitwarden/server#624]
Hi all,

When I create an organisation and assigned it to a user or multiple users when that user logs in to there personal vault they can see the organisational entries in there personal vault

As you can imagine if that user deletes the entry from there personal vault it replicates the deletion on the actual organisation!!! 

Is there anyway of not showing the organisation entries in users personal vault

Thanks,
Rob

**Comment by kspearrin** [comment]
No, there is not a way to remove organization items from the user's vault view. If the user has access to view those items they will always show there.

**Comment by robina80** [comment]
Ohhh course as its shared to that user
