### ISSUE TITLE
Podman support

### ISSUE THREAD

**Issue by TheEagle13** [bitwarden/server#628]
Since RHEL, Fedora, and Centos have all dropped support for docker in favor of podman, I believe it is pertinent to make sure that Bitwarden is able to run on podman. Currently, it does not run on podman (even with docker commands aliased to podman.

**Comment by Mart124** [comment]
See #497 (you could then close this ticket).

**Comment by TheEagle13** [comment]
> See #497 (you could then close this ticket).

I saw this, but this was initially a support ticket that got derailed by users who automatically assume their issues are exactly the same but have no relation. There is also a hint at podman, however no actually request or acknowledgement about podman support.

I wanted to open something directly related to requesting Supporting podman.

**Comment by cclarke591** [comment]
#497 has moved towards actual discussion of supporting podman. Feel free to check it out. Looks like the devs need to solve an issue with selinux fcontexts.

**Comment by Hinton** [comment]
Closing this as a duplicate of https://github.com/bitwarden/server/issues/497
