### ISSUE TITLE
Disable User registration - Create Account Button 

### ISSUE THREAD

**Issue by Sx3** [bitwarden/server#631]
Is there a way we can disable new user registrations on Bitwarden Server
https://help.bitwarden.com/article/install-on-premise/
I followed the steps to setup it on a CentOS 7

**Comment by kspearrin** [comment]
Have a look in `./bwdata/env/global.override.env`. There is a setting to disable user registration.

**Comment by Sx3** [comment]
I was using that option
globalSettings__disableUserRegistration=true
and thinking the buttons should also go away...
Thanks.

**Comment by haneef95** [comment]
The button is still there.

Any plans to have it removed all together?

**Comment by samnewman86** [comment]
Is anyone working on this?

**Comment by RafaelHGBotelho** [comment]
Same problem here. Will the button be removed in an update?

**Comment by NetMango** [comment]
Yes, it would be useful. When I try to submit a new user, the server response is "Registration not allowed" message, which is the expected behaviour. But visibility of the button and the registration form is deceptive. Thank you.

**Comment by Rykimaruh** [comment]
Glad to stumble on this. I was going crazy thinking why the button is not greyed out or hidden when I have this option set to true. 

So the behavior is that when a new user tries to register, they will get an error message? (I have not tried this yet because I don't want to fill my BW instance with user dummy data)

**Comment by joshterrill** [comment]
@nicfab right, it should be a fairly easy change... maybe I can just submit a PR for it.

**Comment by NauelG** [comment]
When registration is disabled, is there a way to add users? There is no option in the admin panel.

**Comment by BirukTes** [comment]
> When registration is disabled, is there a way to add users? There is no option in the admin panel.

Did you not see this?:
![image](https://user-images.githubusercontent.com/23151263/195386292-edbb7f05-7a48-4bd4-aff2-dbac72c7ab92.png)

**Comment by N0AGI** [comment]
by setting the bwdata/env/global.override.env::globalSettings__disableUserRegistration=true, the Login Page :: "Create Account" button is not disabled.  It let's you proceed to the "Create Account" details page.  And, shows the following when to trigger the "Create account" button.

Ideally, by setting this config setting to true, the Login Page :: Create Button, ought to be **disabled**.

<img width="644" alt="image" src="https://github.com/bitwarden/server/assets/74984418/bb8ec5c0-2adc-4bd5-a786-52e346c823ab">
