### ISSUE TITLE
Saving multiple accounts for the same site

### ISSUE THREAD

**Issue by fabiobianchiwebdev** [bitwarden/server#633]
I'm trying to setup with bitwarden my Firefox profiles accounts, but when a click on the plus sign (top-right) it shows me the first account I created for the first profile. Anyone knows how to use on such cases?

**Comment by Likivik** [comment]
@fabiobianchiwebdev Could you please describe the issue in a bit more detail and/or give steps to reproduce the issue?

**Comment by djsmith85** [comment]
Hi @fabiobianchiwebdev, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
