### ISSUE TITLE
Create a variable to specify certbot related IP binding

### ISSUE THREAD

**Issue by Aaron-Ritter** [bitwarden/server#634]
Hi, 

Similar to issue #125 it would be good to allow the same for the letsencrypt certbot container, could you please add a bind IP question during the bitwarden.sh install part in the letsencrypt section.

https://github.com/bitwarden/server/blob/36e97ccbd255ec50ddbcb668ba12792d3a485985/scripts/run.sh#L65-L77

And something similar with (or storing the information for later in the previous step):
https://github.com/bitwarden/server/blob/36e97ccbd255ec50ddbcb668ba12792d3a485985/scripts/run.sh#L116-L123

or maybe instead making it part of the docker-compose.yml?

Thanks
Aaron

**Comment by Aaron-Ritter** [comment]
e.g.

```
        if [ "$LETS_ENCRYPT" == "y" ]
        then
            echo -e -n "${CYAN}(!)${NC} Enter your email address (Let's Encrypt will send you certificate expiration reminders): "
            read EMAIL
            echo ""
            echo -e -n "${CYAN}(!)${NC} Specify an IP for certbot to listen on, otherwhise leave blank: "
            read CERTBOTIPINPUT
            echo ""
            if [ -z "$CERTBOTIPINPUT" ]
            then
                CERTBOTIP=0.0.0.0
            else
                CERTBOTIP=$CERTBOTIPINPUT
            fi

            mkdir -p $OUTPUT_DIR/letsencrypt
            docker pull certbot/certbot
            docker run -it --rm --name certbot -p $CERTBOTIP:80:80 -v $OUTPUT_DIR/letsencrypt:/etc/letsencrypt/ certbot/certbot \
                certonly --standalone --noninteractive  --agree-tos --preferred-challenges http \
                --email $EMAIL -d $DOMAIN --logs-dir /etc/letsencrypt/logs
        fi
    fi
```

**Comment by PeterSurda** [comment]
I second this. Please fix. If you have a system with multiple IP addresses, this prevents you from running any other webserver on the other IPs.

**Comment by dmascord** [comment]
Agree, this needs to be fixed for servers with multiple IPs.

**Comment by cscharf** [comment]
Added to our DevOps board. Thanks!
