### ISSUE TITLE
[Org] Do we really need the email verification process ?

### ISSUE THREAD

**Issue by Mart124** [bitwarden/server#640]
Hi,

Do we really need the email verification process when the user is invited to join an organization ?
Perhaps we could save this step.
The user has clicked the link to join the organization, so the mail-address is already sort of verified...

Thank you 👍

**Comment by kspearrin** [comment]
The 3 step email confirmation process is necessary since it is actually a secure key exchange process.

**Comment by Mart124** [comment]
OK, thank you @kspearrin for your answer, let's then close this :)
