### ISSUE TITLE
Argon2 Encryption

### ISSUE THREAD

**Issue by lordraiden** [bitwarden/server#645]
I think everything is explained here so there is no much more to add.

https://community.bitwarden.com/t/switch-to-argon2/350 (53 Votes)

https://community.bitwarden.com/t/pre-hashing-passwords/9329

At least if it is not the default which it should make it optional for the onpremise customers.

**Comment by lordraiden** [comment]
@cscharf @kspearrin 
Any news about this? I can't think of any other security feature more important and requested than this one.

**Comment by cscharf** [comment]
Yes, sorry, missed this post, see: https://community.bitwarden.com/t/switch-to-argon2/350/24?u=cscharf
