### ISSUE TITLE
Is it possible to limit SQL server threads?

### ISSUE THREAD

**Issue by shillner** [bitwarden/server#646]
Hi, I'm running Bitwarden as Docker images on a VServer (Ubuntu 18.04).

I'm facing issues with forking processes when running commands and even while connecting using ssh. I finally figured out that these issues are caused by bitwarden and the number of threads spawned by the system and I guess this is mainly caused by the number of worker threads created by the MS SQL server or the .NET-Framework.

My question now is if there is a method foreseen to limit the number of worker threads of the database or switch to a different one (Postgres, MySQL, ...)?

**Comment by kspearrin** [comment]
> My question now is if there is a method foreseen to limit the number of worker threads of the database

Unfortunately, I am not familiar with a way to do this.

> or switch to a different one (Postgres, MySQL, ...)?

Not in the near future.

**Comment by shillner** [comment]
Hi, this shall be possible using some SQL configuration commands, please see here: https://docs.microsoft.com/en-us/sql/database-engine/configure-windows/configure-the-max-worker-threads-server-configuration-option?view=sql-server-ver15

I'd be interesed if this issue is known an affects others (I'd guess mainly VServer installations) too or if there's some configuration issue on the machine.

Thanks so far.

**Comment by Thokas** [comment]
Hi, I also run in this specific problem. I have an V-Server and get round about 500 Threads from bitwarden if it is started on it. in "docker stats" i see around ~130 pids assigned to mssql alone and all processes combined are 350‬ in total.

**Comment by shillner** [comment]
Hi, I got around this by using bitwarden_rs server instead which has a much smaller resources footprint.
You can also choose your db there.

**Comment by Thokas** [comment]
It's a shame, but as i need to run other services on my server there is no other option as it seems. Thanks for the info @shillner
