### ISSUE TITLE
Cleaning or Rotating `vault_log.ldf`

### ISSUE THREAD

**Issue by JeffAlyanak** [bitwarden/server#648]
I'm wondering what the best method would be for rotating or clearing the mssql `vault_log.ldf`. On my install, it has ballooned to be much larger than the vault itself and I would like to know the best way to deal with it.

**Comment by kspearrin** [comment]
This isn't a file you can rotate. It is the transaction log for the database. See https://stackoverflow.com/questions/826789/what-is-the-ldf-file-in-sql-server

**Comment by JeffAlyanak** [comment]
My transaction log has ballooned to be many gigabytes in size. If it can't be rotated, can it be shrunk with `dbcc shrinkfile` or otherwise reconfigured to be smaller.

**Comment by Starbase12** [comment]
If I understood correctly tha ldf-files are sql-transaction logs. As soon as there is no fully working backup routine in the background, the transaction will will get bigger and bigger. Is there a way to permanently change the "database recovery mode" to "SIMPLE" for my bitwarden instance?

**Comment by FingerlessGlov3s** [comment]
My `vault_log.ldf` file is currently 1.2G with a `vault.mdf` size of 72M.

Is there any news on getting a proper fix on the cleaning up the log file?

**Comment by zadjadr** [comment]
> My `vault_log.ldf` file is currently 1.2G with a `vault.mdf` size of 72M.
> 
> Is there any news on getting a proper fix on the cleaning up the log file?

I created a PR in August 2023, but I have not gotten any reaction or feedback to it..

**Comment by FingerlessGlov3s** [comment]
> > My `vault_log.ldf` file is currently 1.2G with a `vault.mdf` size of 72M.
> > Is there any news on getting a proper fix on the cleaning up the log file?
> 
> I created a PR in August 2023, but I have not gotten any reaction or feedback to it..

I tried to replicate what you changed in your PR, but I was getting errors when it went to do the `DBCC SHRINKFILE`, is the process still the same?

**Comment by pocoloko** [comment]
surprised this hasn't been fixed yet, my vault_log.ldf file is 2.3GB which sure doesn't seem like a lot in this day and age but it is running on a low end VPS with limited storage so in the end I have to regularly delete backup files to not run out of space
