### ISSUE TITLE
restoring specific MSSQL .bak file?

### ISSUE THREAD

**Issue by perfecto25** [bitwarden/server#651]
Hello, is it possible to restore a specific time-stamped .BAK file?

Im running BW on Centos 7, using docker, dont have any MSSQL tools installed, and was hoping there was an easier way to restore a .BAK than going via MSSQL docker container, didnt find any documentation on doing this.

**Comment by kspearrin** [comment]
You could use sqlcmd inside of the mssql container or expose the mssql container to the host and connect with a sql server tool like SSMS.

**Comment by perfecto25** [comment]
Thank you, the restore process was fairly quick, leaving these instructions for anyone that may run into this, 

## To restore MSSQL database .BAK file

1) get the SA password 
```
bw_host> cat bwdata/env/mssql.override.env 
SA_PASSWORD=<your password>
```
copy BAK file to the container,
```
bw_host>  docker cp /etc/bitwarden/bwdata/mssql/backups/vault_FULL_20191209_235901.BAK  bitwarden-mssql:/tmp
```
login into the container, 
```
bw_host>  docker exec -ti bitwarden-mssql bash
```
check if your BAK file is inside the container, 
```
container> ls /tmp 
```
Login to MSSQL command line,
```
root@aed985081525:/# /opt/mssql-tools/bin/sqlcmd -S localhost -U SA
## provide SA_PASSWORD
```

Restore the Database ,
```
1> ALTER DATABASE vault SET SINGLE_USER
2> WITH ROLLBACK IMMEDIATE
3> GO
Nonqualified transactions are being rolled back. Estimated rollback completion: 0%.
Nonqualified transactions are being rolled back. Estimated rollback completion: 100%.
1> RESTORE DATABASE vault FROM DISK='/tmp/vault_FULL_20200125_235901.BAK' WITH REPLACE
2> GO
Processed 912 pages for database 'vault', file 'vault' on file 1.
Processed 4 pages for database 'vault', file 'vault_log' on file 1.
RESTORE DATABASE successfully processed 916 pages in 2.383 seconds (3.001 MB/sec).
```

exit the container, BW should pick up changes in few minutes
