### ISSUE TITLE
Self Hostet Bitwarden Docker Container email verification via G Suite not working

### ISSUE THREAD

**Issue by donoli1st** [bitwarden/server#653]
Hi
I'm have setting up a Bitwarden Docker Container. Everything is working fine, beside of the email verification for my Account.
I would like to use G suite with the google smtp as a mail server.
Here are my global env settigns:
`globalSettings__mail__replyToEmail=no-reply@mydomain.com`
`globalSettings__mail__smtp__host=smtp.gmail.com`
`globalSettings__mail__smtp__port=465`
`globalSettings__mail__smtp__ssl=true`
`globalSettings__mail__smtp__username=user@mydomain.com`
`globalSettings__mail__smtp__password=securePW`
`globalSettings__disableUserRegistration=false`

Do you know, why this isn't working, or have any idea how to?

Hope i could deliver enough information for my problem, otherwise, just ask.

Thank you

**Comment by kspearrin** [comment]
Did you enable "Less secure apps" on your Google account so that you can use SMTP to log into it?

**Comment by inkdude** [comment]
> Did you enable "Less secure apps" on your Google account so that you can use SMTP to log into it?

Thank you! enabling works
