### ISSUE TITLE
Disabling healthcheck does not disable "GET /admin" (healthcheck?) requests

### ISSUE THREAD

**Issue by kukudemajia** [bitwarden/server#656]
Hi,
I'm running a selfhosted install of bitwarden 1.32.0. on Ubuntu server 18.04. Due to #563 I disabled the healtchchecks of all containers similar to #563 (comment) but noticed that i still get an hourly "GET /admin HTTP/1.1" request which originates from the bitwarden-admin container. I think this should also be disabled.

![1](https://user-images.githubusercontent.com/17118600/75116048-4e336000-569f-11ea-99e5-37be052a794a.jpg)
![2](https://user-images.githubusercontent.com/17118600/75116057-51c6e700-569f-11ea-9ce7-1616dbb0259f.jpg)

#591 9da83cb not work!

**Comment by kspearrin** [comment]
This isn't coming from a health check. The admin portal has a scheduled job that pings itself to keep certain processes from going to sleep.

**Comment by kukudemajia** [comment]
> This isn't coming from a health check. The admin portal has a scheduled job that pings itself to keep certain processes from going to sleep.

Can this scheduled job be canceled?

**Comment by kspearrin** [comment]
No, it cannot.

**Comment by kukudemajia** [comment]
> No, it cannot.

Thanks a lot.
