### ISSUE TITLE
Manager role can't create subcollections

### ISSUE THREAD

**Issue by LegendaryB** [bitwarden/server#673]
Hello guys,

following scenario:
I added a new user and gave him the Manager Role in the organization and selected a collection. Now I want that this user is able to create sub collections + normal password entries. But the user is not able to create subcollections. When I try it I'm always logged out with the message that a unknown error happened.

Any help?

Kind Regards,
Daniel

**Comment by kspearrin** [comment]
I am trying to reproduce this, but I can't. I created a new user with the manager role and assigned to one collection. I logged in as this manager and am able to create additional collections, including sub-collections. Can you please list the reproduction steps?

**Comment by LegendaryB** [comment]
Yes I can:
1. Set role of user to manager
2. Set at Access control to: The user can only access the following collections
3. Login with the user
4. Go to the organization
5. Click on Manage -> Collections -> Add Collection -> Enter TestCollection/TestSubCollection
6. I'm getting logged out and receive the unknown error notification

**Comment by kspearrin** [comment]
Are you using Bitwarden cloud or your own hosted bitwarden server?

**Comment by LegendaryB** [comment]
We are running it selfhosted on a Intel NUC. If it's important it's only reachable via ip and doesn't have a domain or SSL certs

**Comment by kspearrin** [comment]
Can you try updating your self-hosted server?

**Comment by LegendaryB** [comment]
I just set it up yesterday evening. It's the latest docker image version :x
