### ISSUE TITLE
Webserver redirection (DOMAIN NAME)

### ISSUE THREAD

**Issue by freud44** [bitwarden/server#677]
Hi,
I'm looking for a way to disable the automatic redirection of web url.
I'm testing this application on my linux server, I would like to bind the server's ip address and not the domain name.
When I'm navigating to the web home page with IP it automatically redirect to domain, so how to change it if possible ?
Regards

**Comment by kspearrin** [comment]
You can change your server's configured URL under ./bwdata/config.yml and ./bwdata/env/*.env

**Comment by freud44** [comment]
That's I did, but after executing the script.s rebuild, server seems not taking my updates..

**Comment by djsmith85** [comment]
Hi @freud44, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
