### ISSUE TITLE
Some emails are never received, no error message in logs

### ISSUE THREAD

**Issue by atomheartother** [bitwarden/server#682]
Hello world,

This is a mind-boggling issue I've been running into and I can't figure out where the problem could be. I turn to you guys for help because I'm at a loss.

# Behavior 

Recently we've had a wave of new users on our self-hosted instance (which also contains an organization), and they started complaining they never received their invitation email from our bitwarden server. This worked previously and it was still the same instance running so  I found that odd. I investigated and I found the most peculiar behavior:

- Password **hints** are sent without an issue to existing users through email.
- Emails sent to access the admin panel on `/admin` do not send at all, but the `bitwarden-admin` service doesn't show any errors upon sending said email.
- Same for organization invitations, inspired by other issues here I attempted to invite people as User and then promoting them, I tried inviting people who already had accounts on our bitwarden instance, people who didn't have an account... Nothing would do, the logs say everything is fine, at least to me.

# Additional info:

- I'd already read issues like #451 long ago, this definitely isn't it as I've set everything up and, again, emails **work** when it's for password hints.
- The emails are being sent to a GMail address in all those cases (GSuite accounts more specifically), but my users and I have checked our spam box, nothing is there, so it's not the spam filter.
- I updated to the latest BW server version, no success.

# Some files & data:
[Logs from bitwarden-api upon re-sending an invite link](https://github.com/bitwarden/server/files/4403032/apilogs.txt)

My `global.override.env` file:
```
globalSettings__mail__replyToEmail=no-reply@bitwarden.blackfoot.io
globalSettings__mail__smtp__host=ssl0.ovh.net
globalSettings__mail__smtp__port=587
globalSettings__mail__smtp__ssl=false
globalSettings__mail__smtp__username=XXXXXXXXX
globalSettings__mail__smtp__password=XXXXXXXXXXXXXXX
globalSettings__disableUserRegistration=false
globalSettings__hibpApiKey=REPLACE
adminSettings__admins=<my email address>
globalSettings__mail__smtp__trustServer=true
globalSettings__mail__smtp__useDefaultCredentials=false
```

So far I can only assume this is a Bitwarden problem as, again, it used to work and it now only works for certain types of email, so I'd like some insight into the differences between master password hint emails and other types of email if that's at all possible...

**Comment by Raptor039** [comment]
Same problem here. I'm unable to login to admin panel on my self hosted bitwarden cause never receive the mail containing authentication token.

I looked at the log and no error was found.

**Comment by atomheartother** [comment]
Any news on this? This is still a thing.

**Comment by kspearrin** [comment]
Your logs don't show any errors, so it is assumed that the email was sent to the SMTP server. Have you checked your SMTP server logs to see if it received the email to send out?

**Comment by atomheartother** [comment]
There isn't an SMTP server log I can access, the addresses are all Google accounts. As far as bitwarden is concerned though the mails do send... Is there _no_ conceivable bug which could affect all emails except password hints?

It's possible that this is Google being a pain, however before setting up a custom email server and all that jazz just to debug this I'd like to know if there's the slightest possibility it could be on bitwarden's end haha

**Comment by kspearrin** [comment]
I can't think of a reason why certain emails would send and not others. They all flow through the same email pipeline.

**Comment by atomheartother** [comment]
I just made a test yopmail account and set it as admin in `global.override.env` - they also don't receive any email. The plot thickens.

For the record **account creation** still works too, you get your confirmation email just fine - you just can't accept invitations to organizations.

**Comment by kspearrin** [comment]
Can you test switching the SMTP server to another one?

**Comment by atomheartother** [comment]
@kspearrin Alright, so it was that. I still do not for the life of me understand why OVH was dropping some Bitwarden emails and not others, though I suspect it may have had to do with email length maybe???

Anyway sorry for bothering you. This is not a bug with Bitwarden.

**Comment by Pofilo** [comment]
@atomheartother You confirm that confirmations emails (only those ones) are not sent through the OVH SMTP server ? I have the same behavior with no logs ...

**Comment by atomheartother** [comment]
> @atomheartother You confirm that confirmations emails (only those ones) are not sent through the OVH SMTP server ? I have the same behavior with no logs ...

What was going through:
- User password hints
- User registration emails

What wasn't going through:
- Organization invitations
- Admin area login email

**Comment by Raptor039** [comment]
Hi,

thank you all for investigate our problem. My bitwarden instance is hosted by OVH too and use their smtp server to send mails.

I will open soon an incident in OVH to solve this issue. I hope to come back here with an answer wich will able to globally solve our problem.

**Comment by Pofilo** [comment]
> 
> 
> Hi,
> 
> thank you all for investigate our problem. My bitwarden instance is hosted by OVH too and use their smtp server to send mails.
> 
> I will open soon an incident in OVH to solve this issue. I hope to come back here with an answer wich will be able to globally solve our problem.

Okay, thank you, it seems their SMTP server is not working, but only for the "Verification Email" in my case, all other mails seem to work (the "Welcome Email" for example).
