### ISSUE TITLE
Self-hosted accounts have disappeared after upgrade.

### ISSUE THREAD

**Issue by mikemc303** [bitwarden/server#683]
I'm having very strange and urgent problem where, after updating to the last version of docker and the bitwarden self-hosted server, my account that stores my passwords is no longer accessible. When I try to login, it says invalid username or password (I know for sure it's correct). I cannot see anything wrong with the configuration and everything starts up fine with no errors. How do I figure out where my account has gone? I cannot currently access my passwords from any of my clients or via the web interface.

Server: Ubuntu 18.04.4 LTS
Docker: 19.03.6
Bitwarden Server: 1.33.1

Is there a way to see if the system has successfully loaded account information? Please let me know the best way to diagnose this problem. Thanks!

**Comment by mikemc303** [comment]
I've configured admin login access and it confirms that no accounts are being recognised by the system:

<img width="1128" alt="Screenshot 2020-03-31 at 14 37 29" src="https://user-images.githubusercontent.com/1325720/78032682-4e3d1480-735d-11ea-8367-dd798c518c70.png">

**Comment by mikemc303** [comment]
Managed to successfully restore from a backup file after putting the DB in to single user mode and restoring per online instructions. Still no idea why the accounts disappeared in the first place.

**Comment by kspearrin** [comment]
It's hard to say without more evidence, but that should never happen.

**Comment by Kuuchuu** [comment]
Just had the same issue. All accounts gone

**Comment by adamveld12** [comment]
I had the same problem, I reverted to `bitwardenrs/server:1.20.0` and all of my data was still there. It seems like going from 1.20 to 1.21+ is where the issue is.
