### ISSUE TITLE
Session expired on login in chromium

### ISSUE THREAD

**Issue by l0rb** [bitwarden/server#690]
When trying to login to bitwarden via the browser extension, or the web vault I'm getting the error below. It does work with other browsers (tried firefox). It seems that there is a `403` response from `prelogin`.
 
![bitwarden](https://user-images.githubusercontent.com/4580051/78422343-df163780-765e-11ea-9a1e-fcf182cb3bd2.png)

**Comment by Croverit** [comment]
I had a mini heart attack at the beggining knowing that all my saved passwords would be gone if the service I am counting on has some issues.
Well it's time to back up.

**Comment by Kaifeck** [comment]
I'm having the same issue in both the Chrome extension and at vault.bitwarden.com. 
The app seems to still be working for me now.

**Comment by kspearrin** [comment]
Try updating your chrome to latest version.

**Comment by l0rb** [comment]
I'm already using the latest available version for my OS which is Chromium 79.0.3945.130

**Comment by Kaifeck** [comment]
Manually updating my Brave Browser to use Chromium 80 seems to have fixed it. Thanks

**Comment by frjonsen** [comment]
Using nginx as a reverse proxy. Got this issue when my SSL certificates had expired. I'm behind a corporate proxy which injects their own certificate, which may have caused some extra issues.

**Comment by Hinton** [comment]
I don't believe this is an issue any longer since we haven't had reports of this for a long time. So I'm going to close this for now. If anyone is still experiencing issues feel free to re-open it.
