### ISSUE TITLE
Domain Equivalency List: Possible small error

### ISSUE THREAD

**Issue by setyb** [bitwarden/server#691]
The domain equivalency list includes these equivalents:

> alibaba.com, aliexpress.com, aliyun.com, net.cn, www.net.cn

Is there any need to have both `net.cn` and `www.net.cn`?  Is it perhaps a special case because `net` is also a TLD?

**Comment by kspearrin** [comment]
Honestly, I am not sure. Do you use these Chinese websites? Do you know the differences?

**Comment by setyb** [comment]
I have used some of them, but not all.  I don't have logins for any of them.

Is there any case where having both `anything.com` and `www.anything.com` listed as equivalents would be necessary?

**Comment by kspearrin** [comment]
I cannot think of a case where that would be necessary.
