### ISSUE TITLE
API 500 errors for most actions: Procedure or function 'Event_Create' expecting different parameters

### ISSUE THREAD

**Issue by hedgehog1029** [bitwarden/server#698]
Hi,

Recently my Bitwarden installation started throwing 500 errors when performing tasks. The task *is* actually performed, it seems to be a failure in the event logging portion, as it throws the error: `Procedure or function 'Event_Create' expects parameter '@PolicyId', which was not supplied.`

Here's the full stacktrace printed: https://paste.dimdev.org/arapefuguc.php

It's possible that something went out-of-sync with the versions, but I've now pinned all the  image versions to what I believe they were previously, and the error hasn't gone away. I've also tried running the "updatedb" setup command manually, but this hasn't fixed the issue.

**Comment by kspearrin** [comment]
Instead of pinning the versions, try updating to the latest and make sure `updatedb` command is run.

**Comment by hedgehog1029** [comment]
Alright - after upgrading and running the migration, that seems to have fixed it.
I did originally try running the setup image migration with `-corev` and `-webv` specified, but I suppose backwards migrations aren't supported?

Cheers.
