### ISSUE TITLE
Docker Installed Bitwarden- Chrome extension failed to fetch

### ISSUE THREAD

**Issue by cyayung** [bitwarden/server#706]
I am able to connect via browser and app, but gets prompted failed to fetch on chrome extension

**Comment by cyayung** [comment]
Update: Failed to fetch on Google Canary. Working on normal Chrome Browser

**Comment by djsmith85** [comment]
Hi @cyayung thank you for your report. Is this still an issue? If so could you please provide more information. If the issue has been resolved, please close this issue.
