### ISSUE TITLE
Bitwarden won't load login prompts or organization accessing over VPN

### ISSUE THREAD

**Issue by cdsword** [bitwarden/server#708]
Running Bitwarden with Docker and Okta for auth. 
Accessing over SSL VPN. 

Our VM shows the Bitwarden logo and the spinner and sometimes you can login but don't get an organization. No problem accessing on-site it's just over VPN. I found that if I opened a private window, logged into Okta, then to Bitwarden it seems to work. Any ideas or other info I can provide?

**Comment by kspearrin** [comment]
Does developer tools show any issues in the network tab?

**Comment by djsmith85** [comment]
Hi @cdsword, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
