### ISSUE TITLE
Nightly backups not occurring

### ISSUE THREAD

**Issue by wriches** [bitwarden/server#711]
Running the latest docker build and nightly backups do not occur.

Presumably they rely on `cron`, but `cron` is not installed on the `2017-CU18-ubuntu-16.04` image, and neither is it installed in [the Dockerfile](https://github.com/bitwarden/server/blob/master/util/MsSql/Dockerfile).

I've entered the `bitwarden-mssql` container - I see the backup script but `cron` is not installed and I can see nothing relevant in the logs.

**Comment by kspearrin** [comment]
@Mart124 made some changes that do not use cron for backups anymore. It should happen via the backup-db.sh process.

**Comment by Mart124** [comment]
Yes you're right.
The method for SQL backups is the same as for Nginx log files rotation.
So first thing, if your Nginx log files get properly rotated, SQL backups should work.
```
# ls -1 bwdata/logs/nginx/
access.20200426_000000.log.gz
access.20200427_000000.log.gz
access.log
error.20200426_000000.log.gz
error.20200427_000000.log.gz
error.log
```

For Nginx log rotation, you should find such process :
```
# ps -ef | grep logrotate
bitwarden 11424 11150  0 Mar25 ?        00:00:00 /bin/sh /logrotate.sh loop
```

For SQL backup, you should find such process :
```
# ps -ef | grep backup-db
bitwarden 11429 11155  0 Mar25 ?        00:00:00 /bin/sh /backup-db.sh loop
```

They both loop, with big `sleep` duration until the next run.
You can find them, for example :
```
# ps -ef |grep sleep
bitwarden 20509 21544  0 00:00 ?        00:00:00 sleep 86339
bitwarden 20540 18323  0 00:00 ?        00:00:00 sleep 86398
```

One thing, if you have your `BACKUP_DB` environment variable set to `0`, then your SQL backups won't run :
https://github.com/bitwarden/server/blob/119a9501414d1317cd0369b9b5e743f51ffbdc9d/util/MsSql/entrypoint.sh#L53-L56

Hope this will help you to find your issue 👍

**Comment by rogofsky** [comment]
Thanks @Mart124 for the helpful direction.

> So first thing, if your Nginx log files get properly rotated, SQL backups should work.

Unfortunately I have the same problem with the `bitwarden-nginx` container:

```
# ls -l bwdata/logs/nginx/
total 3032
-rw-r--r--. 1 bitwarden bitwarden   47780 Apr 24 00:59 access.20200424_000000.log.gz
-rw-r--r--. 1 bitwarden bitwarden 3038174 Apr 28 05:51 access.log
-rw-r--r--. 1 bitwarden bitwarden     540 Apr 23 10:32 error.20200424_000000.log.gz
-rw-r--r--. 1 bitwarden bitwarden    5200 Apr 27 14:12 error.log
```

The process `logrotate.sh` script started by the entrypoint appears as defunct:

```
# ps -ef | grep logrotate
bitward+    35     1  0 Apr24 ?        00:00:00 [logrotate.sh] <defunct>
```
Same symptom in the `bitwarden-mssql` container:

```
# ps -ef | grep backup-db
bitward+    27     1  0 Apr24 ?        00:00:00 [backup-db.sh] <defunct>
```

> One thing, if you have your `BACKUP_DB` environment variable set to `0`, then your SQL backups won't run

As you can see, this is not the issue, since the backup script is run by the entrypoint. But it never completes for some reason.

I followed [the guide](https://help.bitwarden.com/article/install-on-premise/) to the tee, and docker is running on standard x86_64 hardware so the build should run exactly the same.

**Comment by wriches** [comment]
Thanks @Mart124 for the helpful direction.

> So first thing, if your Nginx log files get properly rotated, SQL backups should work.

Unfortunately I have the same problem with the `bitwarden-nginx` container:

```
# ls -l bwdata/logs/nginx/
total 3032
-rw-r--r--. 1 bitwarden bitwarden   47780 Apr 24 00:59 access.20200424_000000.log.gz
-rw-r--r--. 1 bitwarden bitwarden 3038174 Apr 28 05:51 access.log
-rw-r--r--. 1 bitwarden bitwarden     540 Apr 23 10:32 error.20200424_000000.log.gz
-rw-r--r--. 1 bitwarden bitwarden    5200 Apr 27 14:12 error.log
```

The process `logrotate.sh` script started by the entrypoint appears as defunct:

```
# ps -ef | grep logrotate
bitward+    35     1  0 Apr24 ?        00:00:00 [logrotate.sh] <defunct>
```
Same symptom in the `bitwarden-mssql` container:

```
# ps -ef | grep backup-db
bitward+    27     1  0 Apr24 ?        00:00:00 [backup-db.sh] <defunct>
```

> One thing, if you have your `BACKUP_DB` environment variable set to `0`, then your SQL backups won't run

As you can see, this is not the issue, since the backup script is run by the entrypoint. But it never completes for some reason.

I followed [the guide](https://help.bitwarden.com/article/install-on-premise/) to the tee, and docker is running on standard x86_64 hardware so the build should run exactly the same.

**Comment by Mart124** [comment]
From where did you run your `ps` commands ?
Host or containers ?
does `ps -ef | grep sleep` returns "big" `sleep` processes as above ? (I assume no)
Finally, what is your host OS version ?
And Docker version ?

I may have a clue, I then could come back to you with a possible fix to test.

**Comment by wriches** [comment]
> From where did you run your `ps` commands ?
> Host or containers ?

I ran those from inside the containers.

> does `ps -ef | grep sleep` returns "big" `sleep` processes as above ? (I assume no)

No it doesn't, at least not once the script processes become defunct. Before that, the `sleep` processes are indeed present.

> What is your host OS version ?

```
# cat /etc/*release
CentOS Linux release 7.8.2003 (Core)
```

> And Docker version ?

```
# docker --version
Docker version 19.03.8, build afacb8b
```

> Finally, do the processes go into `defunct` state as soon as you (re)start your containers ?

No, at first they successfully go into loop with a spawned sleep process.

**Comment by Mart124** [comment]
> I ran those from inside the containers.

I'm rather surprised by your answer, as there's no `ps` command in `nginx` container.
Do you run a modified version of the containers, or something else ?

I installed same OS and same Docker version, and had difficulties to reproduce the issue.
Every time I killed the `sleep` processes (from the host), a SQL backup DB or log rotation properly occurred, and loop script remained alive for a subsequent run.
I eventually managed to get a defunct `backup-db.sh` process after having stopped / restarted the container many times in a row. But very hard to reproduce.

Do you reproduce the issue every time you restart your containers ?
What happens if you kill the existing `sleep` processes ?

**Comment by Mart124** [comment]
Fix in #719 👍

**Comment by rogofsky** [comment]
Thanks @Mart124 for the fix!

**Comment by wriches** [comment]
Thanks @Mart124 for the fix!
