### ISSUE TITLE
Icons container not starting properly

### ISSUE THREAD

**Issue by jakobod** [bitwarden/server#724]
I am selfhosting a bitwarden instance on my server and have not been able to use the icon feature from the begin on. They just don't show up at all..

Just now, I noticed that the `bitwarden/icons` container is left in an "unhealthy" state when checking `docker ps` after starting the instance. Furthermore, the log folder is left empty which leaves no trace of why the container will not start..

I have checked `docker logs <container_id>`, but the logs are full of info about fetching certain sites favicons--So also no luck of investigating there..

What can be the problem with starting that specific container? The instance runs fine without it, but I would like to use this feature. Any help?

**Comment by kspearrin** [comment]
Is your server able to make outbound requests? The health check for the icons server checks https://yourserver.com/icons/google.com/icon.png

**Comment by jakobod** [comment]
Yes, outbound connections are not blocked by the firewall. But the server only has an ipv4 address and ipv6 is not enabled, hence it is not addressable using such addresses.
I just found this line in the container logs:
```
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://[::]:5000
```
It seems like the server is using ipv6? Can I disable this anywhere? I think that is the problem.

**Comment by jakobod** [comment]
Additionally, the icons server health check does not check `https://yourserver.com/icons/google.com/icon.png`, but `http://localhost:5000/google.com/icon.png`.
Shouldn't the accessed URI be used from a file like `env/global.override.env`? I set them there accordingly to `http://bitwarden.myserver.xyz/...`.

**Comment by kspearrin** [comment]
health check is defined as:

```
HEALTHCHECK CMD curl -f http://localhost:5000/google.com/icon.png || exit 1
```

Does https://yourserver.com/icons/google.com/icon.png work in your browser?

**Comment by rodehoed** [comment]
Hi,

We are using the commercial self hosted edition too. Our icon service is also unhealthy. Even after restarting. 

I did an update 5 days ago and to my knowledge it was 100% working before that point. But I am not 100% sure when it stopped working with the new version.

It's showing me 404 errors too in the logs. I also see 504 timeouts sometimes (behind nginx). 

And yes: https://<my domain>/icons/google.com/icon.png  is not working here.

**Comment by jakobod** [comment]
I opened port 5000 and tried connecting from my browser. It did not work.

**Comment by jakobod** [comment]
Another thing I could think of is the docker option
```
"iptables": false
```
in `/etc/docker/daemon.json`. Docker messed up my firewall settings without it. I disabled that and now the container works as expected. I'll have to find a way to set the iptables manually I guess, since I really don't want docker to alter them after my firewall rules are set.
