### ISSUE TITLE
[Can't save/or Login] bitwarden-mssql container restarting or not working after update/s

### ISSUE THREAD

**Issue by Joshndroid** [bitwarden/server#725]
Hello,
I have just done an update of Docker to version - Docker Engine v 19.03.8
I have also updated local bitwarden installation with cert renewal, nothing out of the ordinary.

I have noticed the docker bitwarden-mssql container is flaky and shows as running then will sit as restarting. I cannot save passwords due to this. Everything it

Log in docker container lists (for bitwarden-mssql)

> 2020-05-12 02:39:37.35 Server      The licensing PID was successfully processed. The new edition is [Express Edition].
ERROR: BootstrapSystemDataDirectories() failure (HRESULT 0x80070001)
ERROR: BootstrapSystemDataDirectories() failure (HRESULT 0x80070001)
ERROR: BootstrapSystemDataDirectories() failure (HRESULT 0x80070001)

The powershell error (when updating) lists -

> Pausing 60 seconds for database to come online. Please wait...
1.33.1: Pulling from bitwarden/setup
Digest: sha256:ceaaa30350dca9dac12bf43e888947cec87633da4f0ab125e89a3e6f9d64ecdb
Status: Image is up to date for bitwarden/setup:1.33.1
docker.io/bitwarden/setup:1.33.1
Migrating database.
Unhandled exception. System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)
 ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000001, 11): Resource temporarily unavailable
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.GetHostAddresses(String hostNameOrAddress)
   at System.Data.SqlClient.SNI.SNITCPHandle.Connect(String serverName, Int32 port, TimeSpan timeout)
   at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)
   at Bit.Setup.Program.MigrateDatabase(Int32 attempt) in /home/appveyor/projects/server/util/Setup/Program.cs:line 193
   at Bit.Setup.Program.Update() in /home/appveyor/projects/server/util/Setup/Program.cs:line 140
   at Bit.Setup.Program.Main(String[] args) in /home/appveyor/projects/server/util/Setup/Program.cs:line 65
ClientConnectionId:00000000-0000-0000-0000-000000000000
Database update complete

Things I've tried
Running bitwarden update again.
A full reboot does not seem to fix the issue.
Manually trying to start/stop/restart the bitwarden-mssql container does not seem to fix it.
I even tried to play around with firewall as port within container inspect stats listed as not binded (but it doesn't seem to bind whether stopped or running so not sure).

Typically the server has been running fine for long periods then something has broken it at various times, be it a bitwarden update or a docker update. My thoughts at this time that it might be a docker update causing the issue with bitwarden but you will obviously know more @kspearrin 

Let me know if you need any further stats or logs or something that I can provide.
My install is basically useless other than for retrieving passwords at this point lol.

**Comment by kspearrin** [comment]
Looks to be a volume mapping issue. Maybe latest docker version broke that somehow on Windows. It wouldn't be the first time.

**Comment by kspearrin** [comment]
See https://github.com/microsoft/mssql-docker/issues/602

**Comment by Joshndroid** [comment]
Sigh... Docker... that's all i'll say.
for others with this issue whom manage to find this -

> Docker response: This is a regression in Docker. We will fix it. This ticket can be duped against docker/for-win#6646.

**Comment by Zamotic** [comment]
For those with this issue, this post from docker appears to have a pre-release version with a fix in place:
https://github.com/docker/for-win/issues/6646#issuecomment-630697669

**Comment by Joshndroid** [comment]
Can confirm that the pre-release does work to fix syncing bitwarden clients to the docker server.
