### ISSUE TITLE
Password reset - No compatible authentication mechanisms found

### ISSUE THREAD

**Issue by abctaylor** [bitwarden/server#734]
![image](https://user-images.githubusercontent.com/30197206/82086592-a13d1200-96e6-11ea-9cd0-12070cc1c0f0.png)

I'm running 2.13.2 on Ubuntu 18.04 LTS. I'm hitting this error on a fresh installation. The mail environment works fine and the error text is confusing. The logs do not shed any light.

I can definitely connect to my SQL server, tested using sqlcmd with the credentials that `global.override.env` uses.

Andrew

**Comment by kspearrin** [comment]
Did you look at logs for IDentity and Api containers?

**Comment by abctaylor** [comment]
All that's visible in each:

Identity
`2020-04-08 22:26:41.308 +00:00 [Information] Identity started.`

Api:
`2020-05-15 15:20:39.688 +00:00 [Information] Api started.
2020-05-15 18:55:13.746 +00:00 [Information] Api started.
2020-05-15 19:00:00.075 +00:00 [Information] Starting job "AliveJob" at 05/15/2020 19:00:00.
2020-05-15 19:00:00.080 +00:00 [Information] It's alive!
2020-05-15 19:00:00.086 +00:00 [Information] Finished job "AliveJob" at 05/15/2020 19:00:00.
`

**Comment by kspearrin** [comment]
Are all of your containers running without issue? Check `docker ps`

**Comment by abctaylor** [comment]
Hi Kyle - all containers look healthy (image for nicer formatting)

FWIW, this is now a _brand new installation on a brand new VM (Ubuntu 18.04 LTS)_

![image](https://user-images.githubusercontent.com/30197206/82117999-1999e680-976c-11ea-85e8-e6ba2504d1ec.png)

`root@bitwarden1-lon:~# docker ps
CONTAINER ID        IMAGE                            COMMAND             CREATED              STATUS                          PORTS                                                 NAMES
f476db90f679        bitwarden/nginx:1.33.1           "/entrypoint.sh"    About a minute ago   Up About a minute (healthy)     80/tcp, 0.0.0.0:80->8080/tcp, 0.0.0.0:443->8443/tcp   bitwarden-nginx
1d541a398891        bitwarden/admin:1.33.1           "/entrypoint.sh"    About a minute ago   Up About a minute (healthy)     5000/tcp                                              bitwarden-admin
c5863828be74        bitwarden/icons:1.33.1           "/entrypoint.sh"    About a minute ago   Up About a minute (healthy)     5000/tcp                                              bitwarden-icons
7d34ad328b11        bitwarden/attachments:1.33.1     "/entrypoint.sh"    About a minute ago   Up About a minute (healthy)                                                           bitwarden-attachments
5f51c711b9c1        bitwarden/mssql:1.33.1           "/entrypoint.sh"    About a minute ago   Up About a minute (unhealthy)                                                         bitwarden-mssql
5ea505b3b5c6        bitwarden/api:1.33.1             "/entrypoint.sh"    About a minute ago   Up About a minute (healthy)     5000/tcp                                              bitwarden-api
6e38dc4c0fa3        bitwarden/web:2.13.2             "/entrypoint.sh"    About a minute ago   Up About a minute (healthy)                                                           bitwarden-web
65927f3f3f99        bitwarden/events:1.33.1          "/entrypoint.sh"    About a minute ago   Up About a minute (healthy)     5000/tcp                                              bitwarden-events
f8d135db69d7        bitwarden/identity:1.33.1        "/entrypoint.sh"    About a minute ago   Up About a minute (healthy)     5000/tcp                                              bitwarden-identity
29652e133e07        bitwarden/notifications:1.33.1   "/entrypoint.sh"    About a minute ago   Up About a minute (healthy)     5000/tcp                                              bitwarden-notifications
root@bitwarden1-lon:~#
`

**Comment by abctaylor** [comment]
FWIW:

- The same error appears when using email 2FA for a working account
- A valid TOTP code from an authenticator app is considered incorrect by the application
- **If you enter the 2FA code from the app twice, you can access the Vault** and will be told 'An unexpected error occurred'


![image](https://user-images.githubusercontent.com/30197206/82118848-af844000-9771-11ea-8631-327d61a233e5.png)
![image](https://user-images.githubusercontent.com/30197206/82118915-27526a80-9772-11ea-80cc-948fb263ca66.png)

**Comment by abctaylor** [comment]
This seems to be the result of an SMTP server that rejects connections from the Bitwarden server IP address. Closing for now.
