### ISSUE TITLE
Problems to update data

### ISSUE THREAD

**Issue by DanielRios549** [bitwarden/server#738]
I had this problem on Firefox extension, Linux desktop app and Android app, so I think here is the best place to put this issue. So, the problem is that I cannot create and delete login, it show me erros related to JSON.

When I create:
![image](https://user-images.githubusercontent.com/11152535/82289128-74a12880-997a-11ea-8636-f076fa274c34.png)

When I delete:
![image](https://user-images.githubusercontent.com/11152535/82289152-8682cb80-997a-11ea-8f92-56b11ad75781.png)

**Comment by kspearrin** [comment]
Hi, We had some downtime earlier that may have caused this. Please try again.

**Comment by DanielRios549** [comment]
Oh man, really sorry, I thought it was a error in the code, but yeah, it is working now and there was no updates, it was an network error, thanks man.

But this issue could be usseful, fir example, instead of show erros like this to normal users, it could show a more user friendly message.
