### ISSUE TITLE
Custom Certbot DNS plugin configuration resets every time Bitwarden is updated

### ISSUE THREAD

**Issue by IamGimli** [bitwarden/server#745]
I run a self-hosted instance of Bitwarden using the provided Docker containers running on Linux. I run this instance on my own DNS Domain therefore I had to modify the updateLetsEncrypt() function in "/home/Bitwarden/bwdata/scripts/run.sh" so that certbot uses the correct DNS plugin for SSL certificate generation and renewal (in my case, the Cloudflare plugin). 

The issue is that, every time I run "./bitwarden.sh update", the "run.sh" file gets updated and the modifications I need for my SSL certificate to renew properly get wiped out. 

Would it be possible to extract the updateLetsEncrypt() function out of "run.sh" into a separate script that wouldn't get overwritten every time an update is run? An even better solution would be to use a config file for certbot settings but that would require more work.

**Comment by Mart124** [comment]
Easiest way is to generate your SSL certificate by yourself, directly from your Linux host, using `certbot`, out of Bitwarden / Docker containers then.

**Comment by IamGimli** [comment]
I don't think that would work because Bitwarden will still generate its own SSL certificates using the default settings, which will override the ones I would generate outside of Bitwarden. Unless I disable that function in "run.sh", in which case we're back to square one where I have to do that manually every time I update Bitwarden.

**Comment by Mart124** [comment]
When you configure Bitwarden you can ask it not to generate a Let's Encrypt certificate by itself.

**Comment by IamGimli** [comment]
Alright, thank you, I'll try that.

**Comment by IamGimli** [comment]
Ok, so I tried to do this and, following the instructions at https://bitwarden.com/help/article/install-on-premise/#post-install-environment-configuration I edited ./bwdata/config.yml so that ssl_managed_lets_encrypt: goes from "true" to "false", then ran "./bitwarden.sh rebuild" and "./bitwarden.sh update" but bitwarden still tries to use certbot to check for certificate renewal when I start it, which fails and keeps the service from starting. 

Shouldn't the rebuild command make it so certbot is no longer called in the update and start commands?

**Comment by kspearrin** [comment]
You need to delete the letsencrypt folder under ./bwdata so that it is no longer referenced.

**Comment by IamGimli** [comment]
I was hoping to keep it (and existing keys) and just run the SSL renewal manually outside of bitwarden scripts instead. This is really turning out to be a big pain in the butt.

**Comment by Mart124** [comment]
https://github.com/bitwarden/server/issues/436#issuecomment-578246620

> You could also configure Bitwarden, with an alternate port (let's say 44300), and without Let's Encrypt (so with self-signed certificate).
Then reverse-proxy a new virtualhost of your local webserver to 127.0.0.1: 44300, and use your local Let's Encrypt instance to generate a certificate for this virtualhost.
That's the proper way to do !

**Comment by IamGimli** [comment]
Mart124, I really appreciate the help but that's crazy. Having to setup a reverse proxy just to use a proper SSL certificate on a self-hosted instance makes no sense when I was able to modify run.sh to use the correct DNS plug-in and Bitwarden took it in stride. 

All I'm saying here is that this one function could be separated from the main run.sh script so that it doesn't get overwritten every time run.sh is updated. Please consider making this change to the script structure as I think this would be the proper way to do it. 

I love Bitwarden and I'll keep manually updating scripts every time I update if I have to but this should be a fairly simple change that would be extremely beneficial for the self-hosted crowd.

**Comment by Mart124** [comment]
By curiosity, any technical reason why you don't use the default renewal method (through web port 80) ?

Just to finish with the reverse proxy, it's rather easy to deploy, will take you some minutes only.
And it would give you some advantages, for example you won't even have to restart Bitwarden anymore, you'll just have to ask Let's Encrypt / Certbot to reload your webserver to use the renewed certificates, which will then be done without service interruption.

This is how I do, and IMO it is much simpler :)

**Comment by IamGimli** [comment]
I've tried to use http-01 as a verification method before but failed to make it work reliably using a variety of Let's Encrypt automated renewal scripts (certbot and Posh-ACME being the main ones I use). Using the DNS plugin works every time, with all of the scripts I need, so that's always what I default to. 

Reverse proxies have a place but, IMHO, this isn't one of them. They add a failure point for the availability of the service and, realistically, if that's how Bitwarden was meant to be self-hosted then there wouldn't need to be any integration of Bitwarden with certbot at all. You could just really simplify the whole thing by making Bitwarden an unsecure service that requires a reverse proxy to be secure.

I may try to switch from DNS validation to HTTP just for this one service but my previous experience with Bitwarden pretty much ignoring the "ssl_managed_lets_encrypt: false" setting in config.yml doesn't fill me with confidence.

**Comment by IamGimli** [comment]
So this morning I removed the existing certificate and requested a new one using the command used in run.sh install, which worked and provisioned new certs using the http verification but then bitwarden would no longer work (the web interface never came up). Couldn't figure out why after much troubleshooting and I'm not willing to re-install from scratch so I guess manual script updates are in my future.

**Comment by Hinton** [comment]
We currently do not support any customization of the built in certbot. It's mainly there to make the initial set up easier, and we recommend providing your own SSL certificate should you need more complex functionality.

Feel free to make a feature request in our forums if you feel that this should be included in the product. This issue will now be closed.
