### ISSUE TITLE
Updating bitwarden with no script

### ISSUE THREAD

**Issue by robina80** [bitwarden/server#749]
hi all,

so here it says to update bitwarden using the script, but i cant see it

https://bitwarden.com/help/article/updating-on-premise/

root@bw:~# ls -lah /bitwarden/bwdata/
total 56K
drwxr-xr-x 14 root root 4.0K Apr 3 16:45 .
drwxr-xr-x 3 root root 4.0K May 26 21:25 …
drwxr-xr-x 2 nobody nogroup 4.0K Apr 3 16:05 ca-certificates
drwxr-xr-x 5 nobody nogroup 4.0K Apr 3 16:05 core
drwxr-xr-x 2 root root 4.0K Apr 3 16:29 docker
drwxr-xr-x 2 root root 4.0K Apr 3 16:30 env
drwxr-xr-x 2 nobody nogroup 4.0K Apr 3 16:05 identity
drwxr-xr-x 2 nobody nogroup 4.0K Apr 3 16:05 letsencrypt
drwxr-xr-x 10 root root 4.0K Apr 3 16:05 logs
drwxr-xr-x 4 root root 4.0K Apr 3 16:05 mssql
drwxr-xr-x 2 nobody nogroup 4.0K Apr 3 16:05 nginx
drwxr-xr-x 4 nobody nogroup 4.0K Apr 3 16:05 ssl
drwxr-xr-x 2 nobody nogroup 4.0K Apr 3 16:05 web

probably because i have installed bitwarden via the “manual docker installations” way

is the only option to build a new server again and copy “.bwdata” folder over?

or copy over the 1.34 stub folder to the .bwdata folder?

thanks,
rob

**Comment by kspearrin** [comment]
If you installed Bitwarden the manual docker way then you should just pull the new images.

**Comment by robina80** [comment]
so you mean download the new 1.34 here

https://github.com/bitwarden/server/releases/tag/v1.34.0

and extract the "docker-stub.zip"

and copy it to my bwdata folder?

**Comment by robina80** [comment]
i have noticed 1.34 compared to 1.33 doesnt come with these dirs in bwdata

core
letsencrypt
logs
mssql

do i need all these or do i just need to copy the data dir over ie the "mssql"?
