### ISSUE TITLE
Can't run with custom SSL cert

### ISSUE THREAD

**Issue by DatPenguin** [bitwarden/server#750]
Hi,

I have been using bitwarden for some weeks now, but I have an Apache server working on the same server, so I had to stop the latter each time I wanted to restart bitwarden so that the certbot could bind its necessary ports, then I could start Apache again. Today, I wanted to get rid of the certbot and use my own cert. I copied it in the `bwdata/ssl` folder and modified the config.yml (file attached).

When I try to start bitwarden, I have now a critical error making nginx restart again and again : 
`2020/05/27 19:13:37 [emerg] 1#1: cannot load certificate "/etc/nginx/./ssl/cert.pem": BIO_new_file() failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/./ssl/cert.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)`

I have seen the issue #376 but the path in my logs is quite different and the solution offered in that issue does not work in my case.

Am I missing something ?

Thanks a lot.

```
#
# Note: After making changes to this file you need to run the `rebuild` or `update`
# command for them to be applied.
#
# Full URL for accessing the installation from a browser. (Required)
url: https://bitwarden.my-domain
#
# Auto-generate the `./docker/docker-compose.yml` config file.
# WARNING: Disabling generated config files can break future updates. You will be
# responsible for maintaining this config file.
# Template: https://github.com/bitwarden/server/blob/master/util/Setup/Templates/DockerCompose.hbs
generate_compose_config: false
#
# Auto-generate the `./nginx/default.conf` file.
# WARNING: Disabling generated config files can break future updates. You will be
# responsible for maintaining this config file.
# Template: https://github.com/bitwarden/server/blob/master/util/Setup/Templates/NginxConfig.hbs
generate_nginx_config: true
#
# Docker compose file port mapping for HTTP. Leave empty to remove the port mapping.
# Learn more: https://docs.docker.com/compose/compose-file/#ports
http_port: 4381
#
# Docker compose file port mapping for HTTPS. Leave empty to remove the port mapping.
# Learn more: https://docs.docker.com/compose/compose-file/#ports
https_port: 43444
#
# Docker compose file version. Leave empty for default.
# Learn more: https://docs.docker.com/compose/compose-file/compose-versioning/
compose_version:
#
# Configure Nginx for SSL.
ssl: true
#
# SSL versions used by Nginx (ssl_protocols). Leave empty for recommended default.
# Learn more: https://wiki.mozilla.org/Security/Server_Side_TLS
ssl_versions:
#
# SSL ciphersuites used by Nginx (ssl_ciphers). Leave empty for recommended default.
# Learn more: https://wiki.mozilla.org/Security/Server_Side_TLS
ssl_ciphersuites:
#
# Installation uses a managed Let's Encrypt certificate.
ssl_managed_lets_encrypt: false
#
# The actual certificate. (Required if using SSL without managed Let's Encrypt)
# Note: Path uses the container's ssl directory. The `./ssl` host directory is mapped to
# `/etc/ssl` within the container.
ssl_certificate_path: ./ssl/cert.pem
#
# The certificate's private key. (Required if using SSL without managed Let's Encrypt)
# Note: Path uses the container's ssl directory. The `./ssl` host directory is mapped to
# `/etc/ssl` within the container.
ssl_key_path: ./ssl/privkey.pem
#
# If the certificate is trusted by a CA, you should provide the CA's certificate.
# Note: Path uses the container's ssl directory. The `./ssl` host directory is mapped to
# `/etc/ssl` within the container.
ssl_ca_path:
#
# Diffie Hellman ephemeral parameters
# Learn more: https://security.stackexchange.com/q/94390/79072
# Note: Path uses the container's ssl directory. The `./ssl` host directory is mapped to
# `/etc/ssl` within the container.
ssl_diffie_hellman_path:
#
# Communicate with the Bitwarden push relay service (push.bitwarden.com) for mobile
# app live sync.
push_notifications: true
#
# Use a docker volume (`mssql_data`) instead of a host-mapped volume for the persisted database.
# WARNING: Changing this value will cause you to lose access to the existing persisted database.
# Learn more: https://docs.docker.com/storage/volumes/
database_docker_volume: false
#
# Defines "real" IPs in nginx.conf. Useful for defining proxy servers that forward the
# client IP address.
# Learn more: https://nginx.org/en/docs/http/ngx_http_realip_module.html
real_ips:
```

**Comment by cloakedch** [comment]
Your error is that the file `/etc/nginx/./ssl/cert.pem` is not available inside the nginx docker container.

When you run `docker inspect -f '{{ .Mounts }}' NGINX_CONTAINER_ID` you'll see that `./bwdata/ssl` is mapped to  `/etc/ssl`, which is also what is written in the config comments.

You should probably log into the container by running something like `docker exec -it NGINX_CONTAINER_ID /bin/bash` and check the path of the certificate. Having that extra `./` in your path is a little suspicious. Most probably you don't need to specify the path name in the config file and you can just write the file name.

**Comment by niyascript** [comment]
I am having the same issue. My self-signed cert and private key are located in the same directory ./bwdata/ssl/mydomain/cert.crt  private.key

When you suggest not specifying the path name in the config file and only the file, would that be in the bwdata/config.yml? Tested and still receiving the same error codes. Also I cannot connect to the nginx container because it never reaches a "started" state; Just restarting every few seconds.

**Comment by cloakedch** [comment]
Yes, I mean't in the config.yml file.
Did you specify the filename without './'?

**Comment by DatPenguin** [comment]
Just did so : `ssl_certificate_path: cert.pem` and `ssl_key_path: privkey.pem` in `config.yml`.

I can't connect to the container too, for the same reason as @niyascript : the container keeps restarting : `Error response from daemon: Container 6566ac0d15d89101c8061a0926188df232d003a88b10b7cb0a8a97139129bc05 is restarting, wait until the container is running`

**Comment by DatPenguin** [comment]
I fixed the issue by setting the path to `/etc/ssl/cert.pem` in the config file. Still had to remove the letsencrypt folder though.
