### ISSUE TITLE
Where is peoples my vault and organisation data stored

### ISSUE THREAD

**Issue by robina80** [bitwarden/server#751]
hi all,

just wondering where peoples my vault data is stored and where organisational data is stored, is it in the “mssql” dir?

root@bw:~# ls /bitwarden/bwdata/
BitBetter ca-certificates core docker env identity letsencrypt logs mssql nginx ssl web

thanks,
rob

**Comment by kspearrin** [comment]
The mssql directory erpsists the server's database files, yes.
