### ISSUE TITLE
Bitwarden TOTP does not work with Paypal and other Websites

### ISSUE THREAD

**Issue by Y0ngg4n** [bitwarden/server#753]
The TOTP generated by Bitwarden is not accepted by all Sites,
Tried with trimming the spaces and so on, but doesn´t change anything.

Some Websites it does not work with:
- [Paypal](https://www.paypal.com/)
- [Ubisoft](https://www.ubisoft.com)
- [Web.de](https://web.de)
- [Hetzner](https://hetzner.de)
- [Attlassian](https://www.atlassian.com)
- [GitLab](https://gitlab.com)

**Comment by Rubemlrm** [comment]
@Y0ngg4n i'm using bitwarden TOTP with Gitlab and Paypal without any problem. Do you still have any issue ?

**Comment by Y0ngg4n** [comment]
@Rubemlrm works now. Dont know if it was a temporary issue or not.
