### ISSUE TITLE
Bitwarden Update issue

### ISSUE THREAD

**Issue by asuckar** [bitwarden/server#761]
Hello,

I have followed all the steps to install Bitwarden (self-hosted) and it is working great,

I noticed one issue while updating bitwarden:
i run the following command (I scheduled a crontab task to update but I tried manually to check it also both fails):

Note: paths are all good and correct and the scripts runs correctly with error:
./bitwarden.sh updateself
./bitwarden.sh update

so the "updateself" line works great and it prints:
 _     _ _                         _            
| |__ (_) |___      ____ _ _ __ __| | ___ _ __  
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \ 
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2020, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

Docker version 19.03.10, build 9424aeaee9
docker-compose version 1.18.0, build 8dd22a9

Updated self.

but "update" line fails with the following error message:
 _     _ _                         _            
| |__ (_) |___      ____ _ _ __ __| | ___ _ __  
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \ 
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2020, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

Docker version 19.03.10, build 9424aeaee9
docker-compose version 1.18.0, build 8dd22a9

ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

Any Idea how to solve this? ( I am using CentOS 7) any additional information required?
and just a hint: the file ./bwdata/docker/docker-compose.yml is exist and if I try to run the update command from inside docker directory it works and print the following:

 _     _ _                         _            
| |__ (_) |___      ____ _ _ __ __| | ___ _ __  
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \ 
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2020, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

Docker version 19.03.10, build 9424aeaee9
docker-compose version 1.18.0, build 8dd22a9

Update not needed

Please your help is highly appreciated.

**Comment by razorness** [comment]
Facing same issue:

```
[root@docker opt]# ./bitwarden.sh update
 _     _ _                         _
| |__ (_) |___      ____ _ _ __ __| | ___ _ __
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2020, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

Docker version 19.03.11, build 42e35e61f3
docker-compose version 1.25.4, build unknown

ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

[root@xxx opt]# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: Fedora
Description:    Fedora release 31 (Thirty One)
Release:        31
Codename:       ThirtyOne
[root@xxx opt]#
```
`bitwarden.sh` is exact same file as served by `https://go.btwrdn.co/bw-sh`.

**Comment by kspearrin** [comment]
@Mart124 @mportune-bw Does this have anything to do with the recent changes to install/run scripts?

**Comment by Mart124** [comment]
Yes, found the issue, let me push a quick fix.

**Comment by Mart124** [comment]
Please see #763.

**Comment by razorness** [comment]
Can confirm, issue is fixed. 👍

**Comment by Mart124** [comment]
Thank U for your feedback 👍

**Comment by asuckar** [comment]
yes me too, it is working again, thank you all for your fast and quick support
