### ISSUE TITLE
Directory Sync: Results sometimes wrong

### ISSUE THREAD

**Issue by RogerSik** [bitwarden/server#764]
Sometimes the Directory Sync resulsts are wrong. Example there are missing users from a group but they are added to the group. The only currently fix it is, to remove the user from the group and re-add it. Then it works immediately. 

Sometime it also help to clear the sync cache. 

- bitwarden Directory Connector 2.7.0
- bitwarden Server 1.34.0 
- bitwarden Web 2.14.0

**Comment by kolja1507** [comment]
Similar (same?) issue here:

We've included just one group in BWDC's user filter but sometimes AD users outside that Office 365 group get invited to our Bitwarden organization as well. After removing them there manually, they don't get re-invited by the next Azure AD sync. This problem occurred a few times without any apparent reason. So far, we couldn't find a way to willingly reproduce this behavior.

Same versions as above:
- Bitwarden Directory Connector 2.7.0
- Bitwarden Server 1.34.0
- Bitwarden Web 2.14.0

**Comment by djsmith85** [comment]
Hi @RogerSik  it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further. 

If it needs re-opening I'll move the issue over to the [Directory-Connector repo](https://github.com/bitwarden/directory-connector)
