### ISSUE TITLE
ERROR: Service "nginx" uses an undefined network "docker_default"

### ISSUE THREAD

**Issue by JPustkuchen** [bitwarden/server#765]
Bitwarden on docker suddenly stopped working: 

`**./bitwarden.sh start**`
>  
>  _     _ _                         _
> | |__ (_) |___      ____ _ _ __ __| | ___ _ __
> | '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \
> | |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
> |_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|
> 
> Open source password management solutions
> Copyright 2015-2020, 8bit Solutions LLC
> https://bitwarden.com, https://github.com/bitwarden
> 
> ===================================================
> 
> Docker version 19.03.6, build 369ce74a3c
> docker-compose version 1.25.0, build 0a186604
> 
> ERROR: Service "nginx" uses an undefined network "docker_default"

`docker network ls:`

> NETWORK ID          NAME                              DRIVER              SCOPE
> 30fa0213698f        bridge                            bridge              local
> 840891499d88        docker_default                    bridge              local
> 3a486ad17056        host                              host                local
> f9ce64245894        nginx_proxy_published             bridge              local
> 3401952f923d        none                              null                local
> b49352a96218        portainer_default                 bridge              local

`docker ps`:

> fad8370e352b        bitwarden/nginx:1.32.0           "/entrypoint.sh"         4 months ago        Up 10 minutes (healthy)   0.0.0.0:8080->8080/tcp, 80/tcp, 0.0.0.0:8443->8443/tcp   bitwarden-nginx
> 4f3663051cdf        bitwarden/admin:1.32.0           "/entrypoint.sh"         4 months ago        Up 14 minutes (healthy)   5000/tcp                                                 bitwarden-admin
> 6d2719be8b39        bitwarden/web:2.12.0             "/entrypoint.sh"         4 months ago        Up 14 minutes (healthy)   5000/tcp                                                 bitwarden-web
> 438bbe1f9f20        bitwarden/attachments:1.32.0     "/entrypoint.sh"         4 months ago        Up 14 minutes (healthy)   5000/tcp                                                 bitwarden-attachments
> 45472c0bc202        bitwarden/notifications:1.32.0   "/entrypoint.sh"         4 months ago        Up 14 minutes (healthy)   5000/tcp                                                 bitwarden-notifications
> 548698da4cdf        bitwarden/icons:1.32.0           "/entrypoint.sh"         4 months ago        Up 14 minutes (healthy)   5000/tcp                                                 bitwarden-icons
> 853441e4ec15        bitwarden/mssql:1.32.0           "/entrypoint.sh"         4 months ago        Up 14 minutes (healthy)   1433/tcp                                                 bitwarden-mssql
> a2f102c82a06        bitwarden/api:1.32.0             "/entrypoint.sh"         4 months ago        Up 14 minutes (healthy)   5000/tcp                                                 bitwarden-api
> 025749087b63        bitwarden/events:1.32.0          "/entrypoint.sh"         4 months ago        Up 14 minutes (healthy)   5000/tcp                                                 bitwarden-events
> cd658410e649        bitwarden/identity:1.32.0        "/entrypoint.sh"         4 months ago        Up 14 minutes (healthy)   5000/tcp                                                 bitwarden-identity
> 

I couldn't find an issue for that yet and I have no clue what happened, because we made no change to the installation. Suddenly not working anymore. Any thoughts?

**Comment by joekerna** [comment]
I have the same issue

**Comment by cscharf** [comment]
Can you specify what's attached to that network configuration, if anything? `docker network inspect docker_default`, perhaps disconnect and reconnect `fad8370e352b` to a different network?

**Comment by djsmith85** [comment]
Hi @JPustkuchen, @joekerna, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
