### ISSUE TITLE
Self hosted: Apache reverse proxy with nginx throws HTTP Error 400: The plain HTTP request was sent to HTTPS port

### ISSUE THREAD

**Issue by viceldan** [bitwarden/server#768]
Hi everybody,

I have an apache reverse proxy (a virtual machine ) in my network and like to access my bitwarden as a subfolder, like in https://mydomain.net/bitwarden/.
That's why I chose 'No' for having ssl and letsencrypt while installation. The reverse proxy uses letsencrypt.

So while installation I set the location of bitwarden in the net as mydomain.net/bitwarden/.

I updated bwdata/config.yml with the following values:
```
http_port: 5080
https_port: 5443

# This is the IP of my apache reverse proxy
real_ips:
  - 192.168.150.125 
```

Trying this locally from within my network works fine( like https://192.168.160.110:5443/#/vault ), but from outside I get the following error from nginx:

```
400 Bad Request
The plain HTTP request was sent to HTTPS port
```

Even if I explicitly type the https address in the browser.

This is the apache reverse proxy config for it:

```
<IFModule mod_ssl.c>
    <VirtualHost *:80>
        ServerName mydomain.net
        ServerAlias www.mydomain.net
        Redirect permanent / https://mydomain.net/
    </VirtualHost>

    <VirtualHost *:443>
        ServerName mydomain.net
        ServerAlias www.mydomain.net

        Protocols h2 http:/1.1

        <If "%{HTTP_HOST} == 'www.mydomain.net'">
            Redirect permanent / https://mydomain.net/
        </If>

        DocumentRoot /var/www/
        ErrorLog ${APACHE_LOG_DIR}/proxy-error.log
        CustomLog ${APACHE_LOG_DIR}/proxy-access.log combined

        SSLEngine On
        SSLCertificateFile /etc/letsencrypt/live/mydomain.net/cert.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/mydomain.net/privkey.pem
        SSLCertificateChainFile /etc/letsencrypt/live/mydomain.net/chain.pem

        # Other Apache Configuration
        SSLProxyEngine On
        SSLProxyVerify none
        SSLProxyCheckPeerCN off
        SSLProxyCheckPeerName off
        SSLProxyCheckPeerExpire off
        ProxyPreserveHost on

        RewriteEngine On
        # Many other rules here ...
        RewriteRule         ^/bitwarden/(.*)      http://192.168.160.100:5443/$1 [P,L]
        ProxyPassReverse    /bitwarden/           http://192.168.160.100:5443
    </VirtualHost>
</IFModule>
```

**How can I get rid of this http 400 Bad Request error?**

I'm not quite sure if this is an issue of bitwarden nginx or my apache reverse proxy.
I'm running other applications over my reverse proxy and they are all up and running like charm.

What I tried so far:

- Played around with trailing '/' in configs.
- In bwdata/config.yml: set 'generate_nginx_config: false' and
- Adding an error_page directive to bwdata/nginx/default.conf:

```
server {
  listen 8080 default_server;
  listen [::]:8080 default_server;
  server_name mydomain.net;
  # adding following line, rest is default
  error_page 497 301 =307 https://mydomain.net/bitwarden/$request_uri;
  return 301 https://mydomain.net/bitwarden/$request_uri;
}
```

- Put rewrite engine into apache config for *80 and add rewrite rule for bitwarden
```
    <VirtualHost *:80>
        ServerName mydomain.net
        ServerAlias www.mydomain.net
        RewriteRule         ^/bitwarden/(.*)      http://192.168.160.100:5080/$1 [P,L]
        ProxyPassReverse    /bitwarden/           http://192.168.160.100:5080
        # Redirect permanent / https://mydomain.net/
    </VirtualHost>
```
- and combinations of all above

Has anyone a solution for this, please?

Thank you

**Comment by cscharf** [comment]
Try adding: `ssl: off` to your nginx default.conf file, see: https://www.tecmint.com/fix-400-bad-request-in-nginx/; it appears you really want to allow both HTTP and HTTPS traffic due to the redirect to HTTPS, so the raw HTTP package is being proxied by Apache back to nginx which is causing this error, because it expects HTTPS.

**Comment by viceldan** [comment]
Thanks for your quick answer
I did:

- bwdata/config.yml: set 'generate_nginx_config: false'
- bwdata/nginx/default.conf: added 'ssl off;' ( hope that's ok, not 'ssl: off'?)
- rebuilt everything ( ./bitwarden stop => rebuild => updateself => update => updatedb => start)

But the behaviour still is the same getting the same error ...

**Comment by cscharf** [comment]
Do your rewrite rules need to be `https` by chance? (sorry, not too familiar with this configuration)
```
        RewriteRule         ^/bitwarden/(.*)      http://192.168.160.100:5080/$1 [P,L]
        ProxyPassReverse    /bitwarden/           http://192.168.160.100:5080
```
and instead be
```
        RewriteRule         ^/bitwarden/(.*)      https://192.168.160.100:5080/$1 [P,L]
        ProxyPassReverse    /bitwarden/           https://192.168.160.100:5080
```

**Comment by viceldan** [comment]
There are two blocks in my apache config, one for *80, and one for *443, as you may lookup in my config posted before.
But I try that out.

I did:
- Change in my apache reverse proxy from
```
    <VirtualHost *:80>
        ServerName mydomain.net
        ServerAlias www.mydomain.net
        Redirect permanent / https://mydomain.net/
    </VirtualHost>
```

to : 
```
    <VirtualHost *:80>
        ServerName mydomain.net
        ServerAlias www.mydomain.net
        RewriteEngine On
        RewriteRule         ^/bitwarden/(.*)      http://192.168.160.100:5080/$1 [P,L]
        ProxyPassReverse    /bitwarden/           http://192.168.160.100:5080
        #Redirect permanent / https://daniele-online.net/
    </VirtualHost>
```

- apachectl configtest => OK
- systemctl restart apache2.service => OK

Still the same error

- Did the same with the ssl ports in the *80 section:
```
    <VirtualHost *:80>
        ServerName mydomain.net
        ServerAlias www.mydomain.net
        RewriteEngine On
        RewriteRule         ^/bitwarden/(.*)      http://192.168.160.100:5443/$1 [P,L]
        ProxyPassReverse    /bitwarden/           http://192.168.160.100:5443
        #Redirect permanent / https://daniele-online.net/
    </VirtualHost>
```

with the same effect, showing the same error.

**Comment by cscharf** [comment]
Sorry if I wasn't clear what I was suggesting, you have a virtual host block for 443, `<VirtualHost *:443>`, which has `RewriteRule` and `ProxyPassReverse` to `http://` instead of `https://`, which is where I'm assuming (maybe incorrectly, sorry) you're seeing the issue. You're accepting requests on HTTPS for your domain but rewriting to the IP address at HTTP (not HTTPS). This is just a guess since you said internally going directly to the IP address at `https://` works as expected.

**Comment by cscharf** [comment]
```apache
<IFModule mod_ssl.c>
    <VirtualHost *:80>
        ServerName mydomain.net
        ServerAlias www.mydomain.net
        Redirect permanent / https://mydomain.net/
    </VirtualHost>

    <VirtualHost *:443>
        ServerName mydomain.net
        ServerAlias www.mydomain.net

        Protocols h2 http:/1.1

        <If "%{HTTP_HOST} == 'www.mydomain.net'">
            Redirect permanent / https://mydomain.net/
        </If>

        DocumentRoot /var/www/
        ErrorLog ${APACHE_LOG_DIR}/proxy-error.log
        CustomLog ${APACHE_LOG_DIR}/proxy-access.log combined

        SSLEngine On
        SSLCertificateFile /etc/letsencrypt/live/mydomain.net/cert.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/mydomain.net/privkey.pem
        SSLCertificateChainFile /etc/letsencrypt/live/mydomain.net/chain.pem

        # Other Apache Configuration
        SSLProxyEngine On
        SSLProxyVerify none
        SSLProxyCheckPeerCN off
        SSLProxyCheckPeerName off
        SSLProxyCheckPeerExpire off
        ProxyPreserveHost on

        RewriteEngine On
        # Many other rules here ...
        RewriteRule         ^/bitwarden/(.*)      https://192.168.160.100:5443/$1 [P,L]
        ProxyPassReverse    /bitwarden/           https://192.168.160.100:5443
    </VirtualHost>
</IFModule>
```

**Comment by viceldan** [comment]
YES!!!
pat-on-my-forehead! That was it. Thanks a lot for that.

I can access now the website.

There is still an error (An unexpected error occurred), but I think that's another problem.

Thanks again.
