### ISSUE TITLE
Release tag and version numbers in install script do not match

### ISSUE THREAD

**Issue by panos--** [bitwarden/server#772]
The install script found in the commit tagged v1.34.0 will actually install v1.33.1. Looking at the commit history, starting with 1.30.0 there's a commit tagged with the version number and a following commit changes the version numbers in the install scripts.

This complicates things when trying to install a specific version as it is not possible to rely on the version number tags. Instead the specific commit that updated the install scripts has to be used.

**Comment by kspearrin** [comment]
We have to update the install script after the release tag since our CI tools deploy to Docker Hub base don the release. If we updated the install script before the release we would end up with installers referencing a Docker Hub tag that does not exist yet.

What is your use case for referencing our release tags dor installation? We don't have an install path documented for doing that.

**Comment by panos--** [comment]
My use case is a Terraform configuration for deploying Bitwarden.

We recently purchased the enterprise plan and I used this opportunity to migrate our on-prem installation onto new infrastructure, codifying the deployment in Terraform.

I have to admit I took a shortcut here by not going the [manual docker installation](https://bitwarden.com/help/article/install-on-premise/#manual-docker-installations) route but instead opted to use the installer script wrapped by a little expect script (due to #408). To make this reliable I am using an immutable URL (based on the release tag) instead of https://go.btwrdn.co/bw-sh to fetch the script so the expect script can work against a known interface. I know the documentation doesn't mention immutable URLs but it's kind of what "just works" in most cases.

The reasoning behind that approach is that using the installer script I can easily install _as well as_ update Bitwarden automatically, the latter being especially important for a software like this.

So far this works great except for the migration from our old system to the new one where I thought I'd move bwdata of a 1.34.0 installation to a 1.34.0 but instead moved it to a 1.33.1 since that was the version codified in the bitwarden.sh I used on the new system. Led to subtle errors for some users...

Nevertheless since this is not a supported approach feel free to close this issue. Instead I would highly appreciate seeing progress on #408.

Thanks.

**Comment by kspearrin** [comment]
We do this same thing with our install script for the digital ocean marketplace deployments. We just download the install script from https://github.com/bitwarden/server/blob/master/scripts/bitwarden.sh and run it.

**Comment by gangadath** [comment]
How do i update from bitwarden 1.32.0 to 1.37.2, I do not want miss all the datas which i am having on the server. Please help me

**Comment by cscharf** [comment]
Hi @panos-- , hopefully Kyle's response helps in the way that we do our updates. Closing this ticket for now but please let us know if we can help further.

@gangadath , please see the following articles and if you run into undocumented issues please reach out to our [support team via our contact page](https://bitwarden.com/contact) for further assistance:
* https://bitwarden.com/help/article/updating-on-premise/
* https://bitwarden.com/help/article/install-on-premise/#script-commands-reference
