### ISSUE TITLE
Live Sync is not working

### ISSUE THREAD

**Issue by btr3** [bitwarden/server#786]
[Live Sync](https://bitwarden.com/blog/post/live-sync/) isn't working. I am using Bitwarden via bitwarden.com (not self hosted) and none of my instances are live syncing. I actively use the Firefox add-on, desktop application, android app, and iOS app. When adding a new entry via any of these methods I have to manually use the sync feature to get the updates (for each instance). This can be somewhat problematic especially on mobile as the auto-fill dialog will be out of sync until I open the app and sync manually.

**Comment by kspearrin** [comment]
This should now be resolved.
