### ISSUE TITLE
"Unable to validate installation id" error on CentOS 8

### ISSUE THREAD

**Issue by alexacallmebaka** [bitwarden/server#789]
I am trying to install Bitwarden on CentOS 8, and am running into an error very early on in the installation process. When running , `bitwarden.sh install` after I put in my installation id and installation key, I get the following error "Unable to validate installation id. Problem contacting Bitwarden server." I am not using Let's encrypt, running Docker version 19.03.12, build 48a66213fe and 
docker-compose version 1.26.0, build d4451659. This is my first time using docker, so this may be something stupid on my end. Thanks!

**Comment by kspearrin** [comment]
It seems like your docker runtime cannot access our servers. Do you have a firewall?

**Comment by alexacallmebaka** [comment]
I do not have a firewall.

**Comment by cscharf** [comment]
That issue was fixed by launching the docker container with the `--net=host` option (instead of the default `bridged`). Can you confirm what network driver your docker container is running with? Also, see: https://docs.docker.com/network/

**Comment by alexacallmebaka** [comment]
Unless Bitwarden specifies something different within it's setup, I would assume I am running with the default, "bridge". How can I use the `--net=host` option during setup to avoid this error?

**Comment by alexacallmebaka** [comment]
This issue was solved by running ```systemctl disable firewalld``` and then rebooting.
