### ISSUE TITLE
bitwarden.sh update not picking up 1.35.x

### ISSUE THREAD

**Issue by q7joey** [bitwarden/server#801]
I got the email notification of 1.35.0 on 6/26 and just got the 1.35.1 notification today, but running the "bitwarden.sh updateself" followed by "bitwarden.sh update" is not finding any new software.

**Comment by cscharf** [comment]
Client updates and bitwarden.sh are being updated today. Once those are updated you'll be able to pull the latest updates down automatically. We generally cut the release and test on our cloud platform to ensure everything is stable/solid before updating bitwarden.sh to update latest for those folks who are self-hosted.
