### ISSUE TITLE
An unexpected error occurred:requests.exceptions.ConnectionError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory

### ISSUE THREAD

**Issue by mishupaf-create** [bitwarden/server#814]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f8218916dc0>: Failed to establish a new connection: [Errno -3] Try again'))

**Comment by djsmith85** [comment]
Hi @mishupaf-create , it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
