### ISSUE TITLE
Creator of shared element able to see hidden password

### ISSUE THREAD

**Issue by lubochaton** [bitwarden/server#817]
#### Issue description
A user creating a new element can choose the property of the element. When he chooses a collection in which he is subject to the "hidden password" restriction, however, he has access to the password.

#### Steps to reproduce the issue
1. Create a collection
2. Go to the people management tab
3. Tick password hiding on your account 
4. Return in your personal vault
5. Add an element
6. Select the collection you created as owner (tick checkbox)
7. Save. Then open the element you created. You can see the password although you shouldn't

#### What's the result?
You can still see the password

#### What's the expected result?
You should not be able to see the element you just created, as you ticked the "hidden password" option on your account.
_Note that there is a way to reach that result: Reproduce the first five steps and select yourself as the owner. Save, tick the element you just created, go on options, share selected items, and tick the collection. Save. When you open the element again, you can't see the password anymore, which should also be the case when choosing directly the collection as owner._

**Comment by kspearrin** [comment]
I beleive we choose to allow the users to see the password of the item they just created until the next time their vault syncs. @cscharf @Hinton

**Comment by cscharf** [comment]
Correct, we do allow the user to temporarily view a password they have created themselves until the next vault sync, even if they create it in a collection that indicates "Hide Passwords" for them.
