### ISSUE TITLE
how to decode my password

### ISSUE THREAD

**Issue by okami-chen** [bitwarden/server#818]
when I am create an folder, than store in database ,the name value is "2.GPYIkfuKYlM6U+atDQvlzA==|WAXC0+dZfTRm3TGeagiq3w==|fq9CE9q/7lO3G3qpanP1Y1WSCHHyblLSSCvxrvjHg+Q="

how to decode this value with php?

**Comment by cscharf** [comment]
Values in the database are encrypted. They can only be decrypted with your private key (master password). The best way to do this would be to use the CLI or API in order to interact with the data which can be called via php.

**Comment by okami-chen** [comment]
can you give me an example ? java ?python?

**Comment by okami-chen** [comment]
aes + ecb + pkcs7 + 256bits ?

**Comment by cscharf** [comment]
see: https://github.com/bitwarden/jslib/blob/d308245237fe3ddc97ba4e6c1680febd47cb9b58/src/services/crypto.service.ts#L438
