### ISSUE TITLE
Manage people search box not filtering

### ISSUE THREAD

**Issue by darkmaki** [bitwarden/server#821]
## Problem
The company I work at, has a Bitwarden self-hosted docker version. Since the last update some months ago, the search box in the organization admin area does not filter while in the Manage > Pople tab. It does filter in Collections, Groups and Polices while you are writting into the search box, but it does not filter at all in People.

Inspecting the browser's console, I've seen the following errors (attached in the bitwarden_filter-people_error.txt). For security reasons I've replaced the real URL with selfhosted-url.com

### Attachaments
[bitwarden_filter-people_error.txt](https://github.com/bitwarden/server/files/4924040/bitwarden_filter-people_error.txt)

#### Docker versions running
bitwarden/nginx:1.35.1
bitwarden/admin:1.35.1
bitwarden/attachments:1.35.1
bitwarden/mssql:1.35.1
bitwarden/identity:1.35.1
bitwarden/web:2.15.1
bitwarden/api:1.35.1
bitwarden/notifications:1.35.1
bitwarden/events:1.35.1
bitwarden/icons:1.35.1

**Comment by darkmaki** [comment]
### Update

Yesterdar morning (sorry for the delay), there was a change in our self-hosted bitwarden.
Visually, the color from the navbar has changed to #1A3B66 (it's set as !important in the bg-secondary-alt class)
I've asked an none of the other admins has changed anything.
As well as this visual change, now there are not errors in the console and the search box works fine.

What is even more surprising is that the docker versions running are still being the same ones as before (1.35.1) and the docker containers has not been restarted since I opened this issue.

Is there an explanation for this change of behaviour about the error dissappearing and the color changing?
As some extra info, the server in which the docker containers are running has not been updated since the last bitwarden restart before opening the issue.

Thank you.

**Comment by kspearrin** [comment]
Sounds like a browser caching issue

**Comment by djsmith85** [comment]
Hi @darkmaki, it appears we've not heard from you about this issue in some time. While we are now closing this issue, if it continues to be a problem please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.
