### ISSUE TITLE
bitwarden.sh install does not work via proxy

### ISSUE THREAD

**Issue by vitich** [bitwarden/server#832]
```
[root@bitwarden bitwarden]# ./bitwarden.sh install
 _     _ _                         _            
| |__ (_) |___      ____ _ _ __ __| | ___ _ __  
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \ 
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2020, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

Docker version 19.03.1-ol, build ead9442
docker-compose version 1.26.2, build eefe0d31

(!) Enter the domain name for your Bitwarden instance (ex. bitwarden.example.com): bitwarden.company.com

(!) Do you want to use Let's Encrypt to generate a free SSL certificate? (y/n): y

(!) Enter your email address (Let's Encrypt will send you certificate expiration reminders): *******@gmail.com

Using default tag: latest
Trying to pull repository docker.io/certbot/certbot ... 
latest: Pulling from docker.io/certbot/certbot
Digest: sha256:e2a940dbbc1aac8e6c22e43736eb9053bec17259f58af3ae6ec8e27a8b0b2cc7
Status: Image is up to date for certbot/certbot:latest
certbot/certbot:latest
Saving debug log to /etc/letsencrypt/logs/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
An unexpected error occurred:
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='acme-v02.api.letsencrypt.org', port=443): Max retries exceeded with url: /directory (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9c588ee7f0>, 'Connection to acme-v02.api.letsencrypt.org timed out. (connect timeout=45)'))
Please see the logfiles in /etc/letsencrypt/logs for more details.
[root@bitwarden bitwarden]# echo $http_proxy
http://webproxy.host:3128
[root@bitwarden bitwarden]# echo $https_proxy
http://webproxy.host:3128
[root@bitwarden bitwarden]# echo $no_proxy
localhost, 127.0.0.0/8, 10.0.0.0/8

```

```
[root@bitwarden bitwarden]# ./bitwarden.sh install
 _     _ _                         _            
| |__ (_) |___      ____ _ _ __ __| | ___ _ __  
| '_ \| | __\ \ /\ / / _` | '__/ _` |/ _ \ '_ \ 
| |_) | | |_ \ V  V / (_| | | | (_| |  __/ | | |
|_.__/|_|\__| \_/\_/ \__,_|_|  \__,_|\___|_| |_|

Open source password management solutions
Copyright 2015-2020, 8bit Solutions LLC
https://bitwarden.com, https://github.com/bitwarden

===================================================

Docker version 19.03.1-ol, build ead9442
docker-compose version 1.26.2, build eefe0d31

(!) Enter the domain name for your Bitwarden instance (ex. bitwarden.example.com): bitwarden.company.com

(!) Do you want to use Let's Encrypt to generate a free SSL certificate? (y/n): n

Trying to pull repository docker.io/bitwarden/setup ... 
1.35.1: Pulling from docker.io/bitwarden/setup
Digest: sha256:c75ee7c297d97e440268ef7e8fb2ce0b17af0942284c080f70a3ccf69b289ac8
Status: Image is up to date for bitwarden/setup:1.35.1
bitwarden/setup:1.35.1

(!) Enter your installation id (get at https://bitwarden.com/host): ******************************************

(!) Enter your installation key: *************************

Unable to validate installation id. Problem contacting Bitwarden server.
[root@bitwarden bitwarden]# echo $http_proxy
http://webproxy.host:3128
[root@bitwarden bitwarden]# echo $https_proxy
http://webproxy.host:3128
[root@bitwarden bitwarden]# echo $no_proxy
localhost, 127.0.0.0/8, 10.0.0.0/8

```

**Comment by vitich** [comment]
```
[root@bitwarden bitwarden]# telnet webproxy.host 3128
Trying 10.100.17.77...
Connected to webproxy.
Escape character is '^]'.

```

```
[root@bitwarden bitwarden]# curl -I https://google.com
HTTP/1.1 200 Connection established

HTTP/1.1 301 Moved Permanently
Location: https://www.google.com/
Content-Type: text/html; charset=UTF-8
Date: Tue, 21 Jul 2020 11:44:03 GMT
Expires: Thu, 20 Aug 2020 11:44:03 GMT
Cache-Control: public, max-age=2592000
Server: gws
Content-Length: 220
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
Alt-Svc: h3-29=":443"; ma=2592000,h3-27=":443"; ma=2592000,h3-25=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"

```

**Comment by kspearrin** [comment]
You need to configure docker to use your proxy. See https://docs.docker.com/network/proxy/

**Comment by vitich** [comment]
> You need to configure docker to use your proxy. See https://docs.docker.com/network/proxy/

Already configured!

**Comment by vitich** [comment]
I have no problem with any application including docker-compose and docker - only with your script which, I suppose, is designed to work in a "from any to any" environment

**Comment by vitich** [comment]
> You need to configure docker to use your proxy. See https://docs.docker.com/network/proxy/

For docker:
```
[root@bitwarden bitwarden_rs]# grep PROXY /usr/lib/systemd/system/docker.service
Environment="HTTP_PROXY=http://webproxy.host:3128"
Environment="HTTPS_PROXY=http://webproxy.host:3128"
Environment="NO_PROXY=localhost, 127.0.0.0/8, 10.0.0.0/8"

```
For system:
```
[root@bitwarden bitwarden_rs]# cat /etc/profile.d/proxy.sh 
#!/bin/bash
export http_proxy="http://webproxy.host:3128"
export https_proxy="http://webproxy.host:3128"
export no_proxy="localhost, 127.0.0.0/8, 10.0.0.0/8"

```

Why can't you make the correct installer instead of a script that downloads another script, which in turn downloads another one?

**Comment by vitich** [comment]
Despite the correctly configured proxy in the system and in docker, your script tries to connect directly to your site and to the letsencrypt site via https:

```
teampass.intsrv.49834 > 172.65.32.248.https
teampass.intsrv.56340 > 104.26.10.153.https
```
I even tried using the proxy ip address instead of the hostname - the same result

**Comment by vitich** [comment]
Can you help?

**Comment by klepptor** [comment]
@vitich I also had this problem and solved it by adding my proxy settings to  ~/.docker/config.json

see [here](https://docs.docker.com/network/proxy/) also

**Comment by msusta** [comment]
@vitich Did you had any success with this in the end?

I'm also trying the install in a secured environment where the only way out is through proxy. I do have the proxy configuration available in the operating system environment, docker daemon & client configuration - hell I even pass it into the container through the bwdata/env/uid.env file as both lowercase and uppercase environment variables.
No luck for me ATM - will have to start tcpdump which is going to most likely show the dotnet app ignoring the proxy...

**Comment by msusta** [comment]
Aaaand I'm good. After more debugging within the container I found out that one of the configurations managed to pass the http proxy URL into the ENV with the surrounding "" - which (undestandably) didn't work...

@vitich Best thing is to start up the install progress till the setup container is running and then attaching to it with another terminal and testing with other tools. MS documentation for dotnet is also requiring the environment variable to be set in upppercase.

**Comment by djsmith85** [comment]
Hi @vitich, I'm closing this issue now, as it looks like @klepptor and @msusta have a viable workaround or resolution for the issue you're experiencing. Besides the issue might have/had to do with vaultwarden (formerly known as bitwarden_rs). If this is still an issue with the Bitwarden Server, please feel free to re-open this issue and provide any further information that may be helpful in reproducing the problem or helping you further.

**Comment by auerswal** [comment]
When I first read through this issue, I did not immediately understand that *three* configuration pieces are required to make the documented installation procedure work when network access must use a proxy, so I add this as a kind of summary:

1. The **docker service** needs to be configured to use the proxy e.g., for `docker pull`. This can be done by adding the `HTTP_PROXY`, `HTTPS_PROXY`, and `NO_PROXY` variables via Environment statements to, e.g., `/usr/lib/systemd/system/docker.service`.
2. The **install and run scripts** need to be configured to use the proxy by setting the `HTTP_PROXY`, `HTTPS_PROXY`, and `NO_PROXY` environment variables for the user executing the scripts, e.g., via `/etc/profile` or a file in `/etc/profile.d`.
3. The actual **Bitwarden containers**, specifically the container started via run script, need to be configured to use the proxy by adding the `HTTP_PROXY`, `HTTPS_PROXY`, and `NO_PROXY` variables by adding proxy configuration to `$HOME/.docker/config.json` as described on https://docs.docker.com/network/proxy/.

With only 1 and 2 from above, but without 3, the setup process started inside the initial container cannot access remote resources.
