### ISSUE TITLE
Port mapping 80 - 443

### ISSUE THREAD

**Issue by SwingJudge** [bitwarden/server#858]
Hi,

i try to install the BW Server on my web hosting, and i would change the ports mapping because they are already in use on my server.

I find this issue ([https://github.com/bitwarden/server/issues/108](https://github.com/bitwarden/server/issues/108)) and i have the same problem, at install, i have an error , and i don't see prompt for change the configuration of ports.

Can you help me for this please ?

thanks

**Comment by kspearrin** [comment]
Edit ./bwdata/config.yml to use the ports you want and rebuild.

**Comment by SwingJudge** [comment]
@kspearrin kspearrin
it's what i do

http_port: 82
https_port: 3012

but when i launch the docker i have this message

docker: Error response from daemon: driver failed programming external connectivity on endpoint certbot (9fdb8ce0d675049882b17c62ed14c5fd26419f1f10f62c9288c4e6a473083464): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use.

**Comment by kspearrin** [comment]
Make sure you rebuild after making changes.

**Comment by SwingJudge** [comment]
i already do this, but it's the same problem

**Comment by SwingJudge** [comment]
in the scripts.sh file, i have two function that are on ports 80 and 443, do i change this too ?

updateLetsEncrypt and forceUpdateLetsEncrypt

**Comment by kspearrin** [comment]
You cannot use let's encrypt on other ports, so you need to disable that option.

**Comment by SwingJudge** [comment]
ok i try this

**Comment by halton** [comment]
> You cannot use let's encrypt on other ports, so you need to disable that option.

Is that limited by let's encrypt or by the script? If the latter one, I think we can imporve it.
