### ISSUE TITLE
CSV export of vault includes two items that are not visible in browser plugin or web vault!

### ISSUE THREAD

**Issue by jikamens** [bitwarden/server#866]
I am not sure if the server is the right component to be filing this issue in, but I'm assuming that exports are generated on the server. Please correct me if I'm wrong.

This feel like it has security implications, though I can't put my finger on any directly.

I try to save everything to my organization, so there shouldn't be any entries in my local vault, so my export of my local vault should be empty.

I just exported my vault through the browser plugin, and the export has two entries in it. I did the same export from the web vault and the results were the same.

When I search for these entries in either the browser plugin or the web vault, the only matching entries that I can find are in my organization, not in my local vault. Furthermore, I know they're not the same entries because in one of the two cases the password I see in my vault is different from the password in the export!

Furthermore, when I search in the web vault for `>-organizationid:*`, there are no matches! So it clearly should not be possible for the export to contain any entries, and yet it contains two.

**Comment by cscharf** [comment]
@jikamens , are those 2 items in your `Trash`? We have currently have a known issue where items in the Trash are exported.

**Comment by jikamens** [comment]
Yup, that's it. I guess if you have another open issue about this there's no need for me to keep this one open. Thanks for the response.
