### ISSUE TITLE
New Device Logged In From... - wrong Source IP

### ISSUE THREAD

**Issue by mamama1** [bitwarden/server#867]
Hi,

now, that I'm finally getting E-Mails from Bitwarden ;-), I have noticed that the warning mails regarding recent access to Bitwarden show the wrong IP. In my case it is 172.23.0.1, which belongs to "docker_public".

I guess the x-forwarded-for header or something could be used to determine the true Client IP. But as that field could be manipulated by the client, maybe there is another way which would involve Docker config changes?
However in the current state, that's a bit useless, if you can't see the real IP address :-)

Regards

**Comment by cscharf** [comment]
Hi @mamama1 , the `x-forwarded-for` header really is the proper way to pass through originating IP via any reverse proxies, load balancers, etc. It is the generally accepted and universal means used by these for services to be able to capture and use the end user's IP address. If you're not passing that through in your proxy configuration, then yes, you'll always just get your docker_public IP address there.

**Comment by mamama1** [comment]
Ok thanks, I'll look into my reverse proxy configuration and report back. Didn't know, that it would fall back to Docker IPs if x-forwarded-for is not being provided.

**Comment by szaimen** [comment]
@mamama1 is this something that should get fixed inside the Nextcloud VM?

**Comment by mamama1** [comment]
i'm not sure, maybe. i'm using ms web application proxy (looking forward migrating to haproxy or something like that) and i didn't find anything about x-forwarded-for

**Comment by darkrain-nl** [comment]
Not sure if related, but I added the following to config.yml in the bwdata folder to get the real IP.

`# Defines "real" IPs in nginx.conf. Useful for defining proxy servers that forward the
# client IP address.
# Learn more: https://nginx.org/en/docs/http/ngx_http_realip_module.html
real_ips:
- 10.0.0.0/8
- 172.16.0.0/12
- 192.168.0.0/16`
