### ISSUE TITLE
Add guidelines for domain equivalences

### ISSUE THREAD

**Issue by contribucious** [bitwarden/server#884]
_Since it's technical and it concerns the management of the `Issues` / `PRs` of this repository, I post it here, on GitHub._
___
&nbsp;
### Hello,
&nbsp;
Like me, you've probably seen this in the news recently:
:key: [Apple publishes free resources to improve password security](https://www.zdnet.com/article/apple-publishes-free-resources-to-improve-password-security/)

#### :arrow_right_hook: Main links contained in this news: [Apple news](https://developer.apple.com/news/?id=06052020a&1591373342) and [Project on GitHub](https://github.com/apple/password-manager-resources).
&nbsp;
&nbsp;
&nbsp;
# :heavy_multiplication_x: What this issue _isn't_ about
Besides the fact that interfacing with this open project, in the long term, would be interesting _(less work on changing data, more time for the core)_, that is **not** what I would like to discuss.

:arrow_right_hook: Interesting although ... for the part of domain equivalences (this project being larger than just this part), for a smooth transition concerning Bitwarden, it would be probably much easier to manage if a name / ID would be available for each group (requested [here](https://github.com/apple/password-manager-resources/issues/161)) since Bitwarden [uses this system](https://github.com/bitwarden/server/blob/66e67d2172f1bf851765168efca73f6172f60381/src/Core/Utilities/StaticStore.cs) to easily determine which groups are overridden by a user's preferences, if I'm not mistaken.
&nbsp;

# :heavy_check_mark: What this issue _is_ about
It would rather be about adding _(clear)_ guidelines regarding the addition of equivalent domains here, mainly what this term means more precisely for Bitwarden in a short way, as on this new Apple project [available on GitHub](https://github.com/apple/password-manager-resources), while the list is still at a manageable level (currently [83 groups](https://github.com/bitwarden/server/blob/66e67d2172f1bf851765168efca73f6172f60381/src/Core/Enums/GlobalEquivalentDomainsType.cs)).
&nbsp;

# :bulb: Let's try to define this term first
Basically, from the broadest to the narrowest sense, the term "domain equivalences" can mean four things, in my opinion:

#### 1) In the broadest sense, it includes _any_ domain name of the same group sharing the same login, including domain names which are only simple redirects. _That seems to be the current situation._ :information_source:

:arrow_right: **Current example:** `GlobalEquivalentDomainsType.Microsoft` with `windows.com` or `microsoftstore.com` both redirecting to `microsoft.com`.
&nbsp;

#### 2) In a fairly broad sense, it includes _any standalone_ domain name of the same group sharing the same login, including "little brothers" websites (which require going to the "big brother" website to do the login action).

:arrow_right: **Current example:** `GlobalEquivalentDomainsType.Yandex` with `ya.ru` — very light website where any action that may require logging in is only available on `yandex.ru` (big brother) and therefore will always happen from there, on this domain name, where you can log in.
&nbsp;

#### 3) In an even narrower sense, it includes _any standalone_ domain name _(of the same group sharing the same login)_ where the login link MUST BE available on the website present on THIS domain name — i.e. without first having to go via clicks through a "big brother" website to do so.

:arrow_right: **Current example:** `GlobalEquivalentDomainsType.Google` with `youtube.com` — the login link is directly accessible on the website available on _this_ domain name, leading directly to the login page available at `accounts.google.com`, without first going through a "big brother" website (which would be `google.com` in this example).
&nbsp;

#### 4) In the most restricted sense, and it's the one chosen by Apple (@apple), it only groups together related domain names where a login page is available _on them_ and which share the same login of course.

:arrow_right: **Current example:** `GlobalEquivalentDomainsType.Amazon` with `amazon.fr` or `amazon.de`.
&nbsp;

### ILLUSTRATIVE RULE FOR THIS ONE:
_(to be ticked, next to another in the same category, during a pull request like [this one](https://github.com/apple/password-manager-resources/pull/212) on the Apple project)_
> **for websites-with-shared-credential-backends.json**
> - [x] The new group serves login pages on each of the included domains, and those login page accept accounts from the others. (For example, we don't associate google.co.il to google.com, because google.co.il redirects to accounts.google.com for authentication.)

:arrow_right_hook: You can easily see that with this method, the currently present entry `youtube.com` would be excluded from the `GlobalEquivalentDomainsType.Google` list, unlike method n°3.

... Because like `google.co.il`, it redirects to `accounts.google.com` for authentication — i.e. no login page available on `youtube.com` itself.
&nbsp;

# :thought_balloon: My opinion
IMHO, the method currently used by Bitwarden (i.e. the n°1 it seems) is not useful. Except to say that the user could have _manually_ added these redirectional domain names in their vault, but the list may be very long to manage if done globally by Bitwarden; example with the case of Amazon which reserves almost all the TLDs and redirects them (those of countries in particular, to the TLD of the nearest country having an Amazon website typically). And after all ... the user is free to customize that on his side if really needed, anyway.
&nbsp;

# :question: Now ...
1. Would it not be better for Bitwarden, if only for the sake of simplicity, to move from method n°1 to method n°4? At the very least, to method n°3?
&nbsp;
:arrow_right_hook: **What is your opinion on this question?**
&nbsp;
:arrow_right_hook: **Note:**
As a bonus with method n°4, in addition to the drastic reduction of current entries, the transition to [this outsourced common system](https://github.com/apple/password-manager-resources/blob/main/quirks/websites-with-shared-credential-backends.json) would be even easier in the long term, if it's carried out one day. And contributors could contribute _with identical content_ on both sides in the meantime, which is simpler for them. Both to the specific Bitwarden project and to this project open to all _password managers_ (mainly). Bringing a better experience in a more global way to users.

2. _**In any case**_, shouldn't it be made clear via guidelines what "equivalent domains" currently means for Bitwarden? Maybe when opening an issue or PR here, in one way or another (by using a template, etc.), refer to the immediate meaning of this term as Apple has chosen to do **OR** to a Bitwarden _help link_ on this?
&nbsp;
:arrow_right_hook: **Opinion on this also?**
&nbsp;
:arrow_right_hook: **Note:**
_Help page_ still to be created in this last case because nothing on this subject currently in the help, according to a [quick search](https://bitwarden.com/help/search/?q=Equivalent+domains).
&nbsp;
&nbsp;
___
#### _Particularly intended for:_&nbsp; @kspearrin @cscharf @mportune-bw

**Comment by cscharf** [comment]
Hi @contribucious , my apologies for responding so late to this but now getting some time to review and circle back on several number of PRs for equivalent domains and I tend to agree with your assessment of using method n°4 listed above similar to that of Apple's approach. I'll stub out a card on our board for this, although contributions are definitely welcome, even if that perhaps was utilizing the same JSON format referenced but as an embedded resource (for now).

**Comment by contribucious** [comment]
@cscharf No problem. Great! :v: :wink:
