### ISSUE TITLE
import license: version 6 not supported

### ISSUE THREAD

**Issue by mamama1** [bitwarden/server#888]
Hi

I've got a self-hosted Bitwarden installation and a 2 seat Enterprise (annual) license.
One account on my installation has been activated with the license but when I yesterday wanted to activate the license with a second user, Bitwarden threw an error at me, saying that version 6 isn't supported (huh?).

I can't rule out that I made a mistake somewhere as I find the whole organization, admin panel and licensing thing extremely misleading and obscure.

Just give us an admin panel for importing licenses and assigning them to users :-)

What's the cause? What logs do you need?

Thanks

**Comment by Greenderella** [comment]
Are you trying to upload your Enterprise license two times in two different accounts? 

If you have an Enterprise organization license in order to invite more users you need to follow this steps: https://bitwarden.com/help/article/managing-users/

**Comment by mamama1** [comment]
Thanks, makes sense. See what I mean by "misleading"? The whole structure of the admin/licensing/config menus is just too confusing, imho. I may also be stupid but honestly, I'm quite sure I'm kinda not too stupid, really :)

**Comment by sPaCeMoNk3yIam** [comment]
I have a similar problem:
I activated my family licence on my on-premise hosted server. It seems like I can only add attachments to the collection entries of the organisation, not the personal vaults of neither the online or on-premise user.
So to sum it up: Attachments only work for entries within the collections of the organisation, online or on-premise. They are not working for the user's personal vault entries. This seems odd and not expected.

**Comment by Greenderella** [comment]
@sPaCeMoNk3yIam that is the intended behaviour, if you need attachments on items in your personal vault you will need a Premium membership not a Family organization license: https://bitwarden.com/help/article/attachments/
