### ISSUE TITLE
When exporting data, Russian letters turn into "????"

### ISSUE THREAD

**Issue by amd838** [bitwarden/server#917]
When exporting data, Russian letters turn into "????"
i tried exporting to csv and json

**Comment by addisonbeck** [comment]
I'm having trouble getting this to happen for me. Could you provide a few characters that are breaking in the export? I used everything in the below list, and all output as expected for CSV and JSON.

`А а, Б б, В в, Г г, Д д, Е е, Ё ё, Ж ж, З з, И и, Й й, К к, Л л, М м, Н н, О о, П п, Р р, С с, Т т, У у, Ф ф, Х х, Ц ц, Ч ч, Ш ш, Щ щ, Ъ ъ, Ы ы, Ь ь, Э э, Ю ю, Я я`

**Comment by cscharf** [comment]
Hi @amd838 , we haven't heard from you in a while. We were not able to reproduce this issue, if this is still a problem for you please feel free to re-open this issue and provide more detail such as what program you're using to re-open the file, which browser you're using to generate the export, etc.
