### ISSUE TITLE
Update Issue - Update Not Needed?

### ISSUE THREAD

**Issue by dohlin** [bitwarden/server#940]
./bitwarden.sh updateself runs fine, but when I run ./bitwarden.sh update I get a message saying "Update not needed" and it terminates.  I'm trying to update to server 1.37.1/web v2.16.1...my admin dashboard even confirms that I'm still on 1.37.0/2.16.0.  What's up?  Is this to be expected?  I've never had issues with the update process before.

**Comment by lschober-bw** [comment]
Hi dohlin,

Server images were recently pushed to Docker Hub. It may take a bit for them to propagate. If you try updating now, the new version of the images should be pulled by the update script.

**Comment by dohlin** [comment]
Sure enough that worked, thanks!! I wondered if that wasn't what was going on but I had never encountered it before.  Thanks again!
