### ISSUE TITLE
On premise activation failed

### ISSUE THREAD

**Issue by sicarii-13** [bitwarden/server#941]
Hi I ran into a little bug whilte trying to activate our on premise version. 
I also had a work around for it. 

While trying to activate from the user settings it gives me the error code not supported from version 6 on the lastest on premise. When trying to make an organisation you  also get a form field requesting to upload a license file from there it does work.

**Comment by kspearrin** [comment]
It sounds like you were trying to use an organization license in the place where you would use a user premium license.

**Comment by sicarii-13** [comment]
That sounds about right, couldn't make that up from the error.
