### ISSUE TITLE
Self hosted with apache reverse proxy - Unexpected error

### ISSUE THREAD

**Issue by viceldan** [bitwarden/server#946]
Hello everybody,

I've setup bitwarden on a VM (192.168.160.112), using my apache reverse proxy VM (192.168.150.25).   
Requests from https://mydomain.net/bitwarden/ Port 443 => reverse Proxy is directed to  5443 on the bitwarden VM.   
Requests from https://mydomain.net/bitwarden/ Port 80 => reverse Proxy is directed to 5080 on the bitwarden VM.   
The ssl certificate (a letsencrypt cert) is copied (on a regulary basis by a cronjob) from the proxy to the bitwarden VM.

Internal access is ok over https://192.168.160.112:5443/   
From there I could create the first login.   

Doing the same from outside:  https://mydomain.net/bitwarden/#/   
* I can see the login page
* I can fill out the form
* But when I try to send the request, I get "unexpected error"

Well, the whole point of giving bitwarden a good try is to access my passwords from everywhere, so local access should be only good for testing purposes, I think.

I went trough the posts and other related google findings, but I can not see where I went wrong.   

These are my config files so far. I think it's just a small thing that I'm missing, but until now I didn't find it yet...   
Could someone just put a finger on it and say *"Easy, it's just ... Only enter this into your config ..."*   :-)   

**On my reverse proxy:**   

/etc/apache2/sites-enabled/proxy.conf:   

    <IFModule mod_ssl.c>
        <VirtualHost *:80>
            ServerName mydomain.net
            ServerAlias www.mydomain.net
            # Next three lines maybe not necessary, was a desperate test.
            RewriteEngine On
            RewriteRule         ^/bitwarden/(.*)      https://192.168.160.112:5080/$1 [P,L]
            ProxyPassReverse    /bitwarden/           https://192.168.160.112:5080
            Redirect permanent / https://mydomain.net/
        </VirtualHost>

        <VirtualHost *:443>
            ServerName mydomain.net
            ServerAlias www.mydomain.net

            Protocols h2 http:/1.1

            <If "%{HTTP_HOST} == 'www.mydomain.net'">
                Redirect permanent / https://mydomain.net/
            </If>

            DocumentRoot /var/www/
            ErrorLog ${APACHE_LOG_DIR}/proxy-error.log
            CustomLog ${APACHE_LOG_DIR}/proxy-access.log combined

            SSLEngine On
            SSLCertificateFile /etc/letsencrypt/live/mydomain.net/cert.pem
            SSLCertificateKeyFile /etc/letsencrypt/live/mydomain.net/privkey.pem
            SSLCertificateChainFile /etc/letsencrypt/live/mydomain.net/chain.pem

            # Other Apache Configuration
            SSLProxyEngine On
            SSLProxyVerify none
            SSLProxyCheckPeerCN off
            SSLProxyCheckPeerName off
            SSLProxyCheckPeerExpire off
            ProxyPreserveHost on

            RewriteEngine On
            # Other rewrites here into different VMs ...
            ...
            RewriteRule         ^/bitwarden/(.*)      https://192.168.160.112:5443/$1 [P,L]
            ProxyPassReverse    /bitwarden/           https://192.168.160.112:5443
        </VirtualHost>
    </IFModule>

Entry in crontab on proxy to update the ssl cert on the bitwarden VM:

    # m h  dom mon dow   command
    0 1 * * * scp /etc/letsencrypt/live/mydomain.net/fullchain.pem /etc/letsencrypt/live/mydomain.net/privkey.pem 192.168.160.112:/root/bitwarden/bwdata/ssl/mydomain.net

**On my bitwarden VM:**   

My config.yml file, residing in /root/bitwarden/bwdata :   

    # 
    # Note: After making changes to this file you need to run the `rebuild` or `update`
    # command for them to be applied.
    # 
    # Full URL for accessing the installation from a browser. (Required)
    url: http://mydomain.net/bitwarden/
    # 
    # Auto-generate the `./docker/docker-compose.yml` config file.
    # WARNING: Disabling generated config files can break future updates. You will be
    # responsible for maintaining this config file.
    # Template: https://github.com/bitwarden/server/blob/master/util/Setup/Templates/DockerCompose.hbs
    generate_compose_config: true
    # 
    # Auto-generate the `./nginx/default.conf` file.
    # WARNING: Disabling generated config files can break future updates. You will be
    # responsible for maintaining this config file.
    # Template: https://github.com/bitwarden/server/blob/master/util/Setup/Templates/NginxConfig.hbs
    generate_nginx_config: true
    # 
    # Docker compose file port mapping for HTTP. Leave empty to remove the port mapping.
    # Learn more: https://docs.docker.com/compose/compose-file/#ports
    http_port: 5080
    # 
    # Docker compose file port mapping for HTTPS. Leave empty to remove the port mapping.
    # Learn more: https://docs.docker.com/compose/compose-file/#ports
    https_port: 5443
    # 
    # Docker compose file version. Leave empty for default.
    # Learn more: https://docs.docker.com/compose/compose-file/compose-versioning/
    compose_version: 
    # 
    # Configure Nginx for SSL.
    ssl: true
    # 
    # SSL versions used by Nginx (ssl_protocols). Leave empty for recommended default.
    # Learn more: https://wiki.mozilla.org/Security/Server_Side_TLS
    ssl_versions: 
    # 
    # SSL ciphersuites used by Nginx (ssl_ciphers). Leave empty for recommended default.
    # Learn more: https://wiki.mozilla.org/Security/Server_Side_TLS
    ssl_ciphersuites: 
    # 
    # Installation uses a managed Let's Encrypt certificate.
    ssl_managed_lets_encrypt: false
    # 
    # The actual certificate. (Required if using SSL without managed Let's Encrypt)
    # Note: Path uses the container's ssl directory. The `./ssl` host directory is mapped to
    # `/etc/ssl` within the container.
    ssl_certificate_path: /etc/ssl/mydomain.net/fullchain.pem
    # 
    # The certificate's private key. (Required if using SSL without managed Let's Encrypt)
    # Note: Path uses the container's ssl directory. The `./ssl` host directory is mapped to
    # `/etc/ssl` within the container.
    ssl_key_path: /etc/ssl/mydomain.net/privkey.pem
    # 
    # If the certificate is trusted by a CA, you should provide the CA's certificate.
    # Note: Path uses the container's ssl directory. The `./ssl` host directory is mapped to
    # `/etc/ssl` within the container.
    ssl_ca_path: /etc/ssl/mydomain.net/fullchain.pem
    # 
    # Diffie Hellman ephemeral parameters
    # Learn more: https://security.stackexchange.com/q/94390/79072
    # Note: Path uses the container's ssl directory. The `./ssl` host directory is mapped to
    # `/etc/ssl` within the container.
    ssl_diffie_hellman_path: 
    # 
    # Communicate with the Bitwarden push relay service (push.bitwarden.com) for mobile
    # app live sync.
    push_notifications: true
    # 
    # Use a docker volume (`mssql_data`) instead of a host-mapped volume for the persisted database.
    # WARNING: Changing this value will cause you to lose access to the existing persisted database.
    # Learn more: https://docs.docker.com/storage/volumes/
    database_docker_volume: false
    # 
    # Defines "real" IPs in nginx.conf. Useful for defining proxy servers that forward the 
    # client IP address.
    # Learn more: https://nginx.org/en/docs/http/ngx_http_realip_module.html
    real_ips:
    - 192.168.150.25

My global.override.env, residing in /root/bitwarden/bwdata/env/:

    globalSettings__baseServiceUri__vault=http://mydomain.net/bitwarden/
    globalSettings__baseServiceUri__api=http://mydomain.net/bitwarden//api
    globalSettings__baseServiceUri__identity=http://mydomain.net/bitwarden//identity
    globalSettings__baseServiceUri__admin=http://mydomain.net/bitwarden//admin
    globalSettings__baseServiceUri__notifications=http://mydomain.net/bitwarden//notifications
    globalSettings__sqlServer__connectionString="Data Source=tcp:mssql,1433;Initial Catalog=vault;Persist Security Info=False;User ID=sa;Password=XXXRedactedPasswordXXX;MultipleActiveResultSets=False;Connect Timeout=30;Encrypt=True;TrustServerCertificate=True"
    globalSettings__identityServer__certificatePassword=XXXRedactedPasswordXXX
    globalSettings__attachment__baseDirectory=/etc/bitwarden/core/attachments
    globalSettings__attachment__baseUrl=http://mydomain.net/bitwarden//attachments
    globalSettings__dataProtection__directory=/etc/bitwarden/core/aspnet-dataprotection
    globalSettings__logDirectory=/etc/bitwarden/logs
    globalSettings__licenseDirectory=/etc/bitwarden/core/licenses
    globalSettings__internalIdentityKey=XXXSomeFreakyKeyXXX
    globalSettings__duo__aKey=XXXSomeFreakyKeyXXX
    globalSettings__installation__id=XXXSomeInstallationIDXXX
    globalSettings__installation__key=XXXInstallationKeyXXX
    globalSettings__yubico__clientId=REPLACE
    globalSettings__yubico__key=REPLACE
    globalSettings__mail__replyToEmail=my@mydomain.de
    globalSettings__mail__smtp__host=my.provider.com
    globalSettings__mail__smtp__port=587
    globalSettings__mail__smtp__ssl=true
    globalSettings__mail__smtp__username=smtpuser
    globalSettings__mail__smtp__password=mysmtppass
    globalSettings__disableUserRegistration=false
    globalSettings__hibpApiKey=REPLACE
    adminSettings__admins=
    globalSettings__mail__smtp__trustServer=true

**Comment by cscharf** [comment]
So I'm certainly not an expert on any of this but just some things that stand out upon initial review:

* You have port 80 redirect rules to `https://192.168.160.112:5080`, which is okay, exception you're rewrite rule is using `https` protocol but mapping to an http port (5080)
* Check the URLs in your global.override.env file: i.e. `globalSettings__baseServiceUri__api` has a double `//` in the URL (which is not a valid path), `globalSettings__baseServiceUri__identity=http://mydomain.net/bitwarden//identity` for example, will fail when the API tries to communicate with the Identity server.
    * Also may want to ensure these URLs use the expected protocol, i.e. HTTPS
* Perhaps you could try toggling `ProxyPreserveHost on` and remove it (default is off) or setting `ProxyPreserveHost off` and see if that works 🤷🏻 
* Otherwise, hopefully someone else on the team or community will be able to help further.

**Comment by viceldan** [comment]
Thank you for your help, obviously there was a lot to correct in the first place.   

I corrected it as you mentioned and made the new values active: 

    ./bitwarden.sh stop
    ./bitwarden.sh updateself
    ./bitwarden.sh rebuild
    ./bitwarden.sh start
    ./bitwarden.sh updatedb

I also toggled the ProxyPreserveHost directive, but with no effect (finally I turned it off).   
I also commented out the directives for port 80 for my bitwarden part.   

The logs I found in bwdata so far did not really help me to undestand what's going on.   
I found one suspicious entry, but do not really know how to deal with it. :   

    2020/09/23 10:42:52 [warn] 43#43: *6 an upstream response is buffered to a temporary file /var/cache/nginx/proxy_temp
    /1/00/0000000001 while reading upstream, client: 95.114.21.10, server: mydomain.net, request: "GET 
    /app/vendor.8b34420064b2e848cb97.js HTTP/1.1", upstream: "http://192.168.32.3:5000
    /app/vendor.8b34420064b2e848cb97.js", host: "192.168.160.112:5443", referrer: "https://mydomain.net/bitwarden/"

Is there a place other than the following files that could influence such behaviour?  

So the corrected files look like this:

**On my bitwarden VM:**

My config.yml file :

    url: https://mydomain.net/bitwarden/
    generate_compose_config: true
    generate_nginx_config: true
    http_port: 5080
    https_port: 5443
    compose_version: 
    ssl: true
    ssl_versions: 
    ssl_ciphersuites: 
    ssl_managed_lets_encrypt: false
    ssl_certificate_path: /etc/ssl/mydomain.net/fullchain.pem
    ssl_key_path: /etc/ssl/mydomain.net/privkey.pem
    ssl_ca_path: /etc/ssl/mydomain.net/fullchain.pem
    ssl_diffie_hellman_path
    push_notifications: true
    database_docker_volume: false
    real_ips:
    - 192.168.150.25

My global.override.env:

    globalSettings__baseServiceUri__vault=https://mydomain.net/bitwarden/
    globalSettings__baseServiceUri__api=https://mydomain.net/bitwarden/api
    globalSettings__baseServiceUri__identity=https://mydomain.net/bitwarden/identity
    globalSettings__baseServiceUri__admin=https://mydomain.net/bitwarden/admin
    globalSettings__baseServiceUri__notifications=https://mydomain.net/bitwarden/notifications
    globalSettings__baseServiceUri__sso=https://mydomain.net/bitwarden/sso
    globalSettings__baseServiceUri__portal=https://mydomain.net/bitwarden/portal
    globalSettings__sqlServer__connectionString="Data Source=tcp:mssql,1433;Initial Catalog=vault;Persist Security Info=False;User ID=sa;Password=3mLn41eZljD3RnOvnuiNSDnI9sxS2uSF;MultipleActiveResultSets=False;Connect Timeout=30;Encrypt=True;TrustServerCertificate=True"
    globalSettings__identityServer__certificatePassword=Cs9a1EeFPPMWEXoFi0CsxAcBJz4qoQ1r
    globalSettings__attachment__baseDirectory=/etc/bitwarden/core/attachments
    globalSettings__attachment__baseUrl=https://mydomain.net/bitwarden/attachments
    globalSettings__dataProtection__directory=/etc/bitwarden/core/aspnet-dataprotection
    globalSettings__logDirectory=/etc/bitwarden/logs
    globalSettings__logRollBySizeLimit=
    globalSettings__syslog__destination=
    globalSettings__licenseDirectory=/etc/bitwarden/core/licenses
    globalSettings__internalIdentityKey=SomeKey
    globalSettings__oidcIdentityClientKey=SomeClientKey
    globalSettings__duo__aKey=AnotherKey
    globalSettings__installation__id=SomeInstallationID
    globalSettings__installation__key=SomeInstallationKey
    globalSettings__yubico__clientId=REPLACE
    globalSettings__yubico__key=REPLACE
    globalSettings__mail__replyToEmail=myuser@mydomain.de
    globalSettings__mail__smtp__host=myprovider.com
    globalSettings__mail__smtp__port=587
    globalSettings__mail__smtp__ssl=true
    globalSettings__mail__smtp__username=user@myprovider.com
    globalSettings__mail__smtp__password=SuperSecretPasswlrd
    globalSettings__disableUserRegistration=false
    globalSettings__hibpApiKey=REPLACE
    adminSettings__admins=
    globalSettings__mail__smtp__trustServer=true


Thank you in advance for caring about this.

**Comment by cscharf** [comment]
Hmm 🤔 , in regards to that `[warn]` from nginx, I believe that can be safely ignored, if you're curious I did find this [post on serverfault explaining that a bit better](https://serverfault.com/a/587432) and what can be done if it's nagging at you.

The other settings look okay as far as I can tell, and obviously the proxy is getting requests (as the warn would indicate the domain referrer is passing through the proxy to your host), but not sure when, why and how things are just dying for you.

Can you take a look at the docker logs of the API and/or Identity containers?
```bash
docker ps
# Ensure you have running containers for bitwarden-* (api and identity and mssql at the least)
docker logs bitwarden-identity
docker logs bitwarden-api
```
and optionally pipe those to a local file you can cleanse and share if there're any interesting bits in there. You mentioned it's working as expected when going directly to the host IP itself vs. the domain, so the issue would generally point to the reverse proxy (I would think), however it could be something else, perhaps take a look at the docker logs for `docker logs bitwarden-nginx` as well (if that's not already what you did).

**Comment by cscharf** [comment]
Also, comparing from our test self-hosted instance, some other items:

* in `config.yml` file, residing in `/root/bitwarden/bwdata`: The `url:` parameter value should not end with a `/`
* Our test setup is using 80 and 443 for the http and https ports respectively (not sure that matters)
* Can you also look at the main host generated `/root/bitwarden/bwdata/nginx/default.conf` to see how that's generating your nginx configuration from the `config.yml`?

**Comment by viceldan** [comment]
Ok, so what I did now was:

* switching ports to 80 and 443, meaning changing these lines in config.yml:
    http_port: 80
    https_port: 443
* switching ports in the vhosts definition of the apache proxy:
    In the port 80 part:
        RewriteRule         ^/bitwarden/(.*)      http://192.168.160.112:80/$1 [P,L]
        ProxyPassReverse    /bitwarden/           http://192.168.160.112:80

  In the port 443 part:
    RewriteRule         ^/bitwarden/(.*)      https://192.168.160.112:443/$1 [P,L]
    ProxyPassReverse    /bitwarden/           https://192.168.160.112:443
* Correcting the url stanza in config.yml:
    url: https://mydomain.net/bitwarden
* Cycling bitwarden again:
    ./bitwarden.sh stop
    ./bitwarden.sh updateself
    ./bitwarden.sh rebuild
    ./bitwarden.sh start
    ./bitwarden.sh updatedb

Unfortunately this did not help .   

This is the output of `docker ps` :  

    CONTAINER ID        IMAGE                            COMMAND             CREATED             STATUS                 PORTS                                                 NAMES
    1d7d423740cc        bitwarden/nginx:1.37.1           "/entrypoint.sh"    3 hours ago         Up 3 hours (healthy)   80/tcp, 0.0.0.0:80->8080/tcp, 0.0.0.0:443->8443/tcp   bitwarden-nginx
    fe1051aae080        bitwarden/portal:1.37.1          "/entrypoint.sh"    3 hours ago         Up 3 hours (healthy)   5000/tcp                                              bitwarden-portal
    06227323e39b        bitwarden/admin:1.37.1           "/entrypoint.sh"    3 hours ago         Up 3 hours (healthy)   5000/tcp                                              bitwarden-admin
    44210a194028        bitwarden/mssql:1.37.1           "/entrypoint.sh"    3 hours ago         Up 3 hours (healthy)                                                         bitwarden-mssql
    0f3b90616794        bitwarden/attachments:1.37.1     "/entrypoint.sh"    3 hours ago         Up 3 hours (healthy)                                                         bitwarden-attachments
    44e1827ba691        bitwarden/web:2.16.1             "/entrypoint.sh"    3 hours ago         Up 3 hours (healthy)                                                         bitwarden-web
    c7ca8a18c839        bitwarden/identity:1.37.1        "/entrypoint.sh"    3 hours ago         Up 3 hours (healthy)   5000/tcp                                              bitwarden-identity
    cb41913c5666        bitwarden/notifications:1.37.1   "/entrypoint.sh"    3 hours ago         Up 3 hours (healthy)   5000/tcp                                              bitwarden-notifications
    124cfcb5014f        bitwarden/sso:1.37.1             "/entrypoint.sh"    3 hours ago         Up 3 hours (healthy)   5000/tcp                                              bitwarden-sso
    a97d1c86c752        bitwarden/icons:1.37.1           "/entrypoint.sh"    3 hours ago         Up 3 hours (healthy)   5000/tcp                                              bitwarden-icons
    91237431a384        bitwarden/api:1.37.1             "/entrypoint.sh"    3 hours ago         Up 3 hours (healthy)   5000/tcp                                              bitwarden-api
    f86856a433a8        bitwarden/events:1.37.1          "/entrypoint.sh"    3 hours ago         Up 3 hours (healthy)   5000/tcp                                              bitwarden-events


The output of `docker logs bitwarden-identity`
gave multiple entries of lines  like this:   

    info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
        Request starting HTTP/1.1 GET http://localhost:5000/.well-known/openid-configuration  
    info: IdentityServer4.Hosting.IdentityServerMiddleware[0]
        Invoking IdentityServer endpoint: IdentityServer4.Endpoints.DiscoveryEndpoint for /.well-known/openid-configuration
   info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
        Request finished in 1.7511ms 200 application/json; charset=UTF-8


The output of `docker logs bitwarden-api`
gave entries like this :   

    info: Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor[1]
        Executing ObjectResult, writing value of type 'System.DateTime'.
    info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
        Executed action Bit.Api.Controllers.MiscController.Get (Api) in 1.7194ms
    info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
        Executed endpoint 'Bit.Api.Controllers.MiscController.Get (Api)'
    info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
        Request finished in 5.1745ms 200 application/json; charset=utf-8



And this is the nginx/default.conf

    #######################################################################
    # WARNING: This file is generated. Do not make changes to this file.  #
    # They will be overwritten on update. You can manage various settings #
    # used in this file from the ./bwdata/config.yml file for your        #
    # installation.                                                       #
    #######################################################################
    
    server {
      listen 8080 default_server;
      listen [::]:8080 default_server;
      server_name mydomain.net;
    
      return 301 https://mydomain.net/bitwarden$request_uri;
    }
    
    server {
      listen 8443 ssl http2;
      listen [::]:8443 ssl http2;
      server_name mydomain.net;
    
      ssl_certificate /etc/ssl/mydomain.net/fullchain.pem;
      ssl_certificate_key /etc/ssl/mydomain.net/privkey.pem;
      ssl_session_timeout 30m;
      ssl_session_cache shared:SSL:20m;
      ssl_session_tickets off;
    
      ssl_protocols TLSv1.2;
      ssl_ciphers "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256";
      # Enables server-side protection from BEAST attacks
      ssl_prefer_server_ciphers on;
    
      # OCSP Stapling ---
      # Fetch OCSP records from URL in ssl_certificate and cache them
      ssl_stapling on;
      ssl_stapling_verify on;
    
      # Verify chain of trust of OCSP response using Root CA and Intermediate certs
      ssl_trusted_certificate /etc/ssl/mydomain.net/fullchain.pem;
      resolver 1.1.1.1 1.0.0.1 9.9.9.9 149.112.112.112 valid=300s;
    
      include /etc/nginx/security-headers-ssl.conf;
      include /etc/nginx/security-headers.conf;
    
      set_real_ip_from 192.168.150.25;
      real_ip_header X-Forwarded-For;
      real_ip_recursive on;
    
      location / {
        proxy_pass http://web:5000/;
        include /etc/nginx/security-headers-ssl.conf;
        include /etc/nginx/security-headers.conf;
        add_header Content-Security-Policy "default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https://haveibeenpwned.com https://www.gravatar.com; child-src 'self' https://*.duosecurity.com; frame-src 'self' https://*.duosecurity.com; connect-src 'self' wss://mydomain.net https://api.pwnedpasswords.com https://twofactorauth.org; object-src 'self' blob:;";
        add_header X-Frame-Options SAMEORIGIN;
        add_header X-Robots-Tag "noindex, nofollow";
      }
    
      location /alive {
        return 200 'alive';
        add_header Content-Type text/plain;
      }
    
      location = /app-id.json {
        proxy_pass http://web:5000/app-id.json;
        include /etc/nginx/security-headers-ssl.conf;
        include /etc/nginx/security-headers.conf;
        proxy_hide_header Content-Type;
        add_header Content-Type $fido_content_type;
      }
    
      location = /duo-connector.html {
        proxy_pass http://web:5000/duo-connector.html;
      }
    
      location = /u2f-connector.html {
        proxy_pass http://web:5000/u2f-connector.html;
      }
    
      location = /sso-connector.html {
        proxy_pass http://web:5000/sso-connector.html;
      }
    
      location /attachments/ {
        proxy_pass http://attachments:5000/;
      }
    
      location /api/ {
        proxy_pass http://api:5000/;
      }
    
      location /icons/ {
        proxy_pass http://icons:5000/;
      }
    
      location /notifications/ {
        proxy_pass http://notifications:5000/;
      }
    
      location /notifications/hub {
        proxy_pass http://notifications:5000/hub;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
      }
    
      location /events/ {
        proxy_pass http://events:5000/;
      }
    
      location /sso {
        proxy_pass http://sso:5000;
        include /etc/nginx/security-headers-ssl.conf;
        include /etc/nginx/security-headers.conf;
        add_header X-Frame-Options SAMEORIGIN;
      }
    
      location /identity {
        proxy_pass http://identity:5000;
        include /etc/nginx/security-headers-ssl.conf;
        include /etc/nginx/security-headers.conf;
        add_header X-Frame-Options SAMEORIGIN;
      }
    
      location /admin {
        proxy_pass http://admin:5000;
        include /etc/nginx/security-headers-ssl.conf;
        include /etc/nginx/security-headers.conf;
        add_header X-Frame-Options SAMEORIGIN;
      }
    
      location /portal {
        proxy_pass http://portal:5000;
        include /etc/nginx/security-headers-ssl.conf;
        include /etc/nginx/security-headers.conf;
        add_header X-Frame-Options SAMEORIGIN;
      }
    }

**Comment by cscharf** [comment]
Okay, so my apologies there the 80/443 was a red herring (and my missing the other configuration settings which were correct) as the generated config still has `8080 /8443` as the http/https ports, so you can likely set that back. It appears that your configuration _was_ correct, at least from the Bitwarden side. I'm not familiar enough with Apache to know how/where that may be having issues there.

In the docker configuration it appears the port mapping is correct for the nginx proxy, `80/tcp, 0.0.0.0:80->8080/tcp, 0.0.0.0:443->8443/tcp`, so that's also good. You are able to access it directly by its IP address, however when using your hostname through the Apache reverse proxy is when you're having issues on _some_ requests... 🤔 

Okay, quick 💡  idea, can you please revert everything back to where it was when you made the changes here: https://github.com/bitwarden/server/issues/946#issuecomment-697328292. That _should_ be good, and if you're still able to get through the same steps as described in the original post it would seem while we're still not any closer, things look a little cleaner. From there, some other things we can look at:

1. Use the browser dev tools to monitor network requests to see which XHR or Doc request is returning the 4xx/5xx
2. Capture the parameters around that so we can determine which endpoint and/or service appears to be breaking
3. 🤞🏻  Hope that has some obvious answers in it

**Comment by Mart124** [comment]
Below an example (and working) Apache configuration.
Some prerequisites :
- configure Bitwarden using self-signed certificate (you have this option during installation) ;
- disable Bitwarden HTTP port (`http_port:`) which is useless with a reverse-proxy ;
- you can force Bitwarden to listen on localhost (`https_port: 127.0.0.1:5443`).

```
<VirtualHost *:80>
ServerName yourdomain.com
RewriteEngine on
RewriteRule (.*) https://%{HTTP_HOST}$1 [R=permanent]
</VirtualHost>

<VirtualHost *:443>
ServerName yourdomain.com
DocumentRoot /var/www/html
<LocationMatch "^/(.well-known/.*)$">
Require all granted
</LocationMatch>
ProxyPassMatch "^/(.well-known/.*)$" !
ProxyPass / https://127.0.0.1:5443/
SSLEngine on
SSLProxyEngine On
ProxyPreserveHost On
SSLCertificateFile    /etc/letsencrypt/live/yourdomain.com/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/yourdomain.com/privkey.pem
</VirtualHost>
```

The `/var/www/html/.well-known/` specific rule allows you to generate a Let's Encrypt certificate using your host's `certbot`, with `--webroot -w /var/www/html`.

**Comment by viceldan** [comment]
Thank you for the hint.   

I put the configuration back to my original settings, just as you said.  

It seems like the POST event uses a wrong url, so it compains with 404 - not found.   
In my opinion it should be https://mydomain.net/**bitwarden**/api/accounts/register and not https://mydomain.net/api/accounts/register   
That is why that url is not found, I think. But I do not see where this could come from ...   

    Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf eval blockiert ("default-src"). 10 vendor.8b34420064b2e848cb97.js:335:168
    Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf eval blockiert ("default-src"). 4 vendor.8b34420064b2e848cb97.js:335:168
    XHR POST https://mydomain.net/api/accounts/register
    [HTTP/2 404 Not Found 24ms]

	
    POST
	    https://mydomain.net/api/accounts/register
    Status404
    Not Found
    VersionHTTP/2
    Übertragen488 B (196 B Größe)

    	
        content-length
    	    196
        content-type
        	text/html; charset=iso-8859-1
        date
        	Thu, 24 Sep 2020 07:32:25 GMT
        server
        	Apache
        strict-transport-security
        	max-age=63072000; includeSubDomains; preload
        x-content-type-options
        	nosniff
        X-Firefox-Spdy
        	h2
        x-frame-options
        	DENY
    	
        Accept
        	*/*
        Accept-Encoding
    	    gzip, deflate, br
        Accept-Language
        	de,en-US;q=0.7,en;q=0.3
        Cache-Control
        	no-cache
        Connection
        	keep-alive
        Content-Length
        	2559
        content-type
        	application/json; charset=utf-8
        device-type
        	10
        Host
        	mydomain.net
        Origin
        	https://mydomain.net
        Pragma
        	no-cache
        Referer
        	https://mydomain.net/bitwarden/
        TE
        	Trailers
        User-Agent
        	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0

    Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf eval blockiert ("default-src"). 3 vendor.8b34420064b2e848cb97.js:335:168


@Mart124 Thank you for your suggestion, but when I interpret it correctly, I'm afraid that it does not fit into my setup.   
I like to have my different applications in subfolders of my domain, like https://mydomain.net/bitwarden/, https://mydomain.net/owncloud/, https://mydomain.net/wekan/, etc. and all applications run on different VMs, with different IPs.    
From what I see, you assume that the bitwarden container is on the same VM as the proxy, which is why you suggest the localhost redirect.   
But as I mentioned, the bitwarden container runs on a different VM. Did I get this correctly?

**Comment by Mart124** [comment]
> I like to have my different applications in subfolders of my domain

You should use `bitwarden.mydomain.net` instead of `mydomain.net/bitwarden/`, less prone to errors...

> But as I mentioned, the bitwarden container runs on a different VM.

In that case, don't force Bitwarden to listen on localhost (`https_port: 5443`), and use your VM IP in the `ProxyPass` Apache option.
