### ISSUE TITLE
Security issues with container images

### ISSUE THREAD

**Issue by 4c0n** [bitwarden/server#949]
AWS ECR (container registry) performs a security scan when pushing containers, which points out that there are currently some issues with the containers used by Bitwarden.

Please see the attachments for an overview of CVE codes, severity and description.

Zipped csv:
[cves.zip](https://github.com/bitwarden/server/files/5268701/cves.zip)

Exported as PDF for easy viewing:
[cves.pdf](https://github.com/bitwarden/server/files/5268702/cves.pdf)

They might be quite general and not directly related to Bitwarden, however it is distributed with Bitwarden, so it would be wise to analyze the list and take action where required, IMO the best situation would produce no reports of any security issues at all ;)

**Comment by kspearrin** [comment]
Thanks. This report is pretty noisy but we'll look into some of these low priority ones to see if there is anything fixable.

**Comment by KaiBroeker** [comment]
Hey @4c0n,
for which image did you run the sec test? Then I would take a closer look.

**Comment by 4c0n** [comment]
Hi @KaiBroeker the results are from the api image, but other images seem to give the same result, they're probably using the same base image, which is where the vulnerabilities reside (just guessing).
