### ISSUE TITLE
BUG: 2-Factor with yubico not working

### ISSUE THREAD

**Issue by pboatone** [bitwarden/server#966]
Hi,

when adding or login with yubico, there is an error when trying to verfy it:
![2020-10-14 10_31_17-Window](https://user-images.githubusercontent.com/67209365/95963881-8216ed80-0e08-11eb-83aa-58c0dd2d50ac.png)

**Comment by kspearrin** [comment]
is this on vault.bitwarden.com or your own server?

**Comment by pboatone** [comment]
Hi, sry for late anwering, its on the own server

**Comment by kspearrin** [comment]
Did you configure a Yubico API key ?

**Comment by pboatone** [comment]
Hi, sry for late anwering, where can i change the API

**Comment by pboatone** [comment]
globalSettings__yubico__clientId=
globalSettings__yubico__key=

if you mean those, they are configurated

**Comment by pboatone** [comment]
It is just working now the problem was the Update to the newest version. After going back to a snapshot and update agein it works fine
