### ISSUE TITLE
Bitwarden flooding syslog with Docker mount messages

### ISSUE THREAD

**Issue by joekerna** [bitwarden/server#968]
When running bitwarden with `bitwarden.sh start` my `syslog` gets flooded every second with messages like this:

> Oct 19 12:28:40 localhost systemd[1472]: run-docker-runtime\x2drunc-moby-9a1fa5a3c5bbdee34012adcc505fdfcbc746c19ee6e048ef0cf465708be897a8-runc.W3Cp1Z.mount: Succeeded.
> Oct 19 12:28:40 localhost systemd[1]: run-docker-runtime\x2drunc-moby-9a1fa5a3c5bbdee34012adcc505fdfcbc746c19ee6e048ef0cf465708be897a8-runc.W3Cp1Z.mount: Succeeded.
> Oct 19 12:28:40 localhost systemd[167464]: run-docker-runtime\x2drunc-moby-9a1fa5a3c5bbdee34012adcc505fdfcbc746c19ee6e048ef0cf465708be897a8-runc.W3Cp1Z.mount: Succeeded.
> Oct 19 12:28:41 localhost systemd[1472]: run-docker-runtime\x2drunc-moby-8fca82b43b9ea20fdc3e7ac0e822b15778c6dd70ae4f9bd8dbf1a64a731248a0-runc.S5GUQE.mount: Succeeded.
> Oct 19 12:28:41 localhost systemd[1]: run-docker-runtime\x2drunc-moby-8fca82b43b9ea20fdc3e7ac0e822b15778c6dd70ae4f9bd8dbf1a64a731248a0-runc.S5GUQE.mount: Succeeded.
> Oct 19 12:28:41 localhost systemd[167464]: run-docker-runtime\x2drunc-moby-8fca82b43b9ea20fdc3e7ac0e822b15778c6dd70ae4f9bd8dbf1a64a731248a0-runc.S5GUQE.mount: Succeeded.
> Oct 19 12:28:42 localhost systemd[1]: run-docker-runtime\x2drunc-moby-6df0dfdecc7b38f75e685d25c2d0b7fdbacb40332e205e3f73410277baada674-runc.7un3ZU.mount: Succeeded.
> Oct 19 12:28:42 localhost systemd[1472]: run-docker-runtime\x2drunc-moby-6df0dfdecc7b38f75e685d25c2d0b7fdbacb40332e205e3f73410277baada674-runc.7un3ZU.mount: Succeeded.
> Oct 19 12:28:42 localhost systemd[167464]: run-docker-runtime\x2drunc-moby-6df0dfdecc7b38f75e685d25c2d0b7fdbacb40332e205e3f73410277baada674-runc.7un3ZU.mount: Succeeded.

I've stopped bitwarden and the messages disappear.

My system is:
Ubuntu 20.04
Docker 19.03.8

**Comment by joekerna** [comment]
[This issue](https://github.com/docker/for-linux/issues/679) sounds related

**Comment by joekerna** [comment]
https://github.com/docker/for-linux/issues/679#issuecomment-509159724 turns off the messages but I'm not sure if that's a good solution?!

**Comment by Mart124** [comment]
That's the way to go 👍
That's `systemd` / `syslog` configuration related, nothing Bitwarden can do with it :)

**Comment by cscharf** [comment]
Hi @joekerna , closing this for now, and thanks @Mart124  for helping with the response, it's much appreciated!
