### ISSUE TITLE
Where to put the private URL into iOS app of  Bitwarden?

### ISSUE THREAD

**Issue by egberts** [bitwarden/server#972]
I couldn't find the options in which to enter in the private URL (vault.example.net/#/vault) into the  Bitwarden iOS mobile app.

Where is it?

Submitted feature request here: https://community.bitwarden.com/t/guide-to-mobile-app/15109

**Comment by addisonbeck** [comment]
I think what you're looking for might be the help article for [changing client environment urls](https://bitwarden.com/help/article/change-client-environment/).

**Comment by egberts** [comment]
That's the problem.   That initial screen where the setup icon is located is FLASHED momentarily for less than a 10th of a second before going to the "Verify Master Password".

**Comment by egberts** [comment]
Never mind.... pressing "LOGOUT" does the trick and the initial screen with that setup button appears.  

Closing this issue.

Hindsight:  I could use a nice mobile user guide on this but haven't been able to find one.
