### ISSUE TITLE
Steps to Backup and restore bitwarden

### ISSUE THREAD

**Issue by Sx3** [bitwarden/server#975]
We are using bitwarden on docker .and need to move the installation to a new server ....is there any instructions to backup and restore bitwaden database?
Thanks.

**Comment by Greenderella** [comment]
Hi @Sx3,

Once you complete the new installation on the new server, all you need is the entire _bwdata_ directory and the _bitwarden.sh_ script. As long as Docker and Docker Compose are installed on the system, you can start the Bitwarden server and it will rebuild everything based on all the data in the _bwdata_ directory. You could even copy the _bwdata_ directory and _bitwarden.sh_ script to a new server and start it and it would keep all of your data and settings. Of course, you will need to have your DNS and all configured for that server.

**Comment by cscharf** [comment]
Closing this issue for now, if you have any further questions or problems in getting this to work please feel free to re-open it.
