### ISSUE TITLE
Password Safe Import -> Not available anymore

### ISSUE THREAD

**Issue by FaserF** [bitwarden/server#983]
Bitwarden has an option to import Password Safe Data (as xml), unfortunatly Password Safe has removed the xml option. We can now only export the password safe data as csv.
Could you update your instructions/add an option for csv or remove the option?

**Comment by Greenderella** [comment]
Thank you for the report @FaserF 

Given the fact that we do not support the service you are using right now (Password Safe csv), then you will have the option of creating a generic CSV to fit our format. We have detailed info on this format and a template file you can use located here, https://help.bitwarden.com/article/import-data/#generic-csv-format-individual-account.

You can also generate a dummy JSON export file from Bitwarden to use as a template if you prefer working with JSON.

Also, If you would like to provide us with an unencrypted example file of the export format you are given from your current service, I am happy to send it over to the team to investigate adding support. **Please make sure to redact any sensitive information.**

**Comment by FaserF** [comment]
Here are two examples (please rename the files to .csv - as I cant upload .csv here)
[Passwort-CSV-Export_example.txt](https://github.com/bitwarden/server/files/5511611/Passwort-CSV-Export_example.txt)
[Passwort-CSV-Export_lokale Administratoren_example.txt](https://github.com/bitwarden/server/files/5511612/Passwort-CSV-Export_lokale.Administratoren_example.txt)

**Comment by Greenderella** [comment]
Thank you! Would you mind providing us with a step-by-step instruction on how to get the import file from Password Safe? i.e. "Go to Settings > Go to Export > Select CSV > Click Export" so we can update our documentation also?

**Comment by FaserF** [comment]
Here is a guide:

Export your Password Safe 8 passwords (Desktop) (CSV)
1. Open Password Safe 8 and open the "Extras" menu from the left upper corner.
2. Locate the Export option at the left list and choose "Passwords".
3. As type select CSV and define an export location folder. You can leave the coding at UTF-8.
![image](https://user-images.githubusercontent.com/12374134/99631623-32959400-2a3c-11eb-8202-a95b56fb58f8.png)
4. The Export Settings can stay at the default settings.
![image](https://user-images.githubusercontent.com/12374134/99631655-3e815600-2a3c-11eb-9c3f-dd86c6c8c704.png)
5. Klick Finish to start the export

Note: Please note that password safe 8 will export an CSV for EVERY category you had before and not a single CSV.
Also please note that the export can take some time. 8000 passwords took us some hours to export. So prefer doing the export directly at the server.

**Comment by djsmith85** [comment]
Thank you @FaserF for providing the documentation. I've created a PR to add it to the docs.

I've had a look at the importers in bitwarden/jslib and unfortunately the change to the .csv-format CSV by Password Safe makes the import a lot trickier. It seems that there are several different formats (column headers) depending on what category is exported.

**Comment by FaserF** [comment]
In the meantime we have imported the passwords with a CSV Editor, it was a lot of work, so I understand that this is tricky. 
Thanks for the PR.

**Comment by djsmith85** [comment]
Hi @FaserF closing this here, as the PR with the updated instructions has been merged.
