### ISSUE TITLE
How to install BitWarden

### ISSUE THREAD

**Issue by rbdevr** [bitwarden/server#995]
Good day,

I'm looking forward to install BitWarden on my private server but I'm surprise with the lack of documentation. 
There are 2 accepted ways to install a solution
1-linux style - get the binary files from a tarball package and deploy and configure config files.
2-using docker - get a list of containers required and create the containers using image file and configure global variables.
I don't want any miraculous install script to run on my server. I need to understand this deployment step by step so I can properly configure DNS, ports, storage and backup.
I hope someone can give a light on this.

Cheers,

**Comment by kspearrin** [comment]
Please see help docs here for manual docker installation: https://bitwarden.com/help/article/install-on-premise/

**Comment by rbdevr** [comment]
I couldn't find anything there. 
Could you be more specific?

Cheers

**Comment by kspearrin** [comment]
https://bitwarden.com/help/article/install-on-premise/#manual-docker-installations

**Comment by rbdevr** [comment]
Alright. I got that. Now how do the services work? what services are actually needed for standard usage. How to configure each one of them. How to use SQLite instead of MsSql. How to take out nginx and use the services behind apache. How config works.
Those are the data I'm looking for.

**Comment by sutidor** [comment]
Alright. I got that. 

> Now how do the services work? 
Very well according to my experience (2 years)
> what services are actually needed for standard usage. 
All of the services in docker-compose file. As they are all started using docker compose, it's a pretty straight forward and easy install process. The docs are well written. If you follow the process, you have an up and running bitwarden in 10 minutes.
> How to configure each one of them. 
They work out of the box. Extra config like e-mail adress you find in the docs. The easiest that I found is to modify the /env/global.override.env file. Use the your-domain.com/admin interface to see if it's successful.
> How to use SQLite instead of MsSql.
Impossible without modifying the images. Same goes for other databases.
> How to take out nginx and use the services behind apache.
Impossible without modifying the images. Same goes for other webservers.

**Comment by clayadams5226** [comment]
Thank you for getting in touch and bringing this to our attention! We'd like to assist you further. We ask that you please contact us using our contact page, here: https://bitwarden.com/contact. You can include a link to this issue in the message content. The issue here will be closed and moved over to our Help Desk.
