### ISSUE TITLE
Docker-hosted behind reverse proxy yields error message on ios

### ISSUE THREAD

**Issue by pittbull** [bitwarden/server#997]
I have set up Bitwarden on docker located behind a nginx reverse proxy. 

When accessing url in browser internally and externally, the login page shows correctly. 

When accessing it from the Bitwarden app on my Iphone it works externally, but not internally. The following error message is given:

`Exception message: The Internet connection appears to be offline.`

Might anybody have any insights to this?

**Comment by SlothCroissant** [comment]
+1, I have the same issue using Caddy V2 and Bitwarden via Docker

```
(snippet) {
	header {
		Strict-Transport-Security "max-age=31536000; includeSubdomains"
		X-Real-IP {http.request.remote}
		Host {host}
		X-XSS-Protection "1; mode=block"
		X-Frame-Options "DENY"
		-server
	}
	tls {
		issuer acme {
		email user@email.com
				dns cloudflare {env.CLOUDFLARE_API_TOKEN}
					dir https://acme-v02.api.letsencrypt.org/directory
					resolvers 1.1.1.1,1.0.0.1,8.8.8.8,8.8.4.4
			}
	}
	log {
		output file /data/logs/caddy.log {
			roll_size 20MiB
			roll_keep 5
		}
	}
}

vault.url.com {
	reverse_proxy docker02.lan:83
	reverse_proxy /notifications/hub docker02.lan:3012
	reverse_proxy /notifications/hub/negotiate docker02.lan:83
	import snippet
}
```
(docker02.lan = 10.1.10.4, same subnet as my wifi, etc)

When on local wifi, I cannot login to Bitwarden. If already logged in, I cannot "sync" the vault. When connected into my network via Wireguard (so on a different subnet), it works fine.

Also, when accessing vault.url.com via Chrome/Safari for iOS, everything works perfectly fine. So I don't think this is a Caddy issue, at first glance.

Finally, when running `tcpdump` on my Caddy webserver, the HTTP request & TCP SYN from the iOS app literally never shows up. Almost like the app never even tries to connect.

Anything we can do to debug this further?

**Comment by gnowk** [comment]
Ran into this problem today.  See if the Bitwarden iOS app has access to the local network.

Settings > Bitwarden > Local Network

**Comment by SlothCroissant** [comment]
> Ran into this problem today. See if the Bitwarden iOS app has access to the local network.
> 
> Settings > Bitwarden > Local Network

Can confirm - this resolved the issue for me :+1:  After hours of troubleshooting, sometimes it ends up being the simplest solutions, I swear. Thanks @gnowk!
