### ISSUE TITLE
bitwarden-api container doing failed log-in attempts

### ISSUE THREAD

**Issue by benlenau** [bitwarden/server#998]
**ERROR:** Logged in /identity/Identity/log.txt:
```
2020-11-17 07:48:22.411 +00:00 [WRN] Failed login attempt. ::ffff:172.23.0.4
2020-11-17 08:08:20.431 +00:00 [WRN] Failed login attempt. ::ffff:172.23.0.4
2020-11-17 09:29:37.018 +00:00 [WRN] Failed login attempt. ::ffff:172.23.0.4
2020-11-17 14:55:34.488 +00:00 [WRN] Failed login attempt. ::ffff:172.23.0.4
```
**WHEN:** After updating to latest release >v1.38.0 and web >v2.17.0.

**CULPRIT:** IP traced back to _bitwarden-api_ container.

**RE-PRODUCE:** user EDIT any BW entry (in app, webinterface or browser extension) and SAVE - Voila' an error is logged within ./Identity/log.txt.

**MAYBE:** Can't help but think that some of the changes in [src/Api/Controllers/AccountsController.cs](https://github.com/bitwarden/server/compare/v1.37.2...v1.38.0#diff-e6316dfd38aca3fdf30f72792991cad4faa5d4b6ec9373938e7a85ee909c77b9) are to blame.

**INFO:** BW containers have been rock solid for the last two months - Only logging a few "real" malicious log-in attempts.

**Comment by Mart124** [comment]
Try with server 1.38.1 ?

**Comment by benlenau** [comment]
> Try with server 1.38.1 ?

Yeah I did that and still the same. 

`2020-11-19 21:02:37.025 +00:00 [WRN] Failed login attempt. ::ffff:172.21.0.5`

Don't mind that the IP is different it's still the _bitwarden-api_ container (IP changed due to update/restart)

**Comment by Mart124** [comment]
Reproduced, after having migrated from `1.37.2` to `1.38.1`.
As soon as we add, modify or delete an entry, through the web portal, desktop application, browser extensions... the following triggers in `bwdata/logs/identity/Identity/log.txt` :

```
2020-11-27 15:46:10.359 +06:00 [Warning] Failed login attempt. ::ffff:172.21.0.2
2020-11-27 15:46:17.991 +06:00 [Warning] Failed login attempt. ::ffff:172.21.0.2
2020-11-27 15:46:59.490 +06:00 [Warning] Failed login attempt. ::ffff:172.21.0.2
2020-11-27 15:47:05.092 +06:00 [Warning] Failed login attempt. ::ffff:172.21.0.2
```

**Comment by Mart124** [comment]
@kspearrin do you think this could be fixed in 1.38.2 ?
Many thanks 👍

**Comment by benlenau** [comment]
updated to web v2.17.1 (server still at v1.38.1)
`2020-12-03 08:35:09.793 +00:00 [WRN] Failed login attempt. ::ffff:172.21.0.2`

**Comment by Mart124** [comment]
@kspearrin could we think about finding the culprit please ?
Risk here is for Docker container itself to be banned, which is rather annoying...
Many thanks 👍

**Comment by Mart124** [comment]
`1.38.2` still impacted 😕
Do you plan to have this fixed ?
Many thanks 👍

**Comment by Mart124** [comment]
`1.38.4` still suffers from this issue.

```
==> bwdata/logs/identity/Identity/log.txt <==
2020-12-24 14:51:49.411 +00:00 [Warning] Failed login attempt. ::ffff:172.19.0.4

==> /var/log/fail2ban.log <==
2020-12-24 14:51:49,628 fail2ban.filter         [888]: INFO    [bitwarden] Found 172.19.0.4 - 2020-12-24 14:51:49
```

**Comment by benlenau** [comment]
> `1.38.4` still suffers from this issue.
> 
> ```
> ==> bwdata/logs/identity/Identity/log.txt <==
> 2020-12-24 14:51:49.411 +00:00 [Warning] Failed login attempt. ::ffff:172.19.0.4
> 
> ==> /var/log/fail2ban.log <==
> 2020-12-24 14:51:49,628 fail2ban.filter         [888]: INFO    [bitwarden] Found 172.19.0.4 - 2020-12-24 14:51:49
> ```

Exactly the reason I posted this in the first place. I've now set f2b to ignore subnet 172.16.0.0/12 until a fix is posted :-)

**Comment by Mart124** [comment]
@cscharf may we perhaps bring this issue to your attention ?
May in addition reveal an internal misbehavior.
Many thanks for your support 👍

**Comment by cscharf** [comment]
Thanks, I was able to reproduce this; followed in the logs by an error, `{ error = invalid_grant }`. Will tee this up for our dev team.

**Comment by Mart124** [comment]
Really glad, many thanks to you @cscharf and to the dev team 👍

**Comment by benlenau** [comment]
> Really glad, many thanks to you @cscharf and to the dev team 👍 

Finally 🙂

**Comment by Mart124** [comment]
_Still present in `1.39.4`._

**Comment by cscharf** [comment]
This is still open on our internal tracking board.
Likely cause may be: https://github.com/bitwarden/server/pull/992 (will take investigation/debugging) we've just not gotten to this yet. I know it's annoying seeing those in there, my apologies, but we will get to it just not sure when. Thanks guys!

**Comment by Mart124** [comment]
I still sporadically get them.
Then please reopen @benlenau ?

**Comment by benlenau** [comment]
I might have been a bit to fast on the trigger. Please keep me posted @Mart124 since I can't provoke this error anymore.
